### ISSUE TITLE
Unable to pickle dynamically created Inherited model

### ISSUE THREAD

**Issue by dmsfabiano** [pydantic/pydantic#5442] opened 2023-04-11 11:54 UTC
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

I am trying to save my class, which has a dynamically created pydantic model. However, there are several issues trying to serialize `<cyfunction BaseModel.validate`. I have tried using `pickle`, `cloudpickle`, and 'dill` and they all have a similar issue

Here are my data structures:
```python
class ModelOutput(BaseModel, ABC):
    class Config:
        arbitrary_types_allowed = True
        schema_extra: Dict[str, Any] = {}

    @classmethod
    def custom_schema(cls) -> str:
        model = create_model(f"Dynamic{cls.__name__}", __base__=cls)
        model.Config.schema_extra["example"] = cls.example()
        return model.schema_json()

    @classmethod
    @abstractmethod
    def example(cls) -> Dict:
        ...

class ModelOutputWrapper(BaseModel):
    prediction: ModelOutput
    metadata: Dict

class ModelSignature:
    def __init__(self, output_type: Type[ModelOutput]) -> None:
        if not issubclass(output_type, ModelOutput):
            raise Exception

        self._output_type = output_type

        self._output_wrapper_type = create_model(
            "CustomModelOutputWrapper",
            prediction=(output_type, ...),
            metadata=(dict, ...),
            __base__=ModelOutputWrapper,
            __module__=__name__,
        )

        setattr(
            sys.modules[__name__], "CustomModelOutputWrapper", self._output_wrapper_type
        )
```

and here is one of the ways I am attempting to serialize it
```python
import cloudpickle as cp
from pathlib import Path

signature = ModelSignature(MyOutput)
cp.dump(signature, Path("./dump.pkl").open("wb"))
```

which yields

```
Traceback (most recent call last):
  File "c:\Users\dmsfa\code\dstools\github\pydantic\serialization.py", line 68, in <module>
    cp.dump(signature, Path("./dump.pkl").open("wb"))
  File "C:\Users\dmsfa\ds310\lib\site-packages\cloudpickle\cloudpickle_fast.py", line 57, in dump
    ).dump(obj)
  File "C:\Users\dmsfa\ds310\lib\site-packages\cloudpickle\cloudpickle_fast.py", line 632, in dump
    return Pickler.dump(self, obj)
_pickle.PicklingError: Can't pickle <cyfunction BaseModel.validate at 0x00000290118D3C60>: it's not the same object as pydantic.main.BaseModel.validate
```

### Python, Pydantic & OS Version

```Text
            pydantic version: 1.10.7
            pydantic compiled: True
               install path: C:\Users\df89291\Code Environment\mlopso\.env\Lib\site-packages\pydantic
               python version: 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)]
               platform: Windows-10-10.0.19041-SP0
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [X] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by commonism** [comment] 2023-04-11 17:38
works for me:

```
import sys
from abc import ABC, abstractmethod
from typing import Dict, Any, Type

from pydantic import BaseModel, create_model


class ModelOutput(BaseModel, ABC):
    class Config:
        arbitrary_types_allowed = True
        schema_extra: Dict[str, Any] = {}

    @classmethod
    def custom_schema(cls) -> str:
        model = create_model(f"Dynamic{cls.__name__}", __base__=cls)
        model.Config.schema_extra["example"] = cls.example()
        return model.schema_json()

    @classmethod
    @abstractmethod
    def example(cls) -> Dict:
        ...

class ModelOutputWrapper(BaseModel):
    prediction: ModelOutput
    metadata: Dict

class ModelSignature:
    def __init__(self, output_type: Type[ModelOutput]) -> None:
        if not issubclass(output_type, ModelOutput):
            raise Exception

        self._output_type = output_type

        self._output_wrapper_type = create_model(
            "CustomModelOutputWrapper",
            prediction=(output_type, ...),
            metadata=(dict, ...),
            __base__=ModelOutputWrapper,
            __module__=__name__,
        )

        setattr(
            sys.modules[__name__], "CustomModelOutputWrapper", self._output_wrapper_type
        )

import cpickle as pickle
from pathlib import Path

class MyOutput(ModelOutput):
    pass

signature = ModelSignature(MyOutput)
pickle.dump(signature, Path("/tmp/dump.pkl").open("wb"))
```

**Comment by dmsfabiano** [comment] 2023-04-11 17:59
@commonism I have updated the issue so that it includes the python version (3.8)

**Comment by dmontagu** [comment] 2023-04-11 21:41
I ran @commonism's code in python 3.8.16 and it didn't error (though I replaced `import cpickle as pickle` with just `import pickle`).

Considering how much of an edge case this is — issues with pickling caused by cython only on specific python versions and/or with `cloudpickle`(?) when using dynamic models created inside function calls — combined with the fact that I think this will be resolved with v2 (due to dropping cython, if nothing else) and our attention is mostly focused on v2, I'll be honest and say I think this is not something that is likely to get much attention from the pydantic maintainers.

I think we'd be open to a PR fixing it if you can figure out what's going wrong and it doesn't require any major changes, but I suspect v2 will already fix this.

**Comment by dmontagu** [comment] 2023-04-11 21:44
I'll also note that I don't get errors using `pickle` instead of `cloudpickle` in python3.8 with the following code:
```python
import sys
from abc import ABC, abstractmethod
from typing import Dict, Any, Type

from pydantic import BaseModel, create_model


class ModelOutput(BaseModel, ABC):
    class Config:
        arbitrary_types_allowed = True
        schema_extra: Dict[str, Any] = {}

    @classmethod
    def custom_schema(cls) -> str:
        model = create_model(f"Dynamic{cls.__name__}", __base__=cls)
        model.Config.schema_extra["example"] = cls.example()
        return model.schema_json()

    @classmethod
    @abstractmethod
    def example(cls) -> Dict:
        ...


class ModelOutputWrapper(BaseModel):
    prediction: ModelOutput
    metadata: Dict


class ModelSignature:
    def __init__(self, output_type: Type[ModelOutput]) -> None:
        if not issubclass(output_type, ModelOutput):
            raise Exception

        self._output_type = output_type

        self._output_wrapper_type = create_model(
            "CustomModelOutputWrapper",
            prediction=(output_type, ...),
            metadata=(dict, ...),
            __base__=ModelOutputWrapper,
            __module__=__name__,
        )

        setattr(
            sys.modules[__name__], "CustomModelOutputWrapper", self._output_wrapper_type
        )


import pickle
from pathlib import Path

signature = ModelSignature(ModelOutput)
pickle.dump(signature, Path("./dump.pkl").open("wb"))
```
(I did need to change `ModelSignature(MyOutput)` to `ModelSignature(ModelOutput)`, not sure if that's right.. but `MyOutput` was not defined.)

**Comment by dmontagu** [comment] 2023-04-11 21:45
And I can confirm it also works for me with `import pickle` changed to `import cloudpickle as pickle` after pip installing `cloudpickle`.

**Comment by Kludex** [comment] 2023-05-01 05:20
Given that we are unable to reproduce it, I'll be closing the issue.

If you want to continue here, let me know, and I'll reopen it. 🙏

**Closed by Kludex** 2023-05-01 05:20 UTC
Labels: bug V1, unconfirmed
