### ISSUE TITLE
Version 2.4 raises seemingly incorrect "SchemaError: Definitions error: attempted to use `...` before it was filled"

### ISSUE THREAD

**Issue by felix-hilden** [pydantic/pydantic#7628] opened 2023-09-26 08:27 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I upgraded to 2.4 from 2.3 and suddenly got a `SchemaError`. I'm posting it here instead of `pydantic_core` because I could not for the life of me debug it further, so I don't know at what level the issue is, or if I was using the library incorrectly.

Below is a minimal example that reproduces the issue on import. Interestingly, commenting out any of the lines or classes below marked with a `#` makes the issue vanish (for single line class bodies substituting in a `pass` of course to have a valid class).

The full traceback:
```Python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "script.py", line 36, in <module>
    complete_model_class(
  File "...\venv\Lib\site-packages\pydantic\_internal\_model_construction.py", line 499, in complete_model_class
    cls.__pydantic_validator__ = create_schema_validator(schema, core_config, config_wrapper.plugin_settings)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\venv\Lib\site-packages\pydantic\plugin\_schema_validator.py", line 34, in create_schema_validator
    return SchemaValidator(schema, config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.SchemaError: Definitions error: attempted to use `script.EnumMember:2744245419264` before it was filled
```

### Example Code

```Python
from typing import List, Union
from enum import Enum
from pydantic import BaseModel

class EnumMember(str, Enum):
    attr = "attr"

class Model(BaseModel):
    pass

class M1Inner(BaseModel):
    enum: EnumMember  #

class M1(BaseModel):
    inner: M1Inner  #

class M2Inner(BaseModel):
    models: List[Model]  #

class M2(BaseModel):
    models: List[Model]  #
    enum: EnumMember  #
    inner: M2Inner  #

class Container(BaseModel):
    item: Union[M1, M2]  #

class ContainerExtension(Container):  #
    pass
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.4.0
        pydantic-core version: 2.10.0
          pydantic-core build: profile=release pgo=false
                 install path: G:\win\dev\tekore\venv\Lib\site-packages\pydantic
               python version: 3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)]
                     platform: Windows-10-10.0.19045-SP0
             related packages: typing_extensions-4.6.3
```

**Comment by samuelcolvin** [comment] 2023-09-26 08:47
I think this is a duplicate of #7611 and fixed on main.

LMK if it's not fixed on main for you.

**Closed by samuelcolvin** 2023-09-26 08:47 UTC
Labels: unconfirmed, bug V2

**Comment by felix-hilden** [comment] 2023-09-26 12:31
Thanks for the quick response, installing from main worked!
