### ISSUE TITLE
`use_enum_values` should serialize to value but deserialize to the original enum member.

### ISSUE THREAD

**Issue by Tshimanga** [pydantic/pydantic#8672] opened 2024-01-29 22:39 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

If I create a data model with an enum field and configure the model to `use_enum_values` pydantic correctly serializes the field to the value of the enum; however when deserializing the original enum member is not recovered. This _feels_ wrong because I'd expect that serialization and deserialization remain inverses of each other. This also quitely breaks type safety because the deserialized field is no longer the correct type.

### Example Code

```Python
from enum import Enum
from pydantic import BaseModel, ConfigDict

class Something(Enum):
    A = "A"
    B = "B"

class Other(BaseModel):

    model_config = ConfigDict(
         use_enum_values=True
    )

    value: Something


if __name__ == "__main__":
    other = Other(value=Something.A)

    serialized = other.model_dump()
    deserialized = Other(**serialized)
    assert deserialized.value is Something.A  # This fails!!
```

### Python, Pydantic & OS Version

```Text
3.11, pydantic 2.5.3, mac os sonoma 14.2.1
```

**Comment by sydney-runkle** [comment] 2024-02-02 00:57
@Tshimanga,

Thanks for your thoughts. I'm marking this as a duplicate of https://github.com/pydantic/pydantic/issues/6565, and closing it for this reason. I've marked #6565 with a V3 flag.

I think it's worth discussing whether or not we want to deprecate `use_enum_values` in general, then remove it completely in V3. Feel free to follow along on the aforementioned issue for updates.

**Closed by sydney-runkle** 2024-02-02 00:57 UTC
Labels: duplicate, Change
