### ISSUE TITLE
Weird parsing behaviour when trying to parse_obj_as(dict[str, Any], data) for data of type list[dict[str, str]]

### ISSUE THREAD

**Issue by oldnote** [pydantic/pydantic#3801] opened 2022-02-09 18:51 UTC
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```py
>>> import pydantic.utils; print(pydantic.utils.version_info())
             pydantic version: 1.9.0
            pydantic compiled: False
                 install path: /home/xxx/.local/share/virtualenvs/xxx-zP2295Qn/lib/python3.10/site-packages/pydantic
               python version: 3.10.0 (default, Oct  7 2021, 18:11:17) [GCC 10.2.0]
                     platform: Linux-5.9.14-arch1-1-x86_64-with-glibc2.33
     optional deps. installed: ['email-validator', 'typing-extensions']
```

Following code able to parse list into dict type, if list contains a single dict with exactly 2 keys:
```py
Python 3.10.0 (default, Oct  7 2021, 18:11:17) [GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pydantic import parse_obj_as
>>> from typing import Any
>>> parse_obj_as(dict[str, Any], [{'a': 'b', 'c': 'd'}])
{'a': 'c'}
```
Is it valid that list type can be parsed into dict type at all?
The same behaviour happens for the models. My real life case is that I have a field typed as Union[dict[...], list[dict[...]]] and my data is parsed improperly for this exact case, it's represented as dict instead of list[dict].

There're similar examples, but if dict contains more or less then 2 keys, then it fails to parse it as expected:
```py
>>> parse_obj_as(dict[str, Any], [{'a': 'b'}])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/oldnote/.local/share/virtualenvs/mad-devs-swipey-backend-zP2295Qn/lib/python3.10/site-packages/pydantic/tools.py", line 38, in parse_obj_as
    return model_type(__root__=obj).__root__
  File "/home/oldnote/.local/share/virtualenvs/mad-devs-swipey-backend-zP2295Qn/lib/python3.10/site-packages/pydantic/main.py", line 331, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for ParsingModel[dict[str, Any]]
__root__
  value is not a valid dict (type=type_error.dict)
```

```py
>>> parse_obj_as(dict[str, Any], [{'a': 'b', 'c': 'd', 'e': 'f'}])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/oldnote/.local/share/virtualenvs/mad-devs-swipey-backend-zP2295Qn/lib/python3.10/site-packages/pydantic/tools.py", line 38, in parse_obj_as
    return model_type(__root__=obj).__root__
  File "/home/oldnote/.local/share/virtualenvs/mad-devs-swipey-backend-zP2295Qn/lib/python3.10/site-packages/pydantic/main.py", line 331, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for ParsingModel[dict[str, Any]]
__root__
  value is not a valid dict (type=type_error.dict)
```

**Comment by samuelcolvin** [comment] 2023-04-19 07:14
thanks for reporting, sorry this was never answered.

It's a weird case of a duplicate of #1268

**Closed by samuelcolvin** 2023-04-19 07:14 UTC
Labels: bug V1
