### ISSUE TITLE
Forward ref for private attribute doesn't work

### ISSUE THREAD

**Issue by uhlikfil** [pydantic/pydantic#10396] opened 2024-09-12 16:06 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

The example code used to work in 2.8.2, now it fails with `NameError: name 'B' is not defined`.

### Example Code

```Python
from typing import Any

from pydantic import BaseModel


class A(BaseModel):
    hello: str
    _created: "B"

    def __init__(self, **data: Any) -> None:
        super().__init__(**data)
        self._created = B(time=1, parent=self)


class B(BaseModel):
    time: int
    parent: A


a = A(hello="world")
print(a._created.parent)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.9.1
        pydantic-core version: 2.23.3
          pydantic-core build: profile=release pgo=false
                 install path: /home/filda/Code/sex/.venv/lib/python3.12/site-packages/pydantic
               python version: 3.12.5 (main, Aug 17 2024, 16:46:05) [GCC 11.4.0]
                     platform: Linux-6.8.0-40-generic-x86_64-with-glibc2.35
             related packages: pydantic-settings-2.4.0 mypy-1.11.1 typing_extensions-4.12.2 fastapi-0.111.1
                       commit: unknown
```

**Comment by sydney-runkle** [comment] 2024-09-12 17:06
Hi, marking this as a dupe of https://github.com/pydantic/pydantic/issues/10357. Should be fixed on `main`, and we'll release a patch with said fix tomorrow 👍.

**Closed by sydney-runkle** 2024-09-12 17:06 UTC
Labels: bug V2, pending
