### ISSUE TITLE
"NameError: name 'T' is not defined" when using "from __future__ import annotations" with generic function

### ISSUE THREAD

**Issue by hb2638** [pydantic/pydantic#9536] opened 2024-05-31 23:28 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Pydantic gives the below error when using **from __future__ import annotations** with generic functions

```
C:\code\venv\Scripts\python.exe C:\code\devtools\foo.py 
Traceback (most recent call last):
  File "C:\code\devtools\foo.py", line 8, in <module>
    @pydantic.validate_call
     ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\code\venv\Lib\site-packages\pydantic\validate_call_decorator.py", line 66, in validate_call
    return validate(func)
           ^^^^^^^^^^^^^^
  File "C:\code\venv\Lib\site-packages\pydantic\validate_call_decorator.py", line 55, in validate
    validate_call_wrapper = _validate_call.ValidateCallWrapper(function, config, validate_return)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\code\venv\Lib\site-packages\pydantic\_internal\_validate_call.py", line 42, in __init__
    schema = gen_schema.clean_schema(gen_schema.generate_schema(function))
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\code\venv\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 502, in generate_schema
    schema = self._generate_schema_inner(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\code\venv\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 758, in _generate_schema_inner
    return self.match_type(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\code\venv\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 825, in match_type
    return self._callable_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\code\venv\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 1608, in _callable_schema
    type_hints = _typing_extra.get_function_type_hints(function)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\code\venv\Lib\site-packages\pydantic\_internal\_typing_extra.py", line 309, in get_function_type_hints
    type_hints[name] = eval_type_backport(value, globalns, types_namespace)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\code\venv\Lib\site-packages\pydantic\_internal\_typing_extra.py", line 255, in eval_type_backport
    return typing._eval_type(  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\typing.py", line 400, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\typing.py", line 907, in _evaluate
    eval(self.__forward_code__, globalns, localns),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
NameError: name 'T' is not defined

Process finished with exit code 1
```

The code works when I remove **from __future__ import annotations** from the code

### Example Code

```Python
from __future__ import annotations

import typing

import pydantic


@pydantic.validate_call
def max[T](args: typing.Iterable[T]) -> T:
    return sorted(args, reverse=True)[0]

print(max([1,2, 10, 5]))
```

### Python, Pydantic & OS Version

```Text
python -c "import pydantic.version; print(pydantic.version.version_info())"
             pydantic version: 2.7.2
        pydantic-core version: 2.18.3
          pydantic-core build: profile=release pgo=true
                 install path: C:\code\venv\Lib\site-packages\pydantic
               python version: 3.12.1 (tags/v3.12.1:2305ca5, Dec  7 2023, 22:03:25) [MSC v.1937 64 bit (AMD64)]
                     platform: Windows-10-10.0.19044-SP0
             related packages: typing_extensions-4.12.0
                       commit: unknown
```

**Comment by sydney-runkle** [comment] 2024-06-03 15:59
@hb2638,

Thanks for reporting this issue. @alexmojaki, any idea what's going on here?

**Comment by alexmojaki** [comment] 2024-06-03 16:31
This is not uniquely a pydantic problem, and it's not related to `eval_type_backport`:

```python
from __future__ import annotations

import typing

def foo[T]() -> T: ...

print(typing.get_type_hints(foo))
```

```pytb
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    print(typing.get_type_hints(foo))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "typing.py", line 2281, in get_type_hints
    hints[name] = _eval_type(value, globalns, localns)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "typing.py", line 414, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "typing.py", line 924, in _evaluate
    eval(self.__forward_code__, globalns, localns),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
NameError: name 'T' is not defined
```

The good news is that this was fixed in https://github.com/python/cpython/pull/118009 (which apparently will be released tomorrow) and we may be able to mimic the fix.

The bad news is that the fix shows the signature of `_eval_type` changing which may cause bigger breakages.

**Comment by alexmojaki** [comment] 2024-06-03 17:53
OK, `_eval_type` was thankfully made backward-compatible in https://github.com/python/cpython/issues/118418. I've confirmed that the pydantic tests still pass on the latest unreleased Python 3.12.

https://github.com/python/cpython/pull/118695 adds a deprecation warning to Python 3.13 which will be raised from `_eval_type` if we don't start passing a `type_params` value. We should probably add Python 3.13 to CI here.

`eval_type_backport` (primarily the pydantic `_typing_extras` function, but also eventually the package) should start accepting `type_params` and passing it to `_eval_type`. Everything that calls `eval_type_backport` needs to figure out an appropriate value, something like `getattr(obj, "__type_params__", ())`. That should actually fix this issue as well as prevent the warning in 3.13.

**Comment by alexmojaki** [comment] 2024-06-24 20:18
> `eval_type_backport` (primarily the pydantic `_typing_extras` function, but also eventually the package) should start accepting `type_params` and passing it to `_eval_type`. Everything that calls `eval_type_backport` needs to figure out an appropriate value, something like `getattr(obj, "__type_params__", ())`.

Here's a start to that: https://github.com/pydantic/pydantic/compare/alex/type-params

This makes the following pass:

```python
from __future__ import annotations

import pydantic


@pydantic.validate_call(validate_return=False)
def my_max[T](args: list[T]) -> T:
    return 3


assert my_max(['abc']) == 3
```

However with `validate_return=True` we get this error:

```pytb
Traceback (most recent call last):
  File "/Users/alex/work/pydantic/pydantic/_internal/_generate_schema.py", line 695, in _resolve_forward_ref
    obj = _typing_extra.eval_type_backport(obj, globalns=self._types_namespace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alex/work/pydantic/pydantic/_internal/_typing_extra.py", line 262, in eval_type_backport
    return typing._eval_type(  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alex/.pyenv/versions/3.12.4/lib/python3.12/typing.py", line 415, in _eval_type
    return t._evaluate(globalns, localns, type_params, recursive_guard=recursive_guard)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alex/.pyenv/versions/3.12.4/lib/python3.12/typing.py", line 938, in _evaluate
    eval(self.__forward_code__, globalns, locals_to_pass),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
NameError: name 'T' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/alex/Library/Application Support/JetBrains/PyCharm2024.1/scratches/scratch_26.py", line 6, in <module>
    @pydantic.validate_call(validate_return=True)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alex/work/pydantic/pydantic/validate_call_decorator.py", line 54, in validate
    validate_call_wrapper = _validate_call.ValidateCallWrapper(function, config, validate_return)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alex/work/pydantic/pydantic/_internal/_validate_call.py", line 59, in __init__
    schema = gen_schema.clean_schema(gen_schema.generate_schema(return_type))
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alex/work/pydantic/pydantic/_internal/_generate_schema.py", line 504, in generate_schema
    schema = self._generate_schema_inner(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alex/work/pydantic/pydantic/_internal/_generate_schema.py", line 749, in _generate_schema_inner
    return self.generate_schema(self._resolve_forward_ref(obj))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alex/work/pydantic/pydantic/_internal/_generate_schema.py", line 697, in _resolve_forward_ref
    raise PydanticUndefinedAnnotation.from_name_error(e) from e
pydantic.errors.PydanticUndefinedAnnotation: name 'T' is not defined
```

`_resolve_forward_ref` needs to get `type_params` from somewhere to pass to `eval_type_backport`, but the function object is all the way back in `ValidateCallWrapper.__init__` and not passed to `GenerateSchema` so it looks like it might be a lot of work to rewire things to pass it through.

Here's an alternative that works with `validate_return=True`: https://github.com/pydantic/pydantic/compare/alex/type-params2

There the line `namespace = {param.__name__: param for param in type_params} | namespace` is mimicking `typing.ForwardRef._evaluate`. It feels hacky and risky to do this ourselves rather than to let Python take care of it, so I'm not sure we should, but it looks like it might make things a lot easier. We'd still have to perform this logic in other places though.

(it was at this point that I noticed we don't seem to be passing all the correct namespaces anyway: https://github.com/pydantic/pydantic/issues/9744)

Note that even with the old syntax, we don't seem to validate generics properly anyway, e.g:

```python
from __future__ import annotations

import typing

import pydantic

T = typing.TypeVar('T')


@pydantic.validate_call(validate_return=True)
def my_max(args: list[T]) -> T:
    return 3


# I expect this to raise an error because T is both str and int, but nothing happens
assert my_max(['abc']) == 3
```

I know it's good to not raise the original NameError but this would be more compelling if building the correct schema did the correct thing.

**Closed** 2024-06-26 16:02 UTC
Labels: bug V2
