### ISSUE TITLE
Json serialization of datetime microseconds lacks the trailing digit when it's 0

### ISSUE THREAD

**Issue by Lawouach** [pydantic/pydantic#6999] opened 2023-08-02 21:35 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When serialization a datetime with json, the last difit is ignored for microseconds when that digit is a `0`. This causes trouble when testing for date time strings as The python `isoformat()` function will always set that `0`.

To be fair, it's unclear to me if that's really a bug in the sense where microseconds aren't really standards. But I was wondering how the crate in pydantic core made the decision for that last 0 digit.

### Example Code

```python
from datetime import datetime

from pydantic import BaseModel


class MyModel(BaseModel):
    ts: datetime


m = MyModel(ts=datetime.strptime("2023-08-02T19:39:41.147980", "%Y-%m-%dT%H:%M:%S.%f"))
print(m)
print(m.model_dump_json())
print(m.ts.isoformat())


```

Will output

```
ts=datetime.datetime(2023, 8, 2, 19, 39, 41, 147980)
{"ts":"2023-08-02T19:39:41.14798"}
2023-08-02T19:39:41.147980
```

Notice the json serialization lacking the ending `0`

### Python, Pydantic & OS Version

```text
pydantic version: 2.1.1
        pydantic-core version: 2.4.0
          pydantic-core build: profile=release pgo=true mimalloc=true
                 install path: /home/sylvain/dev/.venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.4 (main, Jun  9 2023, 07:59:55) [GCC 12.3.0]
                     platform: Linux-6.2.0-26-generic-x86_64-with-glibc2.37
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @davidhewitt

**Comment by Lawouach** [comment] 2023-08-02 21:42
This happens here https://docs.rs/speedate/latest/src/speedate/time.rs.html#48

Not sure why the crate trims the last digit when it's a `0`.

**Comment by davidhewitt** [comment] 2023-08-03 09:31
Thanks for the report. I think this is a duplicate of #6761

**Closed by davidhewitt** 2023-08-03 09:31 UTC
Labels: unconfirmed, bug V2

**Comment by Lawouach** [comment] 2023-08-03 10:56
Indeed. Thanks!
