### ISSUE TITLE
`Url` "subclasses" don't enforce constraints

### ISSUE THREAD

**Issue by sydney-runkle** [pydantic/pydantic#7353] opened 2023-09-06 14:04 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Currently they don't since they're actually just using `Annotated`.

Solution is to switch:

# what we currently have:
`HttpUrl = Annotated[Url, UrlConstraints(max_length=2083, allowed_schemes=['http', 'https'])]`

# should be more like:
```py
class HttpUrl(Url):
    constraints = UrlConstraints(max_length=2083, allowed_schemes=['http', 'https'])
```

Then we need a clever implementation of `__init_subclass__` or similar, in [this](https://github.com/pydantic/pydantic-core/blob/main/src/url.rs#L37-L39) bit of Rust.

Same goes for `MultiHostUrl`.
```py
from pydantic import HttpUrl, TypeAdapter, ValidationError

print(HttpUrl('ssh://www.google.com'))

try:
    HttpUrl('invalid')
except ValidationError as e:
    print(e)
else:
    raise RuntimeError('should have raised ValidationError')

ta = TypeAdapter(HttpUrl)
try:
    ta.validate_python('ssh://www.google.com')
except ValidationError as e:
    print(e)
else:
    raise RuntimeError('should have raised ValidationError')
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.3.0
        pydantic-core version: 2.7.0
          pydantic-core build: profile=release pgo=false
               python version: 3.10.12 (main, Jul  5 2023, 15:34:07) [Clang 14.0.6 ]
                     platform: macOS-10.16-x86_64-i386-64bit
     optional deps. installed: ['devtools', 'email-validator', 'typing-extensions']
```

**Comment by sydney-runkle** [comment] 2023-09-06 18:20
Looks like the ability to call `HttpUrl('ssh://www.google.com')` wasn't available in V1. Trying to do so produces the following error:

```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "pydantic/networks.py", line 187, in pydantic.networks.AnyUrl.__init__
TypeError: __init__() needs keyword-only argument scheme
```

I spoke with @adriangb, and it does seem as though this would be difficult to implement. If we implement some sort of clever `__init_subclass__` on the rust end of things, we're left with a Python class in the rust code.

Is there any particular reason why we want to be able to avoid the use of the type annotation in favor of a direct constructor call @samuelcolvin?

If we want to approach a solution solely from the `pydantic` side of things, we could implement something like this:
```
from typing import Annotated
from pydantic_core import Url
from pydantic import TypeAdapter
from pydantic.networks import UrlConstraints

class MyUrl(Url):
    url_constraints = UrlConstraints(allowed_schemes=['https'])

    def __new__(cls, url: str) -> 'MyUrl':
        return TypeAdapter(Annotated[Url, getattr(cls, 'url_constraints')]).validate_python(url)
```

However, this is flawed in that the return type is actually `Url`. Not to mention, obviously inefficient.

Excited to hear other thoughts on this.

**Comment by samuelcolvin** [comment] 2023-09-06 18:29
> Is there any particular reason why we want to be able to avoid the use of the type annotation in favor of a direct constructor call @samuelcolvin?

Well the simple version of doing that doesn't work.

We could create our own type and trick typing into thinking it's `Annotated`, but I'm not sure that's worth the extra complexity.

**Comment by haoyun** [comment] 2023-09-12 13:25
I was trying to implement something that making the `password` part of an url a `SecretStr` (pydantic/pydantic#3200), then accidently I came to this issue too, when I tried `AnyHttpUrl("hello://world")`. The docstring (editors show it) of `URL.__new__()` from `_pydantic_core.pyi` suggests me to do so....

**Comment by giacomorebecchi** [comment] 2023-11-28 11:04
Hi there, I'm commenting here to share my experience:
I was trying to obtain an equivalent of pydantic.AnyUrl that can accept having no host, and I did:
```
from typing import Annotated

from pydantic import AfterValidator, AnyUrl, UrlConstraints

GenericUrl = Annotated[
    AnyUrl,
    UrlConstraints(host_required=False),
]
```

now, I expected that calling GenericUrl.build(**kwargs) could accept no host.

I understand that the annotation will not change the class methods, but this is just an example to prove that the current interface is not particularly "developer-friendly".

Also, the fact that you cannot set attributes (e.g. I was trying to set the password with a new value) can be perceived as a limit.

If you happen to have suggestions on how to work around the two cases I mentioned, I would be very grateful. Thanks for the great work!

**Comment by psychedelicious** [comment] 2024-06-03 00:40
The fudged `Url` "subclasses" push a pydantic user towards improper usage of `Annotated`:
![image](https://github.com/pydantic/pydantic/assets/4822129/e5b095ef-eccf-4df7-8f25-472946f9a835)

According to the typing spec, an `Annotated` shouldn't be instantiated. See the last point in: https://typing.readthedocs.io/en/latest/spec/qualifiers.html#id4

Here's a `pyright` issue w/ comment from the maintainer: https://github.com/microsoft/pyright/issues/7370#issuecomment-1971493515

Making these proper classes would resolve this issue. Maybe #9147 has the same root cause.

FWIW, `pyright` does correctly infer the signature of `AnyHttpUrl`'s constructor:
![image](https://github.com/pydantic/pydantic/assets/4822129/4748769c-c2da-44b6-9528-dfa7c1b8aaa9)

**Comment by skeletorXVI** [comment] 2024-06-28 16:14
Another problem that could be solved by moving to dedicated classes is actually extending the `Url` class with additional functionality.

Currently regardless of what class defines the `url_schema`, Pydantic returns an `pydantic_core.Url` instance, as a result one has to move either Url validation to python by building a wrapper type or lose the `UrlConstraints` functionality for a reusable custom Url class.

An example where I ran into this issue is adding a `__truediv__` function to the Url class, to implement a similar experience as `pathlib.Path`.
My workaround is first apply the `UrlConstraints` and the run an AfterValidator that rebuilds the url with my url class.

My idea would allow something like this:

_Note that I am not familiar with the Python-Rust translation, so I am not too sure how this could be implemented_

```py
from typing import Any
from pydantic import GetCoreSchemaHandler
from pydantic_core import Url


class ExampleUrl(Url):
    @classmethod
    def __get_pydantic_core_schema__(
        cls, source: Any, handler: GetCoreSchemaHandler
    ) -> CoreSchema:
        return UrlSchema(url_class=cls, allowed_schemes=["example"])  # Specify while python class to use

    def infer_magic_link() -> str:
        ...

# Usage

class Config(BaseSettings):
    example_endpoint: ExampleUrl
    example_staging_endpoint: Annotated[ExampleUrl, UrlConstraints(default_port=2345)]


config = Config()
print(config.example_staging_endpoint.infer_magic_link())
```

**Comment by sydney-runkle** [comment] 2024-10-18 20:16
Following up here.

I think a subclass approach is good. This should help with https://github.com/pydantic/pydantic/issues/9523. That being said, we're definitely going to enforce constraints on `__init__`. That's what `TypeAdapter` is for.

**Closed** 2024-10-23 15:30 UTC
Labels: bug V2, urls
