### ISSUE TITLE
Using $ref" in examples raises KeyError on .model_json_schema() generation

### ISSUE THREAD

**Issue by vgavro** [pydantic/pydantic#9981] opened 2024-07-26 13:31 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Using {"$ref": "value"} in Field example raises KeyError on `.model_json_schema()` generation.

I'm not sure if this is json-schema spec problem or pydantic problem (is it REQUIRED to resolve `$ref` in any place in schema, even in examples?)

### Example Code

```Python
from pydantic import BaseModel, Field

class Test(BaseModel):
   x: dict = Field(example={"$ref": "#/components/schemas/Pet"})

Test.model_json_schema()

# raises KeyError: '#/components/schemas/Pet'
```

### Python, Pydantic & OS Version

```Text
             pydantic version: 2.8.2
        pydantic-core version: 2.20.1
          pydantic-core build: profile=release pgo=true
                 install path: /home/vgavro/work/myproj/.venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.9 (main, Apr 29 2024, 11:57:25) [GCC 13.2.1 20240417]
                     platform: Linux-6.8.7-arch1-2-x86_64-with-glibc2.39
             related packages: fastapi-0.109.2 typing_extensions-4.9.0 mypy-1.8.0 pydantic-settings-2.3.3
                       commit: unknown
```

**Comment by sydney-runkle** [comment] 2024-07-26 18:34
Yep, marking this as a dupe of https://github.com/pydantic/pydantic/issues/9783.

Thanks for your question @vgavro!

**Comment by Danipulok** [comment] 2024-08-27 16:52
Hey here!

@sydney-runkle, I just tested a similar code at the beta pydantic version.
But I still have the `KeyError`, even though it's supposed to be resolved?
The example from #9783 works for me okay, but not this case.

**Example code**
```python
from pydantic import BaseModel, Field


class Test(BaseModel):
    x: dict = Field(
        examples=[
            # {"key": "val"},  # ok
            # {"$key": "val"},  # ok
            {"$ref": "val"},  # error
        ],
    )


Test.model_json_schema()
```

**Python, Pydantic & OS Version**
```
             pydantic version: 2.9.0b1
        pydantic-core version: 2.23.0
          pydantic-core build: profile=release pgo=false
                 install path: D:\Code\Aliyoop\aliyoop-ai\.venv\Lib\site-packages\pydantic
               python version: 3.12.3 (tags/v3.12.3:f6650f9, Apr  9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)]
                     platform: Windows-10-10.0.19045-SP0
             related packages: fastapi-0.112.1 mypy-1.11.1 pydantic-settings-2.4.0 typing_extensions-4.12.2
                       commit: unknown
```

Is this an expected behavior?

**Comment by sydney-runkle** [comment] 2024-08-28 19:02
@Danipulok,

Thanks for bringing this to our attention! I'll take a look at fixing this for our next beta release.

**Comment by sydney-runkle** [comment] 2024-09-04 10:21
Yeah, reopening this - looks like this isn't a dupe of the original issue. Not sure if we want to support this or not, but we can try in v2.10.

**Comment by sydney-runkle** [comment] 2024-09-16 15:42
Alright, upon further investigation here - we don't plan to support this.

[`$ref`](https://json-schema.org/draft/2020-12/json-schema-core#name-direct-references-with-ref) is used to refer to a schema, and `examples` doesn't contain any schema, so support for this is out of scope.

This is a bit inconsistent with the above referenced change that added support for `http/s` valued refs, and I'd be willing to revert that in the name of consistency if desired.

**Comment by sydney-runkle** [comment] 2024-09-16 15:47
Actually, reopening. We can skip the `examples` key and let folks inject whatever they want here.

**Closed** 2024-09-16 22:24 UTC
Labels: bug V2

**Comment by Danipulok** [comment] 2024-09-16 22:43
@sydney-runkle , hey again!
Here's the example that should be working IMHO and do not raise an error
```
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, ConfigDict, Field


_examples = [
    {"type": "string", "format": "email"},
    {
        "type": "object",
        "required": ["name"],
        "properties": {
            "name": {"type": "string"},
            "address": {"$ref": "#/components/schemas/Address"},
            "age": {"type": "integer", "format": "int32", "minimum": 0},
        },
    },
    {"type": "object", "additionalProperties": {"type": "string"}},
    {
        "type": "object",
        "additionalProperties": {"$ref": "#/components/schemas/ComplexModel"},
    },
    {
        "type": "object",
        "properties": {
            "id": {"type": "integer", "format": "int64"},
            "name": {"type": "string"},
        },
        "required": ["name"],
        "example": {"name": "Puma", "id": 1},
    },
    {
        "type": "object",
        "required": ["message", "code"],
        "properties": {
            "message": {"type": "string"},
            "code": {"type": "integer", "minimum": 100, "maximum": 600},
        },
    },
    {
        "allOf": [
            {"$ref": "#/components/schemas/ErrorModel"},
            {
                "type": "object",
                "required": ["rootCause"],
                "properties": {"rootCause": {"type": "string"}},
            },
        ]
    },
    {
        "type": "object",
        "discriminator": {"propertyName": "petType"},
        "properties": {
            "name": {"type": "string"},
            "petType": {"type": "string"},
        },
        "required": ["name", "petType"],
    },
    {
        "description": "A representation of a cat. "
                       "Note that `Cat` will be used as the discriminator value.",
        "allOf": [
            {"$ref": "#/components/schemas/Pet"},
            {
                "type": "object",
                "properties": {
                    "huntingSkill": {
                        "type": "string",
                        "description": "The measured skill for hunting",
                        "default": "lazy",
                        "enum": [
                            "clueless",
                            "lazy",
                            "adventurous",
                            "aggressive",
                        ],
                    }
                },
                "required": ["huntingSkill"],
            },
        ],
    },
    {
        "description": "A representation of a dog. "
                       "Note that `Dog` will be used as the discriminator value.",
        "allOf": [
            {"$ref": "#/components/schemas/Pet"},
            {
                "type": "object",
                "properties": {
                    "packSize": {
                        "type": "integer",
                        "format": "int32",
                        "description": "the size of the pack the dog is from",
                        "default": 0,
                        "minimum": 0,
                    }
                },
                "required": ["packSize"],
            },
        ],
    },
]


class Schema(BaseModel):
    const: Optional[Any] = None
    multipleOf: Optional[float] = Field(default=None, gt=0.0)
    maximum: Optional[float] = None
    exclusiveMaximum: Optional[float] = None
    minimum: Optional[float] = None
    exclusiveMinimum: Optional[float] = None
    maxLength: Optional[int] = Field(default=None, ge=0)
    minLength: Optional[int] = Field(default=None, ge=0)
    pattern: Optional[str] = None
    maxItems: Optional[int] = Field(default=None, ge=0)
    minItems: Optional[int] = Field(default=None, ge=0)
    uniqueItems: Optional[bool] = None
    maxContains: Optional[int] = Field(default=None, ge=0)
    minContains: Optional[int] = Field(default=None, ge=0)
    maxProperties: Optional[int] = Field(default=None, ge=0)
    minProperties: Optional[int] = Field(default=None, ge=0)
    required: Optional[List[str]] = None
    dependentRequired: Optional[Dict[str, List[str]]] = None
    schema_format: Optional[str] = Field(default=None, alias="format")
    contentEncoding: Optional[str] = None
    contentMediaType: Optional[str] = None
    title: Optional[str] = None
    description: Optional[str] = None
    default: Optional[Any] = None
    deprecated: Optional[bool] = None
    readOnly: Optional[bool] = None
    writeOnly: Optional[bool] = None
    examples: Optional[List[Any]] = None
    example: Optional[Any] = None

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
        json_schema_extra={"examples": _examples},
    )


schema = Schema()
print(schema.model_json_schema())
```

It's a big piece of code to give full context of actual real-world example and the code is taken from [openapi-pydantic](https://github.com/mike-oakley/openapi-pydantic), which aims to port [JsonSchema](https://json-schema.org/) to python.

But if we try to dump json schema of `schema` instance, we get `KeyError: '#/components/schemas/Address'` from the issue.
I tested it just now with the latest `pydantic` release: ` 2.9.1`.

So is there anything that can be done inside `pydantic` so `model_json_schema` does not raise an error if some examples are invalid, perhaps?

**Comment by Viicos** [comment] 2025-01-20 10:02
@vgavro, a [recent regression](https://github.com/pydantic/pydantic/issues/11304) was introduced by the changes fixing this issue. Your use case is still supported but you will have to make it compliant to the JSON Schema spec by using:

```python
from pydantic import BaseModel, Field

class Test(BaseModel):
   x: dict = Field(examples=[{"$ref": "#/components/schemas/Pet"}])
```
