### ISSUE TITLE
Serialize with alias as ConfigDict

### ISSUE THREAD

**Issue by mmzeynalli** [pydantic/pydantic#10107] opened 2024-08-12 14:43 UTC
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

If I have a superclass model which has fields with aliases, I would like to be able to define how to serialize in subclass. For example, I have class which converts date object to month and year as ints, and I have two models which inherits this model:

```python
class DateToMonthYearSchema(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    issue_date: date = Field(
        exclude=True,
        alias='start_date',
    )
    expire_date: Optional[date] = Field(
        default=None,
        exclude=True,
        alias='end_date',
    )

    @computed_field(alias='start_date_month')  # type: ignore[misc]
    @property
    def issue_date_month(self) -> int:
        return self.issue_date.month

    @computed_field(alias='start_date_year')  # type: ignore[misc]
    @property
    def issue_date_year(self) -> int:
        return self.issue_date.year
        
class UserWorkExperienceSchema(DateToMonthYearSchema):
    id: int
    currently_working: bool

class CertificateSchema(DateToMonthYearSchema):
    id: int
```

Ideally, I can use `.model_dump(by_alias=True), however, these two models are also part of another model:

```python
class UserProfileSchema(BaseModel):
    work_experiences: list[UserWorkExperienceSchema] = []
    certificates: list[CertificateSchema] = []
 ```
 
 

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [X] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [X] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment] 2024-08-12 23:48
Hey, thanks for the request. Going to close this as a duplicate of https://github.com/pydantic/pydantic/issues/8379

**Closed by sydney-runkle** 2024-08-12 23:48 UTC
Labels: feature request

**Comment by mmzeynalli** [comment] 2024-08-13 07:22
Yep, sorry, searched for similar name, must have missed it. Thanks
