### ISSUE TITLE
in a nested data structure, model_dump_json fails to dump attributes of a subclass

### ISSUE THREAD

**Issue by mephinet** [pydantic/pydantic#7326] opened 2023-09-04 13:24 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I am using pydantic 2.3.0 to create a JSON dump of a nested data structure where inheritance is used.

The nesting structure is this: 
1. Materials is the root structure, which contains a list of Material instances (or of subclasses - like the one called DataMaterial).
2. DataMaterials contain a list of DataView instances.
3. DataViews have a name property.

My example DataView instance has an attribute name set to "foo". While `model_dump_json` on the DataMaterial (nesting level 2) dumps the name property, it is no longer dumped when the root structure, Materials, is dumped.

When I change the type annotation from `list[Material]` to `list[DataMaterial]`, this issue is gone - so my understanding of the issue is that model_dump fails to check if the list elements are of a subclass of the specified class - and thus does not use the subclass' type definition.

The reproducer can also be found at https://gist.github.com/mephinet/abfd1ceafe29085c02e429111df1e348 

### Example Code

```Python
import pydantic


# nesting level 3:
class DataView(pydantic.BaseModel):
    name: str


# nesting level 2:
class Material(pydantic.BaseModel):
    id: int


class DataMaterial(Material):
    views: list[DataView] = []


# nesting level 1
class Materials(pydantic.BaseModel):
    materials: list[Material]


dm = DataMaterial(id=42, views=[DataView(name="foo")])
materials = Materials(materials=[dm])

# the name attribute is available at nesting level 2
d1 = dm.model_dump_json()
print(d1)
assert "foo" in d1

# but not in nesting level 3
d2 = materials.model_dump_json()
print(d2)
assert "foo" in d2
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.3.0
        pydantic-core version: 2.6.3
          pydantic-core build: profile=release pgo=true
                 install path: /home/.../env/lib/python3.11/site-packages/pydantic
               python version: 3.11.5 (main, Aug 28 2023, 20:02:58) [GCC 13.2.1 20230801]
                     platform: Linux-6.4.12-arch1-1-x86_64-with-glibc2.38
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @adriangb

**Comment by andresliszt** [comment] 2023-09-04 17:44
What about doing this
```
class Materials(pydantic.BaseModel):
    materials: list[Material|DataMaterial]
```

**Comment by adriangb** [comment] 2023-09-05 14:26
Pydantic dumps according to the schema, not the objects. Since you declared `materials: list[Material]` it will only look for the `id: int` field in the items of the list, not the `views: list[DataView] = []` field. For more info see https://github.com/pydantic/pydantic/issues/6403#issuecomment-1620252270.

I would make it a union for now.

**Comment by mephinet** [comment] 2023-09-05 14:34
Thanks for this pointer! Having seen `SerializeAsAny`, maybe a `SerializeAsSubclass` would be an option...

**Comment by adriangb** [comment] 2023-09-05 14:34
`SerialzieAsAny` already exists, it just can't be applied "globally" or at the "model level"

**Comment by drussier** [comment] 2023-09-06 13:13
@mephinet I faced the same issue
this https://docs.pydantic.dev/latest/usage/serialization/#serializing-with-duck-typing solved my problem

Refer to https://docs.pydantic.dev/latest/usage/serialization/#modeldumpjson 
> Subclasses of standard types are automatically dumped like their super-classes
More specifically, only the fields from the annotated type will be included in the dumped object

> Migration warning :
This behavior is different from how things worked in Pydantic V1, where we would always include all (subclass) fields when recursively dumping models to dicts. The motivation behind this change in behavior is that it helps ensure that you know precisely which fields could be included when serializing, even if subclasses get passed when instantiating the object. In particular, this can help prevent surprises when adding sensitive information like secrets as fields of subclasses.

**Comment by sydney-runkle** [comment] 2023-10-30 15:23
Closing, as this is expected behavior and the desired behavior can be configured with the help of the docs links above.

**Closed by sydney-runkle** 2023-10-30 15:23 UTC
Labels: unconfirmed, bug V2
