### ISSUE TITLE
Add an exception to get secret values when dumping JSON

### ISSUE THREAD

**Issue by chermed** [pydantic/pydantic#7242] opened 2023-08-24 10:50 UTC
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Overview

I'm developing an API that handle some sensitive data, the best practice for that is to hint my fields with the `SecretStr` or `SecretBytes`.

Everything is good when the client request data, I can only return the dump json that will automatically redact the sensitive data.

I didn't find any way to put the sensitive data directly to the database without any redaction, In my case it's the json received by the client that I want to put to the database.

I follow the official documentation, and the only way to handle that is to get programmatically the values:
(https://docs.pydantic.dev/latest/usage/types/secrets/)

```python
class SimpleModel(BaseModel):
    password: SecretStr
    password_bytes: SecretBytes


sm = SimpleModel(password='IAmSensitive', password_bytes=b'IAmSensitiveBytes')

# Standard access methods will not display the secret
print(sm)
#> password=SecretStr('**********') password_bytes=SecretBytes(b'**********')
print(sm.password)
#> **********
print(sm.model_dump())
"""
{
    'password': SecretStr('**********'),
    'password_bytes': SecretBytes(b'**********'),
}
"""
print(sm.model_dump_json())
#> {"password":"**********","password_bytes":"**********"}

# Use get_secret_value method to see the secret's content.
print(sm.password.get_secret_value())
#> IAmSensitive
print(sm.password_bytes.get_secret_value())
```

### What I expect as feature:

The feature that I request is to evolve the dump json to request in some exception to dump the secrets:

```python
sm.model_dump_json(with_secrets=True)
```

or using `field_serializer` and adding `sensitive` to `when_used`:

```python
class SimpleModelDumpable(BaseModel):
    password: SecretStr
    password_bytes: SecretBytes

    @field_serializer('password', 'password_bytes', when_used='sensitive')
    def dump_secret(self, v):
        return v.get_secret_value()


sm2 = SimpleModelDumpable(
    password='IAmSensitive', password_bytes=b'IAmSensitiveBytes'
)

print(sm2.model_dump_json(mode="sensitive"))
#> {"password":"IAmSensitive","password_bytes":"IAmSensitiveBytes"}
print(sm2.model_dump_json())
#> {"password":"*********","password_bytes":"******"}
```

### Why this request:

I see many uses cases on which the API is like a validator of data and a proxy between a client and a database tier, there are also many cascading models on which we have to dive to get these values, patch the object and then send to the database.
I think that by implementing this feature we can do on the API something like:
1. On PUT or POST: model_dump_json(mode="sensitive") then send to the database
2. On GET : model_dump_json() then return to the client

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [X] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

Selected Assignee: @adriangb

**Comment by davidhewitt** [comment] 2023-08-24 13:57
I think the way to solve this should be by #7143. Basically, the solution should look like this if `context` was implemented for serialization:

```python
from pydantic import BaseModel, SecretStr, SecretBytes, field_serializer

class SimpleModelDumpable(BaseModel):
    password: SecretStr
    password_bytes: SecretBytes

    @field_serializer('password', 'password_bytes')
    def dump_secret(self, v, info):
        if info.context.get('sensitive', False):
            return v.get_secret_value()
        return str(v)


sm2 = SimpleModelDumpable(
    password='IAmSensitive', password_bytes=b'IAmSensitiveBytes'
)

print(sm2.model_dump_json(context={'sensitive': True}))
#> {"password":"IAmSensitive","password_bytes":"IAmSensitiveBytes"}
```

I'm going to close this as a duplicate of #7143, please ping if you disagree.

**Closed by davidhewitt** 2023-08-24 13:57 UTC
Labels: feature request, unconfirmed

**Comment by nextmat** [comment] 2024-08-14 22:38
For anyone else running into this issue, there is further discussion in https://github.com/pydantic/pydantic-core/issues/851#issuecomment-1663759276 and some historical context in https://github.com/pydantic/pydantic/issues/925.

**Comment by radovanZRasa** [comment] 2025-02-27 23:48
Not having this as a built-in feature for secret types is kind of a bummer but there is a simple solution for `SecretStr`. 
If you need a re-usable type like `SecretStr` you can use `Annotated` to help you out:

```python
REVEAL_SENSITIVE_INFO = "reveal_sensitive_info"

def serialize_sensitive_info(input_value: SecretStr,
                                    info: FieldSerializationInfo) -> str:
    if info.context.get(REVEAL_SENSITIVE_INFO, False):
        return input_value.get_secret_value()
    return str(input_value)

SensitiveInfo = Annotated[SecretStr,
    PlainSerializer(func=serialize_sensitive_info, return_type=Any, when_used="always")]


class User:
    username: str
    password: SensitiveInfo

user = User(username="John", password="my_secret")

user.model_dump(context={REVEAL_SENSITIVE_INFO: True})
# {'username': 'John', 'password': 'my_secret'}

user.model_dump(context={REVEAL_SENSITIVE_INFO: False})
# {'username': 'John', 'password': '***********'}

user.model_dump_json(context={REVEAL_SENSITIVE_INFO: True})
# {'username': 'John', 'password': 'my_secret'}

user.model_dump_json(context={REVEAL_SENSITIVE_INFO: False})
# {'username': 'John', 'password': '***********'}
```

Potentially this can be expanded to generic types to include all secret types.

**Comment by bluenote10** [comment] 2025-05-22 06:52
@davidhewitt If I understand it correctly https://github.com/pydantic/pydantic/issues/7143 is only the foundation for this feature, but it doesn't directly address it, no? At least #7143 seems to be implemented, and yet the possibility to **temporarily** allow dumping secrets is still missing as far as I can see. So would it make sense to re-open this issue?
