### ISSUE TITLE
Json dumping for dict key seems to be broken

### ISSUE THREAD

**Issue by arpit15** [pydantic/pydantic#10724] opened 2024-10-26 00:03 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I am trying to convert a dict with keys being frozen pydantic dataclass to json and back. However, this seems to fail. I have attached a simple example for the same. 

### Example Code

```Python
from dataclasses import field
from typing import Dict, Optional, Tuple

from pydantic.dataclasses import dataclass
from pydantic import BaseModel, RootModel, TypeAdapter

@dataclass(frozen=True)
class TypeA:
    name: str
    counter: int

@dataclass
class TypeB:
    fieldC: str
    fieldD: Dict[TypeA, str] = field(default_factory=dict)

objA = TypeA(name="foo", counter=0)
objB = TypeB(fieldC="shrimp", fieldD={
    objA: "bar"
})


print("-----")
print(objA)
print("--- JSON ---")
print(RootModel[TypeA](objA).model_dump_json())
print("----")
print(objB)
print("--- JSON ---")
json_val = RootModel[TypeB](objB).model_dump_json()
print(json_val)
print("----")
print("RECONSTRUCTED")
reconstructed_objB = TypeAdapter(TypeB).validate_json(json_val)
print(reconstructed_objB.fieldD)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.3
        pydantic-core version: 2.14.6
          pydantic-core build: profile=release pgo=true
                 install path: /home/username/pydantic_checks/.venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.4 (main, Aug 14 2023, 05:19:15) [GCC 7.5.0]
                     platform: Linux-6.8.0-47-generic-x86_64-with-glibc2.35
             related packages: typing_extensions-4.12.2
```

**Comment by mpkocher** [comment] 2024-10-26 06:30
I'm not sure that this specific case is well-defined using JSON as an interchange format. 

Possible different approaches/workarounds:

1. Fundamentally hook into the core serialization and map the structure into a list[{Key, Value}] (or similar) to get the Obj -> Json -> Obj working
2. Create an intermediate data model in Pydantic and add `to_X` method and `from_X` classmethod to get the Obj -> Obj2 -> Json -> Obj2 -> Obj

An example of approach 2:

```python
from typing import Generic, TypeVar, Self
from pydantic import BaseModel, ConfigDict

K = TypeVar("K")
V = TypeVar("V")


class KeyValue(BaseModel, Generic[K, V]):
    key: K
    value: V


class Alpha(BaseModel):
    model_config = ConfigDict(frozen=True)
    name: str
    counter: int


class Beta(BaseModel):
    a: str
    b: dict[Alpha, str]


class BetaIntermediate(BaseModel):
    a: str
    b: list[KeyValue[Alpha, str]]

    def to_beta(self) -> Beta:
        return Beta(a=self.a, b={x.key: x.value for x in self.b})

    @classmethod
    def from_beta(cls, beta: Beta) -> Self:
        return BetaIntermediate(
            a=beta.a,
            b=[KeyValue[Alpha, str](key=k, value=v) for k, v in beta.b.items()],
        )


def demo() -> None:

    beta = Beta(
        a="shrimp",
        b={Alpha(name="a0", counter=7): "0", Alpha(name="a1", counter=1): "1"},
    )

    # intermediate structure
    i = BetaIntermediate.from_beta(beta)
    jx = i.model_dump_json()
    beta2 = i.model_validate_json(jx).to_beta()

    print((beta, beta2))
    print(beta == beta2)
```

I'm not sure that Pydantic should get tangled up trying to solve these types of serialization use cases.

**Comment by arpit15** [comment] 2024-10-28 00:37
Thanks for detailed example. 
I am not sure if I understand why JSON is not a valid interchange format here. I am explicitly passing the types at validation time. I expect pydantic to pass the data directly to the validator of each data member. 
If I change the `TypeB` to following things work for me. 

```
@dataclass
class TypeB:
    fieldC: str
    fieldD: List[Tuple[TypeA, str]] = field(default_factory=list)
```
It seems that the issue is specifically in converting `Dict[TypeA, str]` to json. I am wondering if there is any pydantic bug related to this.

**Comment by mpkocher** [comment] 2024-10-28 03:47
Given the ubiquity of JSON, it can be useful to spend some time familiarizing yourself with the core concepts of the data interchange format. 

- https://json-schema.org/understanding-json-schema/reference/object#object
- https://en.wikipedia.org/wiki/JSON

**Comment by arpit15** [comment] 2024-10-28 16:45
Thanks for the links. After reading through the object section, I don't see any issues in obj -> str -> obj for frozen dataclass. Can you kindly give an example of the issue pydantic would face in parsing things correctly where Dict key is an hashable object which can be converted into string?

**Comment by sydney-runkle** [comment] 2024-10-28 16:49
Hi! Going to close this as a dupe of https://github.com/pydantic/pydantic/issues/9453. Thanks for reporting the issue - feel free to track our progress on support for this there!

**Closed by sydney-runkle** 2024-10-28 16:49 UTC
Labels: bug V2, pending
