### ISSUE TITLE
Type error because `Json` is aliased to `str`

### ISSUE THREAD

**Issue by Dreamsorcerer** [pydantic/pydantic#4105] opened 2022-05-22 20:28 UTC
When using the `Json` type, e.g. as `Json[Foo]`, mypy produces this error:
```
error: "str" expects no type arguments, but 1 given  [type-arg]
or
error: Type application targets a non-generic function or class  [misc]
```

The latter error being produced with:
```
config = parse_obj_as(Json[Config], txt)
```

This appears to be because the type is just an alias for `str` when type checking:
https://github.com/samuelcolvin/pydantic/blob/master/pydantic/types.py#L789

This seems a rather bizarre choice to me. If the runtime type doesn't work with type checking, then it should surely atleast use a `Generic`.

**Comment by samuelcolvin** [comment] 2022-05-22 20:44
Ye, well let's improve it in V2. Will all be easier now we've dropped 3.6.

**Comment by zevisert** [comment] 2022-10-26 22:48
Dupe of #2990?

**Closed** 2022-10-26 22:56 UTC
Labels: bug
