### ISSUE TITLE
GenericModel.construct() typings is broken

### ISSUE THREAD

**Issue by bogdandm** [pydantic/pydantic#1354] opened 2020-03-31 08:22 UTC
# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.4
            pydantic compiled: True
                 install path: .../venv/lib/python3.7/site-packages/pydantic
               python version: 3.7.5 (default, Nov  7 2019, 10:50:52)  [GCC 8.3.0]
                     platform: Linux-5.3.0-42-generic-x86_64-with-Ubuntu-18.04-bionic
     optional deps. installed: ['typing-extensions']

mypy -V        
mypy 0.770 (also tested on 740)
```

```py
from pydantic.generics import GenericModel
from typing import TypeVar, Generic

T = TypeVar('T')

class GenericBase(GenericModel, Generic[T]):
	code: T

class StrCode(GenericBase[str]):
	detail: str

StrCode(code='not_found', detail='Not found')  # This is fine
StrCode.construct(code='not_found', detail='Not found')  # error: Argument "code" to "construct" of "StrCode" has incompatible type "str"; expected "T"
```

So it seems like TypeVar is not resolved in `construct` signature at all or something like this.

**Comment by samuelcolvin** [comment] 2020-04-04 14:37
Are you using the [pydantic mypy plugin](https://pydantic-docs.helpmanual.io/mypy_plugin/)?

If not, try that. If so, I'd be happy to accept a PR to fix this, but won't be looking at it myself any time soon.

**Comment by bogdandm** [comment] 2020-04-04 17:45
Yes, I'm using it, `__init__` method works perfectly fine. 

I'm not familiar with mypy plugin systems so I'm not sure if I can fix it by myself. But maybe I will try :)

**Comment by samuelcolvin** [comment] 2020-04-04 17:50
me neither, it's pretty complex.

It was a pretty impress piece of work by @dmontagu.

**Comment by PrettyWood** [comment] 2020-12-18 22:48
Hi @bogdandm 
I can't reproduce the issue
```
▶ python -c "import pydantic.utils; print(pydantic.utils.version_info())"
             pydantic version: 1.4
            pydantic compiled: False
                 install path: /Users/ericjolibois/pydantic/pydantic
               python version: 3.7.7 (default, Mar 18 2020, 12:01:21)  [Clang 10.0.1 (clang-1001.0.46.4)]
                     platform: Darwin-18.7.0-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions', 'email-validator', 'devtools']
```
```
Success: no issues found in 1 source file
```
The only difference is that I don't run with cython. Do you still have the issue? If yes, does it work when not compiled?
Thanks!

**Comment by bogdandm** [comment] 2020-12-21 09:30
Hello @PrettyWood 

The issue is still there even with not compiled version:
```
❯ pip install git+https://github.com/samuelcolvin/pydantic.git
❯ mypy sandbox.py                                             
sandbox.py:26: error: Argument "code" to "construct" of "StrCode" has incompatible type "str"; expected "T"  [arg-type]
    StrCode.construct(code='not_found', detail='Not found')  # error: Argument "code" to "construct" of "StrCode" has incompatible type "str"; expected "T"
```
(same code example)

```
venv ❯ python -c "import pydantic.utils; print(pydantic.utils.version_info())"
             pydantic version: 1.7.2
            pydantic compiled: False
                 install path: /opt/projects/.../venv/lib/python3.8/site-packages/pydantic
               python version: 3.8.6 (default, Oct  6 2020, 03:22:36)  [GCC 7.5.0]
                     platform: Linux-5.4.0-58-generic-x86_64-with-glibc2.27
     optional deps. installed: ['typing-extensions']
```

MyPy config:
```
[mypy]
pretty = True
show_error_codes = True
warn_redundant_casts = True
ignore_missing_imports = True
warn_unused_configs = True

python_version = 3.8
junit_xml = junit_report.xml
plugins = pydantic.mypy

[pydantic-mypy]
warn_untyped_fields = True
```

**Comment by PrettyWood** [comment] 2020-12-21 14:12
Hello @bogdandm 
You're right I managed to reproduce thanks! The error is not only for `construct` but also for `__init__` (if you set `init_typed`).
The goal is hence to support properly generics with the custom plugin. Don't know how hard it is. Maybe @dmontagu can guide us here :)

**Comment by lig** [comment] 2023-08-17 14:08
This is fixed in Pydantic v2
 
The following test passes with Pydantic v2.2.0

```py
def test_1354():
    from typing import Generic, TypeVar

    from pydantic import BaseModel

    T = TypeVar('T')

    class GenericBase(BaseModel, Generic[T]):
        code: T

    class StrCode(GenericBase[str]):
        detail: str

    assert StrCode(code='not_found', detail='Not found').model_dump() == {'code': 'not_found', 'detail': 'Not found'}
    StrCode.model_construct(code='not_found', detail='Not found').model_dump() == {'code': 'not_found', 'detail': 'Not found'}
```

**Closed by lig** 2023-08-17 14:08 UTC
Labels: bug V1
