### ISSUE TITLE
Pydantic 2.5.0's project's description exceeds Azure DevOps limits

### ISSUE THREAD

**Issue by GiorgosPa** [pydantic/pydantic#8105] opened 2023-11-14 09:31 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

We are using Azure DevOps artifacts for installing our dependencies in our CICD pipilenes and they started failing this morning with the error bellow:

ERROR: Could not install requirement pydantic>=2.0.1 from https://pkgs.dev.azure.com/transport-logistics/d078984b-b6cf-4504-8f42-3ad03340e820/_packaging/8faec573-4cef-4281-976b-bed281e3d20f/pypi/download/pydantic/2.5/pydantic-2.5.0-py3-none-any.whl#sha256=7ce6e766c456ad026fe5712f7bcf036efc34bd5d107b3e669ef7ea01b3a9050c (from prids-adx-metrics==2.0.0) because of HTTP error 400 Client Error: Bad Request - The package description exceeds the maximum length of 324608 bytes. 

The project description outgrew Azure DevOps limit. Although there is not something wrong with the package, I expect it will effect other organisations as well and it is something worth bringing under your attention.

### Example Code

```Python
Not relevant
```

### Python, Pydantic & OS Version

```Text
This is not relevant for this issue
```

**Comment by chan-vince** [comment] 2023-11-14 09:37
I also just hit this issue. Just to clarify, this is a 'problem' with Azure DevOps Artifacts. We are using it to vendor our packages with PyPI upstream. The issue has been brought up before on their forum: https://developercommunity.visualstudio.com/t/python-package-cannot-be-installed-from-azure-arti/1434932?from=email&viewtype=all

While it is not strictly an issue of pydantic, it would be great to update [the PyPI description](https://pypi.org/project/pydantic/) to remove some of the older release details since it goes back to v1.0b1 and there is already a cutoff link to the full changelog on the website.

**Comment by Viicos** [comment] 2023-11-14 09:38
Duplicate of https://github.com/pydantic/pydantic/issues/8096

**Comment by hramezani** [comment] 2023-11-14 09:54
Fixed in https://github.com/pydantic/pydantic/commit/9a9ad407a239c30e7decfde809bc8a2c7303f856

**Closed by hramezani** 2023-11-14 09:54 UTC
Labels: bug V2, pending
