### ISSUE TITLE
Model with variadic generics raise a `TypeError`

### ISSUE THREAD

**Issue by azmeuk** [pydantic/pydantic#9766] opened 2024-06-26 09:11 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

This may be related to [#5804](https://github.com/pydantic/pydantic/issues/5804). Currently, creating a model with variadic generics and several type parameters raise an exception like `TypeError: Too many parameters for <class '__main__.Foo'>; actual 3, expected 1`:

### Example Code

```Python
import typing
import pydantic


Things = typing.TypeVarTuple("Things")

class Foo(pydantic.BaseModel, typing.Generic[*Things]):
    ...

Foo[int, str, bool]
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.7.4
        pydantic-core version: 2.18.4
          pydantic-core build: profile=release pgo=true
                 install path: /home/eloi/.cache/pypoetry/virtualenvs/scim2-models-TH2HRh4a-py3.12/lib/python3.12/site-packages/pydantic
               python version: 3.12.4 (main, Jun  7 2024, 06:33:07) [GCC 14.1.1 20240522]
                     platform: Linux-6.9.6-arch1-1-x86_64-with-glibc2.39
             related packages: pydantic-settings-2.3.3 typing_extensions-4.12.2
                       commit: unknown
```

**Comment by sydney-runkle** [comment] 2024-06-26 17:01
Hi @azmeuk,

Thanks for the request! Indeed, related to #5804. We currently have the necessary infrastructure for this support this in `pydantic-core`, but not yet in `pydantic`. I'm going to close this as a duplicate of #5804.

I do think this is something worth supporting - I'll mark as `help wanted` in case anyone is interested in picking this up before I get around to it!

**Closed by sydney-runkle** 2024-06-26 17:01 UTC
Labels: feature request
