### ISSUE TITLE
Pydantic unable to generate schema() when one of the fields is of type Type

### ISSUE THREAD

**Issue by Koratun** [pydantic/pydantic#4051] opened 2022-05-07 17:17 UTC
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.9.0
            pydantic compiled: True
                 install path: C:\Users\...\.venv\Lib\site-packages\pydantic
               python version: 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)]
                     platform: Windows-10-10.0.22000-SP0
     optional deps. installed: ['typing-extensions']
```

```py
from pydantic import BaseModel
from typing import Type

class TypeTest(BaseModel):
  t: Type[BaseModel]

print(TypeTest.schema())
```

Stack Trace:
```py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pydantic\main.py", line 647, in pydantic.main.BaseModel.schema
  File "pydantic\schema.py", line 185, in pydantic.schema.model_schema
  File "pydantic\schema.py", line 617, in pydantic.schema.model_process_schema
  File "pydantic\schema.py", line 658, in pydantic.schema.model_type_schema
  File "pydantic\schema.py", line 258, in pydantic.schema.field_schema
  File "pydantic\schema.py", line 563, in pydantic.schema.field_type_schema
  File "pydantic\schema.py", line 922, in pydantic.schema.field_singleton_schema
  File "C:\Users\...\AppData\Local\Programs\Python\Python39\lib\abc.py", line 123, in __subclasscheck__
    return _abc_subclasscheck(cls, subclass)
TypeError: issubclass() arg 1 must be a class
```

Instantiating the TypeTest with various types works and raises Validation errors as appropriate.
```py
>>> TypeTest(t=BaseModel)
TypeTest(t=<class 'pydantic.main.BaseModel'>)
>>> TypeTest(t=TypeTest)  
TypeTest(t=<class '__main__.TypeTest'>)
>>> TypeTest(t=int)      
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pydantic\main.py", line 331, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for TypeTest
t
  subclass of BaseModel expected (type=type_error.subclass; expected_class=BaseModel)
```

**Comment by samuelcolvin** [comment] 2022-05-14 11:33
Is this specific to `Type[BaseModel]` or would it happen with `Tuple[AnyClass]`?

PR welcome to fix this, shouldn't be too hard to ignore or use something general for these fields.

**Comment by ofercaspi** [comment] 2022-05-18 11:32
Looks like a duplicate of #3390

**Closed** 2022-08-11 11:47 UTC
Labels: bug
