### ISSUE TITLE
Nested class in input considered a parameter in 2.7?

### ISSUE THREAD

**Issue by judgeaxl** [pydantic/pydantic#9242] opened 2024-04-14 09:39 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I'm returning data in a FastAPI application. The data is a subclass of BaseModel. The class contains a nested class called "Meta", which is used by some serialization customizations. In Pydantic < 2.7 this works fine, even though the base response class is configured with extra="forbid". In 2.7 it fails on "extra attribute Meta not allowed". Reverting back to < 2.7 works.

There are some changelog entries about fixing config inheritance, and private attribute settings, so maybe this was just broken before, but would a nested class normally be considered an attribute to be serialized? It's not listed in the section about automatically excluded attributes.

The real case is a bit more complex than I can convey below, so please consider this more of a question about expected behaviour than an absolute bug at this point.

### Example Code

```Python
# I've been unable to repro the bug in a minimal example, but the general structure is this:

class MyBase(BaseModel:
    # Intention is to set default extra settings for all subclasses
    model_config = ConfigDict(extra="forbid")

class Data(MyBase):
    class Meta:
        internal_config_stuff: str

    a: str

class ResponseData(MyBase):
    # Intention here is to extend the config from MyBase, not replace it
    model_config = ConfigDict(from_attributes=True)

    a: str

@app.post("/path", response_model=ResponseData):
    return Data(a="abc")
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.7.0
        pydantic-core version: 2.18.1
          pydantic-core build: profile=release pgo=true
                 install path: /home/vscode/.cache/pypoetry/virtualenvs/py-server-p38DyKo3-py3.12/lib/python3.12/site-packages/pydantic
               python version: 3.12.1 (main, Dec 19 2023, 20:23:36) [GCC 10.2.1 20210110]
                     platform: Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
             related packages: fastapi-0.110.1 pydantic-settings-2.2.1 typing_extensions-4.11.0
                       commit: unknown
```

**Comment by sydney-runkle** [comment] 2024-04-16 14:36
@judgeaxl,

Here's an expanded version of your sample code, reproducible without FastAPI:

```py
from pydantic import BaseModel, ConfigDict, TypeAdapter


class MyBase(BaseModel):
    model_config = ConfigDict(extra="forbid")

class Data(MyBase):
    class Meta:
        internal_config_stuff: str

    a: str

class ResponseData(MyBase):
    model_config = ConfigDict(from_attributes=True)

    a: str

print(ResponseData.model_config)
#> {'extra': 'forbid', 'from_attributes': True}

d = Data(a="abc", b='extra_not_allowed')
"""
b
  Extra inputs are not permitted [type=extra_forbidden, input_value='extra_not_allowed', input_type=str]
    For further information visit https://errors.pydantic.dev/2.7/v/extra_forbidden
"""

r = ResponseData(a="abc", b='extra_not_allowed')
"""
b
  Extra inputs are not permitted [type=extra_forbidden, input_value='extra_not_allowed', input_type=str]
    For further information visit https://errors.pydantic.dev/2.7/v/extra_forbidden
"""

ta = TypeAdapter(ResponseData)
ta.validate_python(Data(a="abc"), from_attributes=True)
"""
Meta
  Extra inputs are not permitted [type=extra_forbidden, input_value=<class '__main__.Data.Meta'>, input_type=type]
    For further information visit https://errors.pydantic.dev/2.7/v/extra_forbidden
"""
```

Will consult with the team re if the last case is expected or not. Thanks for your question!

**Comment by sydney-runkle** [comment] 2024-04-16 14:37
Here's a more minimal repro:

```py
from pydantic import BaseModel, ConfigDict, TypeAdapter


class Data(BaseModel):
    class Meta:
        internal_config_stuff: str

    a: str

class ResponseData(BaseModel):
    model_config = ConfigDict(extra='forbid')

    a: str


ta = TypeAdapter(ResponseData)
ta.validate_python(Data(a="abc"), from_attributes=True)
"""
pydantic_core._pydantic_core.ValidationError: 1 validation error for ResponseData
Meta
  Extra inputs are not permitted [type=extra_forbidden, input_value=<class '__main__.Data.Meta'>, input_type=type]
    For further information visit https://errors.pydantic.dev/2.7/v/extra_forbidden
"""
```

**Comment by samuelcolvin** [comment] 2024-04-16 18:50
What caused this change in 2.7?

From a first look, I would say this should be fixed/reverted.

**Comment by judgeaxl** [comment] 2024-04-17 01:35
Thanks @sydney-runkle for taking the time to distil this into a minimal repro. My case was rather complex involving subclasses of BaseModel with their own metaclasses, so I was worried that that might be the cause.

But with this minimal repro, it does sound to me like it's either undocumented behaviour or a defect. The behaviour for nested classes is not mentioned anywhere in the docs from what I can tell. If they were never meant to be validated or serialized, then they shouldn't be treated as inputs, IMO.

**Comment by sydney-runkle** [comment] 2024-04-18 13:37
Sounds good. Will work on a fix! Not sure what the issue is yet, but will update this thread once I dig in a bit! Agreed - they shouldn't be treated as inputs.

**Comment by sydney-runkle** [comment] 2024-04-18 17:00
I believe this is from https://github.com/pydantic/pydantic-core/commit/36a1b6c6cebcc666229d8f01cbe28fe10b0443bf, based on my binary-search-ish investigation

**Comment by sydney-runkle** [comment] 2024-04-18 17:53
Consulting with @davidhewitt to see what he thinks might be going wrong here...

**Closed** 2024-04-22 13:13 UTC
Labels: bug V2, pending
