### ISSUE TITLE
PydanticSerializationUnexpectedValue - Serialiazation error after upgrading to v2.9

### ISSUE THREAD

**Issue by vineethvkumar** [pydantic/pydantic#10363] opened 2024-09-10 06:01 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

After upgrading to Pydantic v2.9 model_dump_json() throws PydanticSerializationUnexpectedValue error. There isn't enough info in the error to help debug the issue.

```
  File "/home/ec2/.venv/lib/python3.12/site-packages/pydantic/main.py", line 438, in model_dump_json
    return self.__pydantic_serializer__.to_json(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.PydanticSerializationError: Error serializing to JSON: PydanticSerializationUnexpectedValue: Unexpected Value
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.9.1
pydantic-core version: 2.23.3
pydantic-core build: profile=release pgo=false
install path: /home/ec2/.venv/lib/python3.12/site-packages/pydantic
python version: 3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 15:03:55) [GCC 11.2.0]
platform: Linux-6.1.102-111.182.amzn2023.aarch64-aarch64-with-glibc2.34
related packages: typing_extensions-4.12.2
commit: unknown
```

**Comment by Viicos** [comment] 2024-09-10 07:54
We won't be able to help you without any MRE.

**Comment by sydney-runkle** [comment] 2024-09-10 16:05
Closing for now. Happy to revisit with a MRE.

**Comment by sydney-runkle** [comment] 2024-09-10 19:37
Apparently I'm the queen of saying "closing for now" and not hitting the close button.

**Comment by sydney-runkle** [comment] 2024-09-11 18:09
Thanks for the MRE! Indeed, looks like a bug. I think it sort of existed pre 2.9, but we still could improve serialization here. Will look into this tomorrow.

**Comment by sydney-runkle** [comment] 2024-09-11 18:09
I suppose is a regression in a sense now that it's an error and not a warning.

**Comment by nmichlo** [comment] 2024-09-12 15:24
This is also happening for me. I need to now set `serialize_as_any=True` to `.model_dump()` to get this to pass. When previously everything worked fine. I am not sure what is causing this, because if I do `repr(model)` and then use the generated python to then create the same model, `.model_dump()` works fine after this.

**Comment by sydney-runkle** [comment] 2024-09-12 19:32
So, I know what's going wrong here, but will consult with @davidhewitt re the best way to fix this in v2.9.2.

**Comment by sydney-runkle** [comment] 2024-09-13 14:02
@nmichlo,

Could you attach your reproducible example as well?

**Comment by sydney-runkle** [comment] 2024-09-13 14:11
So, the fix I'm working on for this results in:

```py
UserWarning: Pydantic serializer warnings:
  Expected `frozenset[str]` but got `list` with value `['127.0.0.1/32', '192.168.1.0/24']` - serialized value may not be as expected
  return self.__pydantic_serializer__.to_json(
Deserialized: {"composite_field":{"type":"A","addresses":["127.0.0.1/32","192.168.1.0/24"]}}
```

Which I think is correct - your `return_type` hint isn't actually correct, hence the serializer warning.

**Comment by nmichlo** [comment] 2024-09-13 22:06
@sydney-runkle

The error doesn't seem to be with the model_dump, it actually seems to be with the handling of `class _(str, Enum)`. In 2.8 everything is validated correctly and all my objects have strings converted to the enums, however, in 2.9 this is no longer the case. On initial instantiation its correct, then it doesn't validate properly after modifications later on. Working on a minimal reproducible example.

It seems like its a change in `model_validate` or `model_copy`

**Comment by nmichlo** [comment] 2024-09-13 22:44
I thought this would replicate it, but I can't seem to reproduce the bug. We've got quite a complex config and validation structure. Lots of recursive `model_copy` and `model_validate` calls that seem to produce an invalid config in the new version which then can't be dumped by model_dump. The original config seems to be able to be dumped however. I tried to replicate it here, but its not failing:

<details>

```
class ChildEnum(str, Enum):
    child_1 = "child_1"
    child_2 = "child-2-value"

class Base(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        use_enum_values=True,
    )

class Child1(Base):
    key: Literal[ChildEnum.child_1]

class Child2(Base):
    key: Literal[ChildEnum.child_2] = ChildEnum.child_2

class Root(Base):
    child: Annotated[Union[Child1, Child2], pydantic.Field(discriminator="key")]

print()
print(pydantic.__version__)
print()

c1_a = Root(child=Child1(key=ChildEnum.child_1))
c1_b = Root(child=Child1(key="child_1"))
c1_c = Root.model_validate({"child": {"key": "child_1"}})
c1_d = Root.model_validate({"child": {"key": ChildEnum.child_1}})

print(repr(c1_a), c1_a.model_dump())
print(repr(c1_b), c1_b.model_dump())
print(repr(c1_c), c1_c.model_dump())
print(repr(c1_d), c1_d.model_dump())
print()

c2_a = Root(child=Child2(key=ChildEnum.child_2))
c2_b = Root(child=Child2(key="child-2-value"))
c2_c = Root.model_validate({"child": {"key": "child-2-value"}})
c2_d = Root.model_validate({"child": {"key": ChildEnum.child_2}})
c2_e = Root(child=Child2())

print(repr(c2_a), c2_a.model_dump())
print(repr(c2_b), c2_b.model_dump())
print(repr(c2_c), c2_c.model_dump())
print(repr(c2_d), c2_d.model_dump())
print(repr(c2_e), c2_e.model_dump())

# 2.8.2
# 
# Root(child=Child1(key=<ChildEnum.child_1: 'child_1'>)) {'child': {'key': <ChildEnum.child_1: 'child_1'>}}
# Root(child=Child1(key=<ChildEnum.child_1: 'child_1'>)) {'child': {'key': <ChildEnum.child_1: 'child_1'>}}
# Root(child=Child1(key=<ChildEnum.child_1: 'child_1'>)) {'child': {'key': <ChildEnum.child_1: 'child_1'>}}
# Root(child=Child1(key=<ChildEnum.child_1: 'child_1'>)) {'child': {'key': <ChildEnum.child_1: 'child_1'>}}
# 
# Root(child=Child2(key=<ChildEnum.child_2: 'child-2-value'>)) {'child': {'key': <ChildEnum.child_2: 'child-2-value'>}}
# Root(child=Child2(key=<ChildEnum.child_2: 'child-2-value'>)) {'child': {'key': <ChildEnum.child_2: 'child-2-value'>}}
# Root(child=Child2(key=<ChildEnum.child_2: 'child-2-value'>)) {'child': {'key': <ChildEnum.child_2: 'child-2-value'>}}
# Root(child=Child2(key=<ChildEnum.child_2: 'child-2-value'>)) {'child': {'key': <ChildEnum.child_2: 'child-2-value'>}}
# Root(child=Child2(key=<ChildEnum.child_2: 'child-2-value'>)) {'child': {'key': <ChildEnum.child_2: 'child-2-value'>}}

# 2.9.1
#
# Root(child=Child1(key='child_1')) {'child': {'key': 'child_1'}}
# Root(child=Child1(key='child_1')) {'child': {'key': 'child_1'}}
# Root(child=Child1(key='child_1')) {'child': {'key': 'child_1'}}
# Root(child=Child1(key='child_1')) {'child': {'key': 'child_1'}}
#
# Root(child=Child2(key='child-2-value')) {'child': {'key': 'child-2-value'}}
# Root(child=Child2(key='child-2-value')) {'child': {'key': 'child-2-value'}}
# Root(child=Child2(key='child-2-value')) {'child': {'key': 'child-2-value'}}
# Root(child=Child2(key='child-2-value')) {'child': {'key': 'child-2-value'}}
# Root(child=Child2(key=<ChildEnum.child_2: 'child-2-value'>)) {'child': {'key': <ChildEnum.child_2: 'child-2-value'>}}  # expected this one to fail
```

</details>

**Comment by nmichlo** [comment] 2024-09-13 23:31
@sydney-runkle figured out the minimal reproducible problem:

```
from typing import Tuple

import pydantic


class Model(pydantic.BaseModel):
    values: Tuple[float, ...]


model = Model(values=(0, 1))
print(pydantic.__version__, repr(model), model.model_dump())
model = model.model_copy(deep=True, update={"values": [1, 2]})
print(pydantic.__version__, repr(model), model.model_dump())
model = model.model_validate(model)
print(pydantic.__version__, repr(model), model.model_dump())

# 2.8.2 Model(values=(0.0, 1.0)) {'values': (0.0, 1.0)}
# 2.8.2 Model(values=[1, 2]) {'values': [1, 2]}
# 2.8.2 Model(values=[1, 2]) {'values': [1, 2]}

# 2.9.1 Model(values=(0.0, 1.0)) {'values': (0.0, 1.0)}
# 2.9.1 Model(values=[1, 2]) {'values': [1, 2]}
# 2.9.1 Model(values=[1, 2]) {'values': [1, 2]}
# UserWarning: Pydantic serializer warnings:
#   Expected `tuple[float, ...]` but got `list` with value `[1, 2]` - serialized value may not be as expected
#   return self.__pydantic_serializer__.to_python(
```

Type conversion suddenly got more strict, and also the model_validate/model_copy doesn't behave as expected.

**Closed** 2024-09-16 15:31 UTC
Labels: bug V2, pending
