### ISSUE TITLE
BaseModel is not generating `type: null` for fields when it is an option.

### ISSUE THREAD

**Issue by TCampmany** [pydantic/pydantic#2926] opened 2021-06-17 14:23 UTC
### Checks

* [X] I added a descriptive title to this issue
* [X] I have searched (google, github) for similar issues and couldn't find anything
* [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.2
            pydantic compiled: True
                 install path: /Users/xxxxxxx/venv/lib/python3.8/site-packages/pydantic
               python version: 3.8.10 (default, May  4 2021, 03:06:52)  [Clang 12.0.0 (clang-1200.0.32.29)]
                     platform: macOS-11.4-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

#### Context
```py
from pprint import pprint
from typing import Union, Optional

from pydantic import BaseModel, Field


class Model(BaseModel):
    a: Union[str, int, None] = Field(...)
    b: Union[str, int, None] = Field(None)
    c: Union[str, int, None]
    d: Optional[int] = Field(...)
    e: Optional[int] = Field(None)
    f: Optional[int]
    g: None = Field(...)
    h: None = Field(None)
    i: None


pprint(Model.schema())

```

And the output is:
```
{'properties': {'a': {'anyOf': [{'type': 'string'}, {'type': 'integer'}],
                      'title': 'A'},
                'b': {'anyOf': [{'type': 'string'}, {'type': 'integer'}],
                      'title': 'B'},
                'c': {'anyOf': [{'type': 'string'}, {'type': 'integer'}],
                      'title': 'C'},
                'd': {'title': 'D', 'type': 'integer'},
                'e': {'title': 'E', 'type': 'integer'},
                'f': {'title': 'F', 'type': 'integer'},
                'g': {'title': 'G', 'type': 'null'},
                'h': {'title': 'H', 'type': 'null'},
                'i': {'title': 'I', 'type': 'null'}},
 'required': ['a', 'd', 'g', 'i'],
 'title': 'Model',
 'type': 'object'}
```

#### Expected result

I expected that the `'type': 'null'` would figure on required fields, like `a` and `d`.
But instead, it only appears when the only possible value is `None`.

---

By the way, while typing this issue, I was also wondering if `'type': 'null'` shouldn't appear for all fields, mainly because they can receive a `None` value.
But this is not completely clear in my mind.

**Comment by PrettyWood** [comment] 2021-06-17 16:27
Hi @TCampmany 
Yep will be tackled in https://github.com/samuelcolvin/pydantic/pull/1611 ;)
Hope it helps!

**Comment by DetachHead** [comment] 2022-08-25 05:03
duplicate of #1270

**Comment by samuelcolvin** [comment] 2022-08-25 07:27
Good catch.

**Closed by samuelcolvin** 2022-08-25 07:27 UTC
Labels: bug
