### ISSUE TITLE
mypy plugin incorrectly infers generics that use PEP 695 syntax as invariant instead of covariant on frozen models

### ISSUE THREAD

**Issue by DetachHead** [pydantic/pydantic#10174] opened 2024-08-19 08:31 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

similar to #9580

the new generic syntax added in python 3.12 infers the variance, so i think the mypy plugin needs to be updated to account for that

### Example Code

```Python
# mypy: enable-incomplete-feature=NewGenericSyntax

from pydantic import BaseModel


class Foo[T](BaseModel):
    model_config = {"frozen": True}
    value: T


foo = Foo[int](value=1)
bar: Foo[object] = foo # error: Incompatible types in assignment (expression has type "Foo[int]", variable has type "Foo[object]")
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.8.2
        pydantic-core version: 2.20.1
          pydantic-core build: profile=release pgo=true
                 install path: C:\Users\user\project\.venv\Lib\site-packages\pydantic
               python version: 3.12.0 (tags/v3.12.0:0fb18b0, Oct  2 2023, 13:03:39) [MSC v.1935 64 bit (AMD64)]
                     platform: Windows-11-10.0.22621-SP0
             related packages: typing_extensions-4.12.2
                       commit: unknown
```

**Comment by dmontagu** [comment] 2024-08-19 17:31
I'll just note that you may run into some subtle issues with this code due to the way that pydantic (currently) handles generics — at runtime, all parametrized generics will be invariant due to the fact that we create subclasses for each parametrization (this is currently necessary as many of the validation methods are class methods that need different logic as a function of the class).

We've discussed some ways to resolve/improve this situation but I think most of them will be breaking enough that we won't be able to make those changes before Pydantic V3.

That said, I'd be happy to try to get the mypy plugin to properly reflect the inferred variance, ignoring the potential runtime hiccups. Do you know if this works now if you manually create a covariant typevar rather than using the new feature?

**Comment by dmontagu** [comment] 2024-08-19 17:44
So, I can confirm that it does respect covariance of the typevar properly, i.e., if I don't use the new syntax I get a type error when using an invariant (default) typevar, but not when using a covariant one. Which makes me think this should "just work" unless mypy is somehow distinguishing between typevars declared manually and ones declared using the new syntax, which seems suspicious to me.

More importantly, I get the same error when using this on dataclasses:
```python
# mypy: enable-incomplete-feature=NewGenericSyntax
from dataclasses import dataclass

@dataclass
class Foo[T]:
    model_config = {"frozen": True}
    value: T


foo = Foo[int](value=1)
bar: Foo[object] = foo
```

Unless I'm misunderstanding something and it's not expected for this to work with dataclasses, I think it's not worth looking into this on the pydantic side until it can be demonstrated that this _does_ work with dataclasses and _does not_ work with pydantic, as I am fairly optimistic that it will work with both or neither without any changes required in the plugin.

**Closed** 2024-08-19 17:46 UTC
Labels: bug V2, type checking, pep695

**Comment by DetachHead** [comment] 2024-08-19 23:45
raised https://github.com/python/mypy/issues/17692
