### ISSUE TITLE
Optional field annotated as NoneType if field name is equal to class name

### ISSUE THREAD

**Issue by highviolet** [pydantic/pydantic#7222] opened 2023-08-23 09:23 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I have a model where class names are reused as field names. (See example code below).

When this occurs, and the field is made optional, pydantic annotates the field as NoneType.
Note that this doesn't occur if the field is mandatory.

### Example Code

```Python
from typing import Optional

from pydantic import BaseModel


class Bar(BaseModel):
    Baz: str


class Foo1(BaseModel):
    Bar: Optional[Bar] = None


class Foo2(BaseModel):
    Bar: Bar


# prints: annotation=NoneType required=False
print(Foo1.model_fields["Bar"])

# prints: annotation=Bar required=True
print(Foo2.model_fields["Bar"])

# Fails with ValidationError "Input should be None"
Foo1(Bar=Bar(Baz="z"))
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.2.1
        pydantic-core version: 2.6.1
          pydantic-core build: profile=release pgo=false
                 install path: C:\src\apps\miniconda3\envs\env\Lib\site-packages\pydantic
               python version: 3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 17:59:51) [MSC v.1935 64 bit (AMD64)]
                     platform: Windows-10-10.0.22000-SP0
     optional deps. installed: ['email-validator', 'typing-extensions']
```

Selected Assignee: @Kludex

**Comment by davidhewitt** [comment] 2023-08-24 16:58
I can reproduce it to the following issue:

```python
from typing_extensions import TypeAlias

A: TypeAlias = int
B: TypeAlias = int

class F:
    A: Optional[A]
    B: Optional[B] = None

print(F.__annotations__)
#> {'A': typing.Optional[int], 'B': <class 'NoneType'>}
```

That is, having the assignment `= None` is interfering with evaluation of annotations by using that as the value of `B` instead of the outer scope.

This also blows up using 3.10 union syntax:

```python
from typing_extensions import TypeAlias

A: TypeAlias = int
B: TypeAlias = int

class F:
    A: A | None
    B: B | None = None  # TypeError: unsupported operand type(s) for |: 'NoneType' and 'NoneType'
```

It looks like a possible typing bug to me, I'll report to CPython and see what the response is.

**Comment by davidhewitt** [comment] 2023-08-24 17:23
Reported upstream in https://github.com/python/cpython/issues/108437

The more I think about it, this seems like an expected consequence of scoping rules. I don't think there's anything we can do about this; either it gets fixed upstream of this is an edge case of the Python type system. Will therefore close as wontfix.

**Closed by davidhewitt** 2023-08-24 17:23 UTC
Labels: unconfirmed, bug V2

**Comment by davidhewitt** [comment] 2023-08-25 11:45
From the upstream discussion, this is clearly Python language behaviour. A workaround is to split the annotation and assignment into two statements:

```python
from typing import Optional

from pydantic import BaseModel


class Bar(BaseModel):
    Baz: str


class Foo1(BaseModel):
    Bar: Optional[Bar]; Bar = None    # <-- note this line is split into two with a semicolon


# prints: annotation=Union[Bar, NoneType] required=False
print(Foo1.model_fields["Bar"])

# Succeeds
Foo1(Bar=Bar(Baz="z"))
```

The repetition of `Bar` in `Bar: Optional[Bar]; Bar = None` is a bit unfortunate, it seems like the best that can be done at present.
