### ISSUE TITLE
🐞 Adding `__iter__` gives type errors

### ISSUE THREAD

**Issue by jd-solanki** [pydantic/pydantic#10954] opened 2024-11-23 07:03 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Taking example from the docs:
```py
from pydantic import RootModel


class Pets(RootModel[list[str]]):
    root: list[str]

    def __iter__(self):
        return iter(self.root)

    def __getitem__(self, item: str) -> str:
        return self.root[item]
```

We're getting type errors:
![image](https://github.com/user-attachments/assets/d8d4a3bd-38f6-4b90-ae8f-bfc4240e648b)

`__iter__` => Return type mismatch: base method returns type "TupleGenerator", override returns type "Iterator[str]"
`__getitem__` => No overloads for "__getitem__" match the provided arguments (Even when we define type for )

### Example Code

```Python
from pydantic import RootModel


class Pets(RootModel[list[str]]):
    root: list[str]

    def __iter__(self):
        return iter(self.root)

    def __getitem__(self, item: str) -> str:
        return self.root[item]
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.9.1
        pydantic-core version: 2.23.3
          pydantic-core build: profile=release pgo=false
                 install path: /home/jd/Projects/mine/wrapwithai/backend/.venv/lib/python3.12/site-packages/pydantic
               python version: 3.12.7 (main, Nov  6 2024, 18:29:01) [GCC 14.2.0]
                     platform: Linux-6.11.0-8-generic-x86_64-with-glibc2.40
             related packages: fastapi-0.114.0 typing_extensions-4.12.2 pydantic-settings-2.4.0
                       commit: unknown
```

**Comment by zzstoatzz** [comment] 2024-11-23 08:46
@jd-solanki - why are you overriding the `root` typing?

if you remove that I don't see any type errors
```python
"""This example shows how to create a root model that iterates over a list of strings."""

from pydantic import RootModel


class Pets(RootModel[list[str]]):
    """A root model that iterates over a list of strings."""

    def __iter__(self):
        return iter(self.root)

    def __getitem__(self, item: str) -> str:
        return self.root[item]


if __name__ == '__main__':
    pets = Pets(root=['dog', 'cat', 'bird'])
    for pet in pets:
        print(pet)  # noqa: T201

    assert pets[0] == 'dog'
    assert pets.root == ['dog', 'cat', 'bird']

```

**Comment by zzstoatzz** [comment] 2024-11-23 08:49
hi @jd-solanki (not a maintainer but) why are you overriding `root` typing? if you remove that I see no type errors

```python
"""create a root model that iterates over a list of strings."""

from typing import Iterator

from pydantic import RootModel


class Pets(RootModel[list[str]]):
    """iterates over a list of strings."""

    def __iter__(self) -> Iterator[str]:
        return iter(self.root)

    def __getitem__(self, item: str) -> str:
        return self.root[item]


if __name__ == '__main__':
    pets = Pets(root=['dog', 'cat', 'bird'])
    for pet in pets:
        print(pet)  # noqa: T201

    assert pets[0] == 'dog'
    assert pets.root == ['dog', 'cat', 'bird']
```

**Comment by adarsharegmi** [comment] 2024-11-23 13:31
@jd-solanki could not reproduce issue using same version though. tried using pycharm as well.

**Comment by adarsharegmi** [comment] 2024-11-23 13:32
pydantic version: 2.9.1
        pydantic-core version: 2.23.3
          pydantic-core build: profile=release pgo=false
                 install path: /Users/addy/Documents/pydantic-testing/venv/lib/python3.12/site-packages/pydantic
               python version: 3.12.4 (v3.12.4:8e8a4baf65, Jun  6 2024, 17:33:18) [Clang 13.0.0 (clang-1300.0.29.30)]
                     platform: macOS-15.0-arm64-arm-64bit
             related packages: typing_extensions-4.12.2
                       commit: unknown

**Comment by jd-solanki** [comment] 2024-11-23 15:43
@adarsharegmi This occurs with the pylance which isn't exist in pycharm

**Comment by mpkocher** [comment] 2024-11-24 02:20
BaseModel implements `__iter__`, hence you're seeing a collision issue. 

In general, I'm not sure that adding `__X__` methods is going to mesh well with pydantic. 

Also, in your example, I believe `__getitem__(self, item: str) -> str`  needs to have `item` be an `int` and/or a `slice`.

**Comment by sydney-runkle** [comment] 2024-11-25 20:53
Indeed, this is expected.

Closing as resolved - feel free to `# type: ignore` these errors if you're confident in your implementation.

**Closed by sydney-runkle** 2024-11-25 20:53 UTC
Labels: bug V2, pending
