### ISSUE TITLE
Annotated with generic class

### ISSUE THREAD

**Issue by mattangus** [pydantic/pydantic#8202] opened 2023-11-22 14:52 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Pydantic doesn't seem to work with generic annotated values. `Generic` and `Annotated` can work together according to the docs since [python 3.9](https://docs.python.org/3.9/library/typing.html#typing.Annotated). See the example below for reproducing the error.

### Example Code

```Python
from pydantic import BaseModel, Field
from typing import List, Literal, Dict, Tuple, Optional, TypeVar, Generic, Annotated, Union

T = TypeVar('T')

class RangeValues(BaseModel, Generic[T]):
    values_type: Literal["range"] = "range"
    max: T
    min: T
    step: T

class ListValues(BaseModel, Generic[T]):
    values_type: Literal["list"] = "list"
    values: List[T]

Values = Annotated[Union[RangeValues[T], ListValues[T]], Field(..., discriminator='values_type')]

class Container(BaseModel):
    floats: Values[float]
    ints: Values[int]

# importing this file will result in the error
# typing.Annotated[typing.Union[RangeValues, ListValues], FieldInfo(annotation=NoneType, required=True, discriminator='values_type')] is not a generic class
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.2
        pydantic-core version: 2.14.5
          pydantic-core build: profile=release pgo=true
                 install path: /home/matt/workspace/virtual_environments/python3.10/lib/python3.10/site-packages/pydantic
               python version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
                     platform: Linux-6.2.0-34-generic-x86_64-with-glibc2.35
             related packages: mypy-1.4.1 typing_extensions-4.7.1 typing_extensions-4.8.0 typing_extensions-4.6.3 fastapi-0.100.0 pydantic-extra-types-2.0.0
```

**Comment by sydney-runkle** [comment] 2023-11-22 20:25
Hi @mattangus,

Thanks for reporting this. I've marked this as a feature request. We indeed don't support this currently. A workaround in the meantime is the following:

```py
from pydantic import BaseModel, Field
from typing import List, Literal, Dict, Tuple, Optional, TypeVar, Generic, Union, Annotated

T = TypeVar('T')

class RangeValues(BaseModel, Generic[T]):
    values_type: Literal["range"] = "range"
    max: T
    min: T
    step: T

class ListValues(BaseModel, Generic[T]):
    values_type: Literal["list"] = "list"
    values: List[T]


class Container(BaseModel):
    floats: Annotated[Union[RangeValues[float], ListValues[float]], Field(..., discriminator='values_type')]
    ints: Annotated[Union[RangeValues[int], ListValues[int]], Field(..., discriminator='values_type')]
```

**Comment by rafales** [comment] 2023-12-06 11:22
I think I'm having a similar problem. I'm trying to type a simple RPC with types similar to rust result/`returns` containers. The typing is as follows:

```python

T = t.TypeVar("T")
E = t.TypeVar("E")


class Ok(BaseModel, t.Generic[T]):
    result: T
    ok: t.Literal[True] = True

    def __init__(self, result: T) -> None:
        super().__init__(result=result)


class Err(BaseModel, t.Generic[E]):
    error: E
    ok: t.Literal[False] = False

    def __init__(self, error: E) -> None:
        super().__init__(error=error)


Result: t.TypeAlias = t.Union[Ok[T], Err[E]]
```

With this setup `Result[str, int]` will throw the following error:

```
In [25]: Result[str, int]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:1                                                                                    │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: __main__.Ok | __main__.Err is not a generic class
```

It's weird how there is no actionable traceback. If I remove `BaseModel` from `Ok` and `Err` classes - it works.

**Comment by drew-mcclelland-ch** [comment] 2024-05-08 20:27
I ran into this issue as well. I was trying to extend the pyrsistent library to be compatible with Pydantic models. But in order to allow PVectors and other classes to function correctly, I think I'd need generic support for annotated types.

```

T = TypeVar("T")


class _PydPVectorAnnotation:
    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: Any, handler: GetCoreSchemaHandler
    ) -> CoreSchema:
        origin = get_origin(source_type)
        if origin is None:  # used as `x: Owner` without params
            origin = source_type
            item_tp = Any
        else:
            item_tp = get_args(source_type)[0]
        # both calling handler(...) and handler.generate_schema(...)
        # would work, but prefer the latter for conceptual and consistency reasons
        item_schema = handler.generate_schema(item_tp)

        def val_item(
            v: PVector[Any], handler: ValidatorFunctionWrapHandler
        ) -> PVector[Any]:
            v = handler(v.tolist())
            return pvector(v)

        python_schema = core_schema.chain_schema(
            # `chain_schema` means do the following steps in order:
            [
                # Ensure the value is an instance of Owner
                core_schema.is_instance_schema(cls),
                # Use the item_schema to validate `items`
                core_schema.no_info_wrap_validator_function(val_item, item_schema),
            ]
        )

        return core_schema.json_or_python_schema(
            # for JSON accept an object with name and item keys
            json_schema=core_schema.chain_schema(
                [
                    core_schema.list_schema(),
                    # after validating the json data convert it to python
                    core_schema.no_info_before_validator_function(
                        lambda data: pvector(data),
                        # note that we re-use the same schema here as below
                        python_schema,
                    ),
                ]
            ),
            python_schema=python_schema,
        )


PydPVector = Annotated[PVector, _PydPVectorAnnotation]

class Context(BaseModel):
    ids: PydPVector[int]


x = Context(
    ids=pvector(1),
)
# Throws TypeError: typing.Annotated[pyrsistent._pvector.PVector, <class '__main__._PydPVectorAnnotation'>] is not a generic class
```

**Comment by a3ng7n** [comment] 2024-08-02 06:38
Just happened upon this and wanted to share a small possible workaround:
```
from pydantic import BaseModel, Field
from typing import List, Literal, Dict, Tuple, Optional, TypeVar, Generic, Annotated, Union

T = TypeVar('T')

class RangeValues(BaseModel, Generic[T]):
    values_type: Literal["range"] = "range"
    max: T
    min: T
    step: T

class ListValues(BaseModel, Generic[T]):
    values_type: Literal["list"] = "list"
    values: List[T]

class Values(Generic[T]):
    def __class_getitem__(cls, item: Type[T]):
        return Annotated[Union[RangeValues[item], ListValues[item]], Field(..., discriminator='values_type')]


class Container(BaseModel):
    floats: Values[float]
    ints: Values[int]
```

**Comment by Viicos** [comment] 2024-11-03 21:12
When an `Annotated[...]` special form is created, the internal typing logic collect all the type parameters of the annotated type. That is, with the following:

```python
Test = Annotated[list[T], ...]
```
Calling `Test[int]` works because `Test.__parameters__ == (T,)`.

Internally, `list[T]` is what's called a generic alias. It's _an instance_ (not a class!) of `typing._GenericAlias`, and the internal typing module has logic to understand these aliases (like getting the type variables of such an alias).

However, generic Pydantic models aren't defined as aliases. `RangeValues[T]` is an actual class, as is `RangeValues[int]`. Unless we change this to match the generic aliases semantics, there's no way we can support the described use case. This is also the root cause of https://github.com/pydantic/pydantic/issues/3559.

Alternatively, you can define `Values` as a PEP 695 type alias:

```python
type Values[T] = Annotated[Union[RangeValues[T], ListValues[T]], Field(..., discriminator='values_type')]
```

To be thoroughly tested, but quickly looking at the `Container` core schema this works as expected.

**Closed by Viicos** 2024-11-03 21:12 UTC
Labels: feature request
