### ISSUE TITLE
Union validator fails with Generator members

### ISSUE THREAD

**Issue by andresliszt** [pydantic/pydantic#8887] opened 2024-02-24 18:21 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

`Union` validator fails when the member types are Generators. Seems to be that is picking up the first generator member to perform the validation 

### Example Code

```Python
from pydantic import BaseModel
from typing import Generator, Union


class Test(BaseModel):
    x: Union[Generator[int, None, None], Generator[str, None, None]]

def gen_int():
    for val in range(3):
        yield val

def gen_str():
    for val in 'foo':
        yield val

# This is Valid
Test(x=gen_int())
>>> Test(x=ValidatorIterator(index=0, schema=Some(Int(IntValidator { strict: false }))))

list(Test(x=gen_int()).x)
>>> [1,2,3]

# This shows the same repr than above
Test(x=gen_str())
>>> Test(x=ValidatorIterator(index=0, schema=Some(Int(IntValidator { strict: false }))))

# And accessing the members raises error
list(Test(x=gen_str()).x)
>>> *** pydantic_core._pydantic_core.ValidationError: 1 validation error for ValidatorIterator
0
  Input should be a valid integer, unable to parse string as an integer [type=int_parsing, input_value='f', input_type=str]
    For further information visit https://errors.pydantic.dev/2.7/v/int_parsing
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.7.0a1
        pydantic-core version: 2.16.3
          pydantic-core build: profile=release pgo=false
                 install path: /Users/andres.sandoval/Desktop/pydantic/pydantic
               python version: 3.10.10 (v3.10.10:aad5f6a891, Feb  7 2023, 08:47:40) [Clang 13.0.0 (clang-1300.0.29.30)]
                     platform: macOS-12.4-x86_64-i386-64bit
             related packages: pydantic-extra-types-2.1.0 typing_extensions-4.8.0 pydantic-settings-2.0.3 mypy-1.1.1 email-validator-2.1.0.post1
                       commit: 3c96cf91
```

**Comment by sydney-runkle** [comment] 2024-02-24 20:30
This seems to be a duplicate of https://github.com/pydantic/pydantic/issues/8699.

Closing this as a duplicate. I believe there is a fix in progress in `pydantic-core` for the above issue.

**Closed by sydney-runkle** 2024-02-24 20:30 UTC
Labels: duplicate, bug V2
