### ISSUE TITLE
Indention of ` get_discriminator_value`  for docs

### ISSUE THREAD

**Issue by Anselmoo** [pydantic/pydantic#8882] opened 2024-02-23 19:16 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

It looks like the indentation is wrong in the docs to execute the code

<img width="770" alt="image" src="https://github.com/pydantic/pydantic/assets/13209783/ab12101f-6f52-498d-bbf2-4b0e0b20cd79">

### Example Code

```Python
https://github.com/pydantic/pydantic/blob/deeb110e711ba38f91326430b2bbdf4e72d08976/docs/concepts/unions.md?plain=1#L226C1-L229
```

### Python, Pydantic & OS Version

```Text
online
```

**Comment by sydney-runkle** [comment] 2024-02-24 20:32
I believe this is a duplicate of https://github.com/samuelcolvin/mkdocs-run-code/issues/5.

Closing this here, as I believe the issue belongs in that repo. I'll take a closer look this week!

**Closed by sydney-runkle** 2024-02-24 20:32 UTC
Labels: bug V2, pending

**Comment by Anselmoo** [comment] 2024-02-27 06:12
thx @sydney-runkle for sharing the correct repo
