### ISSUE TITLE
`ser_json_inf_nan` not respected when used with an Any list

### ISSUE THREAD

**Issue by matsjoyce-refeyn** [pydantic/pydantic#8693] opened 2024-02-01 10:34 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When using a dataclass with a non-specialised list, NaNs are serialised in json mode as None, not NaN, even when `ser_json_inf_nan` is set to constants. This behaviour goes away if `list[float]` is used. But for my use case, the list might be arbitrarily nested (e.g. `list[list[list[float]]]`) so leaving it as `list[Any]` seems to be the only solution (unless recursive type aliases are supported).

### Example Code

```Python
import pprint

import pydantic

@dataclasses.dataclass(frozen=True)
class Z:
    inner: list
    __pydantic_config__ = {"ser_json_inf_nan": "constants"}

a = pydantic.TypeAdapter(Z)

pprint.pprint(a.core_schema)
# Output:
# {'cls': <class 'tests.parsing.test_utils.test_parse_then_unparse_nans.<locals>.Z'>,
#  'config': {'ser_json_inf_nan': 'constants', 'title': 'Z'},
#  'fields': ['inner'],
#  'metadata': {'pydantic.internal.needs_apply_discriminated_union': False},
#  'post_init': False,
#  'ref': 'tests.parsing.test_utils.test_parse_then_unparse_nans.<locals>.Z:1355051499120',
#  'schema': {'collect_init_only': False,
#             'computed_fields': [],
#             'dataclass_name': 'Z',
#             'fields': [{'init': True,
#                         'kw_only': False,
#                         'metadata': {'pydantic_js_annotation_functions': [<function get_json_schema_update_func.<locals>.json_schema_update_func at 0x0000013B4670E9E0>],
#                                      'pydantic_js_functions': []},
#                         'name': 'inner',
#                         'schema': {'items_schema': {'type': 'any'},
#                                    'strict': False,
#                                    'type': 'list'},
#                         'type': 'dataclass-field'}],
#             'type': 'dataclass-args'},
#  'slots': False,
#  'type': 'dataclass'}

pprint.pprint(a.dump_python(Z([math.nan]), mode="json"))
# Output:
# {'inner': [None]}
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.0
        pydantic-core version: 2.16.1
          pydantic-core build: profile=release pgo=true
                 install path: C:\Users\matthew.joyce\Repos\iscat\venv\venv_develop\Lib\site-packages\pydantic
               python version: 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]
                     platform: Windows-10-10.0.19045-SP0
             related packages: mypy-1.2.0 typing_extensions-4.9.0
                       commit: unknown
```

**Comment by BoxyUwU** [comment] 2024-08-20 12:22
I can't reproduce this locally, it seems pydantic/pydantic-core#1251 was marked as fixing this but then removed the `Fixes` annotation? Perhaps that did fix this since the problem seems to be the our handling of `Any` wasn't correct

**Comment by sydney-runkle** [comment] 2024-08-20 22:20
Huh, nice. I'm also not able to repro this on `main`. I don't think that PR fixed it, but maybe something since then did. Anywho, we can close this as resolved for now!

**Comment by sydney-runkle** [comment] 2024-08-20 22:21
Can confirm, the results on `main`:

```py
import pydantic
import math

@pydantic.dataclasses.dataclass(frozen=True)
class Z:
    inner_any: list
    inner_float: list[float]

    __pydantic_config__ = {"ser_json_inf_nan": "constants"}

a = pydantic.TypeAdapter(Z)
print(a.dump_python(Z(inner_any=[math.nan], inner_float=[math.nan]), mode="json"))
# {'inner_any': [nan], 'inner_float': [nan]}
```

**Closed by sydney-runkle** 2024-08-20 22:20 UTC
Labels: bug V2
