### ISSUE TITLE
Installing pydantic 2.5.0 from Azure DevOps feeds fails due to description too long

### ISSUE THREAD

**Issue by memoryz** [pydantic/pydantic#8117] opened 2023-11-14 19:40 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Installing pydantic 2.5.0 from Azure DevOps feeds results in this error:
HTTP error 400 Client Error: Bad Request - The package description exceeds the maximum length of 324608 bytes.

### Python, Pydantic & OS Version

```Text
2.5.0
```

**Comment by samuelcolvin** [comment] 2023-11-14 19:41
Duplicate of #8105.

Please check for duplicates before creating issues.

The new release will be out as soon as GitHub actions behave.

**Closed by samuelcolvin** 2023-11-14 19:41 UTC
Labels: bug V2, pending
