### ISSUE TITLE
why `from`

### ISSUE THREAD

**Issue by dsharma522** [pydantic/pydantic#6205] opened 2023-06-21 04:40 UTC
I am using sqlalchemy and pydantic in fast api application. I have orm queries using join. When using `from_orm` from pydantic , it is calling database again. I confirmed via enabling sqlalchemy logs. 

### Original problem

```python
notification_rules_subquery = (
    db.query(NotificationRuleModel.id).filter_by(**rule_filter).subquery()
)
rows = (
    db.query(NotificationRuleModel, NotificationModel)
    .join(NotificationModel, NotificationModel.rule_id == NotificationRuleModel.id)
    .filter(... Some filter)
    .all()
)
db.commit()
```

```python

# Sqlalchemy db model

ModelBase = declarative_base()

@declarative_mixin
class TimestampMixin:
    created_at = Column(DateTime, nullable=False, server_default=func.now())
    updated_at = Column(DateTime, nullable=False, server_default=func.now(), onupdate=func.now())


class NotificationRule(ModelBase):
    __tablename__ = _NOTIFICATION_RULE_TABLE_NAME
    id = Column(Integer, unique=True, primary_key=True)
    community_id = Column(UUID(as_uuid=True), nullable=False)

class Notification(ModelBase, TimestampMixin):
    __tablename__ = _NOTIFICATION_TABLE_NAME

    id = Column(Integer, primary_key=True, unique=True, autoincrement=True)
    uuid = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    rule_id = Column(Integer, ForeignKey(NotificationRule.id), nullable=False)

# pydantic model
class NotificationRule(BaseModel):
    id: int
    community_id: uuid.UUID
    
    class Config:
        orm_mode = True

class NotificationBaseResponse(DateMixin):
    uuid: uuid.UUID
    id: int
    rule_id: int
    time_frame_start: Optional[datetime]

    class Config:
        orm_mode = True


```

The rows returned by the above query is the list of tuples in form (NotificationRule, Notification), so
When doing 
```
rule = NotificationRule.from_orm(rows[0][0])
```

this calls database again. I am unable to figure out why.

### Another case

I debugged it and found that even on single table query, the from_orm is calling database

```python
row = (
        db.query(NotificationModel)
        .filter(NotificationModel.rule_id == some_id)
        .order_by(NotificationModel.created_at.desc())
        .limit(1)
        .all()
    )
    db.commit()
```

When calling on `Notification.from_orm(row)` on above, it is calling database again. 
However, If i change the query as 
```
row = (
        db.query(*inspect(NotificationModel).attrs)
        .filter(NotificationModel.rule_id == some_id)
        .order_by(NotificationModel.created_at.desc())
        .limit(1)
        .all()
    )
    db.commit()
```
(added *inspect(NotificationModel).attrs )

and then calling from_orm on it, It does not call database again.

### Logs for ref of join query
```bash
INFO:     2023-06-21 09:49:36|base.py -> _log_info[136]|sqlalchemy.engine.Engine|BEGIN (implicit)
INFO:     2023-06-21 09:49:36|base.py -> _log_info[136]|sqlalchemy.engine.Engine|SELECT notification_rule.id AS notification_rule_id, notification_rule.community_id AS notification_rule_community_id, notification_rule.user_id AS notification_rule_user_id, notification_rule.purpose AS notification_rule_purpose, notification_rule.targets AS notification_rule_targets, notification_rule.frequency AS notification_rule_frequency, notification_rule.send_at AS notification_rule_send_at, notification_rule.rule AS notification_rule_rule, notification_rule.active AS notification_rule_active, notification_rule.created_at AS notification_rule_created_at, notification_rule.last_run_at AS notification_rule_last_run_at, notification_rule.scheduled_next_run AS notification_rule_scheduled_next_run, notification_rule.status AS notification_rule_status, notification_rule.task_id AS notification_rule_task_id, notification.created_at AS notification_created_at, notification.updated_at AS notification_updated_at, notification.id AS notification_id, notification.uuid AS notification_uuid, notification.rule_id AS notification_rule_id_1, notification.status AS notification_status, notification.time_frame_start AS notification_time_frame_start
FROM notification_rule JOIN notification ON notification_rule.id = notification.rule_id
WHERE notification.status IN (%(status_1_1)s, %(status_1_2)s) AND notification_rule.id IN (SELECT anon_1.id
FROM (SELECT notification_rule.id AS id
FROM notification_rule
WHERE notification_rule.community_id = %(community_id_1)s) AS anon_1) ORDER BY notification.id DESC
INFO:     2023-06-21 09:49:36|base.py -> _log_info[136]|sqlalchemy.engine.Engine|[generated in 0.00036s] {'community_id_1': UUID('74b46d04-e8c5-4ab9-a466-9721b4bd8e4c'), 'status_1_1': <NotificationStatus.SENT: 'SENT'>, 'status_1_2': <NotificationStatus.DELIVERED: 'DELIVERED'>}
INFO:     2023-06-21 09:49:36|base.py -> _log_info[136]|sqlalchemy.engine.Engine|COMMIT
INFO:     2023-06-21 09:49:36|base.py -> _log_info[136]|sqlalchemy.engine.Engine|BEGIN (implicit)
INFO:     2023-06-21 09:49:36|base.py -> _log_info[136]|sqlalchemy.engine.Engine|SELECT notification_rule.id AS notification_rule_id, notification_rule.community_id AS notification_rule_community_id, notification_rule.user_id AS notification_rule_user_id, notification_rule.purpose AS notification_rule_purpose, notification_rule.targets AS notification_rule_targets, notification_rule.frequency AS notification_rule_frequency, notification_rule.send_at AS notification_rule_send_at, notification_rule.rule AS notification_rule_rule, notification_rule.active AS notification_rule_active, notification_rule.created_at AS notification_rule_created_at, notification_rule.last_run_at AS notification_rule_last_run_at, notification_rule.scheduled_next_run AS notification_rule_scheduled_next_run, notification_rule.status AS notification_rule_status, notification_rule.task_id AS notification_rule_task_id
FROM notification_rule
WHERE notification_rule.id = %(pk_1)s
INFO:     2023-06-21 09:49:36|base.py -> _log_info[136]|sqlalchemy.engine.Engine|[generated in 0.00012s] {'pk_1': 2}
INFO:     2023-06-21 09:49:36|base.py -> _log_info[136]|sqlalchemy.engine.Engine|SELECT notification.created_at AS notification_created_at, notification.updated_at AS notification_updated_at, notification.id AS notification_id, notification.uuid AS notification_uuid, notification.rule_id AS notification_rule_id, notification.status AS notification_status, notification.time_frame_start AS notification_time_frame_start
FROM notification
WHERE notification.id = %(pk_1)s AND notification.uuid = %(pk_2)s
INFO:     2023-06-21 09:49:36|base.py -> _log_info[136]|sqlalchemy.engine.Engine|[generated in 0.00013s] {'pk_1': 5, 'pk_2': UUID('e1b6020d-57c2-4bbc-8c3c-99cdfe3e3a32')}
```

_Originally posted by @dsharma522 in https://github.com/pydantic/pydantic/discussions/6197_

**Comment by hramezani** [comment] 2023-06-21 07:33
Isn't this a duplicate of #6206 ?

**Closed** 2023-06-21 07:35 UTC
