### ISSUE TITLE
Parsing a timedelta from a float using TypeAdapter truncates decimals

### ISSUE THREAD

**Issue by eltechnic0** [pydantic/pydantic#9267] opened 2024-04-17 13:10 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Parsing a float number into a `timedelta` truncates decimals (`1.5` => `timedelta(seconds=1)`).

I would expect to get decimals up to microseconds, as supported by `timedelta`.

### Example Code

```Python
# %%
from dataclasses import dataclass
from pydantic import TypeAdapter
from datetime import datetime, timedelta, timezone
from typing import Union

@dataclass
class Dummy:
    start_time: datetime
    duration: timedelta
    # duration: Union[timedelta, float]
    # duration: float
# %%
# item_data = {'start_time': datetime.now(timezone.utc).isoformat(), 'duration': timedelta(seconds=0.5)}
item_data = {'start_time': datetime.now(timezone.utc).isoformat(), 'duration': 0.5}
items = TypeAdapter(Dummy).validate_python(item_data)
print(items)

# prints:
# Dummy(start_time=datetime.datetime(...), duration=datetime.timedelta(0))
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.7.0
        pydantic-core version: 2.18.1
          pydantic-core build: profile=release pgo=true
                 install path: /eng/ggambon/.local/lib/python3.9/site-packages/pydantic
               python version: 3.9.18 (main, Jan 26 2024, 05:26:53)  [GCC 9.3.1 20200408 (Red Hat 9.3.1-2)]
                     platform: Linux-3.10.0-1062.12.1.el7.x86_64-x86_64-with-glibc2.17
             related packages: typing_extensions-4.11.0
                       commit: unknown
```

**Comment by sydney-runkle** [comment] 2024-04-18 13:34
@eltechnic0,

Hmm, I'm not able to reproduce on 2.7:

```py

from dataclasses import dataclass
from pydantic import TypeAdapter
from datetime import datetime, timedelta, timezone
from typing import Union

@dataclass
class Dummy:
    start_time: datetime
    duration: timedelta
    # duration: Union[timedelta, float]
    # duration: float

# item_data = {'start_time': datetime.now(timezone.utc).isoformat(), 'duration': timedelta(seconds=0.5)}
item_data = {'start_time': datetime.now(timezone.utc).isoformat(), 'duration': 1.5}
items = TypeAdapter(Dummy).validate_python(item_data)
print(items)
#> Dummy(start_time=datetime.datetime(2024, 4, 18, 13, 34, 25, 433385, tzinfo=TzInfo(UTC)), duration=datetime.timedelta(seconds=1, microseconds=500000))
```

Closing as resolved, feel free to ping me if I've missed something!

**Closed** 2024-06-19 23:36 UTC
Labels: bug V2, pending
