### ISSUE TITLE
strings do not cast to Literal types during model validation

### ISSUE THREAD

**Issue by slingshotvfx** [pydantic/pydantic#10566] opened 2024-10-07 17:17 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When instantiating a model that uses Literal types, Pydantic doesn't seem to cast the inputs to the Literal type.  This can lead to inconsistencies between `bool` and `Literal[False]` types, for example, where a `"False"` string will successfully validate to the former but not to the latter.

This is specifically an issue for me when trying to instantiate a settings model from environment variables, which are always strings.  See https://github.com/pydantic/pydantic-settings/issues/435

### Example Code

```Python
from pydantic import BaseModel

class Literals(BaseModel):
    A: bool
    B: Literal[False]
    C: int
    D: Literal[1]


args = {"A": "False", "B": "False", "C": "1", "D": "1"}

print(Literals(**args))


---

pydantic_core._pydantic_core.ValidationError: 2 validation errors for Literals
B
  Input should be False [type=literal_error, input_value='False', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/literal_error
D
  Input should be 1 [type=literal_error, input_value='1', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/literal_error
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.9.2
        pydantic-core version: 2.23.4
          pydantic-core build: profile=release pgo=false
               python version: 3.12.1 (tags/v3.12.1:2305ca5, Dec  7 2023, 22:03:25) [MSC v.1937 64 bit (AMD64)]
                     platform: Windows-11-10.0.22631-SP0
             related packages: fastapi-0.115.0 pydantic-settings-2.4.0 typing_extensions-4.12.2
                       commit: unknown
```

**Comment by sydney-runkle** [comment] 2024-10-07 17:48
Hi @slingshotvfx,

Marking this as a dupe of https://github.com/pydantic/pydantic/issues/9991, and closing accordingly. Thanks for your question - we don't plan to support this, for now.

**Closed by sydney-runkle** 2024-10-07 17:48 UTC
Labels: bug V2, pending
