### ISSUE TITLE
Migrating from pydantic v1 to v2 - Facing (no-member) warnings during code checking with pylint

### ISSUE THREAD

**Issue by devicehzy** [pydantic/pydantic#7051] opened 2023-08-09 03:15 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

* I am encountering some issues while migrating my project from pydantic v1 to v2.
* My project uses pylint for code checking, and I did not receive any (no-member) warnings when checking the code in v1. However, after upgrading to v2, I am getting a lot of (no-member) warnings. I understand that the Required, optional, and nullable fields in v2 are a significant change. How can I modify my code to pass the checks?  
```
 E1101: Instance of 'FieldInfo' has no 'split' member (no-member)
```

### Example Code

```Python
from typing import Optional
from pydantic import BaseModel, Field


"""
Origin Response:
{
    "Name": "test", # Name: Nullable
}
"""


class Model(BaseModel):
    name: Optional[str] = Field(default=None, alias="Name")


def get_name(**kwargs):
    obj = Model(**kwargs)
    if obj.name:
        return obj.name.split("")
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0
        pydantic-core version: 2.0.1 release build profile
                 install path: /Users/huangzhenyu/.pyenv/versions/3.10.12/envs/common-env/lib/python3.10/site-packages/pydantic
               python version: 3.10.12 (main, Aug  8 2023, 11:50:13) [Clang 14.0.3 (clang-1403.0.22.14.1)]
                     platform: macOS-13.4.1-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @Kludex

**Comment by Viicos** [comment] 2023-08-09 05:52
Duplicate of https://github.com/pydantic/pydantic/issues/6909

**Comment by Kludex** [comment] 2023-08-09 06:17
Thanks @Viicos 🙏

**Closed by Kludex** 2023-08-09 06:17 UTC
Labels: unconfirmed, bug V2

**Comment by tylerflex** [comment] 2023-08-09 14:09
@Kludex let me know if you figure out a good workaround. This is still an issue and neither pylint nor pydantic seem to have a solution

**Comment by kamichal** [comment] 2024-11-19 12:05
Related issue in pylint: https://github.com/pylint-dev/pylint/issues/10087
