### ISSUE TITLE
Unable to parse Zulu datetimes using standard library

### ISSUE THREAD

**Issue by harvey251** [pydantic/pydantic#6028] opened 2023-06-07 08:00 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

previously I was able to parse the datetimes using the standard library but now due to the "z" instead of "+00:00" I can't. 

not sure if this is expected behaviour

### Example Code

```Python
import json
from datetime import datetime
from pydantic import (
    BaseModel, AwareDatetime,
)
class Event(BaseModel):
    date_time: AwareDatetime
    other_date_time: datetime
event = Event(date_time="2022-07-28T15:48:57.045398+00:00", other_date_time="2022-07-28T15:48:57.045398+00:00").model_dump_json()
'{"date_time":"2022-07-28T15:48:57.045398Z","other_date_time":"2022-07-28T15:48:57.045398Z"}'
datetime.fromisoformat(json.loads(event)["date_time"])
Traceback (most recent call last):
  File "/snap/pycharm-professional/336/plugins/python/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 12, in <module>
ValueError: Invalid isoformat string: '2022-07-28T15:48:57.045398Z'
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0b2
        pydantic-core version: 0.38.0 release build profile
                 install path: /home/i31889/indicator-service/venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.7 (main, Sep  5 2022, 13:12:31) [GCC 11.2.0]
                     platform: Linux-5.19.0-43-generic-x86_64-with-glibc2.35
     optional deps. installed: ['typing-extensions']
```

**Comment by hramezani** [comment] 2023-06-07 09:31
It's working on Python 3.11 because [datetime.fromisoformat](https://docs.python.org/3.11/library/datetime.html#datetime.datetime.fromisoformat) has been changed in 3.11 to handle this format.

> not sure if this is expected behaviour

I am not sure but do you know which version of Pydantic was working before?

**Comment by harvey251** [comment] 2023-06-07 09:58
It was pydantic version 1.10.8

**Comment by hramezani** [comment] 2023-06-07 10:26
I think this is expected behavior but you can change the field serialization by `field_serializer` decorator:

```py
import json
from datetime import datetime
from pydantic import (
    BaseModel, AwareDatetime, field_serializer
)
class Event(BaseModel):
    date_time: AwareDatetime
    other_date_time: datetime

    @field_serializer('date_time')
    def ser_other_date_time(v):
        return v.isoformat()

event = Event(date_time="2022-07-28T15:48:57.045398+00:00", other_date_time="2022-07-28T15:48:57.045398+00:00").model_dump_json()
# '{"date_time":"2022-07-28T15:48:57.045398+00:00","other_date_time":"2022-07-28T15:48:57.045398Z"}'
d = datetime.fromisoformat(json.loads(event)["date_time"])
```

**Comment by harvey251** [comment] 2023-06-07 12:37
Thank you

I can work with that, it would be handy to to able to specify the format on the field or Annotations. I'm still trying to work it out from the limited docs.

**Comment by dmontagu** [comment] 2023-06-19 17:31
@harvey251 I think it should work now to use a custom annotation for this. Here's an example:

```python
import json
from datetime import datetime
from typing import Annotated

from pydantic import (
    BaseModel, AwareDatetime, field_serializer, PlainSerializer
)

NonZuluDatetime = Annotated[datetime, PlainSerializer(lambda v: v.isoformat())]


class Event(BaseModel):
    date_time: NonZuluDatetime
    other_date_time: datetime


event = Event(date_time="2022-07-28T15:48:57.045398+00:00", other_date_time="2022-07-28T15:48:57.045398+00:00").model_dump_json()
print(event)


# '{"date_time":"2022-07-28T15:48:57.045398+00:00","other_date_time":"2022-07-28T15:48:57.045398Z"}'
d = datetime.fromisoformat(json.loads(event)["date_time"])
```

If you want to be able to add this PlainSerializer to any type with a cleaner syntax, you could do something like this:
```python
AnyType = TypeVar('AnyType')

if typing.TYPE_CHECKING:
    NonZulu = Annotated[AnyType, ...]  # NonZulu[<type>] will be treated by type checkers as <type>
else:

    @dataclasses.dataclass
    class NonZulu:
        def __class_getitem__(cls, item: Any) -> Any:
            return Annotated[item, PlainSerializer(lambda v: v.isoformat())]
```
then you'd do:

```python
class Event(BaseModel):
    date_time: NonZulu[datetime]
    other_date_time: datetime
```
and things like `NonZulu[AwareDatetime]` etc. should "just work".

Given the above, I'm going to close this issue, but let us know if you want it reopened/etc.

**Closed by dmontagu** 2023-06-19 17:31 UTC
Labels: bug V2

**Comment by atom-andrew** [comment] 2023-10-28 00:17
I'm curious why https://github.com/pydantic/pydantic/issues/6518 was considered a regression (and was fixed) but this issue was not.  Can anyone say why?
