### ISSUE TITLE
Mypy plugin has issues with optional fields of base classes

### ISSUE THREAD

**Issue by haynesgt** [pydantic/pydantic#8052] opened 2023-11-07 22:27 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Optional base-class fields in objects of derived classes are not treated as optional in field assignments when running mypy with the pydantic-mypy plugin.

```
$ cat setup.cfg
[mypy]
plugins = pydantic.mypy
$ mypy test.py
test.py:12: error: Incompatible types in assignment (expression has type "None", variable has type "str")  [assignment]
```

### Example Code

```Python
from pydantic import BaseModel
from typing import Optional

class TestThing(BaseModel):
    my_type: Optional[str] = None

class DerivedThing(TestThing):
    pass

def go() -> None:
    val = DerivedThing()
    val.my_type = None
```

### Python, Pydantic & OS Version

```Text
             pydantic version: 2.4.2
        pydantic-core version: 2.10.1
          pydantic-core build: profile=release pgo=true
                 install path: /home/ubuntu/.local/share/virtualenvs/alert_storage-OtOo_1gT/lib/python3.11/site-packages/pydantic
               python version: 3.11.1 (main, Apr 20 2023, 06:08:03) [GCC 9.4.0]
                     platform: Linux-5.15.0-1047-aws-x86_64-with-glibc2.31
             related packages: email-validator-2.1.0.post1 pydantic-settings-2.0.3 typing_extensions-4.8.0 mypy-1.6.1 fastapi-0.103.2

mypy==1.6.1
```

**Comment by sydney-runkle** [comment] 2023-11-08 03:34
Hi @haynesgt,

Looks like you're using `pydantic` V1. When I run this example with V2, I don't get any errors. I'm not surprised that there are some issues with the `mypy` plugin and V1. We're only supporting critical bug fixes for V1 though, so I'd recommend switching to V2.

**Comment by haynesgt** [comment] 2023-11-08 03:36
@sydney-runkle 
Sorry this is with v2. I ran the version-getting command in the wrong vnev

**Comment by haynesgt** [comment] 2023-11-08 03:36
Did you use the setup.cfg when you tested it?

**Comment by haynesgt** [comment] 2023-11-08 03:41
[pt.zip](https://github.com/pydantic/pydantic/files/13291858/pt.zip)

**Comment by sydney-runkle** [comment] 2023-11-08 12:22
@haynesgt, yep I used the pydantic plugin specification. I was able to reproduce this in a different environment though, so I'll reopen 👍. Thanks for reporting!

**Comment by cesarmg1980** [comment] 2023-11-27 14:37
Hello! Any objections on me taking this bug? I've wanting to contribute and seems that this is a `good first issue`, thanks in advance! ✋🏽

**Comment by tyki6** [comment] 2024-01-04 16:25
Hello,
I am also seeing a similar problem.
Do you have any news @cesarmg1980 ?

# Test example
```python
from __future__ import annotations
from pydantic import BaseModel
from typing import Optional

class Foo(BaseModel):
    foo: Optional[str] = None

class Bar(Foo):
    bar: Optional[str] = None

test = Foo(foo="", bar="")
if test.foo is none:
  print("Hello World")
```

**mypy.ini**:
```bash
[mypy]
warn_unreachable = True
plugins = pydantic.mypy

[pydantic-mypy]
init_forbid_extra = True
```
# Env informations

**MYPY VERSION**: `mypy 1.8.0 (compiled: yes)`
**PYTANTIC VERSION** : `2.5.3`
**PYTHON VERSION** : `3.12.1`
**OS** : `linux (kali-linux)`

# Actual Behavior

```bash
mypy .
test.py:13: note: Revealed type is "builtins.str"
```

# Expected behaviour

```bash
mypy .
Success: no issues found in 286 source files
```

**Comment by cesarmg1980** [comment] 2024-01-04 23:50
> Do you have any news @cesarmg1980 / @sydney-runkle?

@tyki6 sorry, I couldn't start working on this yet, you should have news anytime soon

**Comment by cesarmg1980** [comment] 2024-02-17 23:38
@sydney-runkle feel free pass this issue to somebody else, I couldn't do much due to lack of time, I'll come back later to work on another issue

**Comment by KotlinIsland** [comment] 2024-04-08 05:22
This is a real blocker of using `BaseModels`, I've had to refactor everything to `dataclass` because of this.

**Comment by alexeyt101** [comment] 2024-04-09 14:13
Hello guys!
I'd like to work on this :)

**Comment by sydney-runkle** [comment] 2024-04-09 16:29
@alexeyt101,

Go for it!

**Comment by alexeyt101** [comment] 2024-04-13 11:57
Hello everyone!
I've tried to reproduce the code above and have got the errors.
I've also checked it on latest Pydantic (v.2.7.0) - it works clearly.

Fortunately, there is a fix which repairs the wrong behavior with Optional field https://github.com/pydantic/pydantic/commit/325ddf65af3ce01619b6ed028a6322d71f3c3c49

Seems it's not else to do here :)
@sydney-runkle , can you check my observations?

PS: I've noticed that some docs related with Pydantic mypy plugin aren't up to date. For example, source code section [here](https://docs.pydantic.dev/2.0/api/mypy/#pydantic.mypy.PydanticModelField.expand_type) and [here](https://docs.pydantic.dev/2.0/api/mypy/#pydantic.mypy.PydanticModelField.expand_typevar_from_subtype)

**Comment by sydney-runkle** [comment] 2024-04-28 20:44
@alexeyt101,

Awesome, closing now! Feel free to open a PR with a docs update if you see fit!

**Closed by sydney-runkle** 2024-04-28 20:44 UTC
Labels: help wanted, bug V2, good first issue, mypy
