### ISSUE TITLE
`merge_field_infos` doesn't merge `json_schema_extra` properly

### ISSUE THREAD

**Issue by philiptzou** [pydantic/pydantic#8581] opened 2024-01-18 20:20 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

We found if multiple `FieldInfo` instance is provided for a single field through `Annotated`, Pydantic will merge them into one `FieldInfo` instance. However, if multiple ones defined `json_schema_extra`, the different `json_schema_extra` won't be merged but the last one will be kept.

### Example Code

```Python
from pydantic.fields import FieldInfo, Field

def test_merge_json_schema_extra():
    field1 = Field(json_schema_extra={'aaa': 'bbb'})
    field2 = Field(json_schema_extra={'ccc': 'ddd'})
    # this failed
    assert FieldInfo.merge_field_infos(field1, field2).json_schema_extra == {'aaa': 'bbb', 'ccc': 'ddd'}
```

### Python, Pydantic & OS Version

```Text
        pydantic version: 2.5.3
        pydantic-core version: 2.14.6
          pydantic-core build: profile=release pgo=false
                 install path: /Users/philip/.local/share/virtualenvs/.../lib/python3.9/site-packages/pydantic
               python version: 3.9.18 (main, Nov  2 2023, 16:51:22)  [Clang 14.0.3 (clang-1403.0.22.14.1)]
                     platform: macOS-14.2.1-arm64-arm-64bit
             related packages: typing_extensions-4.9.0 mypy-1.8.0
```

**Comment by sydney-runkle** [comment] 2024-01-19 11:51
Hi @philiptzou,

Thanks for reporting this. Indeed - though this may seem counterintuitive, there's some logic behind this. Going to close this as a duplicate of #7686.

See [this comment](https://github.com/pydantic/pydantic/issues/7686#issuecomment-1743012511) regarding the reason why we're not planning on changing this behavior in V2, but would consider a change in V3!

**Closed by sydney-runkle** 2024-01-19 11:51 UTC
Labels: bug V2, pending
