### ISSUE TITLE
Ragatouille broken with pydantic==2.10.0 release

### ISSUE THREAD

**Issue by Quinn-Meyer-Sustainment** [pydantic/pydantic#10905] opened 2024-11-20 21:36 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

FYI for the devs since pydantic==2.10.0 released less than an hour ago.

Upgrading to pydantic==2.10.0 broke using ragatouille.

Downgrading to pydantic==2.9.2 solved the issue.

`

### Example Code

```Python
from ragatouille import RAGPretrainedModel

RAG = RAGPretrainedModel.from_pretrained("colbert-ir/colbertv2.0")

Here's the (long) stack trace:
`Traceback (most recent call last):
  File "/app/src/my_ragatouille_stuff.py", line 7, in <module>
    from ragatouille import RAGPretrainedModel
  File "/usr/local/lib/python3.10/dist-packages/ragatouille/__init__.py", line 2, in <module>
    from .RAGPretrainedModel import RAGPretrainedModel
  File "/usr/local/lib/python3.10/dist-packages/ragatouille/RAGPretrainedModel.py", line 8, in <module>
    from ragatouille.data.corpus_processor import CorpusProcessor
  File "/usr/local/lib/python3.10/dist-packages/ragatouille/data/__init__.py", line 1, in <module>
    from .corpus_processor import CorpusProcessor
  File "/usr/local/lib/python3.10/dist-packages/ragatouille/data/corpus_processor.py", line 4, in <module>
    from ragatouille.data.preprocessors import llama_index_sentence_splitter
  File "/usr/local/lib/python3.10/dist-packages/ragatouille/data/preprocessors.py", line 5, in <module>
    from llama_index.core import Document
  File "/usr/local/lib/python3.10/dist-packages/llama_index/core/__init__.py", line 19, in <module>
    from llama_index.core.indices import (
  File "/usr/local/lib/python3.10/dist-packages/llama_index/core/indices/__init__.py", line 4, in <module>
    from llama_index.core.indices.composability.graph import ComposableGraph
  File "/usr/local/lib/python3.10/dist-packages/llama_index/core/indices/composability/__init__.py", line 4, in <module>
    from llama_index.core.indices.composability.graph import ComposableGraph
  File "/usr/local/lib/python3.10/dist-packages/llama_index/core/indices/composability/graph.py", line 5, in <module>
    from llama_index.core.base.base_query_engine import BaseQueryEngine
  File "/usr/local/lib/python3.10/dist-packages/llama_index/core/base/base_query_engine.py", line 20, in <module>
    from llama_index.core.instrumentation.events.query import (
  File "/usr/local/lib/python3.10/dist-packages/llama_index/core/instrumentation/events/query.py", line 21, in <module>
    class QueryEndEvent(BaseEvent):
  File "/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_model_construction.py", line 226, in __new__
    complete_model_class(
  File "/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_model_construction.py", line 658, in complete_model_class
    schema = cls.__get_pydantic_core_schema__(cls, handler)
  File "/usr/local/lib/python3.10/dist-packages/pydantic/main.py", line 697, in __get_pydantic_core_schema__
    return handler(source)
  File "/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_schema_generation_shared.py", line 84, in __call__
    schema = self._handler(source_type)
  File "/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_generate_schema.py", line 612, in generate_schema
    schema = self._generate_schema_inner(obj)
  File "/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_generate_schema.py", line 881, in _generate_schema_inner
    return self._model_schema(obj)
  File "/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_generate_schema.py", line 693, in _model_schema
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
  File "/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_generate_schema.py", line 693, in <dictcomp>
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
  File "/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_generate_schema.py", line 1073, in _generate_md_field_schema
    common_field = self._common_field_schema(name, field_info, decorators)
  File "/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_generate_schema.py", line 1261, in _common_field_schema
    schema = self._apply_annotations(
  File "/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_generate_schema.py", line 2051, in _apply_annotations
    schema = get_inner_schema(source_type)
  File "/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_schema_generation_shared.py", line 84, in __call__
    schema = self._handler(source_type)
  File "/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_generate_schema.py", line 2032, in inner_handler
    schema = self._generate_schema_inner(obj)
  File "/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_generate_schema.py", line 886, in _generate_schema_inner
    return self.match_type(obj)
  File "/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_generate_schema.py", line 988, in match_type
    return self._match_generic_type(obj, origin)
  File "/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_generate_schema.py", line 1016, in _match_generic_type
    return self._union_schema(obj)
  File "/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_generate_schema.py", line 1323, in _union_schema
    choices.append(self.generate_schema(arg))
  File "/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_generate_schema.py", line 612, in generate_schema
    schema = self._generate_schema_inner(obj)
  File "/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_generate_schema.py", line 886, in _generate_schema_inner
    return self.match_type(obj)
  File "/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_generate_schema.py", line 984, in match_type
    return self._dataclass_schema(obj, None)
  File "/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_generate_schema.py", line 1765, in _dataclass_schema
    args = sorted(
  File "/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_generate_schema.py", line 1766, in <genexpr>
    (self._generate_dc_field_schema(k, v, decorators) for k, v in fields.items()),
  File "/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_generate_schema.py", line 1090, in _generate_dc_field_schema
    common_field = self._common_field_schema(name, field_info, decorators)
  File "/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_generate_schema.py", line 1261, in _common_field_schema
    schema = self._apply_annotations(
  File "/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_generate_schema.py", line 2051, in _apply_annotations
    schema = get_inner_schema(source_type)
  File "/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_schema_generation_shared.py", line 84, in __call__
    schema = self._handler(source_type)
  File "/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_generate_schema.py", line 2032, in inner_handler
    schema = self._generate_schema_inner(obj)
  File "/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_generate_schema.py", line 886, in _generate_schema_inner
    return self.match_type(obj)
  File "/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_generate_schema.py", line 988, in match_type
    return self._match_generic_type(obj, origin)
  File "/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_generate_schema.py", line 1045, in _match_generic_type
    return self._unknown_type_schema(obj)
  File "/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_generate_schema.py", line 515, in _unknown_type_schema
    raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for typing.AsyncGenerator[str, NoneType]. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.`
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.10.0
        pydantic-core version: 2.27.0
          pydantic-core build: profile=release pgo=false
                 install path: /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/pydantic
               python version: 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:45:18) [GCC 12.3.0]
                     platform: Linux-5.10.228-219.884.amzn2.x86_64-x86_64-with-glibc2.26
             related packages: typing_extensions-4.12.2 pydantic-settings-2.6.1
                       commit: unknown
```

**Comment by budleigh** [comment] 2024-11-20 21:42
We are also seeing this error in the new release via an unpegged dependency of llama-index and llama-parse.

**Comment by alexferl** [comment] 2024-11-20 21:50
I think it also broke SQLModel:

```
<string>:4: in __init__
    ???
../../Library/Caches/pypoetry/virtualenvs/reference-SpjYadir-py3.13/lib/python3.13/site-packages/sqlalchemy/orm/state.py:571: in _initialize_instance
    with util.safe_reraise():
../../Library/Caches/pypoetry/virtualenvs/reference-SpjYadir-py3.13/lib/python3.13/site-packages/sqlalchemy/util/langhelpers.py:146: in __exit__
    raise exc_value.with_traceback(exc_tb)
../../Library/Caches/pypoetry/virtualenvs/reference-SpjYadir-py3.13/lib/python3.13/site-packages/sqlalchemy/orm/state.py:569: in _initialize_instance
    manager.original_init(*mixed[1:], **kwargs)
../../Library/Caches/pypoetry/virtualenvs/reference-SpjYadir-py3.13/lib/python3.13/site-packages/sqlmodel/main.py:811: in __init__
    sqlmodel_init(self=__pydantic_self__, data=data)
../../Library/Caches/pypoetry/virtualenvs/reference-SpjYadir-py3.13/lib/python3.13/site-packages/sqlmodel/_compat.py:355: in sqlmodel_init
    sqlmodel_table_construct(
../../Library/Caches/pypoetry/virtualenvs/reference-SpjYadir-py3.13/lib/python3.13/site-packages/sqlmodel/_compat.py:255: in sqlmodel_table_construct
    defaults[name] = field.get_default(call_default_factory=True)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = FieldInfo(annotation=str, required=False, default_factory=<lambda>)

    def get_default(self, *, call_default_factory: bool = False, validated_data: dict[str, Any] | None = None) -> Any:
        """Get the default value.

        We expose an option for whether to call the default_factory (if present), as calling it may
        result in side effects that we want to avoid. However, there are times when it really should
        be called (namely, when instantiating a model via `model_construct`).

        Args:
            call_default_factory: Whether to call the default factory or not.
            validated_data: The already validated data to be passed to the default factory.

        Returns:
            The default value, calling the default factory if requested or `None` if not set.
        """
        if self.default_factory is None:
            return _utils.smart_deepcopy(self.default)
        elif call_default_factory:
            if validated_data is None:
>               raise ValueError("'validated_data' must be provided if 'call_default_factory' is True.")
E               ValueError: 'validated_data' must be provided if 'call_default_factory' is True.

../../Library/Caches/pypoetry/virtualenvs/reference-SpjYadir-py3.13/lib/python3.13/site-packages/pydantic/fields.py:596: ValueError
```

**Comment by logan-markewich** [comment] 2024-11-20 22:08
I am seeing this error in llama-index-core specifically. Would love to know why `typing.AsyncGenerator[str, None]` would cause a validation error even when `allow_arbitrary_types=True` is set 😅  Will see if I can write a patch for llama-index

**Comment by daroczig** [comment] 2024-11-20 22:14
We also started to see this error, e.g. at https://github.com/SpareCores/sc-data/actions/runs/11942356741/job/33289210581, probably due to using an [SQLModel field with a `default_factory` that doesn't take any args](https://github.com/SpareCores/sc-crawler/blob/main/src/sc_crawler/table_bases.py#L214-L218).

**Comment by sydney-runkle** [comment] 2024-11-20 22:22
Hey folks,

Thanks for the report. We're looking into this now, and will work on getting a fix out in a patch release soon!

**Comment by sydney-runkle** [comment] 2024-11-20 22:23
@zzstoatzz,

Looks like a different issue, can you please open a new ticket? Thanks!

**Comment by sydney-runkle** [comment] 2024-11-20 22:24
> We also started to see this error, e.g. at https://github.com/SpareCores/sc-data/actions/runs/11942356741/job/33289210581, probably due to using an [SQLModel field with a default_factory that doesn't take any args](https://github.com/SpareCores/sc-crawler/blob/main/src/sc_crawler/table_bases.py#L214-L218).

This should still work, we attempted to ensure backwards compatibility here, so we'll dig into this as well.

**Comment by logan-markewich** [comment] 2024-11-20 22:31
Detailing more adventures specific to llama-index
- we had some pydantic objects that had dataclass objects as items in the pydantic class
- the dataclass itself was failing to validate arbitrary types in this case (even though `allow_arbitrary_types=True` was set on the pydantic class, dataclass has no such option)
- after fixing that, seeing hundreds of errors, all similar to this but for various classes
```
pydantic.errors.PydanticUserError: `MockPostProcessor` is not fully defined; you should define `Dict`, then call `MockPostProcessor.model_rebuild()`.
```

Going to pin llama-index to <2.10 until this settles (thanks @sydney-runkle !)

**Comment by sydney-runkle** [comment] 2024-11-20 22:40
@logan-markewich,

Thanks for looking into this. Any chance you're able to provide a small contained example that we can use to reproduce?

**Comment by logan-markewich** [comment] 2024-11-20 22:43
For the dataclass issue, the below works in 2.9, breaks in 2.10

```
from dataclasses import dataclass
from typing import AsyncGenerator
from pydantic import BaseModel, ConfigDict

@dataclass
class Test:
  gen: AsyncGenerator[str, None]

class Reproduce(BaseModel):
  model_config = ConfigDict(arbitrary_types_allowed=True)
  test: Test

if __name__ == "__main__":
  async def async_gen():
    for x in "hello world":
      yield x

  repro = Reproduce(test=Test(gen=async_gen()))
```

**Comment by sydney-runkle** [comment] 2024-11-20 22:53
So, a couple of issues here:

- [ ] dataclass one with `AsyncGenerator`, working on a fix
- [ ] default factories x `SQLModel`, addressed here: https://github.com/pydantic/pydantic/pull/10909
- [ ] `Dict` namespace issues, waiting for a reproducible example

**Comment by sydney-runkle** [comment] 2024-11-20 23:23
Regarding the above dataclass issue, I'm not sure if that **should** work.

We only promise that config applies to the given model (or dataclass), and it doesn't push down to nested models (or dataclasses)...

**Comment by sydney-runkle** [comment] 2024-11-20 23:24
This works fine:

```py
from dataclasses import dataclass
from typing import AsyncGenerator
from pydantic import BaseModel, ConfigDict

@dataclass
class Test:
  gen: AsyncGenerator[str, None]

  __pydantic_config__ = ConfigDict(arbitrary_types_allowed=True)

class Reproduce(BaseModel):
  model_config = ConfigDict(arbitrary_types_allowed=True)
  test: Test

if __name__ == "__main__":
  async def async_gen():
    for x in "hello world":
      yield x

  repro = Reproduce(test=Test(gen=async_gen()))
```

**Comment by AyushParikh** [comment] 2024-11-21 00:29
llamaparse is broken

**Comment by logan-markewich** [comment] 2024-11-21 01:23
@AyushParikh llama parse is fine. Either install `llama-index-core==0.12.1` or ensure you install `pydantic<2.10` (let's try to keep this issue with very specific examples/reproducible code only)

**Comment by logan-markewich** [comment] 2024-11-21 02:05
@sydney-runkle Ok, I reproduced the `Dict` issue (this is as simple as I could make it)

`base.py`
```python
from __future__ import annotations

from typing import Any, Dict
from pydantic import BaseModel, model_serializer

class BaseComponent(BaseModel):

    @model_serializer(mode="wrap")
    def custom_model_dump(self, handler: Any) -> Dict[str, Any]:
        return handler(self)
```

`main.py`
```python
from base import BaseComponent

class Reproduce2(BaseComponent):
  is_base: bool = False

if __name__ == "__main__":
  repro = Reproduce2()
```

If I comment out `from __future__ import annotations` -- then it works.

Somehow, pydantic V2.10 broke this (arguably obscure) setup 😅

**Comment by Viicos** [comment] 2024-11-21 10:00
Many different issues were raised here. To avoid future duplicates, I'm closing this one in favor of:

- https://github.com/pydantic/pydantic/issues/10912

- https://github.com/pydantic/pydantic/issues/10917

- https://github.com/pydantic/pydantic/issues/10919

- https://github.com/pydantic/pydantic/issues/10907

- https://github.com/pydantic/pydantic/issues/10914

**Closed by Viicos** 2024-11-21 10:00 UTC
Labels: bug V2, pending

**Comment by sydney-runkle** [comment] 2024-11-21 11:16
Thanks @Viicos!
