### ISSUE TITLE
Pydantic fails to parse object: invents a new irrelevant object instead

### ISSUE THREAD

**Issue by HansBrende** [pydantic/pydantic#2513] opened 2021-03-12 06:52 UTC
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.1
            pydantic compiled: True
                 install path: /Users/hansbrende/opt/miniconda3/envs/testenv/lib/python3.7/site-packages/pydantic
               python version: 3.7.10 | packaged by conda-forge | (default, Feb 19 2021, 15:59:12)  [Clang 11.0.1 ]
                     platform: Darwin-19.0.0-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

```py
import pydantic
from typing import Union, List

class Item(pydantic.BaseModel):
    name: str

class Items(pydantic.BaseModel):
    items: Union[Item, List[Item]]

print(Items(items=[{'name': 'MY NAME', 'irrelevant': 'foobar'}]))
```
OUTPUT:
```
items=Item(name='irrelevant')
```
EXPECTED OUTPUT:
```
items=[Item(name='MY NAME')]
```
--------------------------
**EDIT: After discussion & reflection, I think the presence of the `Union` type in my example is a red herring. Here is an even more minimal example (with `Union` absent) that reproduces the fundamental bug here:**

```python
import pydantic

class Item(pydantic.BaseModel):
    name: str

print(Item.parse_obj([{'name': 'MY NAME', 'irrelevant': 'foobar'}]))
```

**OUTPUT:** 
```
name='irrelevant'
```
**EXPECTED OUTPUT: `ValidationError`**

**Note:** if I swap the order of fields in the dict to: `print(Item.parse_obj([{'irrelevant': 'foobar', 'name': 'MY NAME'}]))`, I do get a `ValidationError` as expected:
```
pydantic.error_wrappers.ValidationError: 1 validation error for Item
name
  field required (type=value_error.missing)
```
And if I add or remove a field from the dict (so that the dict no longer contains 2 items), I get the expected `ValidationError`:
```
pydantic.error_wrappers.ValidationError: 1 validation error for Item
__root__
  Item expected dict not list (type=type_error)
```

I have proposed a couple [quick-fixes](https://github.com/samuelcolvin/pydantic/issues/2513#issuecomment-797818962) for this bug; I can open a PR for one of them if desired. As pointed out in the comments, I realize this will be fixed automatically in v2 by #1268; however, 3 of my proposed fixes are pretty much backwards-compatible with existing behavior, so I would think one of them could be introduced *before* v2.

**Comment by PrettyWood** [comment] 2021-03-12 06:55
Hi @HansBrende 
This is a known issue that may be fixed in v1.9
See https://github.com/samuelcolvin/pydantic/pull/2092#issuecomment-763833122 for the proposal

**Comment by HansBrende** [comment] 2021-03-12 06:57
@PrettyWood Although the issue you linked to also involves unions, I don't believe this is the same issue AT ALL... unless I am totally missing something!

**Comment by HansBrende** [comment] 2021-03-12 07:04
@PrettyWood to give you a better idea of how weird this is, if I change the dictionary order to:
```
print(Items(items=[{'irrelevant': 'foobar', 'name': 'MY NAME'}]))
```
Then the output is correct:
```
items=[Item(name='MY NAME')]
```
If I add a second irrelevant key to the dictionary:
```
print(Items(items=[{'name': 'MY NAME', 'irrelevant': 'foobar', 'irrelevant2': 'hello'}]))
```
Then the output is still correct:
```
items=[Item(name='MY NAME')]
```

**Comment by PrettyWood** [comment] 2021-03-12 07:17
Yes I know it's the exact same issue that I linked even though it's hard to see the relationship. Pydantic tries to match types in the order of the union. And for this can coerce.
The issue is that it first calls `dict()` to match a BaseModel.
And `dict([{a: 1, b: 2}]) == {a: b}`. If the number of items is odd the coercion fails but if it's even it works.
Hence the solution I linked with cases like https://github.com/PrettyWood/pydantic/pull/66/files#diff-bd467a363c9f155a2e6a7716aeca0c351089135a53d09a66138cea4f16506ebdR2728-R2738

**Comment by HansBrende** [comment] 2021-03-12 07:21
@PrettyWood Gotcha, that makes sense. Thanks for the explanation!

**Comment by PrettyWood** [comment] 2021-03-12 11:49
I keep it open since I'll need to add extra logic for this in the PR for `SmartUnion`

**Comment by HansBrende** [comment] 2021-03-12 23:11
@PrettyWood coming back to this now that I've had some time to mull it over: the real bug in this specific example (in my mind) is not so much the absence of `SmartUnion` but the _ability_ of pydantic to parse such a contrived `Item` from a list containing a dict. So if we remove the `Union` type altogether to avoid the red herring, what this really boils down to is the following bug:
```
import pydantic

class Item(pydantic.BaseModel):
    name: str

print(Item.parse_obj([{'name': 'MY NAME', 'irrelevant': 'foobar'}]))
```
OUTPUTS:
```
name='irrelevant'
```
EXPECTED OUTPUT: Validation Error

Whereas, swapping the order of the dict to
```
print(Item.parse_obj([{'irrelevant': 'foobar', 'name': 'MY NAME'}]))
```
We get the expected validation error, as we should:
```
pydantic.error_wrappers.ValidationError: 1 validation error for Item
name
  field required (type=value_error.missing)
```

Current behavior is very much non-deterministic... which should qualify as a bug in its own right (*independent of how unions are implemented*).

**Comment by HansBrende** [comment] 2021-03-12 23:53
@PrettyWood here is a *rough* quick-fix that would completely eliminate this problem. Rather than unconditionally calling `dict(input)` on everything, why not do something along these lines?

```
def convert_to_a_REASONABLE_dict(input) -> dict
    if hasattr(input, '__iter__'):
       for x in input:
           if isinstance(x, dict):
               raise ValidationError
    return dict(input)
```

**Comment by PrettyWood** [comment] 2021-03-13 10:58
This will be done for v2 https://github.com/samuelcolvin/pydantic/issues/1268

**Comment by HansBrende** [comment] 2021-03-13 19:48
@PrettyWood Great to hear! In that case, my approach 2 or 3 (or something similar) could potentially be snuck in before 2.0, since it is not really a breaking change, correct?

**Comment by HansBrende** [comment] 2021-03-14 00:18
### Approach #​4: use existing `validators.tuple_validator()`!
I just noticed as I was browsing the `pydantic.validators` source code that you _already_ have a `tuple_validator` written. So a 4th approach would be to simply tweak your existing `dict_validator` via your existing `tuple_validator` (importantly, the `tuple_validator` does *not* allow dicts)!

```python
def dict_validator(v: Any) -> Dict[Any, Any]:
    if isinstance(v, dict):
        return v
    if not hasattr(v, 'keys'):
       v = (tuple_validator(t) for t in v)
    try:
        return dict(v)
    except (TypeError, ValueError, errors.TupleError):
        raise errors.DictError()
```

**Comment by HansBrende** [comment] 2021-03-14 00:26
@PrettyWood @samuelcolvin What do you think? Should I submit a PR for one of these approaches?

**Comment by dmontagu** [comment] 2023-04-28 17:44
This is fixed in v2

**Closed by dmontagu** 2023-04-28 17:44 UTC
Labels: bug V1
