### ISSUE TITLE
Upgrade from v1.10.14 to 1.10.16 breaks the create_model().schema()

### ISSUE THREAD

**Issue by rc19** [pydantic/pydantic#9687] opened 2024-06-18 22:23 UTC
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

I have a function and I am creating a pydantic model for its signature using `from inspect import signature` method.

Here is the code for creating a pydantic model

```
def create_schema_from_function(
    name: str,
    func: Callable[..., Any],
) -> Type[BaseModel]:
    """Create schema from function."""
    fields = {}
    params = signature(func).parameters
    for param_name in params:
        param_type = params[param_name].annotation
        param_default = params[param_name].default

        if param_type is params[param_name].empty:
            param_type = Any

        if param_default is params[param_name].empty:
            # Required field
            fields[param_name] = (param_type, FieldInfo())
        elif isinstance(param_default, FieldInfo):
            # Field with pydantic.Field as default value
            fields[param_name] = (param_type, param_default)
        else:
            fields[param_name] = (param_type, FieldInfo(default=param_default))

    return create_model(name, **fields)
```
now let'sa say I have a function `fn` and I do `fn_schema = create_schema_from_function("hello", fn)`

when I do `fn_schema.__fields__`

in v1.10.14 I get

```
{'bu': ModelField(name='bu', type=List[str], required=True),
 'md': ModelField(name='md', type=int, required=False, default=1),
 'mnu': ModelField(name='mnu', type=Optional[int], required=False, default=None),
 'cs': ModelField(name='cs', type=bool, required=False, default=False)}
```

while in v1.10.16 I get

```
{'bu': ModelField(name='bu', type=List[str], required=False, default=FieldInfo(default=PydanticUndefined, extra={})),
 'md': ModelField(name='md', type=int, required=False, default=FieldInfo(default=1, extra={})),
 'mnu': ModelField(name='mnu', type=Optional[int], required=False, default=FieldInfo(extra={})),
 'cs': ModelField(name='cs', type=bool, required=False, default=FieldInfo(default=False, extra={}))}
```

The only things different is the version of pydantic. My code (`fn`) is unchanged.

**Potential Bugs**
- the `bu` variable changes from being required to not being required
- the defaulr values changes to `FieldInfo` which runs into the issue of `Object of type 'FieldInfo' is not JSON serializable` when I call fn_schema.schema()

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.14
            pydantic compiled: False
                 install path: /Users/chetanyarastogi/Library/Caches/pypoetry/virtualenvs/gateway-1yhqMIT8-py3.12/lib/python3.12/site-packages/pydantic
               python version: 3.12.3 (main, Apr  9 2024, 08:09:14) [Clang 15.0.0 (clang-1500.1.0.2.5)]
                     platform: macOS-14.5-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [X] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [X] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment] 2024-06-19 13:43
Hmm, I'm not able to reproduce this issue on v1.10.16. Could you please check your development environment + report back regarding the version you're using?

```py
from inspect import signature
from typing import Any, Callable, List, Optional, Type
from pprint import pprint

from pydantic import BaseModel, create_model
from pydantic.fields import FieldInfo


def create_schema_from_function(
    name: str,
    func: Callable[..., Any],
) -> Type[BaseModel]:
    """Create schema from function."""
    fields = {}
    params = signature(func).parameters
    for param_name in params:
        param_type = params[param_name].annotation
        param_default = params[param_name].default

        if param_type is params[param_name].empty:
            param_type = Any

        if param_default is params[param_name].empty:
            # Required field
            fields[param_name] = (param_type, FieldInfo())
        elif isinstance(param_default, FieldInfo):
            # Field with pydantic.Field as default value
            fields[param_name] = (param_type, param_default)
        else:
            fields[param_name] = (param_type, FieldInfo(default=param_default))

    return create_model(name, **fields)


def fn(bu: List[str], md: int = 1, mnu: Optional[int] = None, cs: bool = False):
    pass


fn_schema = create_schema_from_function('hello', fn)
pprint(fn_schema.__fields__)
"""
{'bu': ModelField(name='bu', type=List[str], required=True),
 'cs': ModelField(name='cs', type=bool, required=False, default=False),
 'md': ModelField(name='md', type=int, required=False, default=1),
 'mnu': ModelField(name='mnu', type=Optional[int], required=False, default=None)}
"""
```

**Comment by sydney-runkle** [comment] 2024-06-19 15:01
We're not able to reproduce this bug at the moment, so I'm going to close this issue.

**Closed by sydney-runkle** 2024-06-19 15:01 UTC
Labels: bug V1, pending
