### ISSUE TITLE
"none is not an allowed value" in recursive type

### ISSUE THREAD

**Issue by jlamypoirier** [pydantic/pydantic#1624] opened 2020-06-10 21:00 UTC
# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.5.1
            pydantic compiled: True
                 install path: /home/joel/Python3.7/lib/python3.7/site-packages/pydantic
               python version: 3.7.7 (default, Mar 10 2020, 15:16:38)  [GCC 7.5.0]
                     platform: Linux-5.3.0-53-generic-x86_64-with-Ubuntu-18.04-bionic
     optional deps. installed: ['typing-extensions']
```

I'm defining a recursive type with `None` allowed, here is a minimal example:
```py

from pydantic import BaseModel, StrictInt
from typing import Dict, List, Union
Nested = Union[
    None,
    StrictInt,
    List["Nested"],
    Dict[str, "Nested"],
]

class Model(BaseModel):
    var: Nested
```

It works fine at the first level and for integers
```
>>> Model(var={"a":None, "b": 6, "c": {"a": 4}})
Model(var={'a': None, 'b': 6, 'c': {'a': 4}})
```

However it doesn't complain for nested entries
```
>>> Model(var={"a":None, "b": 6, "c": {6: 4.5}})
Model(var={'a': None, 'b': 6, 'c': {'6': 4.5}})
```

I would assume there is no validation in the recursive part, which is OK I guess, but it crashes if there is a `None` in a nested dict or list. For example, the following should be valid but raises an error:
```
>>> Model(var={"a": {"a":None}})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pydantic/main.py", line 338, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for Model
var
  value is not a valid integer (type=type_error.integer)
var
  value is not a valid list (type=type_error.list)
var -> a
  value is not a valid integer (type=type_error.integer)
var -> a
  value is not a valid list (type=type_error.list)
var -> a -> a
  none is not an allowed value (type=type_error.none.not_allowed)
```
```
>>> Model(var={"a": [None]})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pydantic/main.py", line 338, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for Model
var
  value is not a valid integer (type=type_error.integer)
var
  value is not a valid list (type=type_error.list)
var -> a
  value is not a valid integer (type=type_error.integer)
var -> a -> 0
  none is not an allowed value (type=type_error.none.not_allowed)
var -> a
  value is not a valid dict (type=type_error.dict)

```

**Comment by samuelcolvin** [comment] 2020-06-11 14:31
`Model(var={"a":None, "b": 6, "c": {6: 4.5}})` is valid - currently ints are coerced to strings, this might change in v2 but that isn't related to this problem.

---

The problem is that pydantic has some custom bahaviour to cope with `None` (this was for performance reasons but might have been a mistake - again fixing that is an option in v2).

I suspect the problem is that the recursive model somehow means that `field.allow_none` is not being set to `True`.

I'll try and fix this in the reworking for v2, but feel free to try and work on it now - if you get it fix with suitable unit tests it'll stay fixed in v2.

**Comment by jlamypoirier** [comment] 2020-06-11 23:38
> `Model(var={"a":None, "b": 6, "c": {6: 4.5}})` is valid - currently ints are coerced to strings, this might change in v2 but that isn't related to this problem.

Sorry I got the string part of the example wrong, but `4.5` is also accepted as a `StrictInt`. 

A more correct example for the string entry:
```
from pydantic import BaseModel, StrictInt, StrictStr
from typing import Dict, List, Union
Nested = Union[
    None,
    StrictInt,
    List["Nested"],
    Dict[StrictStr, "Nested"],
]

class Model(BaseModel):
    var: Nested
```
```
>>> Model(var={"a":None, "b": 6, "c":{ "d":{6: 4}}})
Model(var={'a': None, 'b': 6, 'c': {'d': {6: 4.5}}})
```

**Comment by jlamypoirier** [comment] 2020-06-12 00:45
Dug into the issue a bit, the problem seems to be only at the second level of recursion
```
>>> Model(var=[None]) # Ok
Model(var=[None])
>>> Model(var=[[None]]) # Ok but crashes
[...]
pydantic.error_wrappers.ValidationError: 5 validation errors for Model
var
  value is not a valid integer (type=type_error.integer)
var -> 0
  value is not a valid integer (type=type_error.integer)
var -> 0 -> 0
  none is not an allowed value (type=type_error.none.not_allowed)
var -> 0
  value is not a valid dict (type=type_error.dict)
var
  value is not a valid dict (type=type_error.dict)
>>> Model(var=[[[None]]]) # Ok but not validated
Model(var=[[[None]]])
```
Looking at the field type
```
>>> Model.__fields__["var"].type_
typing.Union[NoneType, pydantic.types.StrictInt, typing.List[typing.Union[NoneType, pydantic.types.StrictInt, typing.List[ForwardRef('Nested')], typing.Dict[pydantic.types.StrictStr, ForwardRef('Nested')]]], typing.Dict[pydantic.types.StrictStr, typing.Union[NoneType, pydantic.types.StrictInt, typing.List[ForwardRef('Nested')], typing.Dict[pydantic.types.StrictStr, ForwardRef('Nested')]]]]
```
It matches the location of the `ForwardRef('Nested')`. For nested models there is a check on validation https://github.com/samuelcolvin/pydantic/blob/master/pydantic/main.py#L866 but not for nested fields. (In any case calling `Model.update_forward_refs` is causing an infinite recursion for recursive types.) In the end the second level of recursion contains a `ForwardRef` that is not validated at all (https://github.com/samuelcolvin/pydantic/blob/master/pydantic/validators.py#L555), but its `allow_none` variable is set to False (https://github.com/samuelcolvin/pydantic/blob/master/pydantic/fields.py#L352). 

Explicitly setting `allow_none=True` for `ForwardRef` would prevent crashes with `None`, although I don't think `ForwardRef` is meant to be used at all in validation, and it still doesn't validate recursively.

**Comment by samuelcolvin** [comment] 2023-04-25 18:21
should be fixed on main, please create a new issue if you still see this or related.

**Closed by samuelcolvin** 2023-04-25 18:21 UTC
Labels: bug V1
