### ISSUE TITLE
model_dump_json discards significant figures in timestamps that end in 0

### ISSUE THREAD

**Issue by tucked** [pydantic/pydantic#7084] opened 2023-08-11 02:00 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

``` python
(Pdb) pp obj.modified
datetime.datetime(2023, 8, 11, 1, 12, 16, 55400, tzinfo=TzInfo(UTC))
(Pdb) pp str(obj.modified)
'2023-08-11 01:12:16.055400+00:00'
(Pdb) pp obj.model_dump_json(include="modified")
'{"modified":"2023-08-11T01:12:16.0554Z"}'
```
`055400` indicates 6-digit precision while `0554` only indicates 4-digit precision.
Truncating trailing zeroes implies that either
- those 2 digits are _not_ significant, or
- the timestamp has infinite precision, such that an arbitrary number of trailing zeroes may be appended

Neither of which are true.
Moreover, the dumped JSON can't be reloaded using `datetime.fromisoformat`:
``` python
(Pdb) pp datetime.fromisoformat(str(obj.modified))
datetime.datetime(2023, 8, 11, 1, 12, 16, 55400, tzinfo=datetime.timezone.utc)
(Pdb) pp datetime.fromisoformat(json.loads(obj.model_dump_json(include="modified"))["modified"])
*** ValueError: Invalid isoformat string: '2023-08-11T01:12:16.0554Z'
```

### Python, Pydantic & OS Version

```Text
             pydantic version: 2.1.1
        pydantic-core version: 2.4.0
          pydantic-core build: profile=release pgo=true mimalloc=true
                 install path: /ifs/home/tucked/projects/some-project/.tox/py38/lib/python3.8/site-packages/pydantic
               python version: 3.8.14 (default, May  4 2023, 21:08:14)  [GCC 7.5.0]
                     platform: Linux-5.14.21-150400.24.74-default-x86_64-with-glibc2.29
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @davidhewitt

**Comment by davidhewitt** [comment] 2023-08-11 08:29
Thanks - duplicate of #6761, and we're working to fix this 👍

**Closed by davidhewitt** 2023-08-11 08:29 UTC
Labels: unconfirmed, bug V2
