### ISSUE TITLE
V2: Generics

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic#4665] opened 2022-10-27 16:12 UTC
I think @PrettyWood has some ideas on this.

Basically we want generic models to work on V2, at least as well as they do on V1.

@PrettyWood if you don't think you'll have time to work on this, please unassign yourself, and hopefully someone else can take this on.

Either way, it would be great if you could describe what you were thinking.

**Comment by PrettyWood** [comment] 2022-11-02 15:32
Now that we don't have cython, generic models should be handled easily following [PEP 484](https://peps.python.org/pep-0484/#user-defined-generic-types). That's all!
But I'll be more than happy to check out if everything works well (validation, schema generation...)

**Comment by daviskirk** [comment] 2022-11-02 18:59
As I'll probably be using these in various places, I will also try to iron out any kinks I might find

**Comment by samuelcolvin** [comment] 2023-01-04 13:09
Try to support #4908

**Comment by samuelcolvin** [comment] 2023-01-11 16:49
@dmontagu who implemented the original Generic functionality mentioned he might be able to work on this.

@PrettyWood hope that's okay, if you're really keen to take this one, let us know and I'm sure that's fine.

**Comment by PrettyWood** [comment] 2023-01-11 16:54
I'm more than happy to work less :D

**Comment by caniko** [comment] 2023-01-18 10:33
Please keep [PEP646](https://peps.python.org/pep-0646/), variadic generics, in mind! I haven't tested Pydantic with variadic generic yet, I'll look into it if noone else has.

**Comment by dmontagu** [comment] 2023-01-18 18:28
@samuelcolvin

It seems to me that if we want to drop the use of `GenericModel` (and I think we should), there are a handful of places we could put the relevant logic for doing different things to the class if `typing.Generic` is one of the bases:
* `BaseModel.__class_getitem__`  (as it currently is in `GenericModel`)
* `ModelMetaclass.__new__`
* `BaseModel.__init_subclass__`
* Somewhere else?

Before I go too far down the rabbit hole I wanted to see if you already had any thoughts about this choice. I know when we implemented `GenericModel`, compatibility with Cython dictated some of the awkwardness; since that's no longer an issue I wanted to make sure I reconsidered all possibilities. (I can't remember if some of the above approaches had other problems that were not related to Cython; guess I'll find out 😅 ).

I'm sure at least some of the logic will belong in `__class_getitem__` (since that's where the new class has to be created) but I was just thinking moving some of the class creation logic (specifically, the typevar substitution) to one of the other methods above _might_ be able to reduce the need for complex calls to `create_model`. Or maybe not, I haven't fully refreshed my recollection of how the typevar substitution happens.

If you haven't thought about it too much or otherwise don't have strong opinions about how this should be done, I would propose to start by just adding `__class_getitem__` as a method on `BaseModel`, and making (non-invasive) changes to `ModelMetaclass.__new__` and/or add a `BaseModel.__init_subclass__` method as feels appropriate.

If you have a different approach in mind, or want me to more strongly bias away from changes to anything besides `BaseModel.__class_getitem__`, just let me know.

**Comment by dmontagu** [comment] 2023-01-18 18:42
> Please keep [PEP646](https://peps.python.org/pep-0646/), variadic generics, in mind! I haven't tested Pydantic with variadic generic yet, I'll look into it if nobody has.

Just dropping a note here for reference during the implementation, since it took me some effort to think through how pydantic should work with `TypeVarTuple` -- I think it would be nice if we could handle the use case of having a generic pydantic model capable of validating the shape/types of a tensor-like object.

Drawing heavily on the summary example in PEP646, it would be nice if you could define something like:

```
from typing import TypeVar, TypeVarTuple

DType = TypeVar('DType')
Shape = TypeVarTuple('Shape')

class Array(Generic[DType, *Shape]):
    def __abs__(self) -> Array[DType, *Shape]: ...
    def __add__(self, other: Array[DType, *Shape]) -> Array[DType, *Shape]: ...

class MyArrayWrapper(BaseModel, Generic[DType, *Shape]):
    array: Array[DType, *Shape]
```

and, through some set of validator definitions, etc., set it up so that:
```
Height = NewType('Height', int)
Width = NewType('Width', int)

array1 = Array([1.0, 2.0])
array2 = Array([[1.0, 2.0]])
MyArrayWrapper[float, Height](array=array1)  # validates successfully
MyArrayWrapper[float, Height, Width](array=array2)  # validates successfully

MyArrayWrapper[float, Height](array=array2)  # raises ValidationError
MyArrayWrapper[float, Height, Width](array=array1)  # raises ValidationError
```

Perhaps there is a more concise/general example to work from than a generic wrapper type for the generic `Array`, but this is a good example of a use case where runtime validation could help significantly shorten the debugging process for errors caused by invalid array shape issues (especially when interfacing with data that doesn't have fully specified dimension types). And in principle, assuming the underlying arrays aren't tiny, I would think the runtime overhead of this specific use case (i.e., validating dimensions/data types) should be pretty cheap, so it seems like a realistic example.

**Comment by samuelcolvin** [comment] 2023-01-18 22:01
> there are a handful of places we could put the relevant logic for doing different things to the class if typing.Generic is one of the bases:

We currently use `ModelMetaclass.__new__`, I thought about moving all the logic to `__init_subclass__` but there was a reason (I can't rember why I didn't). I think it might be possible now or in the future.

The main thing to say is that the majority of the logic for building a pydantic model is actually in [`pydantic._internal._model_construction`](https://github.com/pydantic/pydantic/blob/main/pydantic/_internal/_model_construction.py) - where possible I'd prefer to keep complex logic, then "just call it" from whichever method on `BaseModel`.

There should be no need whatsoever to use `create_model` - `create_model` only really exists now for external use and for backwards compatibility.

I guess my initial guess at how generics should work is as follows:
* the current logic builds a schema but not the validator and serializer - this is the same as the logic we have for models which can't be fulled defined until later, see #4882 for some discussion
* `__class_getitem__` completes `__pydantic_validation_schema__` to include schema for the generics bits
* `__class_getitem__` then builds the validator (and serializer) based on the new core-schema - you might be able to do the rebuilding logic using [`model_rebiuld()`](https://github.com/pydantic/pydantic/blob/ef8f9fe51b9d0e38693f70482c29ba124f810d5a/pydantic/main.py#L464)

**Comment by dmontagu** [comment] 2023-01-18 22:29
@samuelcolvin another question -- I noticed in 1.X it lets you use non-parameterized TypeVars and handles the case of having a bound and having constraints as you'd expect. Is this something we want to retain? I assumed the answer was yes, but I noticed that `pydantic._internal._generate_schema.GenerateSchema.generate_schema` doesn't seem to handle `TypeVar`s and that made me second guess.

In particular, if we want to retain the current behavior of allowing typevars (which I think makes sense considering it's similar to an un-parameterized `list` or `dict`), I would propose adding:
```python
        elif isinstance(obj, typing.TypeVar):
            if obj.__bound__:
                return self.generate_schema(obj.__bound__)
            if obj.__constraints__:
                return self._union_schema(typing.Union[*obj.__constraints__])
            return core_schema.AnySchema(type='any')
```
(or something like it) on line 120 here: https://github.com/pydantic/pydantic/blob/ef8f9fe51b9d0e38693f70482c29ba124f810d5a/pydantic/_internal/_generate_schema.py#L116-L123.

Is that reasonable?

Sorry for all the questions, I just figure that the way we handle TypeVars might have a large impact on the way the rest of the class creation stuff works.

**Comment by samuelcolvin** [comment] 2023-01-18 22:37
Just an oversight on my part, I'm sure `generate_schema` as lots of omissions.

Whatever you think the best behaviour is, bonus if it's compatible with V1.

**Comment by dmontagu** [comment] 2023-01-19 17:50
@samuelcolvin 

> There should be no need whatsoever to use create_model - create_model only really exists now for external use and for backwards compatibility.

My current conception is that when we parameterize generics models, we will create a new class (specifically, a new subclass of BaseModel) that will have the updated schema, etc. (It feels to me like this is necessary in order to have multiple coexisting generic parameterizations.)

Am I missing something? And/or did you have something else in mind?

If not, is there a preferred way to create a subclass of the parent (generic) class that will have the updated schema/validators/serialization/etc.? I could declare a subclass in the `__class_getitem__`, or just use some subset of the logic in the current `create_model`, but, at least my current understanding is that we'd need a new class to get different schema-related behavior, and I don't see where that would happen without something along the lines of `create_model`.

**Comment by dmontagu** [comment] 2023-01-19 17:55
Yes that makes sense; if we don't want to use `create_model`, is there a different preferred way of creating the subclass? Just declaring it like standard python and manipulating the `__name__`, `__module__`, etc., as appropriate?

**Comment by samuelcolvin** [comment] 2023-01-19 18:08
Best to use standard machinery to create the subclass, then modify the core schema and build the validator etc.

You could even modify the current model construction logic to support generics.

**Comment by dmontagu** [comment] 2023-03-13 18:31
@samuelcolvin Can we close this issue? I'd prefer to create a separate issue for handling dataclasses and TypedDict, but we could use this for tracking those if preferred.

**Comment by dmontagu** [comment] 2023-04-04 18:34
Closing in favor of #5351

**Closed by dmontagu** 2023-04-04 18:34 UTC
Labels: feature request, help wanted
