### ISSUE TITLE
MyPy with Pydantic plugin unable to handle annotated default / default_factory

### ISSUE THREAD

**Issue by palle-k** [pydantic/pydantic#11036] opened 2024-12-03 13:59 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When type checking a base model with annotated default / default_factory values, Mypy complains about missing named arguments.

mypy.ini:

```
[mypy]
plugins = pydantic.mypy
```

With the example code in main.py, running `mypy main.py` yields the following type errors:

```
main.py:11: error: Missing named argument "foo" for "Example"  [call-arg]
main.py:11: error: Missing named argument "bar" for "Example"  [call-arg]
Found 2 errors in 1 file (checked 1 source file)
```

```
$ mypy --version
mypy 1.13.0 (compiled: yes)
``` 

### Example Code

```Python
from typing import Annotated
from pydantic import BaseModel, Field


class Example(BaseModel):
    foo: Annotated[list[str], Field(default=[])]
    bar: Annotated[list[str], Field(default_factory=list)]


if __name__ == "__main__":
    print(Example())
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.10.2
        pydantic-core version: 2.27.1
          pydantic-core build: profile=release pgo=false
                 install path: /path/to/venv/lib/python3.12/site-packages/pydantic
               python version: 3.12.7 (main, Oct  1 2024, 02:05:46) [Clang 16.0.0 (clang-1600.0.26.3)]
                     platform: macOS-15.2-arm64-arm-64bit
             related packages: pydantic-settings-2.6.1 mypy-1.13.0 fastapi-0.115.5 typing_extensions-4.12.2
                       commit: unknown
```

**Comment by palle-k** [comment] 2024-12-03 16:05
Additional note: Using the `field_name: list[...] = Field(default=...)` syntax emits a PyCharm type checker error (PyDataclass: Mutable default 'Field(default_factory=list)' is not allowed. Use 'default_factory')

**Comment by Viicos** [comment] 2024-12-05 17:01
Duplicate of https://github.com/pydantic/pydantic/issues/6713.

> Additional note: Using the `field_name: list[...] = Field(default=...)` syntax emits a PyCharm type checker error (PyDataclass: Mutable default 'Field(default_factory=list)' is not allowed. Use 'default_factory') - https://youtrack.jetbrains.com/issue/PY-77433/Incorrect-Mutable-Default-Error-in-Pydantic-Model

As far as type checkers are concerned, Pydantic models behave the same way as dataclasses, hence the error.

**Closed by Viicos** 2024-12-05 17:01 UTC
Labels: bug V2, pending
