### ISSUE TITLE
Mypy plugin doesn't consider `allow_population_by_field_name`

### ISSUE THREAD

**Issue by jonathanslenders** [pydantic/pydantic#5070] opened 2023-02-17 21:43 UTC
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Probably an issue with the Pydantic mypy plugin. It happened after the mypy 1.0.0 release.

Consider this code, and run `mypy --strict`:
```python
from pydantic import BaseModel, Field

class Model(BaseModel):
    field: str = Field(alias="alias")

    class Config:
        allow_population_by_field_name = True

Model(alias="")  # OK.
Model(field="")  # error: Unexpected keyword argument "field" for "Model"  [call-arg]
```

At runtime, this is fine, because of the `allow_population_by_field_name` setting, but the mypy plugin only allows instantiating the class through the alias.

### Python, Pydantic & OS Version

```Text
Python 3.9.13
Pydantic 1.10.5
Ubuntu on ARM, Linux 5.15.0-58
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [X] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [X] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by jonathanslenders** [comment] 2023-02-21 13:17
More interesting, there is a difference between mypy 1.0.1 and the latest from GitHub. They do the opposite. The file `test.py` is the snippet from above:

```
$ mypy --version
mypy 1.0.1 (compiled: no)

$ mypy --strict ./test.py
test.py:9: error: Unexpected keyword argument "alias" for "Model"  [call-arg]
Found 1 error in 1 file (checked 1 source file)

$ mypy --version
mypy 1.1.0+dev.ed3a6c1c019a8098f65e768697f1048d1f97a4a1 (compiled: no)

$ mypy --strict ./test.py
test.py:10: error: Unexpected keyword argument "field" for "Model"  [call-arg]
Found 1 error in 1 file (checked 1 source file)
```

**Comment by cdce8p** [comment] 2023-02-21 13:32
> More interesting, there is a difference between mypy 1.0.1 and the latest from GitHub. They do the opposite.

The current mypy master breaks the pydantic mypy plugin. See #5077 for a fix.

**Comment by hramezani** [comment] 2023-02-22 16:36
Thanks @jonathanslenders for reporting this.

Yes, you are right. I can confirm the problem in `1.10.5` with both `mypy 1.0.1` and `mypy 1.1.0+dev`.
I've tested it on `V2` and they return `Unexpected keyword argument "field" for "Model"  [call-arg]` with both `mypy 1.0.1` and `mypy 1.1.0+dev`

@cdce8p I've tried [your fix on mypy](https://github.com/python/mypy/pull/14734) with https://github.com/pydantic/pydantic/pull/5077, but it doesn't fix the problem on `1.10.x` and `V2`

**Comment by cdce8p** [comment] 2023-02-23 11:36
> @cdce8p I've tried [your fix on mypy](https://github.com/python/mypy/pull/14734) with #5077, but it doesn't fix the problem on `1.10.x` and `V2`

That fix only restores the state of `1.0.1`. I.e. the only error should be
```
test.py:9: error: Unexpected keyword argument "alias" for "Model"  [call-arg]
```

--
Technically, the behavior described here is documented that way in docs
> If `Config.allow_population_by_field_name=True`, the generated signature will use the field names, rather than aliases.

https://docs.pydantic.dev/mypy_plugin/#plugin-capabilities

It's also similar to how pyright handles it, although it always uses the `alias` and ignores `allow_population_by_field_name` completely.

In theory it might be possible to allow both with custom overloads but that would require a larger change to the mypy plugin and would get complicated pretty quickly. You would need an overload for every single combination of possible args.

**Comment by dmontagu** [comment] 2023-02-23 14:48
> You would need an overload for every single combination of possible args.

I think it would be a significant improvement to just do two overloads -- one that uses all aliases, and one that uses none (when both are acceptable). Usually users are consistent about using one of these two approaches. (I personally would want it to always _not_ use aliases when the field names are acceptable, but I understand not everyone feels the same..) That said, we'd probably want to make sure that it didn't result in a significant increase in error message verbosity (and corresponding decrease in clarity) when using invalid keyword arguments, i.e., arguments that aren't a part of either signature.

I haven't worked on the mypy plugin for a while (and am not very familiar with pyright) so I don't know how hard this would be.

**Comment by hramezani** [comment] 2023-02-23 20:01
> That fix only restores the state of `1.0.1`. I.e. the only error should be
>```
>test.py:9: error: Unexpected keyword argument "alias" for "Model"  [call-arg]
>```


@cdce8p BTW, I've installed `mpy dev` (that contains [the other fix](https://github.com/python/mypy/commit/54635dec2379e2ac8b65b6ef07778015c69cfb6a)) [with your patch](https://github.com/pydantic/pydantic/pull/5077) but it returns:
`Unexpected keyword argument "field" for "Model"  [call-arg]`

**Comment by cdce8p** [comment] 2023-02-24 01:21
> > That fix only restores the state of `1.0.1`. I.e. the only error should be
> > ```
> > test.py:9: error: Unexpected keyword argument "alias" for "Model"  [call-arg]
> > ```
> 
> @cdce8p BTW, I've installed `mpy dev` (that contains [the other fix](https://github.com/python/mypy/commit/54635dec2379e2ac8b65b6ef07778015c69cfb6a)) [with your patch](https://github.com/pydantic/pydantic/pull/5077) but it returns: `Unexpected keyword argument "field" for "Model" [call-arg]`

Are you sure you've enabled the plugin in the mypy config?

Tbh I'm testing the version backported to `1.10.X` of my PR as mypy is quite slow with `2.0.dev` but that works as explained above.

**Comment by dmontagu** [comment] 2023-03-07 23:06
For what it's worth, if this is not resolved by #5111, I would be happy to accept a PR fixing this (in pydantic v1.10.X or v2).

If no one else gets to this first, I expect we will fix this at some point in the not-distant future in connection with the v2 release, but it will definitely happen faster if someone has a chance to figure it out what's going wrong before then.

For what it's worth, I would be okay with _either_ of these approaches:
* Generating only a single signature using no aliases when `allow_population_by_field_name` is `True`
* Generating two overloads, one with all aliases and one with no aliases, when `allow_population_by_field_name` is `True`

I don't think it's a good idea to try to support every combination of keyword argument names as that will bog mypy down massively for any model with a large number of keywords, but the all-aliases and no-aliases approach seems reasonable to me.

**Comment by jonathanslenders** [comment] 2023-03-08 11:35
@dmontagu : I'd very much appreciate the two overloads. Unfortunately I don't have time right now to contribute.

**Comment by mdgilene** [comment] 2023-04-03 16:30
I'm running into this issue as well and have narrowed it down to `pydantic==1.10.3` causing issues with `mypy==1.1.1`

Downgrading to `pydantic=1.10.2` resolves the issue for me.

**Comment by dmontagu** [comment] 2023-04-03 16:54
I currently suspect this is an issue caused by moving to using `ConfigDict` instead of `class Config:`. Resolving this will be my top priority to investigate once we put out the alpha release.

**Comment by dmontagu** [comment] 2023-04-04 17:39
I can't seem to reproduce this issue — I get:
```
9: error: Missing named argument "field" for "Model"  [call-arg]
```
as the only error when running on the code shared in the start of this issue with every pydantic 1.10.X version I've tried, and with mypy==1.1.1 and mypy==1.0.1 (and older versions of mypy)

If someone can confirm the issue is still happening and confirm to me how to reproduce it, I'll be happy to investigate.

One note: if you haven't, I would try deleting the mypy cache (generally stored in a folder called `.mypy_cache`). It's _possible_ that this could be the source of some issues (though I thought we had things in place to prevent that).

**Comment by mdgilene** [comment] 2023-04-04 19:23
> I can't seem to reproduce this issue — I get:
> 
> ```
> 9: error: Missing named argument "field" for "Model"  [call-arg]
> ```
> 
> as the only error when running on the code shared in the start of this issue with every pydantic 1.10.X version I've tried, and with mypy==1.1.1 and mypy==1.0.1 (and older versions of mypy)
> 
> If someone can confirm the issue is still happening and confirm to me how to reproduce it, I'll be happy to investigate.
> 
> One note: if you haven't, I would try deleting the mypy cache (generally stored in a folder called `.mypy_cache`). It's _possible_ that this could be the source of some issues (though I thought we had things in place to clear the cache on upgrade).

I just created this repo and ran it in codespaces and encountered the issue. I am new to codespaces so if there is a way to grant you direct access to the codespace let me know and I can do that as well.

https://github.com/mdgilene/pydantic-mypy

**Comment by dmontagu** [comment] 2023-04-04 22:07
@mdgilene can you share the result of running:

```
python -c "from mypy.version import __version__; print(f'                 mypy_version: {__version__}')"
python -c "import pydantic.utils; print(pydantic.utils.version_info())"
```

**Comment by dmontagu** [comment] 2023-04-04 22:11
I cloned your repository, and with this set of version info:
```
                 mypy_version: 1.0.1
             pydantic version: 1.10.5
            pydantic compiled: True
                 install path: /Users/davidmontague/Programming/pydantic/pydantic-v1/env/lib/python3.11/site-packages/pydantic
               python version: 3.11.1 (main, Jan 11 2023, 20:15:27) [Clang 13.0.0 (clang-1300.0.27.3)]
                     platform: macOS-12.2.1-arm64-arm-64bit
     optional deps. installed: ['devtools', 'dotenv', 'email-validator', 'typing-extensions']
```
I just get:
```
pydantic-mypy on  main is 📦 v0.1.0 via 🐍 v3.11.1 (env) 
❯ mypy .          
mypy_pydantic/model.py:11: error: Unexpected keyword argument "alias" for "Model"  [call-arg]
Found 1 error in 1 file (checked 1 source file)
```

**Comment by mdgilene** [comment] 2023-04-04 22:23
Version Info

```
(mypy-pydantic-py3.10) @mdgilene ➜ /workspaces/codespaces-blank (main) $ python -c "from mypy.version import __version__; print(f'                 mypy_version: {__version__}')" && python -c "import pydantic.utils; print(pydantic.utils.version_info())"
                 mypy_version: 1.1.1
             pydantic version: 1.10.3
            pydantic compiled: True
                 install path: /home/codespace/.cache/pypoetry/virtualenvs/mypy-pydantic-keAEYBDO-py3.10/lib/python3.10/site-packages/pydantic
               python version: 3.10.4 (main, Mar 13 2023, 19:44:25) [GCC 9.4.0]
                     platform: Linux-5.4.0-1105-azure-x86_64-with-glibc2.31
     optional deps. installed: ['typing-extensions']
```

MyPy Output
```
(mypy-pydantic-py3.10) @mdgilene ➜ /workspaces/codespaces-blank (main) $ mypy mypy_pydantic/model.py 
mypy_pydantic/model.py:10: error: Unexpected keyword argument "field" for "Model"  [call-arg]
Found 1 error in 1 file (checked 1 source file)
```

**Comment by mdgilene** [comment] 2023-04-04 22:36
I just downgraded `mypy` to `1.0.1` like you have and it looks like the error actually goes away and I am seeing what you are seeing. I am wondering then if this change in `mypy` `1.1.1` is causing issues with `pydantic`.

https://mypy-lang.blogspot.com/2023/03/mypy-111-released.html#:~:text=Support%20for%20dataclass_transform,recognized%20by%20mypy.

> This release adds full support for the dataclass_transform decorator defined in [PEP 681](https://peps.python.org/pep-0681/#decorator-function-example). This allows decorators, base classes, and metaclasses that generate a __init__ method or other methods based on the properties of that class (similar to dataclasses) to have those methods recognized by mypy.

**Comment by dmontagu** [comment] 2023-04-05 00:05
@mdgilene okay, I'm able to reproduce it now using mypy 1.1.1 in your repo. I'll see if I can figure out what the issue is

**Comment by dmontagu** [comment] 2023-04-05 00:07
@mdgilene okay, it looks to me like this is fixed with pydantic==1.10.7 and mypy==1.1.1

**Comment by mdgilene** [comment] 2023-04-05 13:54
Okay yes, upgrading to 1.10.7 does resolve the issue.

**Comment by dmontagu** [comment] 2023-04-05 14:19
Okay, given that, I'm going to close this. (There were various issues with the mypy plugin that were resolved in the 1.10.7 release.) But please continue to report any issues with the plugin

**Closed by dmontagu** 2023-04-05 14:19 UTC
Labels: bug V1

**Comment by andersfylling** [comment] 2023-04-09 02:10
Just tested this locally with poetry and python v3.10.10.

`poetry init` go with defaults
`poetry add pydantic@1.10.7`
`poetry add mypy@1.2.0`

create main.py containing:
```python
from pydantic import BaseModel, Field

class Model(BaseModel):
    field: str = Field(alias="alias")

    class Config:
        allow_population_by_field_name = True

Model(alias="")
Model(field="")
```

Running `poetry run mypy .` fails with the following:
![image](https://user-images.githubusercontent.com/7851860/230750531-5be9a6d8-2a5e-449e-84f4-3ae97c86da8f.png)

Adding the pydantic plugin by creating `mypy.ini` with the following content:
```ini
[mypy]
plugins = pydantic.mypy
```

Running `poetry run mypy .`fails with the following:
![image](https://user-images.githubusercontent.com/7851860/230750581-6b9ef593-ba74-4c21-b0b8-9f43348a7750.png)


It seems to me that this is still an issue. Could we re-open this?

**Comment by dmontagu** [comment] 2023-04-10 14:40
@andersfylling as far as I can tell, the code in your example is behaving as expected.

Keep in mind that without the use of the mypy plugin, we are largely dependent on the way mypy handles `dataclass_transform`.

One thing we may be able to do is add another keyword argument besides alias that does the same thing, but would be ignored by `@dataclass_transform`, and you could use _that_ keyword argument if you don't want the type-checked signature to use the alias. That would be a pretty straightforward change, though we'd need to establish consensus on the name of that keyword argument, etc.

If you want to generate an overloaded signature for `__init__` (where one overload uses all aliases and the other uses none), I think that would be more work than I'm willing to put into V1 at this stage, though I would review a PR. Even for v2, I would probably prefer the option above of letting you use a different keyword argument to `Field` to specify whether you want the alias to affect the `__init__` signature or not.

Either way, I think it would be better to create a new issue to keep it focused on the requested feature, rather than continuing in this issue (which was about a different problem that was resolved in 1.10.7).

**Comment by andersfylling** [comment] 2023-04-11 08:26
This is the same issue as described in the thread. While it works at runtime, mypy complains. The message above fails when using the mypy plugin and without the mypy plugin. Exactly the same error.

> If Config.allow_population_by_field_name=True, the generated signature will use the field names, rather than aliases.

As this doesn't work,  I'd suggest this bug report to be reconsidered as open. It's currently blocking us from upgrading pydantic and mypy.

**Comment by mdgilene** [comment] 2023-04-11 19:17
> ```python
> from pydantic import BaseModel, Field
> 
> class Model(BaseModel):
>     field: str = Field(alias="alias")
> 
>     class Config:
>         allow_population_by_field_name = True
> 
> Model(alias="")
> Model(field="")
> ```

@andersfylling, I think what you're missing is that given the above, only 1 variation can ever be valid at a given time. 

`Config.allow_population_by_field_name` just switches which one is valid for mypy when used with the plugin.

**Comment by pkit** [comment] 2024-10-16 18:26
Just FYI for anybody ending here on google search.
```
[mypy]
plugins = pydantic.mypy, pydantic.v1.mypy
```
