### ISSUE TITLE
Validator got dict type value instead of custom type value.

### ISSUE THREAD

**Issue by akayunov** [pydantic/pydantic#3370] opened 2021-10-28 14:03 UTC
Root validator in Item class got value with type(value)=dict, looks strange for me, because I pass object of type Item.
Also strange because main reason why we decide to use pydantic is replace all our dict's  and use very introspective models, but now we've got dicts again. Could you don't cast object to dict type for validatiors functions.

```
from typing import Tuple

from pydantic import root_validator
from pydantic.main import BaseModel


class Item(BaseModel):
    status: str

    @root_validator(pre=True)
    def resolve(cls, value):
        # I would like to use dot to get access to attributes, but type of value is dict
        value.status = value.status.replace('_', '-')
        # value['status'] = value['status'].replace('_', '-')
        return value


class Shares(BaseModel):
    total_item_count: int
    items: Tuple[Item, ...]

    @root_validator(pre=True)
    def resolve(cls, value):
        # here value of items is still Item
        print(type(value['items'][0]))
        return value

Shares(total_item_count=1, items=(Item(**{'status': 'ready'}), Item(**{'status': 'not_ready'})))
```

**Comment by andrch-FS** [comment] 2022-09-07 10:20
Any update on this? The documentation has examples with values being a dictionary, yet this is marked as a bug. Does that mean the intention was to make it be an object of the model's class? Any reason this hasn't been done in a year, or that it shouldn't? Is there a way to cast the values to an object of that class inside the validator, since that's much more convenient, as mentioned by the OP?

**Comment by samuelcolvin** [comment] 2022-09-07 10:22
Bug was automatically added when the issue was created. It's not a bug.

The behaviour won't change in V1, I think it will change in V2 so the input to a root validator is the raw value you pass to the the model.

**Closed by samuelcolvin** 2022-09-07 10:22 UTC
