### ISSUE TITLE
Recursive pydantic models no longer work since pydantic 2.4

### ISSUE THREAD

**Issue by rokj-isystem** [pydantic/pydantic#7635] opened 2023-09-26 11:55 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Example code works with Pydantic 2.3.0, but produces following SchemaError with Pydantic 2.4.0:

```
Traceback (most recent call last):
  File "C:\Projects\tests\pydantic_demo\annotated_union_error_demo.py", line 11, in <module>
    class TestSuiteResult(TestResult):
  File "C:\test_venv\lib\site-packages\pydantic\_internal\_model_construction.py", line 184,
    in __new__ complete_model_class(
  File "C:\test_venv\lib\site-packages\pydantic\_internal\_model_construction.py", line 498, in
    complete_model_class cls.__pydantic_core_schema__ = schema = validate_core_schema(schema)
  File "C:\test_venv\lib\site-packages\pydantic\_internal\_core_utils.py", line 631, in validate_core_schema
    return _validate_core_schema(schema)
pydantic_core._pydantic_core.SchemaError: Invalid Schema:
definitions.definitions.1.model.schema.model-fields.fields.child_results.schema.default.schema.list.items_schema.tagged-union.choices.TestSuiteResult
  Recursion error - cyclic reference detected [type=recursion_loop, input_value={'type': 'model', 'cls': ...teResult:3045773757024'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.4/v/recursion_loop

```
### Example Code

```Python
from typing import List, Literal, Union
from typing_extensions import Annotated
from pydantic import BaseModel, Field


class TestResult(BaseModel):
    result_type: Literal['TestResult'] = 'TestResult'
    test_item_id: str = None


class TestSuiteResult(TestResult):
    result_type: Literal['TestSuiteResult'] = 'TestSuiteResult'
    child_results: List[Annotated[Union[TestResult, 'TestSuiteResult'],
                                  Field(discriminator='result_type')]] = []
```

### Python, Pydantic & OS Version

```Text
Python version: 3.8.7
Pydantic version: 2.4.0 (pydantic-core version 2.10.0)
Pydantic version: 2.3.0 (pydantic-core version 2.6.3) Latest version of pydantic example code works with
Platform: Windows-10-10.0.19041-SP0
```

**Comment by hramezani** [comment] 2023-09-26 11:59
Thanks @rokj-isystem for reporting this 🙏 

I think this is a duplicate of #7611 and fixed on `main`.

LMK if it's not fixed on `main` for you.

**Comment by rokj-isystem** [comment] 2023-09-26 12:15
Thanks @hramezani, I checked and it is fixed in `main`.

**Closed** 2023-09-26 12:17 UTC
Labels: bug V2
