### ISSUE TITLE
Deserializing a model fails if one of the fields is a dict with hashable model-type key

### ISSUE THREAD

**Issue by lshug** [pydantic/pydantic#10473] opened 2024-09-23 22:21 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When deserializing a model JSON, model_type ValidationError will be raised if the serialized model contains a dict-type field with hashable model-type key.

Colab to reproduce the issue:
https://colab.research.google.com/drive/15XbYUKCPP0JVcxuMG-yuug68QovRcxJO?usp=sharing

### Example Code

```Python
from pydantic import BaseModel

class SomeModel(BaseModel, frozen=True):
    some_int_field: int

some_model_instance = SomeModel(some_int_field=10)

class SomeOtherModel(BaseModel):
    some_field: dict[SomeModel, float]

some_other_model_instance = SomeOtherModel(some_field={some_model_instance: 0.0})

dumped_json = some_other_model_instance.model_dump_json()
SomeOtherModel.model_validate_json(dumped_json)

"""
ValidationError: 1 validation error for SomeOtherModel
some_field.some_int_field=10.[key]
  Input should be an object [type=model_type, input_value='some_int_field=10', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/model_type
"""

```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.9.2
        pydantic-core version: 2.23.4
          pydantic-core build: profile=release pgo=false
                 install path: /home/user/.cache/pypoetry/virtualenvs/pypolyphonicanalysis-8IYXowuZ-py3.11/lib/python3.11/site-packages/pydantic
               python version: 3.11.2 (main, Aug 26 2024, 07:20:54) [GCC 12.2.0]
                     platform: Linux-6.1.0-20-amd64-x86_64-with-glibc2.36
             related packages: mypy-1.10.0 pydantic-settings-2.2.1 typing_extensions-4.12.2
                       commit: unknown
```

**Comment by sydney-runkle** [comment] 2024-09-25 13:22
Closing as a dupe of https://github.com/pydantic/pydantic/issues/9453

**Closed by sydney-runkle** 2024-09-25 13:22 UTC
Labels: bug V2, pending
