### ISSUE TITLE
Pydantic Generic Basemodel Validation Error

### ISSUE THREAD

**Issue by oliver-helix** [pydantic/pydantic#9348] opened 2024-04-30 00:13 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Pydantic [Generic BaseModels](https://docs.pydantic.dev/latest/concepts/models/#generic-models) fails unexpectedly when validating python instances but succeeds when validating the same data as a dictionary.

### Example Code

```Python
from typing import Generic, TypeVar

from pydantic import BaseModel

U = TypeVar("U")


class M1(BaseModel, Generic[U]):
    a: list[U]
    b: list[U]


class M2(BaseModel):
    a: str
    m1: M1[int]


# works
m2 = M2.model_validate(
    {
        "a": "s",
        "m1": {
            "a": [1],
            "b": [2]
        }
    }
)

# does not work
m2 = M2(
    a="s",
    m1=M1(
        a=[1],
        b=[2]
    )
)  # fails :(


# does not work
m2 = M2.model_validate(
    dict(
        a="s",
        m1=M1(
            a=[1],
            b=[2]
        )
    )
)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.7.1
        pydantic-core version: 2.18.2
          pydantic-core build: profile=release pgo=true
                 install path: /Users/.../.venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.8 (main, Feb  6 2024, 21:21:21) [Clang 15.0.0 (clang-1500.1.0.2.5)]
                     platform: macOS-14.4.1-arm64-arm-64bit
             related packages: typing_extensions-4.11.0
                       commit: unknown
```

**Comment by aaraney** [comment] 2024-04-30 02:16
This doesn't look like a bug. It looks like you didn't parametrize the `M1` instance with a type. So, constructing `M2` is not failing, it's the construction of `M1` that is failing.

```python

m2 = M2(
    a="s",
    m1=M1( # missing generic type
        a=[1],
        b=[2]
    )
)  # fails :(

# this works

m2 = M2(
    a="s",
    m1=M1[int](
        a=[1],
        b=[2]
    )
)
```

**Comment by aaraney** [comment] 2024-04-30 02:22
Seems like a duplicate of #8071

**Comment by sydney-runkle** [comment] 2024-06-19 23:42
Closing as a duplicate, thanks folks!

**Closed by sydney-runkle** 2024-06-19 23:42 UTC
Labels: duplicate, bug V2, generic
