### ISSUE TITLE
Pydantic coerces iterables to `pydantic_core._pydantic_core.ValidatorIterator`

### ISSUE THREAD

**Issue by Ravencentric** [pydantic/pydantic#9826] opened 2024-07-03 04:13 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Pydantic coereces `collections.abc.Iterable` to `ValidatorIterator`. It should not do this. Input interable should be returned as is if the validation suceeds, i.e, list should be return as a list, tuple should be returned as a tuple, set should be returned as a set, and so on.

### Example Code

```Python
from collections.abc import Iterable

from pydantic import BaseModel, validate_call


class TestModel(BaseModel):
    iterable: Iterable[str]

@validate_call
def iterable(obj: Iterable[str]) -> None:
    print(obj)

iterable(["test", "test2"])
#> ValidatorIterator(index=0, schema=Some(Str(StrValidator { strict: false, coerce_numbers_to_str: false })))
print(TestModel(iterable=["test", "test2"]))
#> iterable=ValidatorIterator(index=0, schema=Some(Str(StrValidator { strict: false, coerce_numbers_to_str: false })))
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.8.0
        pydantic-core version: 2.20.0
          pydantic-core build: profile=release pgo=true
                 install path: C:\Users\raven\Documents\GitHub\pyanilist\.venv\Lib\site-packages\pydantic
               python version: 3.12.3 (tags/v3.12.3:f6650f9, Apr  9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)]
                     platform: Windows-11-10.0.22631-SP0
             related packages: mypy-1.9.0 pydantic-extra-types-2.7.0 typing_extensions-4.11.0
                       commit: unknown
```
```

**Comment by sydney-runkle** [comment] 2024-07-03 10:50
Indeed, this is definitely a bug. Going to close this as a duplicate of https://github.com/pydantic/pydantic/issues/9541 though!

**Closed by sydney-runkle** 2024-07-03 10:50 UTC
Labels: duplicate, bug V2
