### ISSUE TITLE
Types which are not json serializable, raise error on schema gen even when `Field(exclude=True)`.

### ISSUE THREAD

**Issue by zakstucke** [pydantic/pydantic#6630] opened 2023-07-12 15:05 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I don't **think** this is intended/desired behaviour, if it is then `exclude=True` needs to apply to schema gen **not just** dumping.

In V1, attributes which couldn't be converted to a schema, would be omitted, now they raise an error.

It seems like `exclude` is only applied to dumping, not schema generation, this seems to be the same in V1, but wasn't an issue as the schema would omit these items with no problems.

```
Traceback (most recent call last):
  File "mypy_playground.py", line 9, in <module>
    Foo.model_json_schema()
  File "venv/lib/python3.11/site-packages/pydantic/main.py", line 372, in model_json_schema
    return model_json_schema(
           ^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 2077, in model_json_schema
    return schema_generator_instance.generate(cls.__pydantic_core_schema__, mode=mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 381, in generate
    json_ref_counts = self.get_json_ref_counts(json_schema)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 1992, in get_json_ref_counts
    _add_json_refs(json_schema)
  File "venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 1980, in _add_json_refs
    raise self._core_defs_invalid_for_json_schema[defs_ref]
  File "venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 1659, in definitions_schema
    self.generate_inner(definition)
  File "venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 519, in generate_inner
    json_schema = current_handler(schema)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 36, in __call__
    return self.handler(__core_schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 493, in new_handler_func
    json_schema = js_modify_function(schema_or_field, current_handler)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/pydantic/main.py", line 558, in __get_pydantic_json_schema__
    return __handler(__core_schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 36, in __call__
    return self.handler(__core_schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 493, in new_handler_func
    json_schema = js_modify_function(schema_or_field, current_handler)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 198, in modify_model_json_schema
    json_schema = handler(schema_or_field)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 36, in __call__
    return self.handler(__core_schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 476, in handler_func
    json_schema = generate_for_schema_type(schema_or_field)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 1252, in model_schema
    json_schema = self.generate_inner(schema['schema'])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 519, in generate_inner
    json_schema = current_handler(schema)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 36, in __call__
    return self.handler(__core_schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 476, in handler_func
    json_schema = generate_for_schema_type(schema_or_field)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 1348, in model_fields_schema
    json_schema = self._named_required_fields_schema(named_required_fields)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 1160, in _named_required_fields_schema
    field_json_schema = self.generate_inner(field).copy()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 519, in generate_inner
    json_schema = current_handler(schema)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 36, in __call__
    return self.handler(__core_schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 511, in new_handler_func
    json_schema = js_modify_function(schema_or_field, current_handler)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 753, in json_schema_update_func
    return {**handler(schema), **json_schema_updates}
              ^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 36, in __call__
    return self.handler(__core_schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 476, in handler_func
    json_schema = generate_for_schema_type(schema_or_field)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 1228, in model_field_schema
    return self.generate_inner(schema['schema'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 519, in generate_inner
    json_schema = current_handler(schema)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 36, in __call__
    return self.handler(__core_schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 476, in handler_func
    json_schema = generate_for_schema_type(schema_or_field)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 723, in callable_schema
    return self.handle_invalid_for_json_schema(schema, 'core_schema.CallableSchema')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 1996, in handle_invalid_for_json_schema
    raise PydanticInvalidForJsonSchema(f'Cannot generate a JsonSchema for {error_info}')
pydantic.errors.PydanticInvalidForJsonSchema: Cannot generate a JsonSchema for core_schema.CallableSchema

For further information visit https://errors.pydantic.dev/2.0.2/u/invalid-for-json-schema
```

### Example Code
```Python
import typing as tp
from pydantic import BaseModel, Field

class Foo(BaseModel):
    handler: tp.Callable[[], None] = Field(exclude=True)

Foo.model_json_schema()    

# V1: 
# UserWarning: Callable handler was excluded from schema since JSON schema has no equivalent type.
# {'title': 'Foo', 'type': 'object', 'properties': {}}

# V2: error
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.2
        pydantic-core version: 2.1.2 release build profile
                 install path: venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.4 (main, Jun  7 2023, 12:45:48) [GCC 11.3.0]
                     platform: Linux-5.19.0-46-generic-x86_64-with-glibc2.35
     optional deps. installed: ['devtools', 'email-validator', 'typing-extensions']
```

Selected Assignee: @dmontagu

**Comment by dmontagu** [comment] 2023-07-12 15:34
Another option is to override the JSON schema generation for invalid JSON schemas to just exclude them:
```python
import typing as tp

from pydantic_core import PydanticOmit, core_schema

from pydantic import BaseModel, Field
from pydantic.json_schema import GenerateJsonSchema, JsonSchemaValue


class Foo(BaseModel):
    handler: tp.Callable[[], None] = Field(exclude=True)


class MyGenerateJsonSchema(GenerateJsonSchema):
    def handle_invalid_for_json_schema(self, schema: core_schema.CoreSchema, error_info: str) -> JsonSchemaValue:
        raise PydanticOmit


print(Foo.model_json_schema(mode='validation', schema_generator=MyGenerateJsonSchema))
# > {'properties': {}, 'title': 'Foo', 'type': 'object'}
```

**Comment by zakstucke** [comment] 2023-07-12 15:37
Okay then I'm thinking this might be a FastApi problem, this is happening silently and breaking the schema when calling `api.openapi()`, which check further and get back.

**Comment by zakstucke** [comment] 2023-07-12 15:44
```Python
import typing as tp
from fastapi import FastAPI
from pydantic import BaseModel, Field

app = FastAPI()

class Foo(BaseModel):
    bar: int
    handler: tp.Callable[[], None] = Field(exclude=True)

@app.post("/check")
def validator_check() -> Foo:
    return Foo(handler=lambda: None, bar=1)

app.openapi()
```
```JSON
{
   "openapi":"3.1.0",
   "info":{
      "title":"FastAPI",
      "version":"0.1.0"
   },
   "paths":{
      "/check":{
         "post":{
            "summary":"Validator Check",
            "operationId":"validator_check_check_post",
            "responses":{
               "200":{
                  "description":"Successful Response",
                  "content":{
                     "application/json":{
                        "schema":{
                           "$ref":"#/components/schemas/__main____FooInput__1"
                        }
                     }
                  }
               }
            }
         }
      }
   }
}
```

Definitely a problem here, see it creates a random invalid ref and ommits the actual `Foo`.

Do you think this is FastApi side?

**Comment by zakstucke** [comment] 2023-07-13 08:17
https://github.com/tiangolo/fastapi/discussions/9709#discussioncomment-6435347

Added to FastApi discussion, feel free to close if it's decided it's on FastApi to sort :)

**Comment by Kludex** [comment] 2023-07-13 12:13
@dmontagu I'll close this, I think the issue is on FastAPI's side.

**Closed by Kludex** 2023-07-13 12:13 UTC
