### ISSUE TITLE
JSON serialization performance decrease when upgrading from 2.0.3 to 2.1.1

### ISSUE THREAD

**Issue by JordanZimmitti** [pydantic/pydantic#7001] opened 2023-08-03 13:15 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hi,

After upgrading Pydantic to version `2.0.3` we were really impressed with the improvement of our response times for our FastAPI Project with an average of `250ms`! Once Upgrading to version `2.1.1` the average response time of our API doubled to an average of `450ms`. Once reverting back to `2.0.3` it immediately went back to an average of `250ms`. 

Below is an image showing average response time for our API over time based on the Pydantic version being used. I'm hoping someone can look into what caused the performance impact in the latest release

<img width="709" alt="avg_response_time" src="https://github.com/pydantic/pydantic/assets/11902836/b2dc2f19-23cd-4ed5-bfa7-393f76d1acf7">

Thanks in Advance!

### Python, Pydantic & OS Version

```Text
Version with fast performance
-----------------------------
pydantic version: 2.0.3
pydantic-core 
  version: 2.3.0 
  release build profile install path: <redacted>/lib/python3.11/site-packages/pydantic
  python version: 3.11.4 (main, Jul 25 2023, 17:07:07) [Clang 14.0.3 (clang-1403.0.22.14.1)]
platform: macOS-13.4-x86_64-i386-64bit
optional deps. installed: ['email-validator', 'typing-extensions']

Version with performance impact
-------------------------------
pydantic version: 2.1.1
pydantic-core version: 2.4.0
pydantic-core 
  build: profile=release pgo=false mimalloc=true
  install path: <redacted>/lib/python3.11/site-packages/pydantic
  python version: 3.11.4 (main, Jul 25 2023, 17:07:07) [Clang 14.0.3 (clang-1403.0.22.14.1)]
platform: macOS-13.4-x86_64-i386-64bit
optional deps. installed: ['email-validator', 'typing-extensions']
```

Selected Assignee: @adriangb

**Comment by adriangb** [comment] 2023-08-08 18:20
It's hard to investigate without a reproducible example. It'd be very helpful if you could give us a self-contained example using just pydantic (e.g. serializes something in a loop) that you find suffers from this slowdown so we can time it and explore.

**Comment by adriangb** [comment] 2023-08-10 14:36
@davidhewitt this probably requires some profiling in `pydantic-core`. Can I assign this to you since you'll do that much better than I can?

**Comment by sydney-runkle** [comment] 2023-12-14 21:08
Closing this for now, we're onto more efficient versions and way past `2.1.1`.

**Closed by sydney-runkle** 2023-12-14 21:08 UTC
Labels: unconfirmed, bug V2
