### ISSUE TITLE
use_enum_value not working as expected when default value is provided

### ISSUE THREAD

**Issue by HenriqueMAlmeida** [pydantic/pydantic#7791] opened 2023-10-10 16:06 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hi,

The following piece of code returns `{'status': <Status.OK: 0>}` when I believe it is expected to return `{'status': 0}`
Is this the expected behaviour or am I doing something wrong? 
How can I obtain the enum value when defining the default value as shown in the code below?

Thank you!

### Example Code

```Python
from enum import IntEnum
from typing import ClassVar

from pydantic import BaseModel, ConfigDict

class Status(IntEnum):
    OK = 0
    NOT_OK = 1


class ModelTest(BaseModel):

    model_config: ClassVar[ConfigDict] = ConfigDict(use_enum_values=True)
    status: Status = Status.OK


print(ModelTest().model_dump())
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.4.2
        pydantic-core version: 2.10.1
          pydantic-core build: profile=release pgo=true
               python version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
                     platform: Linux-6.2.0-33-generic-x86_64-with-glibc2.35
             related packages: typing_extensions-4.8.0
```

**Comment by sydney-runkle** [comment] 2023-10-10 17:33
Hi @HenriqueMAlmeida,

Thanks for your question. You can find a duplicate of this question (with a response) at #7757. Essentially, you'll need to use `validate_default=True` if you want to get the behavior you're expecting. You can add this either on the field with an `Enum` default or on the `model_config`.

Let me know if you have any other questions 😄.

**Closed by sydney-runkle** 2023-10-10 17:33 UTC
Labels: duplicate, question
