### ISSUE TITLE
`model_dump()` shows `Pydantic serializer warnings` after call `@cached_property` method

### ISSUE THREAD

**Issue by koxudaxi** [pydantic/pydantic#6422] opened 2023-07-04 13:57 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

I found strange behavior in Pydantic V2 with specific conditions.

### How to reproduce
1. the model field has a `union` field, and the union type has a self-class.
2.  the model has `@cached_property`
3. initiate the model 
4. call the `@cached_property` method in the nested model
5. call model_dump()
6. Show `Pydantic serializer warnings`

Please check the example code.

### Example Code

```Python
from __future__ import annotations
from functools import cached_property

from pydantic import BaseModel


class Model(BaseModel):
    nested: Model | str = 'default'

    @cached_property
    def name(self) -> str:
        return 'dog'

m = Model(nested=Model())

# This line doesn't; show any warning.
m.model_dump()

# call cached_property method
m.nested.name

# Show warning
m.model_dump()

# /home/koudai/PycharmProjects/pythonProject/venv11/lib/python3.11/site-#packages/pydantic/main.py:292: UserWarning: Pydantic serializer warnings:
#  Expected `Union[definition-ref, str]` but got `Model` - serialized value may not be as #expected
#  return self.__pydantic_serializer__.to_python(
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0
        pydantic-core version: 2.0.2 release build profile
                 install path: /home/koudai/PycharmProjects/pythonProject/venv11/lib/python3.11/site-packages/pydantic
               python version: 3.11.4 (main, Jun  7 2023, 12:45:48) [GCC 11.3.0]
                     platform: Linux-6.0.6-060006-generic-x86_64-with-glibc2.35
     optional deps. installed: ['email-validator', 'typing-extensions']
```

Selected Assignee: @samuelcolvin

**Comment by koxudaxi** [comment] 2023-07-04 14:00
@Kludex 
I have created this issue for https://github.com/koxudaxi/datamodel-code-generator/issues/803

**Comment by dmontagu** [comment] 2023-07-04 21:20
This is a neat one. @adriangb if I can't figure it out shortly, I think you might be able to figure it out faster than me

**Comment by dmontagu** [comment] 2023-07-04 21:25
Okay, I think the issue is that `@cached_property` puts the value in `model.__dict__` and in various places we assume that only fields are in there. It's definitely weird to me that this only affects the nested field though..

**Comment by dmontagu** [comment] 2023-07-04 21:49
Okay I think I made some progress. It's hitting [this line](https://github.com/pydantic/pydantic-core/blob/d08d269b0999f07088a688e94e64f5e4ba856add/src/serializers/fields.rs#L204) in pydantic-core and I think that's bubbling up into the definitions ref validator and it's not realizing it should do the standard validation approach.

Note that there's something going on specifically with the definitions reference validator because it doesn't error if you just use a union validator with a Model and str..

**Comment by dmontagu** [comment] 2023-07-04 21:56
Okay think I figured it out — we need to implement `retry_with_lax_check` for a `DefinitionRefSerializer`, so that it checks what the returned value is for the referenced serializer, and I think that will resolve it.

I don't think I'll be able to do that today, and I think it may require a bit of modification to `DefinitionRefSerializer` to make it store that since the `retry_with_lax_check` doesn't have the necessary information to look it up. But I might be wrong about that, or it might not be that hard. I defer to @samuelcolvin or @adriangb on this, happy to keep trying though if you guys can't resolve this quickly.

**Comment by koxudaxi** [comment] 2023-07-05 00:00
@dmontagu 
Thank you for investigating the warning.
Does the warning affect  `.model_dump()` result?
datamodel-code-generator uses `model_dump()` to dump nested objects like this.
https://github.com/koxudaxi/datamodel-code-generator/blob/1cb7609288bc8dc32895c3e0459eef8e33318f98/datamodel_code_generator/parser/jsonschema.py#L220

The repo passed all unittest tests the same as pydantic v1.
I guess the behavior of `model_dump()` is not changed v1 by the waring :thinking:

**Comment by dmontagu** [comment] 2023-07-05 17:18
I'll also just note that (as discussed this morning) there will be an issue with strict validation of unions of basemodels when `@cached_property` is used since it will look for the presence of the exact right fields in the `__dict__`, and we probably should give it a way to know that there might be some items that can be ignored if present (i.e., at least any `@cached_property` attributes).

**Comment by dmontagu** [comment] 2023-07-05 17:22
@koxudaxi for the majority of cases I don't think it will affect the result. The main thing I'd be concerned about is, I think it might be possible to produce a union of model types with the same fields but different serialization behavior, and it might choose to serialize it as the wrong one. That said, currently, I think it would be hard to actually hit misbehavior though without going out of your way to try. That said, definitely want to get rid of the warning (and fix the underlying possibility for misbehavior), it's just a bit complicated..

**Comment by sydney-runkle** [comment] 2024-09-05 14:38
Looks like this is now fixed on `main`, I'm guessing due to the union serializer fixes included in v2.9!

**Closed by sydney-runkle** 2024-09-05 14:38 UTC
Labels: bug V2
