### ISSUE TITLE
SecretStr comparison fails when field is defined with Field

### ISSUE THREAD

**Issue by slykar-hpts** [pydantic/pydantic#5741] opened 2023-05-11 11:30 UTC
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

I'm comparing 2 `SecretStr` values and it fails to produce a `True` result even though the values are equal. The issue is caused by a difference in how the fields are defined.

### Example Code

```Python
from pydantic import BaseModel, SecretStr, Field

class TestConfig(BaseModel):
    secret_a: SecretStr
    secret_b: SecretStr = Field(max_length=8)
    
config = TestConfig.parse_obj({'secret_a': 'foo', 'secret_b': 'foo'})
config.secret_b == config.secret_a
# False
config.secret_b.get_secret_value() == config.secret_a.get_secret_value()
# True

type(config.secret_a)
# <class 'pydantic.types.SecretStr'>

type(config.secret_b)
# <class 'abc.SecretStr'>

```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.7
            pydantic compiled: True
                 install path: /Users/slykar/Projects/studio-backend/.venv/lib/python3.9/site-packages/pydantic
               python version: 3.9.10 (main, Sep  5 2022, 13:45:50)  [Clang 13.1.6 (clang-1316.0.21.2.5)]
                     platform: macOS-12.6-arm64-arm-64bit
     optional deps. installed: ['dotenv', 'email-validator', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [X] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [X] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by slykar-hpts** [comment] 2023-05-11 11:35
I believe the equality check was implemented just for `pydantic.types.SecretStr` (#1079)

**Comment by hramezani** [comment] 2023-05-11 12:05
Hi @slykar-hpts,

Thanks for reporting this. Yes, I can confirm it on `V1`.

But it's working as expected in `V2`.

As you may know, `Pydantic V2` is in alpha state and you can install it by `pip install pydantic --pre` and test it.

Note: `parse_obj` is deprecated in `V2` and you can use `model_validate` instead.

We only provide security and patch releases for `V1` and we will accept a fix for this problem on `V1` if it is an easy one.

**Comment by Kludex** [comment] 2023-08-25 14:51
Since this is working on V2, I'll be closing this issue.

As @hramezani said:

> We only provide security and patch releases for V1 and we will accept a fix for this problem on V1 if it is an easy one.

👍

**Closed by Kludex** 2023-08-25 14:51 UTC
Labels: bug V1
