### ISSUE TITLE
Error when adding a default value to a field with name conflict

### ISSUE THREAD

**Issue by AdrienVannson** [pydantic/pydantic#10572] opened 2024-10-08 14:23 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

The following example raises the error `AttributeError: 'NoneType' object has no attribute 'Other'`.

No error is raised if the default value isn't specified, or if Python's dataclasses are used. No error either if the `other` field is renamed to something else.

### Example Code

```Python
# other.py
from pydantic.dataclasses import dataclass

@dataclass
class Other:
    x: int

# test.py
from pydantic.dataclasses import dataclass
import other

@dataclass
class Class:
    other: "other.Other | None" = None
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.10.0a1
        pydantic-core version: 2.24.0
          pydantic-core build: profile=release pgo=false
                 install path: [XXX]/.venv/lib/python3.12/site-packages/pydantic
               python version: 3.12.6 (main, Sep 10 2024, 00:05:17) [GCC 11.4.0]
                     platform: Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
             related packages: typing_extensions-4.12.2 mypy-1.11.2
                       commit: unknown
```

**Comment by sydney-runkle** [comment] 2024-10-10 17:52
Hi @AdrienVannson,

I believe this is a duplicate of the issues referenced here. Closing as not planned for now. I'd recommend checking out some of those issues for further explanation!

https://github.com/pydantic/pydantic/issues/9907#issuecomment-2232688862

**Closed by sydney-runkle** 2024-10-10 17:52 UTC
Labels: bug V2, pending

**Comment by AdrienVannson** [comment] 2024-10-15 08:49
Sorry, I thought that it was valid Python. Thank you for the answer!
