### ISSUE TITLE
model_dump exclude_defaults, and field_serializer *

### ISSUE THREAD

**Issue by CharlesPerrotMinotHCHB** [pydantic/pydantic#10757] opened 2024-11-02 07:35 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hi,

I think there's an issue with `model_dump` using `exclude_defaults = True`, if the Model uses a `field_serializer` with "*". My best guess is that `field_serializer` masks the actual default for `model_dump`?

In the example below, I checked the FieldInfo for that attribute and they seem correct to me:
For `testlist`: `annotation=list[str] required=False default=[]`
For `teststr`: `annotation=str required=False default=''`

Both the `model_dump` calls give `{'testlist': [], 'teststr': ''}`, wether `exclude_defaults` is `False` or `True`

Thank you!

### Example Code

```Python
from datetime import datetime
from typing import Any

from pydantic import (
    BaseModel,
    SerializationInfo,
    SerializerFunctionWrapHandler,
    field_serializer,
)


class Model(BaseModel):
    @field_serializer("*", mode="wrap")
    def serialize_special_types(  # type: ignore[no-untyped-def] # noqa: ANN201
        self,
        value: Any,
        nxt: SerializerFunctionWrapHandler,
        _info: SerializationInfo,
    ):
        if isinstance(value, datetime):
            return value.isoformat(timespec="seconds")
        return nxt(value)

class Payload(Model):
    testlist: list[str] = []
    teststr: str = ""

payload = Payload()
print(payload.model_fields["testlist"])
print(payload.model_fields["teststr"])
print(payload.model_dump(exclude_defaults=False))
print(payload.model_dump(exclude_defaults=True))
```

### Python, Pydantic & OS Version

```Text
pydantic 2.9.2
python 3.12.7
```

**Comment by sydney-runkle** [comment] 2024-11-05 16:31
Hi! Thanks for reporting this. Going to mark this as a dupe of https://github.com/pydantic/pydantic/issues/6969, which we're considering changing in V3. Thanks for your feedback!

**Closed by sydney-runkle** 2024-11-05 16:31 UTC
Labels: bug V2, pending

**Comment by CharlesPerrotMinotHCHB** [comment] 2024-11-05 16:49
Thank you @sydney-runkle!
Completely missed that one. Appreciate!
