### ISSUE TITLE
Incorrect behavior of uniqueness check for the list or Sequence

### ISSUE THREAD

**Issue by AlexanderPodorov** [pydantic/pydantic#4867] opened 2022-12-22 15:15 UTC
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

See example code.

### Example Code

```Python
from pydantic import BaseModel, Field

# we want to consider both Inners to be equal when their id are the same
class Inner(BaseModel):
    id: int
    name: str
    
    def __eq__(self, other: object) -> bool:
        if isinstance(other, Inner):
            return self.id == other.id
        raise NotImplemented

Inner(id=1, name='name1') == Inner(id=1, name='name2')
# returns True, as expected

# Define the container. list can be any Sequence. ConstrainedList can be used instead.
# The setup below for the sake of simplicity
class Outer(BaseModel):
    items: list[Inner] = Field(..., unique_items=True)

# Produces the error, behavior is OK
o1 = Outer(items=[Inner(id=1, name='name'), Inner(id=1, name='name')])

# Produces the error, behavior is OK
o2 = Outer(items=[Inner(id=1, name='name1'), Inner(id=1, name='name2')])

# Produces the error, behavior is OK
o3 = Outer.parse_obj({'items': [{'id': 1, 'name': 'name'}, {'id': 1, 'name': 'name'}]})

# Does not produce error, behavior is NOT OK
o4 = Outer.parse_obj({'items': [{'id': 1, 'name': 'name1'}, {'id': 1, 'name': 'name2'}]})
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.2
            pydantic compiled: True
               python version: 3.11.1 (v3.11.1:a7a450f84a, Dec  6 2022, 15:24:06) [Clang 13.0.0 (clang-1300.0.29.30)]
                     platform: macOS-13.0.1-x86_64-i386-64bit
     optional deps. installed: ['dotenv', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [X] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [X] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by AlexanderPodorov** [comment] 2022-12-22 15:18
As far as I understand, when pydantic parses a list, it just compares raw dicts. But it would be more reasonable to convert to the list of models and then check uniqueness.

**Comment by ybressler** [comment] 2022-12-30 18:51
This looks like it might be addressed by Pydantic V2. Let's wait for Samuel C to respond to this issue.

**Comment by samuelcolvin** [comment] 2022-12-30 19:55
See https://github.com/pydantic/pydantic-core/issues/296, currently the uniqueness check isn't implemented in v2/pydantic-core mostly because i wasn't sure of the best approach.

**Comment by AlexanderPodorov** [comment] 2022-12-30 21:01
@samuelcolvin , thanks a lot for the pydantic!
In my opinion, it would be reasonable to change the behavior for sequence uniqueness check. The first reason would be consistency between creating models manually and parsing from json or file.
The second reason, if we write `list[T]` and define it to have unique items, then people usually expect to have uniqueness check based on `T` and not the underlying `dict`. Technically the `__eq__` method of `T` can be defined in arbitrary way.
What do you think? Thank you!

**Comment by samuelcolvin** [comment] 2022-12-31 09:50
I totally agree that uniqueness should be based on the output type. It also matches the pydantic governing rule that we guarantee the integrity and correctness of the output data, not the input data.

The problem is that whatever we do, we can't really use `__eq__` - if we use `__eq__` we'd need to compare every pair of values in the input or output list which is O(n!) or something horrific like that.

Instead we need to maintain a set of hashes of each element of the input or output value and check if the hash of each new value is already in the set, we therefore need an efficient way to hash the output types.

My proposal would be that we restrict the functionality to only work if the output type type is hashable, and raise an internal error in other cases. `__hash__` is already implemented on models if you mark them as `frozen`, you can also add your own `__hash__` method to customise this.

**Comment by AlexanderPodorov** [comment] 2022-12-31 19:06
@samuelcolvin , thanks a lot for comment!
In regards to O(n!), it seems like this estimate is way too big. We could sort input/output list (requires O(n*log(n))), then compare items pairwise (another O(n)).
In regards to `__hash__`, I personally don’t mind about it, however it might be confusing for people that we require list items to be hashable, since normal python list doesn’t require it.
The whole point of all of that, is that we could use our custom `__eq__` or/and `__hash__`, since in some cases it would be great to override pydantic standard implementation. Another reason of excluding some fields is that sometimes it does not make sense to use them (like with my example with `id`).
Thank you!

**Comment by AlexanderPodorov** [comment] 2023-03-28 19:40
Hello, thanks!
Yes, I'm currently using my custom validator for that. However it would be nicer if V2 could support that.
If V2 is allowing to wrap my custom "unique items" validator into `Annotated`, something like that:
```python

def validate_unique_somehow() -> None: ....

UniqueItems = Annotated[list[Inner], Predicate(validate_unique), Field(uniqueItems=True)]
```
This would be ideal for me. I can reuse that type in the models without a need to duplicate custom validator.

**Comment by dmontagu** [comment] 2023-03-28 19:48
In v2, you'll be able to do, for example:
```python
from typing import Any, Annotated, List

from pydantic_core import CoreSchema, core_schema

from pydantic import BaseModel


class ValidateUnique:
    @classmethod
    def validate_unique(cls, values: list[Any], _info):
        # Could implement whatever logic you like here; could even subclass and override the method,
        # e.g. for the purpose of implementing O(N*log(N))-based sorted-uniqueness checks if item is not hashable 
        if len(set(values)) < len(values):
            raise ValueError("Not all values were unique")
        return values

    @classmethod
    def __get_pydantic_core_schema__(cls, schema: CoreSchema):
        return core_schema.general_after_validator_function(
            cls.validate_unique,
            schema,
        )


class Model(BaseModel):
    x: Annotated[List[int], ValidateUnique]


Model(x=[1, 2])
Model(x=[1, 2, 2])
"""
pydantic_core._pydantic_core.ValidationError: 1 validation error for Model
x
  Value error, Not all values were unique [type=value_error, input_value=[1, 2, 2], input_type=list]
"""
```
(The above works for me on current main branch)

**Comment by AlexanderPodorov** [comment] 2023-03-28 20:01
Yes, that's pretty close to what I'm thinking.
I will probably try to make it generic, so I will be able to validate `List[int]`, `List[UUID]`, or whatever object I want:
```python
T = TypeVar('T')
UniqueItems[T]: TypeAlias = Annotated[List[T], ValidateUnique]

class Model(BaseModel):
    a: UniqueItems[int]
    b: UniqueItems[ComplexObject]
```
`O(N*log(N))` based logic is nice, but requires to implement all rich comparisons for target object, in order to use it in `sorted`. Thanks!

**Comment by Kludex** [comment] 2023-04-30 02:08
Given the example provided on https://github.com/pydantic/pydantic/issues/4867#issuecomment-1487505462 for V2, I'll be closing this issue. 🙏

**Closed** 2023-04-30 02:07 UTC
Labels: Change
