### ISSUE TITLE
Pydantic Mypy plugin strips Optional types off of fields inherited by subclasses

### ISSUE THREAD

**Issue by Roarsj22** [pydantic/pydantic#8561] opened 2024-01-16 11:03 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

The Pydantic mypy plugin seems to be causing Optional types to be stripped from fields on subclasses that are inherited from the parent class when running mypy.

Expected behaviour:
- Create a class (`A`) with an optional `str` field called `name`
- Create a subclass (`B`) of the class (`A`)
- Assign None to the `name` field of a subclass (`B`) instance
- Mypy should not complain

Actual Behaviour
- Create a class (`A`) with an optional `str` field called `name`
- Create a subclass (`B`) of the class (`A`)
- Assign None to the `name` field of a subclass (`B`) instance
- Mypy throws an assignment error such as: `error: Incompatible types in assignment (expression has type "None", variable has type "str")`
- When checking the types of the fields using mypy's `reveal_type` utility, it shows that `A.name` has type: `Union[builtins.str, None]` as expected, but `B.name` has type: `builtins.str`

[minimal code sandbox](https://codesandbox.io/p/devbox/pydantic-v2-inherited-optional-types-6x7w3y)

### Example Code

```Python
from pydantic import BaseModel
from typing import Optional


class A(BaseModel):
    name: Optional[str]


class B(A):
    pass

# With the pydantic.mypy plugin and running mypy
reveal_type(A.name)  # mypy output: Union[builtins.str, None]
reveal_type(B.name) # mypy output: builtins.str

# Without the pydantic.mypy plugin and running mypy
reveal_type(A.name) # mypy output: Union[builtins.str, None]
reveal_type(B.name) # mypy output: Union[builtins.str, None]
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.3
pydantic-core version: 2.14.6
pydantic-core build: profile=release pgo=true
install path: /usr/local/lib/python3.12/site-packages/pydantic
python version: 3.12.0 (main, Nov 29 2023, 03:12:07) [GCC 12.2.0]
platform: Linux-6.1.43-x86_64-with-glibc2.36
related packages: typing_extensions-4.9.0 mypy-1.8.0
```

**Comment by sydney-runkle** [comment] 2024-01-16 15:17
@Roarsj22,

Could you please try this using the `main` branch of `pydantic`? I'm not able to reproduce your error, as I get the following output:

```
test.py:13: note: Revealed type is "Union[builtins.str, None]"
test.py:14: note: Revealed type is "Union[builtins.str, None]"
test.py:17: note: Revealed type is "Union[builtins.str, None]"
test.py:18: note: Revealed type is "Union[builtins.str, None]"
```

Closing for now, but happy to reopen if you're able to repro on `main`.

**Closed by sydney-runkle** 2024-01-16 15:17 UTC
Labels: bug V2, pending

**Comment by Roarsj22** [comment] 2024-01-16 16:56
I recreated it on main and it does seem to be fixed.
Will have to wait for v2.6.x to be released for the fix to come through.
