### ISSUE TITLE
Field: Argument 'title' has incorrect type when passing a lazy proxy. Cythonized

### ISSUE THREAD

**Issue by idlesign** [pydantic/pydantic#2145] opened 2020-11-25 05:32 UTC
### Checks

* [ x] I added a descriptive title to this issue
* [x ] I have searched (google, github) for similar issues and couldn't find anything
* [ x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.7.1
            pydantic compiled: True
                 install path: /home/me/venv/lib/python3.8/site-packages/pydantic
               python version: 3.8.5 (default, Jul 28 2020, 12:59:40)  [GCC 9.3.0]
                     platform: Linux-5.4.0-54-generic-x86_64-with-glibc2.29
     optional deps. installed: ['typing-extensions']

```

Trying to pass a proxy object into `title` typed as `str`.

```py
from django.utils.translation import gettext_lazy as _

from pydantic import BaseModel
from pydantic.fields import Field


class MySchema(BaseModel):

    alias: str = Field(title=_('Alias'))

```
This worked on py3.6 (Ubuntu 18.04) for a long time but failed in new env with py3.8 (Ubuntu 20.04) giving:
`TypeError: Argument 'title' has incorrect type (expected str, got __proxy__)`

This seems basically the same as mentioned in #1070: dropping `fields.cpython-38-x86_64-linux-gnu.so` fixes that.

**Comment by dkrussia** [comment] 2021-04-28 15:02
Is there any solution to this problem?

**Comment by idlesign** [comment] 2021-04-29 01:04
> Is there any solution to this problem?

It seems that so far deleting `fields.cpython-38-x86_64-linux-gnu.so` from package installed is the only way.

**Comment by dkrussia** [comment] 2021-04-29 19:52
> > Is there any solution to this problem?
> 
> It seems that so far deleting `fields.cpython-38-x86_64-linux-gnu.so` from package installed is the only way.

There is some issue on windows system ..( 
Python 3.9.1
Pydantic==1.8.1

**Comment by Kludex** [comment] 2023-04-30 13:23
Given the issue is two years old, and there wasn't much interaction, and also considering that we are focusing on releasing V2, I'll be closing this issue.

We don't cythonize Pydantic on V2, so we are good.

**Closed by Kludex** 2023-04-30 13:23 UTC
Labels: bug V1
