### ISSUE TITLE
JSON encoder for child model is not being called

### ISSUE THREAD

**Issue by GlenNicholls** [pydantic/pydantic#4629] opened 2022-10-17 17:28 UTC
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

I have a sub-model for my design that requires special handling of the JSON serialization. However, I am noticing that when calling `json` on the parent model, the child/sub-model JSON encoder is not being called and I'm not sure why. I would expect that setting the `json_encoder` for the type and calling `<model>.json(models_as_dict=True)` would call the encoder.

In the below reproducer, I am seeing the following from the print:

```
{'people': [{'name': 'john', 'private': {'dob': '1/1/2000'}}, {'name': 'jane', 'private': {'dob': ''}}]}
```

But I expect to see

```
{'people': [{'name': 'john', 'private': 'dob: ***'}, {'name': 'jane', 'private': 'dob: ***'}]}
```

I have tested putting the encoder in `Model`, `Account` and `PersonalInfo` and they all produce the same results.

### Example Code

```Python
import json
from pydantic import BaseModel, Field

def encoder(val):
        return f"dob: ***"

    class PersonalInfo(BaseModel):
        dob: str = ""

    class Account(BaseModel):
        name: str
        private: PersonalInfo = Field(default_factory=PersonalInfo)

        class Config:
            json_encoders = {
                PersonalInfo: encoder,
            }

    class Model(BaseModel):
        people: List[Union[str, Account]]

        @validator("people", each_item=True, pre=True)
        def transform(cls, v):
            if isinstance(v, str):
                v = Account(name=v)
            return v

    Model.update_forward_refs()
    m = Model(people=[{"name": "john", "private": {"dob": "1/1/2000"}}, "jane"])
    d = json.loads(m.json(models_as_dict=False))
    print(d)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.9.2
            pydantic compiled: True
                 install path: /ssd/gnicholls/venv/lib64/python3.6/site-packages/pydantic
               python version: 3.6.8 (default, Sep 10 2021, 09:13:53)  [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
                     platform: Linux-4.18.0-348.2.1.el8_5.x86_64-x86_64-with-centos-8.5.2111
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [X] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [X] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment] 2022-10-18 06:30
Please check for existing issues before creating new ones.

Duplicate of #2277.

**Closed by samuelcolvin** 2022-10-18 06:30 UTC
Labels: bug, unconfirmed

**Comment by GlenNicholls** [comment] 2022-10-18 17:20
@samuelcolvin sorry about that, my MWE is an exact duplicate, but it was an oversimplification of my actual use-case which is my bad. After some more digging, the problem I'm running into is setting the json encoder for a nested `BaseModel`:

``` python
import json
from pydantic import BaseModel, Field

def encoder(val):
    return f"dob: ***"

class PersonalInfo(BaseModel):
    dob: str = ""

    class Config:
        json_encoders = {
            "PersonalInfo": encoder,
        }

PersonalInfo.update_forward_refs()

class Account(BaseModel):
    name: str
    private: PersonalInfo = Field(default_factory=PersonalInfo)

class Model(BaseModel):
    people: List[Account]

Model.update_forward_refs()
m = Model(people=[{"name": "john", "private": {"dob": "1/1/2000"}}])
d = json.loads(m.json(models_as_dict=False))
print(d)
```

I attempted the two workarounds proposed by @PrettyWood in https://github.com/pydantic/pydantic/issues/2277#issuecomment-764010272, but I get the same result where the encoder isn't called. I did some more digging and found https://github.com/pydantic/pydantic/discussions/2622 which appears to be exactly the problem I'm experiencing. The PR for that discussion, https://github.com/pydantic/pydantic/pull/2650, is merged so I'm not sure if I'm seeing a bug or if my results are expected.
