### ISSUE TITLE
Validation executes in the wrong order. FieldValidationInfo does not contain expected data

### ISSUE THREAD

**Issue by snovik75** [pydantic/pydantic#7005] opened 2023-08-03 15:45 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

This code should raise a field validation error on line 17. However, it raises a KeyError on line 24 where the reference is made to the context field which IS required and provided:

    _ = context.data["data_type"]
    KeyError: 'data_type'

Printing the context shows that this field does not exist in data:

FieldValidationInfo(config={'title': 'Column'}, context=None, data={'name': 'bbbbbbb'}, field_name='date_format')

### Example Code

```Python
from typing import Optional

from pydantic import BaseModel, field_validator
from pydantic_core.core_schema import FieldValidationInfo


ALLOWED_TYPES = ["char"]

class Column(BaseModel):
    name: str
    data_type: str
    date_format: Optional[str] = None

    @field_validator("data_type")
    def _validate_data_type(cls, data_type: str, context: FieldValidationInfo):
        if data_type not in ALLOWED_TYPES:
            raise ValueError(f"Unknown data type for column {context.data['name']}: {data_type}")

        return data_type

    @field_validator("date_format")
    def _validate_date_format(cls, date_format: str, context: FieldValidationInfo):
        print(context)
        _ = context.data["data_type"]
        return date_format


cols = Column(name="bbbbbbb", data_type="string", date_format=None)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.1.1
        pydantic-core version: 2.4.0
          pydantic-core build: profile=release pgo=false mimalloc=true
                 install path: /home/coder/.cache/pypoetry/virtualenvs/apex-de-ingestion--Q1J_zSC-py3.9/lib/python3.9/site-packages/pydantic
               python version: 3.9.16 (main, May  4 2023, 02:16:04)  [GCC 10.2.1 20210110]
                     platform: Linux-5.15.108-aarch64-with-glibc2.35
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @hramezani

**Comment by hramezani** [comment] 2023-08-07 07:14
Thanks @snovik75 for reporting this 🙏 

I can reproduce the problem.

Better to use [`@model_validator`](https://docs.pydantic.dev/latest/usage/validators/#model-validators) in case of validation on multiple field as we mentioned in docs:

```
However, in most cases where you want to perform validation using multiple field values, it is better to use @model_validator
 which is discussed in the section below.
```

**Comment by AlexElizard** [comment] 2023-10-31 08:53
Hello. When I upgraded to v2 I encountered a similar problem.

I 'm use:
- Python == 3.11.6
- pydantic_core == 2.10.1
- pydantic-extra-types  == 2.1.0
- pydantic-settings == 2.0.3
- pydantic ==2.4.2


Consider the following models:
```
import json
from datetime import datetime
from pydantic import BaseModel, ValidationInfo, field_validator, v1


class DTO_V2(BaseModel):
    created_at: datetime
    updated_at: datetime

    @field_validator('updated_at')
    @classmethod
    def check_updated_at(cls, v: datetime, info: ValidationInfo):
        created_at = info.data['created_at']
        print("created_at is", created_at)
        return v


class DTO_V1(v1.BaseModel):
    created_at: datetime
    updated_at: datetime

    @v1.validator('updated_at')
    @classmethod
    def check_updated_at(cls, v: datetime, values):
        created_at = values['created_at']
        print("created_at is", created_at)
        return v
```

If the data is valid, then everything goes well.
```
valid_data = json.loads("""
{
    "created_at": "2023-10-31T15:33:00.000000+10:00",
    "updated_at": "2023-07-31T15:33:00.000000+10:00"
}
""")
DTO_V1.parse_obj(valid_data)
DTO_V2.model_validate(valid_data)
```

But if we have an invalid created_at, then we fail in v2. 
```
invalid_data = json.loads("""
{
    "created_at": "2023-10-31T15:33:00.000000+10",
    "updated_at": "2023-07-31T15:33:00.000000+10:00"
}
""")
DTO_V1.parse_obj(invalid_data)
DTO_V2.model_validate(invalid_data)
```

Is this expected behavior? 
In my opinion, the example shown in the [documentation](https://docs.pydantic.dev/2.4/concepts/validators/#field-validators), which talks about using **model_validator**, does not fully explain the reasons for the problem.
Moreover, there are situations when you need to check several fields based on other fields. I did not find in the documentation how to implement such functionality using **model_validator**

**Comment by WoolyFoo** [comment] 2024-03-04 14:57
I stumbled upon the same issue, after investigating a bit, I think that it happens because pydantic tries to run all the validators before showing all the errors.

The problem is that as the validator of data_type raises an error, the value is not put in info.data.
Then when validating date_format, the validator raise a KeyError which is not caught by pydantic, thus we get this error and not the one of the first validator.

**Comment by sydney-runkle** [comment] 2024-03-27 17:39
Closing this for now - as @hramezani suggested, you should use `model_validator` for best results in this case.

**Closed by sydney-runkle** 2024-03-27 17:39 UTC
Labels: bug V2
