### ISSUE TITLE
GenericModel with generic TypedDict parameters

### ISSUE THREAD

**Issue by bewt85** [pydantic/pydantic#4258] opened 2022-07-20 07:46 UTC
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
$ python -c "import pydantic.utils; print(pydantic.utils.version_info())"
             pydantic version: 1.9.1
            pydantic compiled: True
                 install path: /home/ben/miniconda3/lib/python3.9/site-packages/pydantic
               python version: 3.9.7 (default, Sep 16 2021, 13:09:58)  [GCC 7.5.0]
                     platform: Linux-5.11.0-25-generic-x86_64-with-glibc2.31
     optional deps. installed: ['devtools', 'dotenv', 'email-validator', 'typing-extensions']
```

```py
from typing import Generic, TypeVar
from typing_extensions import TypedDict
from pydantic.generics import GenericModel

NumericLike = TypeVar('NumericLike')

class Bar(TypedDict, Generic[NumericLike]):
    number: NumericLike

class Foo(GenericModel, Generic[NumericLike]):
    bar: Bar[NumericLike]

Foo[int].schema_json()
```

```
$ python scratch.py
Traceback (most recent call last):
  File "/home/ben/test_project/scratch.py", line 10, in <module>
    class Foo(GenericModel, Generic[NumericLike]):
  File "pydantic/main.py", line 205, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 491, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 421, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 537, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 710, in pydantic.fields.ModelField._type_analysis
IndexError: tuple index out of range
```

Hi @samuelcolvin, thanks for making such a lovely tool.

I'm trying to parse some `TypedDicts` and want to reuse some code using generics.  I tried making a model from `GenericModel` which uses a `TypedDict` but then hit an error.

I followed the error down into `fields.py` which showed that a `Bar[~NumericLike]` fails `is_typeddict` but `Bar` passes.

I was tempted to change make a change in `typing.py` in `is_typeddict` to check if `cls` has an `__origin__` and see if that passes the same test.  That causes a later issue in `create_model_from_typeddict` so that doesn't seem right.

I'm not an experienced pydantic or generics user so apologies if this is all a big misunderstanding and that I'm using the library wrong.  I did try searching for similar issues but didn't find anything.

Thanks again, Ben

**Comment by samuelcolvin** [comment] 2022-08-30 12:35
Sorry for the slow reply. This is a feature request not a bug.

We'll try to support this in V2, in theory shouldn't be too hard.

**Comment by bewt85** [comment] 2022-08-30 13:18
Super. Sorry for my confusion and thanks for the great tool.

Ben

**Comment by tuchandra** [comment] 2022-11-29 22:58
I ran into something that seems like this, but I wasn't using GenericModel myself. I was using parse_obj_as to make sure that incoming data matches a generic TypedDict. I think GenericModel is still used under the hood here, so it's not super surprising to me, but I did want to leave a comment about it.

```
$ python -c "import pydantic.utils; print(pydantic.utils.version_info())"
             pydantic version: 1.9.2
            pydantic compiled: True
                 install path: /Users/tushar.chandra/Library/Caches/pypoetry/virtualenvs/demo-project-9ZhMDHIs-py3.8/lib/python3.8/site-packages/pydantic
               python version: 3.8.9 (default, Jun 10 2021, 17:11:50)  [Clang 12.0.0 (clang-1200.0.32.29)]
                     platform: macOS-10.16-x86_64-i386-64bit
     optional deps. installed: ['dotenv', 'typing-extensions']
```

```python
from __future__ import annotations

from typing import Dict, Generic, TypeVar
from pydantic import parse_obj_as
from typing_extensions import TypedDict

class UnremarkableTD(TypedDict):
    version: str
    enabled: bool

DataType = TypeVar("DataType")

class GenericTD(UnremarkableTD, Generic[DataType]):
    data: DataType

SomeData = TypedDict("SomeData", {"field": str, "field2": int})

class NonGenericTD(UnremarkableTD):
    data: SomeData

demo_data: GenericTD[SomeData] = {  # this annotation is fine, at least with pyright
    "version": "v1",
    "enabled": True,
    "data": {"field": "", "field2": 0},
}

parse_obj_as(GenericTD[SomeData], demo_data)  # fails, see below
parse_obj_as(NonGenericTD, demo_data)  # works
```

## Error
The first call fails with what I think is the same error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pydantic/tools.py", line 37, in pydantic.tools.parse_obj_as
  File "pydantic/tools.py", line 30, in pydantic.tools._get_parsing_type
  File "pydantic/main.py", line 1006, in pydantic.main.create_model
  File "pydantic/main.py", line 205, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 491, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 421, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 537, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 710, in pydantic.fields.ModelField._type_analysis
IndexError: tuple index out of range
```

but the second one works fine (and is a reasonable workaround, especially given how much we're pushing the type system here).

**Comment by dmontagu** [comment] 2023-04-29 17:57
This is fixed in v2, the only change is that we've eliminated `GenericModel` and you can make the `BaseModel` class generic directly:

```python
from typing import Generic, TypeVar
from typing_extensions import TypedDict
from pydantic import BaseModel

NumericLike = TypeVar('NumericLike')

class Bar(TypedDict, Generic[NumericLike]):
    number: NumericLike

class Foo(BaseModel, Generic[NumericLike]):
    bar: Bar[NumericLike]

print(Foo[int].schema_json())
```
I looked at the generated json schema and it seemed right.

(Also, the `schema_json` is now deprecated, but if you just replace it with `model_json_schema` which behaves exactly the same, that will get rid of the deprecation warning.)

**Closed by dmontagu** 2023-04-29 17:57 UTC
Labels: feature request

**Comment by bewt85** [comment] 2023-04-30 18:06
Thank you.
