### ISSUE TITLE
validate_call on method + inheritance prevents patching

### ISSUE THREAD

**Issue by robertschweizer** [pydantic/pydantic#8152] opened 2023-11-16 12:54 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Having a method decorated with `@validate_call` in the parent class, I cannot patch it in a child class.

Workarounds:
* Patch the parent class directly
* Use the deprecated `@validate_arguments` decorator

The same exception was also reported for a different action in a comment in https://github.com/pydantic/pydantic/issues/7687#issuecomment-1741729806

### Example Code

```Python
from unittest.mock import patch
from pydantic import validate_call

class Parent:
    @validate_call
    def do_something(self, param: int):
        print("not mocked:", param)

class Child(Parent):
    pass

# This works:
with patch.object(Parent, "do_something", lambda *args: print("mocked:", args)):
    Child().do_something("abc")

# This does not work:
with patch.object(Child, "do_something", lambda *args: print("mocked:", args)):
    Child().do_something("abc")
```

Outputs:
```
mocked: (<__main__.Child object at 0x1038aac20>, 'abc')
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/unittest/mock.py", line 1410, in get_original
    original = target.__dict__[name]
KeyError: 'do_something'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kftf964/playground/pytest_repro/test_repro.py", line 17, in <module>
    with patch.object(Child, "do_something", lambda *args: print("mocked:", args)):
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/unittest/mock.py", line 1447, in __enter__
    original, local = self.get_original()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/unittest/mock.py", line 1412, in get_original
    original = getattr(target, name, DEFAULT)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/pydantic/_internal/_validate_call.py", line 139, in __get__
    object.__setattr__(objtype, self._name, result)
TypeError: can't apply this __setattr__ to type object
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.1
        pydantic-core version: 2.14.3
          pydantic-core build: profile=release pgo=true
                 install path: /opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/pydantic
               python version: 3.10.10 | packaged by conda-forge | (main, Mar 24 2023, 20:12:31) [Clang 14.0.6 ]
                     platform: macOS-13.6-arm64-arm-64bit
             related packages: typing_extensions-4.7.1 mypy-1.7.0
```

**Comment by sydney-runkle** [comment] 2023-11-16 14:54
Hi,

Thanks for reporting this issue. In the future, please make sure to search through other issues to see if the problem you're encountering has been reported. Marking this as a duplicate of #8146. We'll continue discussions about this bug there 👍

**Closed by sydney-runkle** 2023-11-16 14:54 UTC
Labels: duplicate, bug V2
