### ISSUE TITLE
Building json-schema with discriminator fails if calling a nested model class default

### ISSUE THREAD

**Issue by bruno-f-cruz** [pydantic/pydantic#8590] opened 2024-01-19 19:12 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Consider the following examples.  When trying to convert the second model, the following error is thrown:

`AttributeError: 'WhiteCat' object has no attribute 'root'`.

I would expect both models to be able to be converted successfully. When using the first model, the discriminator is correctly detected and there are no problems generating the default value for WhiteCat. However, if the call is nested it throws the aforementioned error.

#### Working as intended:
```Python

from typing import Annotated, List, Literal, Union
from pydantic import BaseModel, Field, RootModel

class BlackCat(BaseModel):
    pet_type: Literal['cat'] = 'cat'
    color: Literal['black'] = 'black'
    black_name: str

class WhiteCat(BaseModel):
    pet_type: Literal['cat'] = 'cat'
    color: Literal['white'] = 'white'
    white_name: str

class Cat(RootModel):
    root: Annotated[Union[BlackCat, WhiteCat], Field(discriminator='color')]

class Dog(BaseModel):
    pet_type: Literal['dog'] = 'dog'
    name: str

class Pet(RootModel):
    root: Annotated[Union[Cat, Dog], Field(discriminator='pet_type')]


class MyFavoritePet(BaseModel):
    my_favorite_pet: Pet = Field(WhiteCat(white_name='Snowball'), description='My favorite pet')
    dob: str = Field("Today", description='Date of birth')

class Model(BaseModel):
    other_pets: List[Pet]
    my_pets: List[Pet]
    my_favorite_pet: Pet = Field(WhiteCat(white_name='Snowball'), description='My favorite pet')
    n: int

if __name__ == '__main__':
    import json
    print(json.dumps(Model.model_json_schema(), indent=True))
```

#### Fails to convert. Replace the previous Model class.
```python
class Model(BaseModel):
    other_pets: List[Pet]
    my_pets: List[Pet]
    my_favorite_pet: MyFavoritePet = Field(MyFavoritePet())
    n: int

```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.3
        pydantic-core version: 2.14.6
          pydantic-core build: profile=release pgo=true
                 install path: (...).venv\Lib\site-packages\pydantic
               python version: 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)]
                     platform: Windows-10-10.0.22631-SP0
             related packages: typing_extensions-4.9.0
```

**Comment by sydney-runkle** [comment] 2024-01-20 12:44
@bruno-f-cruz,

Thanks for reporting this. Adding this to the related milestone. Here's a related issue with a workaround, in case that helps: https://github.com/pydantic/pydantic/issues/7491

**Comment by sydney-runkle** [comment] 2024-01-23 20:46
@bruno-f-cruz,

Ah, found the issue here. You need to validate the default for `WhiteCat` in your `MyFavoritePet `, or else it's assumed that said default is already a `Pet` model, which it's not.

For example, the below code works.

```py

from typing import Annotated, List, Literal, Union
from pydantic import BaseModel, Field, RootModel

class BlackCat(BaseModel):
    pet_type: Literal['cat'] = 'cat'
    color: Literal['black'] = 'black'
    black_name: str

class WhiteCat(BaseModel):
    pet_type: Literal['cat'] = 'cat'
    color: Literal['white'] = 'white'
    white_name: str

class Cat(RootModel):
    root: Annotated[Union[BlackCat, WhiteCat], Field(discriminator='color')]

class Dog(BaseModel):
    pet_type: Literal['dog'] = 'dog'
    name: str

class Pet(RootModel):
    root: Annotated[Union[Cat, Dog], Field(discriminator='pet_type')]


class MyFavoritePet(BaseModel):
    my_favorite_pet: Pet = Field(WhiteCat(white_name='Snowball'), description='My favorite pet', validate_default=True)
    dob: str = Field("Today", description='Date of birth')

class Model(BaseModel):
    other_pets: List[Pet]
    my_pets: List[Pet]
    my_favorite_pet: MyFavoritePet = Field(MyFavoritePet())
    n: int

if __name__ == '__main__':
    import json
    print(json.dumps(Model.model_json_schema(), indent=True))
```

Closing this as completed, as this was an error in field definition, not a bug in schema generation. Thanks again for reporting the issue with a reproducible example.

**Closed by sydney-runkle** 2024-01-23 20:46 UTC
Labels: bug V2
