### ISSUE TITLE
Pydantic 2.5.0 fails to install in Azure Pipelines due to package description exceeding maximum length of of 324608 bytes

### ISSUE THREAD

**Issue by asos-nathanpowell** [pydantic/pydantic#8131] opened 2023-11-15 10:30 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When installing pydantic==2.5.0 in an Azure Pipelines environment, the package fails to install because the description exceeds Microsoft's package description limit of 324608 bytes.

ERROR: Could not install requirement pydantic>=1.9.1 from <pypi index url> because of HTTP error 400 Client Error: Bad Request - The package description exceeds the maximum length of 324608 bytes. 

To reproduce:

1. Specify pydantic==2.5.0 in requirements.txt
2. Create Azure Pipelines environment
3. Attempt to pip install -r requirements.txt within Azure Pipeline
4. Observe installation failure

### Python, Pydantic & OS Version

```Text
Ubuntu 20.04
```

**Comment by Viicos** [comment] 2023-11-15 10:42
Duplicate of https://github.com/pydantic/pydantic/issues/8105.

I think it might be worth pinning the original issue to avoid other duplicates

**Comment by hramezani** [comment] 2023-11-15 10:54
Thanks @Viicos 

Agree, I just pinned the original issue

**Closed by hramezani** 2023-11-15 10:54 UTC
Labels: bug V2, pending
