### ISSUE TITLE
Cython methods are not ignored when checking field annotations

### ISSUE THREAD

**Issue by nokados** [pydantic/pydantic#10282] opened 2024-09-01 18:43 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When trying to сythonize Pydantic code with a method in a model, I get the following error

```
Traceback (most recent call last):
  ...
  File "src/qaclassifiers/common/config.py", line 248, in init qaclassifiers.common.config
    class StorageConfiguration(BaseModel):
  File ".../lib/python3.9/site-packages/pydantic/_internal/_model_construction.py", line 96, in __new__
    private_attributes = inspect_namespace(
  File ".../lib/python3.9/site-packages/pydantic/_internal/_model_construction.py", line 401, in inspect_namespace
    raise PydanticUserError(
pydantic.errors.PydanticUserError: A non-annotated attribute was detected: `get_kwargs = <cyfunction StorageConfiguration.get_kwargs at 0x7f69db992e10>`. All model fields require a type annotation; if `get_kwargs` is not meant to be a field, you may be able to resolve this error by annotating it as a `ClassVar` or updating `model_config['ignored_types']`.

For further information visit https://errors.pydantic.dev/2.8/u/model-field-missing-annotation
```
I've written about it in https://github.com/pydantic/pydantic/issues/1162#issuecomment-2322968668

Look at the minimal reproducible example. It's from the history of pydantic tests. It worked until Pydantic 2.

### Example Code

```Python
import cython

def test_cython_function_untouched():
    Model = cython.inline(
        # language=Python
        """
from pydantic import BaseModel
class Model(BaseModel):
    a: float = 0.0
    b: int = 10
    def get_double_a(self) -> float:
        return self.a + self.b
return Model
"""
    )
    model = Model(a=10.2)
    assert model.a == 10.2
    assert model.b == 10
    assert model.get_double_a() == 20.2
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.8.2
        pydantic-core version: 2.20.1
          pydantic-core build: profile=release pgo=true
                 install path: /home/nokados/.pyenv/versions/3.9.19/envs/qaclassifiers39-pdm/lib/python3.9/site-packages/pydantic
               python version: 3.9.19 (main, May  1 2024, 19:26:02)  [GCC 9.4.0]
                     platform: Linux-5.4.0-177-generic-x86_64-with-glibc2.31
             related packages: fastapi-0.112.2 typing_extensions-4.12.2
                       commit: unknown

Cython version: 3.0.11
```

**Comment by nokados** [comment] 2024-09-01 19:05
So, I've already investigated the issue. The inspect_namespace function ignores methods by default; however, after Cython compilation, isinstance(method, types.FunctionType) returns False, so the methods are no longer ignored. Yes, this does seem to be primarily a Cython bug.

However, I would propose two solutions that can be implemented in Pydantic:

### 1.  Add `cyfunction` to `default_ignored_types`
This is a bit hacky because we can’t directly import the cyfunction type from Cython. Instead, we can create a simple function and determine its type from there.

```python
def default_ignored_types() -> tuple[type[Any], ...]:
    from ..fields import ComputedFieldInfo

    ignored_types = [
        FunctionType,
        property,
        classmethod,
        staticmethod,
        PydanticDescriptorProxy,
        ComputedFieldInfo,
        ValidateCallWrapper,
    ]

    try:
        import cython
        CyFunctionType = type(cython.inline("def f(): pass")["f"])
        ignored_types.append(CyFunctionType)
    except ImportError:
        pass

    return tuple(ignored_types)
```

### 2. Check the name
In this solution, we create a specific method that checks if a value is a cyfunction. The code is based on [Cython’s tests](https://github.com/cython/cython/blob/606a132a1b651ebfcdd7772978fa9ec97a47caac/runtests.py#L155).

```python
def is_cython_function(value: Any) -> bool:
    return type(value).__name__ == 'cython_function_or_method'
```

And modify the conditions in inspect_namespace:

```python
        elif (
            isinstance(value, all_ignored_types)
            or value.__class__.__module__ == 'functools'
            or is_cython_function(value)  # <-- the new condition
        ):
            ignored_names.add(var_name)
            continue
```

So, if you accept either of these solutions, I'll make a PR.

**Comment by da-woods** [comment] 2024-09-01 19:43
>  Yes, this does seem to be primarily a Cython bug.

To be very clear: this is **not a Cython bug**. This is an accurate test for the type.

**Comment by Viicos** [comment] 2024-09-02 05:21
Closing as a duplicate of https://github.com/pydantic/pydantic/issues/6670, which provides a workaround.

**Closed by Viicos** 2024-09-02 05:21 UTC
Labels: bug V2, pending
