### ISSUE TITLE
subclass's computed field overwriting parent class's attribute with same name causes unexpected behavior

### ISSUE THREAD

**Issue by raceychan** [pydantic/pydantic#7574] opened 2023-09-22 22:31 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

The problem itself can be easily reproduced:

when a subclass defines a computed_field that shares the same name with an attribute in its parent class, 
it would stays as a property object. However, one can still access the expected value via its getter method.

The fact that this behavior acts differently from dataclass or plain python object is considered as unexpected. 
please see my code example below

### Example Code

```Python
import sys

from pydantic import BaseModel, computed_field, __version__ as pydantic_version


class Event(BaseModel):
    event_id: str


class RandomEvent(Event):
    @computed_field
    @property
    def event_id(self) -> str:
        return "random_id"


e = RandomEvent()
assert isinstance(e.event_id, property)
assert e.event_id.fget(e) == "random_id"
print(f"python version: {sys.version_info}")
print(f"pydantic version: {pydantic_version}")
```

### Python, Pydantic & OS Version

```Text
python version: sys.version_info(major=3, minor=10, micro=13, releaselevel='final', serial=0)
pydantic version: 2.3.0

Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal


             pydantic version: 2.3.0
        pydantic-core version: 2.6.3
          pydantic-core build: profile=release pgo=true
                 install path: /home/raceychan/miniconda3/envs/askgpt/lib/python3.10/site-packages/pydantic
               python version: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
                     platform: Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
     optional deps. installed: ['typing-extensions']
```

**Comment by sydney-runkle** [comment] 2023-09-22 22:45
Hi @raceychan,

See [this issue](https://github.com/pydantic/pydantic/issues/7250) where this was discussed. Docs updates should be released quite soon in the next release. The above behavior will throw an error in Pydantic 2.4.0.

Let me know if you have any other questions!

**Comment by sydney-runkle** [comment] 2023-09-22 22:49
Also, this behavior isn't supported by `dataclasses`:
```py
from dataclasses import dataclass

@dataclass
class Event:
    event_id: str


@dataclass
class RandomEvent(Event):

    @property
    def event_id(self) -> str:
        return "random_id"


e = RandomEvent(event_id="my_id")
#> AttributeError: can't set attribute 'event_id'
```

**Comment by sydney-runkle** [comment] 2023-09-22 22:52
Closing bc it's a duplicate of #7250. Feel free to follow up if you have any other questions / feedback 😄.

**Closed by sydney-runkle** 2023-09-22 22:52 UTC
Labels: question

**Comment by raceychan** [comment] 2023-09-22 22:53
> Also, this behavior isn't supported by `dataclasses`:
> 
> ```python
> from dataclasses import dataclass
> 
> @dataclass
> class Event:
>     event_id: str
> 
> 
> @dataclass
> class RandomEvent(Event):
> 
>     @property
>     def event_id(self) -> str:
>         return "random_id"
> 
> 
> e = RandomEvent(event_id="my_id")
> #> AttributeError: can't set attribute 'event_id'
> ```

yeah I tested it using dataclass and plain python object, 
the reason dataclass does not support it is because that class definition happens before dataclass's auto-generated __init__ function, so that when it executes 
```python
def __init__(self, event_id:str):
  self.event_id = event_id
```
it would runs into problem, since event_id has no setter.

**Comment by raceychan** [comment] 2023-09-22 23:29
people who search for the same issue, here is my workaround

```python

class Event(DomainBase):
    # event_id: str
    @computed_field
    @property
    def event_id(self) -> str:
        return str(uuid4())

    @event_id.setter
    def event_id(self, event_id):
        self.event_id = event_id

class RandomEvent(Event):
    @computed_field
    @property
    def event_id(self) -> str:
        return "random_id"
e = RandomEvent()
assert e.event_id == "random_id"
```

**Comment by raceychan** [comment] 2023-09-22 23:35
> Closing bc it's a duplicate of #7250. Feel free to follow up if you have any other questions / feedback 😄.
i also have question about this:
shoudn't this cause infinite loop or raise Exception?

```python
class RandomEvent(BaseModel):
    @computed_field
    @property
    def event_id(self) -> str:
        return "random_id"
        
    @event_id.setter
    def event_id(self, event_id):
        self.event_id = event_id
        
e = RandomEvent(event_id="something")
assert e.event_id == "random_id"
```

**Comment by sydney-runkle** [comment] 2023-09-25 16:37
Hi @raceychan,

Thanks for following up. I'm going to discuss this behavior with the team and will get back to you after! I'll also take a closer look at the new issue you opened.

**Comment by Aleksandr-Frolov** [comment] 2023-10-03 20:36
I am facing a similar problem, I have an optional field for which I need to calculate a value if it is missing. Could you please advise me how to override the value for the optional field on  2.4.2 pydantic version:
```
class Foo(BaseModel):
    bar_1: int
    bar_2: int
    total_sum: int | None = Field(default=None)

    @computed_field
    @property
    def total_sum(self) -> int:
        return self.bar_1 + self.bar_2


test_1 = Foo(**{'bar_1': 1, 'bar_2': 2, 'total_sum': 5})
# ValueError: you can't override a field with a computed field


test_2 = Foo(**{'bar_1': 1, 'bar_2': 2})
# ValueError: you can't override a field with a computed field
```
