### ISSUE TITLE
2.5.1: changing checksum for north_star_data_bytes fixture

### ISSUE THREAD

**Issue by dvzrv** [pydantic/pydantic#8180] opened 2023-11-20 20:16 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hi! :wave: 
I package this project for Arch Linux.
I am currently seeing issues with version 2.5.1 and the test setup. The fixture `north_star_data_bytes` appears to provide wrong results:

```
=========================== short test summary info ============================
ERROR tests/benchmarks/test_north_star.py::test_north_star_validate_json - Va...
ERROR tests/benchmarks/test_north_star.py::test_north_star_validate_json_strict
ERROR tests/benchmarks/test_north_star.py::test_north_star_dump_json - ValueE...
ERROR tests/benchmarks/test_north_star.py::test_north_star_validate_python - ...
ERROR tests/benchmarks/test_north_star.py::test_north_star_validate_python_strict
ERROR tests/benchmarks/test_north_star.py::test_north_star_dump_python - Valu...
ERROR tests/benchmarks/test_north_star.py::test_north_star_json_loads - Value...
ERROR tests/benchmarks/test_north_star.py::test_north_star_json_dumps - Value...
=========== 4605 passed, 152 skipped, 9 xfailed, 8 errors in 20.63s ============
```

This is the current build script: https://gitlab.archlinux.org/archlinux/packaging/packages/python-pydantic/-/blob/86d7dd5bb1fbd48ffa3aa33ce402d70680c4be2a/PKGBUILD

The full build and test log:
[python-pydantic-2.5.1-1-x86_64-check.log](https://github.com/pydantic/pydantic/files/13418983/python-pydantic-2.5.1-1-x86_64-check.log)
[python-pydantic-2.5.1-1-x86_64-build.log](https://github.com/pydantic/pydantic/files/13418984/python-pydantic-2.5.1-1-x86_64-build.log)

### Python, Pydantic & OS Version

```Text
n/a (I'm building from the 2.5.1 source tarball).
```

**Comment by sydney-runkle** [comment] 2023-11-21 13:21
@dvzrv,

Thanks for reporting. Closing as a duplicate of #8099.

**Closed by sydney-runkle** 2023-11-21 13:21 UTC
Labels: duplicate
