### ISSUE TITLE
`model_dump` should serialise bools as bools for json

### ISSUE THREAD

**Issue by Booplicate** [pydantic/pydantic#7294] opened 2023-08-30 12:26 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Currently when dumping model to json, objects of type `bool` are being serialised as integers in json. I think this is a bug because json natively supports booleans (`true`/`false`).

### Example Code

```Python
class SomeModel(BaseModel):
    value: StrictFloat | StrictInt | StrictBool

m = SomeModel(value=True)

# Passes
assert type(m.model_dump(mode="python")["value"]) is bool
# This will fail
assert type(m.model_dump(mode="json")["value"]) is bool, "didn't serialise as bool"
```

### Python, Pydantic & OS Version

```Text
Python 3.11.4
Pydantic 2.1.1
Pydantic Core 2.4.0
Windows 10
```

Selected Assignee: @davidhewitt

**Comment by fatelei** [comment] 2023-08-31 15:15
<img width="996" alt="image" src="https://github.com/pydantic/pydantic/assets/961094/913e5fbe-910c-4884-a607-fd853ec41cde">

recommend to use `model_dump_json`

**Comment by Booplicate** [comment] 2023-09-04 08:01
`model_dump_json` dumps to a `str`, I need to serialise to json data types (object/array/int//float/bool/string).

**Comment by sydney-runkle** [comment] 2023-09-28 00:04
Hi @Booplicate,

Thanks very much for reporting this. I can confirm that this is a bug. This issue is a duplicate of the #6830 bug. We're working on fixing this issue in `pydantic-core`.

The issue is actually with the wrong type being selected when serializing a `Union`.

See the example below:

```py
from pydantic import BaseModel, StrictBool, StrictFloat, StrictInt


class SomeModel(BaseModel):
    value: StrictFloat | StrictInt | StrictBool


class BoolModel(BaseModel):
    value: StrictBool


m1 = SomeModel(value=True)
m2 = BoolModel(value=True)

# Passes
assert type(m1.model_dump(mode="python")["value"]) is bool
# This will fail
assert type(m1.model_dump(mode="json")["value"]) is bool, "didn't serialise as bool"


# Passes
assert type(m2.model_dump(mode="python")["value"]) is bool
# Passes
assert type(m2.model_dump(mode="json")["value"]) is bool
```

I'm going to close this issue given that it's a duplicate of #6830, but we will include a test case like this one in our test suite once we fix this bug.

**Comment by Booplicate** [comment] 2023-09-28 17:33
Good to know, thank you.

**Comment by gustelle** [comment] 2024-07-15 19:12
Hello, is that fixed ? I'm having the issue with `pydantic==2.8.2`

See below:

```py

class MyModel(BaseModel):
    value: str | float | int | bool 

m1 = MyModel(value=True)

# fails
assert type(test.model_dump(mode="json")["expected"]) is bool

**Comment by sydney-runkle** [comment] 2024-07-17 18:38
You're right, this is still an issue

**Comment by dexterionut** [comment] 2024-08-14 17:09
> You're right, this is still an issue

@sydney-runkle Was this fixed with https://github.com/pydantic/pydantic-core/pull/1398 ? The test case in that PR is only with ints.

**Comment by sydney-runkle** [comment] 2024-08-15 22:52
Ah @dexterionut, yep! This is fixed by that PR, great call!

**Closed** 2024-08-15 22:52 UTC
Labels: bug V2
