### ISSUE TITLE
Decimal JSON encoder is lossy

### ISSUE THREAD

**Issue by lsorber** [pydantic/pydantic#1511] opened 2020-05-13 11:02 UTC
## Version
```
             pydantic version: 1.5.1
            pydantic compiled: True
                 install path: 
               python version: 3.8.2 (default, May  6 2020, 02:49:43)  [Clang 4.0.1 (tags/RELEASE_401/final)]
                     platform: macOS-10.15.4-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions', 'email-validator']
```

## Bug

```py
from pydantic import BaseModel

class MyModel(BaseModel): 
    foo: Decimal

m = MyModel(foo="31231239131093781902381093810298310983123.12000000")
m.json()  # {"foo": 3.1231239131093784e+40} is lossy
```

## Proposed solution

Replace the current `Decimal: float` JSON encoder [1] with `Decimal: str`.

[1] https://github.com/samuelcolvin/pydantic/blob/master/pydantic/json.py#L27

**Comment by samuelcolvin** [comment] 2020-05-18 12:26
I think we used to have it like that but changed it since the current solutions is most user-friendly in most scenarios.

You can change this yourself on a model (and use a custom base model to extend the functionality to all your models):

```py
from decimal import Decimal

from devtools import debug
from pydantic import BaseModel


class MyModel(BaseModel):
    foo: Decimal

    class Config:
        json_encoders = {Decimal: str}


m = MyModel(foo='31231239131093781902381093810298310983123.12000000')
debug(m.json())
"""
> test.py:14 <module>
    m.json(): '{"foo": "31231239131093781902381093810298310983123.12000000"}' (str) len=61
"""
```

**Comment by lsorber** [comment] 2020-05-18 12:45
If I may challenge that decision: the primary use case for using Decimals is that you need to store and work with arbitrary precision decimals. Serialising these as floats will cause loss of information. If you don't care about storing all digits, then you might as well use `float` instead of `Decimal`.

In other words: if you all you need is convenience, we already have `float`. If you need arbitrary precision, you need `Decimal`. It would somewhat disappointing that users that need arbitrary precision also need a workaround to actually store those Decimals without loss of precision.

**Comment by hassanselim0** [comment] 2020-09-16 20:42
I agree with @lsorber here, the whole idea of using an uncommon datatype like `Decimal` is to get full precision like when dealing with monetary calculations. So having the default encoding be a JSON Number defeats that purpose.
Using `Decimal` is already a hassle, one that you even have to pass off to people consuming your API. I expect a convenient library like pydantic to not make my life harder here.

The solution suggested with the `Config` class is less elegant when using `dataclass`. I'm contemplating just putting `ENCODERS_BY_TYPE[Decimal] = str` somewhere in my code and consider this solved for all models and dataclasses.

Note: Django REST Framework's Serializers by default converts `Decimal` to `str`, and it's a default that I was glad to have, because back then I wasn't sure whether the JSON Number type would preserve the precision or not.

**Comment by lsorber** [comment] 2020-11-21 21:46
@samuelcolvin would you consider reopening this discussion, or otherwise providing some insight as to why the current behaviour is the desired behaviour?

As it stands, there is little value in using `Decimal` fields because they are encoded to `float`, in which case you might as well annotate those fields as `float` to begin with.

Additionally, the workaround is somewhat fragile in that you'd need to be diligent about including it in every model that has `Decimal` fields, which can be non-obvious when subclassing models with custom `Config`s for example.

**Comment by samuelcolvin** [comment] 2020-11-22 08:34
> As it stands, there is little value in using Decimal fields

Even if we accept your point, this is incorrect since many people are not using JSON.

The work around is not fragile if you make consistent use of a custom base class.

I did it this way because I think floats are the most obvious analogue for decimals in JSON. In most situations this "just works".

---

All that said, I'll consider changing this in V2 if no one has any powerful counter arguments.

**Comment by ale-rinaldi** [comment] 2021-05-13 08:30
I strongly agree with the idea that the flat representation of a Decimal should be a string by default, having it as a float makes it pointless to use it.

Usually when someone choose to use Decimal it's not a random choice, and it totally makes sense to follow the best practices on it. The vast majority of all the other encoders render it as a string, too.

**Comment by shanahanjrs** [comment] 2021-12-16 04:49
Would anyone here be opposed to me submitting a PR for this?
I'd like to add a new type `DecimalStr` which would get encoded into a str when `.json()` is called.
After implementation it would look something like:

```
from pydantic.types import DecimalStr

class MyModel(BaseModel):
    foo: Decimal
    bar: DecimalStr

m = MyModel(
    foo="31231239131093781902381093810298310983123.12000000",
    bar="31231239131093781902381093810298310983123.12000000"
)

print(m.json())
"""
{"foo": 3.1231239131093784e+40,  # is lossy
 "bar": "31231239131093781902381093810298310983123.12000000"} 
"""
```

Thoughts? @lsorber @samuelcolvin

**Comment by EdgyEdgemond** [comment] 2022-02-15 11:14
Just my 2c, but if there is going to be a custom type, `DecimalFloat` feels like the correct option, with Decimal -> str as the default encoding, as like most other commenters here, I am using Decimal for precision in financial data.

Having the default throw that precision on the floor feels unhelpful, and counterintuitive. With everything else pydantic provides this feels like it goes against why this library is useful.

If I want to use Decimals and don't want to maintain precision and am happy with floats mutating my data, having the option to chose that, if Decimal -> str doesn't work for me, feels like a better solution.

**Comment by shanahanjrs** [comment] 2022-03-04 03:14
@EdgyEdgemond I agree, losing the precision is definitely bad, the reason I suggested making a new type `DecimalStr` is only so it would be a non-breaking change.

**Comment by LarsHill** [comment] 2022-08-06 23:24
As an additional argument: [simplejson](https://github.com/simplejson/simplejson), the externally maintained development version of the inbuilt json library, supports Decimal serialization out of the box and serializes to string. 

Since new features in simplejson eventually will be part of json, I think it would make sense for pydantic to follow that approach. 

The obvious problem with float serialization (loss of precision) was mentioned before.

**Comment by samuelcolvin** [comment] 2022-08-07 06:22
Ok, let's change it in V2.

I don't think we should have an additional type, I don't think we should change it before V2.

**Comment by dmontagu** [comment] 2023-02-15 21:09
@samuelcolvin We've discussed this recently and I think were tentatively keeping the generated schema as `number`, but I @Kludex brought this issue to my attention (in the context of the JSON schema stuff) and it looks like at some point in the past, there was a plan was to change to `str` as part of v2.

Given that usually when people are using Decimal it is more of a niche use case where they are choosing it to prioritize perfect precision, I think this issue is a pretty strong argument for using `str` as suggested here, and I think my vote would be to change it for v2.

But I wanted to get some explicit reconfirmation from you about how you want to handle this. (Especially if you are aware of any users that this would cause problems for.)

**Comment by ale-rinaldi** [comment] 2023-02-16 09:19
I strongly reconfirm that, for me, it should be serialized as a `string`, to ensure maximum precision. In my use cases I've never seen a decimal value serialized in something else than a string.

**Comment by kosta** [comment] 2023-02-16 09:55
I strongly agree as well. The whole point of decimal is having a human-friendly _non-lossy_ representation of a number. `string` is such a non-lossy representation, `number` is not (due to floats).

**Comment by danisana** [comment] 2023-02-16 10:58
I agree, maximum precision must be ensured

**Comment by bosshog** [comment] 2023-02-16 10:59
Better to have the representation as `string`, it helps a lot

**Comment by xela92** [comment] 2023-02-16 11:03
I agree, you don't expect precision loss from a Decimal representation

**Comment by samuelcolvin** [comment] 2023-02-16 11:04
Okay, please stop the "me too" messages.

We're talking about two distinct things here:
1. what `type` we use when generating JSON schema for a model - by default this should stick say as `number` - but that's not what this issue is about
2. what how we serialize `Decimal`s when dumping a model to JSON, this **should** change to be a `str` - that's what this issue is about

There's the added complexity of whether we should supporting generating a separate JSONSchema to define the format of a serialised model. **If** we do add support for this, obviously it should match the output format and therefore show the `type` of a `Decimal` field as `string`.

**Comment by ale-rinaldi** [comment] 2023-02-16 11:56
For point 2 I guess we all agree it totally makes sense for it to be a string.
For point 1, is there a separate discussion or shall we discuss it here as well? Logically speaking, of course it would be a number, but of course validators will complain if you pass a string and you expect a number. So, pratically, a string with a regex constraint like `/^(-?(0|[1-9]\d*)?(\.\d+)?(?<=\d)(e-?(0|[1-9]\d*))?|0x[0-9a-f]+)$/i` (https://slavik.meltser.info/validate-number-with-regular-expression/) would probably make more sense.

**Comment by samuelcolvin** [comment] 2023-02-16 11:58
Please don't confuse this issue, for the validation JSON Schema question, see https://github.com/pydantic/pydantic/pull/5029#discussion_r1107356818.

**Comment by lsorber** [comment] 2023-02-16 15:50
> what how we serialize Decimals when dumping a model to JSON, this should change to be a str - that's what this issue is about

I would consider two options here:

1. Serialize `Decimal` as a JSON string. For example, `Decimal(1) / Decimal(3)` would be serialized as `"0.333333333333333333333333333"`.
2. Serialize `Decimal` as a JSON number. For example, `Decimal(1) / Decimal(3)` would be serialized as `0.333333333333333333333333333`.

The advantage of (2) is that you can configure your JSON parser to use `Decimal` to parse JSON numbers. For example:
```python
import simplejson as json
json.loads("0.333333333333333333333333333", use_decimal=True) == Decimal("0.333333333333333333333333333")
```

**Comment by ale-rinaldi** [comment] 2023-02-16 17:26
@lsorber the problem is that, as you cast it to a number, you're already losing precision.

**Comment by lsorber** [comment] 2023-02-16 20:57
@ale-rinaldi The JSON specification doesn’t limit the number of digits a number consists of, so you don’t have to lose any precision.

**Comment by dmontagu** [comment] 2023-05-06 20:59
I believe this has been resolved in v2:
```python
from decimal import Decimal

from pydantic import BaseModel

class MyModel(BaseModel):
    foo: Decimal

m = MyModel(foo="31231239131093781902381093810298310983123.12000000")
print(m.model_dump_json())
#> {"foo":"31231239131093781902381093810298310983123.12000000"}
```

----

While I recognize that in principle we could make it work so that json-loading a number type would preserve the full precision of the provided number in the serialized JSON, given that without significant effort that won't be compatible with `json.loads`, I think that should be treated as out-of-scope for this issue.

If there is still interest in ensuring that `model_parse_json` preserves full precision for numeric JSON (not string-valued JSON), please open a separate issue for that specific request.

**Closed by dmontagu** 2023-05-06 20:59 UTC
Labels: Change

**Comment by pinkfrog9** [comment] 2023-07-26 17:11
@dmontagu Is it possible for me to swap the default json deserializer with my own? E.g., switch to simplejson or others.

**Comment by colesiegel** [comment] 2024-01-29 16:51
Is there a way to force the validator/deserializer for Decimal to only accept a string instead of coercing a number into a string?

I'd like the input and output to be consistent (string for both) on my API, but pydantic produces a schema which allows string or number for input and string for output.

**Comment by samuelcolvin** [comment] 2024-01-29 16:57
@colesiegel your question isn't clear - are you asking to change the validation or change the generated JSON schema?

If you want to change the validation logic, use a `model='before'` validator and raise and error if the input is not a string, if you want to change the JSON Schema, see [the docs](https://docs.pydantic.dev/latest/concepts/json_schema/#customizing-json-schema).
