### ISSUE TITLE
Autocompletion not working in VS Code with Pydantic

### ISSUE THREAD

**Issue by holyoaks** [pydantic/pydantic#9175] opened 2024-04-05 15:26 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I followed the instructions at https://docs.pydantic.dev/latest/integrations/visual_studio_code/#configure-vs-code but no matter what I do, I do not get autocompletion. I'm using Pylance (as noted in the docs, the default) as my language server, and can confirm Pydantic ==2.6.4 is installed in my virtual environment that VS Code is using. When I enable basic | standard | strict type checking in VS Code, I DO get type checking, but I always get `BaseModelSubclass(**data)` as the autocomplete for all of my Pydantic BaseModel subclasses. What might be wrong here?

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.4
        pydantic-core version: 2.16.3
          pydantic-core build: profile=release pgo=false
                 install path: /var/www/venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.6 (main, Oct  8 2023, 05:06:43) [GCC 13.2.0]
                     platform: Linux-6.6.16-linuxkit-aarch64-with-glibc2.38
             related packages: fastapi-0.110.0 email-validator-2.0.0 typing_extensions-4.10.0
                       commit: unknown
```

**Comment by sydney-runkle** [comment] 2024-04-09 16:35
@holyoaks,

Thanks for reporting. I'm not sure what the issue is - maybe someone else from the community has experienced this problem / has a fix? Can leave this open for now 👍

**Comment by Viicos** [comment] 2024-04-15 19:58
> but I always get `BaseModelSubclass(**data)` as the autocomplete for all of my Pydantic BaseModel subclasses

Could you share a screenshot of what you get in VSCode?

**Comment by holyoaks** [comment] 2024-04-15 20:29
A better one
![Screenshot 2024-04-15 at 3 28 59 PM](https://github.com/pydantic/pydantic/assets/5797525/5d863671-191e-4a43-9683-0b5960f86227)

**Comment by Viicos** [comment] 2024-04-16 07:05
Interesting, it shows the signature of `BaseModel` and not `Test` :thinking:

I see a warning on your `BaseModel` import, what is it saying? I'm guessing you are already on the latest version of Pylance, but could you also give your current version?

**Comment by holyoaks** [comment] 2024-04-16 12:33
@Viicos That's simply a Ruff warning (Import block is un-sorted or un-formatted Ruff [I001](https://docs.astral.sh/ruff/rules/unsorted-imports); I had not yet saved the file when I made the screenshot.

**Comment by holyoaks** [comment] 2024-05-21 14:08
As of today, without any changes on my part (that I'm aware of) the autocompletion started working. I have no idea.

**Comment by sydney-runkle** [comment] 2024-05-30 18:06
Haha, ok! Marking as resolved then. Thanks @holyoaks!

**Closed by sydney-runkle** 2024-05-30 18:06 UTC
Labels: bug V2
