### ISSUE TITLE
`SecretStr` not JSON serialisable in `__pydantic_extra__`

### ISSUE THREAD

**Issue by KasperZutterman** [pydantic/pydantic#8749] opened 2024-02-07 09:42 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

## Current Behaviour

`SecretStr` is unable to be serialised when it's in the __pydantic_extra__ values.

It results in the following error:
```
Traceback (most recent call last):
  File "/Users/kasperzutterman/test/pydantic.py", line 26, in <module>
    print(guest_info_extra.model_dump_json())
  File "/Users/kasperzutterman/.pyenv/versions/3.10.12/envs/pydantic/lib/python3.10/site-packages/pydantic/main.py", line 358, in model_dump_json
    return self.__pydantic_serializer__.to_json(
pydantic_core._pydantic_core.PydanticSerializationError: Unable to serialize unknown type: <class 'pydantic.types.SecretStr'>
```

## Expected Behaviour

```python
from pydantic import BaseModel, ConfigDict, SecretStr

class GuestInfoExtra(BaseModel):
    model_config = ConfigDict(extra='allow')
    __pydantic_extra__: dict[str, SecretStr]

    first_name: SecretStr


guest_info_extra = GuestInfoExtra(first_name='redacted_first_name', last_name='redacted_last_name')
print(guest_info_extra)                     # first_name=SecretStr('**********') last_name=SecretStr('**********')
print(guest_info_extra.__pydantic_extra__)  # {'last_name': SecretStr('**********')
print(guest_info_extra.model_dump())        # {'first_name': SecretStr('**********'), 'last_name': SecretStr('**********')}
print(guest_info_extra.model_dump_json())   # {"first_name":"**********", "last_name": "**********"}
```

I would expect `guest_info_extra.model_dump_json()` to correctly handle the `SecretStr` from the `__pydantic_extra__` field when serialising, as it works for the regular fields declared on the model.

### Example Code

```Python
from pydantic import BaseModel, ConfigDict, SecretStr


class GuestInfo(BaseModel):
    first_name: SecretStr


guest_info = GuestInfo(first_name='redacted_first_name', last_name='redacted_last_name')
print(guest_info)                       # first_name=SecretStr('**********')
print(guest_info.__pydantic_extra__)    # None
print(guest_info.model_dump())          # {'first_name': SecretStr('**********')}
print(guest_info.model_dump_json())     # {"first_name":"**********"}


class GuestInfoExtra(BaseModel):
    model_config = ConfigDict(extra='allow')
    __pydantic_extra__: dict[str, SecretStr]

    first_name: SecretStr


guest_info_extra = GuestInfoExtra(first_name='redacted_first_name', last_name='redacted_last_name')
print(guest_info_extra)                     # first_name=SecretStr('**********') last_name=SecretStr('**********')
print(guest_info_extra.__pydantic_extra__)  # {'last_name': SecretStr('**********')
print(guest_info_extra.model_dump())        # {'first_name': SecretStr('**********'), 'last_name': SecretStr('**********')}
print(guest_info_extra.model_dump_json())
# Traceback (most recent call last):
#   File "/Users/kasperzutterman/test/pydantic.py", line 26, in <module>
#     print(guest_info_extra.model_dump_json())
#   File "/Users/kasperzutterman/.pyenv/versions/3.10.12/envs/pydantic/lib/python3.10/site-packages/pydantic/main.py", line 358, in model_dump_json
#     return self.__pydantic_serializer__.to_json(
# pydantic_core._pydantic_core.PydanticSerializationError: Unable to serialize unknown type: <class 'pydantic.types.SecretStr'>
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.1
        pydantic-core version: 2.16.2
          pydantic-core build: profile=release pgo=true
                 install path: /Users/kasperzutterman/.pyenv/versions/3.10.12/envs/pydantic/lib/python3.10/site-packages/pydantic
               python version: 3.10.12 (main, Jun 16 2023, 15:59:26) [Clang 14.0.3 (clang-1403.0.22.14.1)]
                     platform: macOS-14.2.1-arm64-arm-64bit
             related packages: typing_extensions-4.8.0
                       commit: unknown
```

**Comment by sydney-runkle** [comment] 2024-02-07 13:54
@KasperZutterman,

Good catch. This is a bug as well. I've done some work with the secret types recently, so I'll take a closer look at this and root around for a fix.

**Comment by sydney-runkle** [comment] 2024-06-10 19:12
I'm going to close this as a duplicate of [#9491](https://github.com/pydantic/pydantic/issues/9491) - when that one is fixed (soon, hopefully), this one will be too!

**Closed by sydney-runkle** 2024-06-10 19:12 UTC
Labels: duplicate
