### ISSUE TITLE
mypy plugin internal error

### ISSUE THREAD

**Issue by xSAVIKx** [pydantic/pydantic#6992] opened 2023-08-02 11:42 UTC
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Pydantic v1.10 mypy plugin is not compatible with mypy v1.4.1

whatever I'm trying to check with mypy fails with the mypy internal error stack trace.

```
poetry run mypy . --show-error-context --pretty --namespace-packages --explicit-package-bases --show-traceback
PyProjects/.venv/lib/python3.11/site-packages/pydantic/env_settings.py:22: error: INTERNAL ERROR -- Please try using mypy master on GitHub:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 1.4.1
Traceback (most recent call last):
  File "mypy/semanal.py", line 6451, in accept
  File "mypy/nodes.py", line 1139, in accept
  File "mypy/semanal.py", line 1582, in visit_class_def
  File "mypy/semanal.py", line 1667, in analyze_class
  File "mypy/semanal.py", line 1694, in analyze_class_body_common
  File "mypy/semanal.py", line 1777, in apply_class_plugin_hooks
  File "pydantic/mypy.py", line 154, in pydantic.mypy.PydanticPlugin._pydantic_model_class_maker_callback
  File "pydantic/mypy.py", line 317, in pydantic.mypy.PydanticModelTransformer.transform
  File "pydantic/mypy.py", line 496, in pydantic.mypy.PydanticModelTransformer.add_construct_method
TypeError: __init__() missing required argument 'default' (pos 6)
/PyProjects/.venv/lib/python3.11/site-packages/pydantic/env_settings.py:22: : note: use --pdb to drop into pdb
```

### Example Code

```Python
import pydantic

class Item(pydantic.BaseModel):
    
    any_field: str
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.8
            pydantic compiled: True
                 install path: .venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.4 (main, Jun  7 2023, 12:45:48) [GCC 11.3.0]
                     platform: Linux-5.19.0-50-generic-x86_64-with-glibc2.35
     optional deps. installed: ['typing-extensions']
```
```


### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [X] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

Selected Assignee: @dmontagu

**Comment by dmontagu** [comment] 2023-08-02 12:56
Because we did a fairly significant overhaul of the mypy plugin for v2, I don't think we currently intend to maintain the pydantic v1 mypy plugin for compatibility with the latest versions of mypy (unless there is enough demonstration of interest), but I would be happy to review a PR against the 1.10.X-fixes branch if someone wants to fix this.

**Comment by Kilo59** [comment] 2023-08-02 19:23
Anecdotally, I've seen creating a fresh virtual environment and re-installing `mypy 1.4.1` and `pydantic `v1.10` resolve this issue.

Notably just clearing the `mypy` cache did not seem to be enough to fix this.

**Comment by satheler** [comment] 2023-08-05 21:38
I had the same problem here after upgrading `mypy` from version 1.3.0 to 1.4.1 using Pydantic version 1.10.2.
I tried clearing mypy's cache and rebuilding the virtual environement and the problem persisted.
I went back to version 1.3.0 and it worked perfectly.

**Comment by dmontagu** [comment] 2023-08-07 11:57
I am going to close this issue because:

1. I can't reproduce the issue using the provided example code with the latest pydantic-v1 and mypy (note, various issues with the mypy plugin _have_ been fixed in patch releases of 1.10.X)
2. Other users have indicated above that updating mypy _and_ pydantic and in a new environment resolved the issue for them.

I do suspect that this is just fixed in the latest version of pydantic, given the traceback is pointing at a line in the plugin code that has been changed/no longer exists.

If you still run into this with the latest version of pydantic (even v1), feel free to re-open the issue with additional details describing the issue after updating (since, at the very least, the traceback would be different).

**Closed by dmontagu** 2023-08-07 11:57 UTC
Labels: bug V1, unconfirmed
