### ISSUE TITLE
Inconsistent behaviour with validate_assignment

### ISSUE THREAD

**Issue by mjclarke94** [pydantic/pydantic#7034] opened 2023-08-07 19:05 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Not sure if this is a bug as such, or more something that should be documented as an anti-pattern.

I'm setting up some nested models and am using model validators to ensure that the contents of one field is a subset of another. (+1 for model_validators, they're incredible!)

An issue I ran in to when using this is that using a `+=` operator on a list type field will cause the `revalidate_assignment` to kick in, whilst using `.append()` or `.extend()` doesn't. I'm not sure if there is a good way to capture the change with the latter methods, but if not then highlighting that this is a pattern to avoid is worth doing!

### Example Code

```Python
import pydantic
class TestModel(pydantic.BaseModel, validate_assignment = True):
    list_of_strings : list[str]

TestModelInstance = TestModel(list_of_strings=['a', 'b', 'c'])

TestModelInstance.list_of_strings.append(1)
TestModelInstance.list_of_strings.extend([2]) # Makes it here fine
TestModelInstance.list_of_strings += [3] # Here, not so much...
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.1.1
   pydantic-core version: 2.4.0
     pydantic-core build: profile=release pgo=false mimalloc=true
            install path: /Users/matt/dev/elysia/gen3/.venv/lib/python3.10/site-packages/pydantic
          python version: 3.10.12 (main, Jul 28 2023, 18:34:01) [Clang 14.0.3 (clang-1403.0.22.14.1)]
                platform: macOS-13.5-arm64-arm-64bit
optional deps. installed: ['devtools', 'typing-extensions']
```

Selected Assignee: @dmontagu

**Comment by adriangb** [comment] 2023-08-09 14:53
This is (unfortunately) a known issue. I'll close this as a duplicate of https://github.com/pydantic/pydantic/issues/6597 please subscribe there for updates. But yes for now you'll either (1) have to avoid assigning or (2) use `object.__setattr__`.

**Closed by adriangb** 2023-08-09 14:53 UTC
Labels: unconfirmed, bug V2
