### ISSUE TITLE
Mypy error when inheriting from multiple `BaseModel`s and having an optional field, with mypy flag `no_strict_optional=True`

### ISSUE THREAD

**Issue by kikones34** [pydantic/pydantic#8729] opened 2024-02-05 15:31 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Likely related to https://github.com/pydantic/pydantic/issues/8665.

When a model inherits from two other models and contains an optional field, mypy throws the following validation errors:
```
pydantic_mypy_test.py:12: error: Definition of "model_construct" in base class "Model1" is incompatible with definition in base class "Model2"  [misc]
pydantic_mypy_test.py:12: error: Definition of "model_construct-redefinition2" in base class "Model1" is incompatible with definition in base class "Model2"  [misc]
pydantic_mypy_test.py:12: error: Definition of "model_construct-redefinition" in base class "Model1" is incompatible with definition in base class "Model2"  [misc]
Found 3 errors in 1 file (checked 1 source file)
```
This doesn't happen if the model inherits from just one model, or if the model doesn't have any optional fields.
Also, as in the mentioned issue, it only happens with the mypy flag `no_strict_optional=True`.

### Example Code

```Python
from pydantic import BaseModel


class Model1(BaseModel):
    pass


class Model2(BaseModel):
    pass


class Model3(Model1, Model2):
    field: str | None
```

### Python, Pydantic & OS Version

```Text
             pydantic version: 2.6.1
        pydantic-core version: 2.16.2
          pydantic-core build: profile=release pgo=true
                 install path: /home/k34/repos/internal/trio-cloud-search/.venv/lib/python3.12/site-packages/pydantic
               python version: 3.12.1 (main, Dec 10 2023, 15:07:36) [GCC 11.4.0]
                     platform: Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
             related packages: pydantic-settings-2.1.0 mypy-1.8.0 pydantic-extra-types-2.5.0 fastapi-0.109.2 typing_extensions-4.9.0 email-validator-2.1.0.post1
                       commit: unknown
```

**Comment by sydney-runkle** [comment] 2024-02-06 13:44
@kikones34,

Thanks for reporting this. @dmontagu, could you take a look at implementing a fix for this to be included in v2.6.2? Thanks!

**Comment by aaronsewall** [comment] 2024-02-07 20:02
So I get a similar but not exactly the same error with a slightly different test case, with strict_optional=False. This was working previously in pydantic 2.5.3.

```
from typing import Optional

from pydantic import ConfigDict
from pydantic.main import BaseModel as PydanticBaseModel


class BaseModel(PydanticBaseModel):
    model_config = ConfigDict(
        validate_assignment=True,
        validate_default=True,
        extra="forbid",
        frozen=True,
    )

class HealthStatus(BaseModel):
    status: str
    description: Optional[str] = None


hs = HealthStatus(status="healthy")
```

Mypy output is
```
scratch.py:20: error: Unexpected keyword argument "status" for "HealthStatus"  [call-arg]
Found 1 error in 1 file (checked 1 source file)
```

```
pydantic version: 2.6.1
pydantic-core version: 2.16.2
pydantic-core build: profile=release pgo=false
python version: 3.9.6 (default, Nov 10 2023, 13:38:27)  [Clang 15.0.0 (clang-1500.1.0.2.5)]
platform: macOS-14.2.1-x86_64-i386-64bit
related packages: mypy-1.8.0 typing_extensions-4.9.0
commit: unknown
```

**Comment by dmontagu** [comment] 2024-02-15 14:06
@aaronsewall 
I can't reproduce the issue using the following mypy config file:
```
[build-system]
requires = ["poetry>=0.12"]
build_backend = "poetry.masonry.api"

[tool.poetry]
name = "test"
version = "0.0.1"
readme = "README.md"
authors = [
    "author@example.com"
]

[tool.poetry.dependencies]
python = "*"

[tool.pytest.ini_options]
addopts = "-v -p no:warnings"

[tool.mypy]
plugins = [
    "pydantic.mypy"
]
follow_imports = "silent"
strict_optional = false
warn_redundant_casts = true
warn_unused_ignores = true
disallow_any_generics = true
check_untyped_defs = true
no_implicit_reexport = true
disallow_untyped_defs = true

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true

[[tool.mypy.overrides]]
module = [
    'pydantic_core.*',
]
follow_imports = "skip"
```
Could you share the exact mypy config you are using when getting that error?

**Comment by dmontagu** [comment] 2024-02-15 14:35
@kikones34 this issue is not related to #8665, the errors you are seeing are because the `model_construct` method has incompatible signatures. Mypy special cases the handling of `__init__` to allow incompatible signatures inherited from multiple parent classes, but it doesn't allow that for a method named `model_construct`. You can reproduce this after replacing your BaseModel types with dataclasses by defining a method `model_construct` with the same signature as the `__init__` on each class.

As far as I can tell, there's no way for us to define a correct signature for `model_construct` without hitting this. (I would be happy to be proven wrong on that though.)

One option would be to add to the pydantic mypy plugin config the ability to disable generation of the typed `model_construct` method signature, that should be easy to implement and would suppress the issue, but would mean calls to `model_construct` are not properly typechecked. Other than that I think it may be hard to resolve this short of adding a `# type: ignore` in your code.

**Comment by kikones34** [comment] 2024-02-15 15:25
@dmontagu Thanks for your reply! I don't know much about Pydantic's inner workings, but following your reasoning, I'm having a hard time understanding how that would explain why this issue occurs only if the model contains an optional field, and only with the `no_strict_optional=True` flag enabled. Does this change in any way how the `model_construct` behaves?

Also, note that this was working fine before the update (using `pydantic-core==2.14.6` and `pydantic==2.5.3`), does that mean that `model_construct` was not type-checked before..?

**Comment by dmontagu** [comment] 2024-02-21 05:25
Yeah, @kikones34 I see that you are right that it didn't used to do this. I think it's due to other bugfixes causing it to now hit a branch in the mypy code where it checks for incompatibility in a way it didn't before. In particular, for some reason it is hitting this line https://github.com/python/mypy/blob/8107e53158d83d30bb04d290ac10d8d3ccd344f8/mypy/checker.py#L2698 now but was not before. I think it will take significantly more investigation to get to the bottom of this, unfortunately I think there were various other bugs that the relevant code changes fixed, so it's not as simple as just reverting them.

This will probably require more serious investigation to get to the bottom of, I can't promise I'll have time in the near future but I will try to look into this more when I can spare some time to work on the mypy integration (I would recommend using a `#type: ignore` for this in the meantime).

**Comment by dmontagu** [comment] 2024-07-17 23:14
I don't know exactly when this was fixed, but I can no longer reproduce this on main.

If I'm being dumb and this is not actually fixed, please let us know and we can reopen the issue.

(If it is still broken, please share the mypy version you are using.)

**Closed by dmontagu** 2024-07-17 23:14 UTC
Labels: bug V2, mypy

**Comment by MarcSalvat** [comment] 2024-09-05 10:23
Qu
