### ISSUE TITLE
Unable to set __test__ = False on models

### ISSUE THREAD

**Issue by antazoey** [pydantic/pydantic#6095] opened 2023-06-12 13:28 UTC
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

I can't figure out how to set `__test__ = False` on a Pydantic model.
According to Pytest and other testing frameworks, this is the standard for ignoring test collection.
However, everything I have tried, I cannot use this approach to ignore a Pydantic model from pytest collection.

### Example Code

```Python
from pydantic import BaseModel


class MyBase(BaseModel):
    """My base model."""
    
    __test__ = False  # Trying in base class too, just in case.


class TestModel(MyBase):
    __test__ = False  # Trying to ignore from pytest collection


model = TestModel()
# `__test__` must be in `__dict__` to work.
# However, it never is.
print(model.__dict__)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.8
            pydantic compiled: True
                 install path: /Users/jules/virtualenvs/yoko/lib/python3.9/site-packages/pydantic
               python version: 3.9.13 (main, Jun 28 2022, 09:33:10)  [Clang 13.1.6 (clang-1316.0.21.2.5)]
                     platform: macOS-13.3-x86_64-i386-64bit
     optional deps. installed: ['dotenv', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [X] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by dmontagu** [comment] 2023-06-13 21:50
`__test__` isn't in `model.__dict__`, it's in `TestModel.__dict__`.

In general, we don't (currently) support storing arbitrary data in the `__dict__` attribute on `BaseModel` due to how model construction, etc. works — `__dict__` currently holds the field values.

Can you give an example of something you want to do in pytest that this is preventing? That might help us figure out how to resolve this issue or otherwise better support the use case.

**Comment by dmontagu** [comment] 2023-06-13 21:55
I also tried creating a BaseModel with `__test__ = False` in both pydantic v1 and v2 and it seemed to get pytest to ignore the tests for me (i.e., the expected behavior) in both cases. So I don't think we can help unless you can share a full example of what is misbehaving.

**Comment by antazoey** [comment] 2023-06-14 13:26
Oh? That is quite interesting... thanks for checking, perhaps the bug is in the custom runner / collect handlers, I hadn't thought of that.

**Comment by dmontagu** [comment] 2023-06-19 16:25
Given I don't see anything misbehaving and can't reproduce an issue, I'll close this for now, but feel free to request it being reopened especially if you can find a problematic pydantic-specific behavior.

**Closed by dmontagu** 2023-06-19 16:25 UTC
Labels: bug V1, unconfirmed

**Comment by antazoey** [comment] 2023-06-29 16:37
More information (still haven't figured this out):

* It is happening in a test that is tested through `pytester`, the pytest plugin for testing pytest plugins
* It is happening on the pydantic model being imported into this test

**Comment by antazoey** [comment] 2023-06-29 16:51
OK I figured it out. Here is what I did to my code (see comment)to make it work:

```
from ape_test.accounts import TestAccount


# NOTE: Even though `__test__` is set to `False` on the class,
# it must be set here as well for it to properly work for some reason.
TestAccount.__test__ = False
```

Sorry - not sure this is Pydantic related though, probably should put this in pytest or something
