### ISSUE TITLE
Custom serializer works for "int | CustomType" but not for "EnumType | CustomType"

### ISSUE THREAD

**Issue by larsks** [pydantic/pydantic#6960] opened 2023-07-31 13:04 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I am using a custom type with a custom serializer in my pydantic classses. When a field is defined like this:

```
class Example1(BaseModel):
    model_config = ConfigDict(arbitrary_types_allowed=True)
    someAttribute: int | CustomType
```

Then the custom serializer is called as expected when the attribute value is a `CustomType` instance. But if I define the model like this instead:

```
class SomeEnum(int, Enum):
    VALUE0 = 0
    VALUE1 = 1


class Example1(BaseModel):
    model_config = ConfigDict(arbitrary_types_allowed=True)
    someAttribute: SomeEnum | CustomType
```

Then the custom serializer is never called, and serializing to JSON will fail with:

```
pydantic_core._pydantic_core.PydanticSerializationError: Error serializing to JSON: PydanticSerializationError: Unable to serialize unknown type: <__main__.CustomType object at 0x7fec6c113810>
```

### Example Code

```Python
from typing import Annotated
from pydantic import BaseModel, ConfigDict, PlainSerializer
from enum import Enum


class CustomType:
    pass

CustomTypeField = Annotated[
    CustomType,
    PlainSerializer(lambda _: "!custom", when_used="json"),
]


class SomeEnum(int, Enum):
    VALUE0 = 0
    VALUE1 = 1


class Example1(BaseModel):
    model_config = ConfigDict(arbitrary_types_allowed=True)

    name: str
    count: int
    location: int | CustomTypeField


class Example2(BaseModel):
    model_config = ConfigDict(arbitrary_types_allowed=True)

    name: str
    count: int
    location: SomeEnum | CustomTypeField


obj1 = Example1(name='example1', count=10, location=CustomType())
obj2 = Example2(name='example1', count=10, location=CustomType())

print('obj1:', obj1.model_dump_json())
print('obj2:', obj2.model_dump_json())
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.1.1
        pydantic-core version: 2.4.0
          pydantic-core build: profile=release pgo=true mimalloc=true
                 install path: /home/lars/tmp/python/.venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.4 (main, Jun  7 2023, 00:00:00) [GCC 13.1.1 20230511 (Red Hat 13.1.1-2)]
                     platform: Linux-6.4.4-200.fc38.x86_64-x86_64-with-glibc2.37
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @lig

**Comment by lig** [comment] 2023-08-10 07:36
I can confirm that the error reproduces in Pydantic v2.1.1.

Also, without `when_used="json"` the error reproduces for `Example2(name='example1', count=10, location=CustomType()).model_dump()` as well.

Minimal reproducible example:

```
def test_enum_annotated_with_custom_type():
    from enum import Enum
    from typing import Annotated

    from pydantic import BaseModel, ConfigDict, PlainSerializer

    class CustomType:
        pass

    CustomTypeField = Annotated[CustomType, PlainSerializer(lambda _: '!custom')]

    class SomeEnum(int, Enum):
        VALUE0 = 0
        VALUE1 = 1

    class Example2(BaseModel):
        model_config = ConfigDict(arbitrary_types_allowed=True)
        location: SomeEnum | CustomTypeField

    obj2 = Example2(name='example1', count=10, location=CustomType())
    assert obj2.model_dump() == dict(name='example1', count=10, location='!custom')
```

**Comment by sydney-runkle** [comment] 2024-08-12 14:40
Looks like this is fixed on `main`.

**Closed by sydney-runkle** 2024-08-12 14:40 UTC
Labels: help wanted, bug V2
