### ISSUE TITLE
v2.8 create_model breaking change to api (__model_name->model_name), not in changelog

### ISSUE THREAD

**Issue by fraser-langton** [pydantic/pydantic#9901] opened 2024-07-16 06:10 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

#9479 

[Commit](https://github.com/pydantic/pydantic/commit/eeea647f0b2a1107a923d4c0e3369344c985d38a#diff-8708af8d26c26644976866f974e0b810b0940ede43ff487e457057d5a1f07999)

Interesting to find this #1367 which originally changed model_name -> __model_name

### Python, Pydantic & OS Version

```Text
pydantic version: 2.7.4
        pydantic-core version: 2.18.4
          pydantic-core build: profile=release pgo=true
                 install path: C:\Users\fraser\.virtualenvs\render-services-IYdnVPWc\Lib\site-packages\pydantic
               python version: 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
                     platform: Windows-10-10.0.22631-SP0
             related packages: fastapi-0.111.0 mypy-1.8.0 typing_extensions-4.12.2
                       commit: unknown
```

**Comment by fraser-langton** [comment] 2024-07-16 06:18
The change added `/` to the signature, might I suggest also adding `__model_name` as a kw arg deprecated just for back compat - that should cover all cases it was being used, either positional or kw would work after such a change

**Comment by Viicos** [comment] 2024-07-16 07:38
> The change added `/` to the signature, might I suggest also adding `__model_name` as a kw arg deprecated just for back compat - that should cover all cases it was being used, either positional or kw would work after such a change

I'm personally -1 on this, `__model_name` wasn't supposed to be used as per the [typing specification](https://typing.readthedocs.io/en/latest/spec/historical.html#positional-only-parameters). Do you have a use case where replacing `create_model(__model_name=...)` by `create_model(...)` isn't possible?

**Comment by fraser-langton** [comment] 2024-07-16 23:08
> Do you have a use case where replacing create_model(__model_name=...) by create_model(...) isn't possible?

Nup it's obviously a niche use case (but we had it) and easy to fix, updating the changelog to show a breaking change makes sense

**Comment by sydney-runkle** [comment] 2024-07-17 15:28
@Viicos, thanks for opening the PR - I've approved.

@fraser-langton, see https://github.com/pydantic/pydantic/issues/9810, which is a duplicate of this issue.

**Closed** 2024-07-17 15:31 UTC
Labels: bug V2, pending
