### ISSUE TITLE
Unable to `cloudpickle` Pydantic model classes

### ISSUE THREAD

**Issue by shrekris-anyscale** [pydantic/pydantic#6763] opened 2023-07-20 04:05 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

`cloudpickle` cannot serialize Pydantic model classes. It fails with a `TypeError: cannot pickle 'pydantic_core._pydantic_core.SchemaSerializer' object` exception.

### Example Code

```Python
# bug.py

"""Cloudpickling Pydantic models raises an exception."""

from pydantic import BaseModel
import ray.cloudpickle as cloudpickle

class SimpleModel(BaseModel):
    val: int

cloudpickle.dumps(SimpleModel)

"""
Output:

% python bug.py

Traceback (most recent call last):
  File "/Users/shrekris/Desktop/scratch/dump4.py", line 9, in <module>
    cloudpickle.dumps(SimpleModel)
  File "/Users/shrekris/Desktop/ray/python/ray/cloudpickle/cloudpickle_fast.py", line 88, in dumps
    cp.dump(obj)
  File "/Users/shrekris/Desktop/ray/python/ray/cloudpickle/cloudpickle_fast.py", line 733, in dump
    return Pickler.dump(self, obj)
TypeError: cannot pickle 'pydantic_core._pydantic_core.SchemaSerializer' object
"""
```

### Python, Pydantic & OS Version

```Text
/Users/shrekris/miniforge3/envs/pydantic-fix/lib/python3.9/site-packages/pydantic/_migration.py:275: UserWarning: `pydantic.utils:version_info` has been moved to `pydantic.version:version_info`.
  warnings.warn(f'`{import_path}` has been moved to `{new_location}`.')
             pydantic version: 2.0.3
        pydantic-core version: 2.3.0 release build profile
                 install path: /Users/shrekris/miniforge3/envs/pydantic-fix/lib/python3.9/site-packages/pydantic
               python version: 3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:38:11)  [Clang 14.0.6 ]
                     platform: macOS-11.4-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @lig

**Comment by shrekris-anyscale** [comment] 2023-07-20 04:07
The root cause seems to be that the `SchemaSerializer` cannot be serialized. I tried overriding the `CloudPickler`'s `reducer_override` method with [a workaround](https://gist.github.com/shrekris-anyscale/1d82c20d4aafd508a25df4d67f19d8fd) that deletes the `SchemaSerializer` upon serialization and recreates it upon deserialization, which seems to work. However, I cannot use this workaround in my project since it requires modifying cloudpickle's `reducer_override` method, which is used across all objects that need to be serialized. Ideally, this workaround could be pushed into the Pydantic classes themselves, so `cloudpickl`ing them just works.

**Comment by lig** [comment] 2023-07-21 14:05
@shrekris-anyscale Thank you for the report. Any ideas what could make it work?

**Comment by dmontagu** [comment] 2023-07-21 16:41
Is there a dunder method that cloudpickle uses? We have custom `__getstate__` and `__setstate__` to make models pickleable, not sure if there's something we could/should do to make it work with cloudpickle.

**Comment by shrekris-anyscale** [comment] 2023-07-21 21:50
One solution is to store `SchemaSerializer`'s [schema and config](https://github.com/pydantic/pydantic-core/blob/608db7ba72e836380a39c716d651a06c745eb2cd/python/pydantic_core/_pydantic_core.pyi#L114-L115) as instance attributes in the serializer. Then, we can define a custom `__reduce__` method that serializes the `SchemaSerializer` by serializing its schema and config. To deserialize, we can initialize a new `SchemaSerializer` using the schema and config.

Essentially, adding the following methods to `SchemaSerializer`:

```python
def __init__(self, schema: CoreSchema, config: CoreConfig):
    self.schema = schema
    self.config = config

def __reduce__(self):
    return SchemaSerializer, (schema_cache, config_cache, )
```

Here's [a gist](https://gist.github.com/shrekris-anyscale/3d7836a6e606dcc8272c1f22a5cf4ccf) where I overwrote the `SchemaSerializer`'s `__init__` and `__reduce__` methods as proposed. `cloudpickle` and `pickle` successfully serialize the Pydantic model.

**Comment by dmontagu** [comment] 2023-07-22 03:56
If you’d like to make a PR adding this on pydantic-core I’m sure we’d accept it, otherwise @davidhewitt maybe you could whip something up?

**Comment by samuelcolvin** [comment] 2023-07-22 06:13
I don't think `SchemaSerializer` needs to be picklable, you should just store the core scheme and recreate the serializer.

**Comment by shrekris-anyscale** [comment] 2023-07-24 17:51
> I don't think `SchemaSerializer` needs to be picklable, you should just store the core scheme and recreate the serializer.

I agree, but I don't think this plays nicely with `cloudpickle`. I tried adding `__reduce__` methods to the `ModelMetaclass` and the `BaseModel` classes, but `cloudpickle` didn't enter them when it tried to `dump` the model classes. Instead, it seems to try to serialize all the attributes of the classes directly, including the `SchemaSerializer`.

I'm not sure how we'd be able to just store the schema and recreate the serializer if we can't use a custom `__reduce__` method in these classes.

**Comment by davidhewitt** [comment] 2023-07-25 12:50
I did some digging and it looks like `cloudpickle` switches between "by reference" or "by value" pickling modes according to whether your type is importable.

So in the repro discussed above, the class is `__main__.SimpleModel` which is treated as not importable. In this case it looks to me like `cloudpickle` attempts to recreate a "skeleton" class which functions the same as the provided type. I don't see a way to customise this behaviour. So to support "by value" pickling we need to support naive pickling for all the attributes of the class, as @shrekris-anyscale says. I can't see a way to customise this behaviour. Maybe cloudpickle maintainers know of solutions.

On the other hand, if `SimpleModel` is moved into a module and imported from there (e.g. `from foo import SimpleModel`), then `cloudpickle` will use "by reference" pickling. This already works fine (the pickled data just contains the reference to the import path).

So @shrekris-anyscale a possible workaround may be to move your model definitions out of `__main__` files / entry points into modules. Without knowing the full details of your application I don't know if that's actually viable.

**Comment by davidhewitt** [comment] 2023-07-26 14:22
The downside of this is that I'd expect we'd need to take a deep copy of the schema and config and store them inside the `SchemaSerializer`. Currently it just contains Rust state which derives from those (the inverse operation, while possible, is not implemented and would likely be complex).

This would probably also be the case for `SchemaValidator`.

It seems like a lot of extra CPU and memory baggage that most users will not need. The zero-cost solution would be to implement the "inverse operation" described above (i.e. rebuild schema and config from the Rust state). I couldn't guarantee that's even possible, though.

A proposal which allows pickle support to be opt-in may be a more feasible solution for now.

**Comment by shrekris-anyscale** [comment] 2023-07-26 16:16
Another low-baggage alternative is to delete the serializer upon serialization and reconstruct whenever it's first called. The `SchemaSerializer`'s `__reduce__` function could be:

```python
def __reduce__(self):
    return lambda: None, tuple()
```

Then whenever the `SchemaSerializer` is first called, the Pydantic model can initialize it using the schema and config and cache it.

This should only affect users that are serializing the `SchemaSerializer`, and the only added cost is the initialization upon the first call.

**Comment by shrekris-anyscale** [comment] 2023-07-26 16:20
Another option is to have the `SchemaSerializer` hold a reference to the Pydantic model that it's a part of. Upon serialization, the serializer could use this reference to obtain the schema and config. That way, the serializer won't contain a deep copy of either one during its lifetime.

**Comment by shrekris-anyscale** [comment] 2023-07-26 17:11
> Does this work with monkey-patching `SchemaSerializer`?

I haven't actually run that example myself, so I'm not sure if the syntax is correct. The high level approach of that `__reduce__` method should be possible though. I don't think monkeypatching alone is sufficient because the `SchemaSerializer` also needs to be re-initialized in the `BaseModel` and `ModelMetaclass` whenever it's first called.

**Comment by jrapin** [comment] 2023-10-02 14:58
Hello,
FYI I am running into the exact same issue (pickling a locally defined model, which is really convenient for prototyping code), but my error is slightly different from what is mentioned before (with the exact same "SimpleModel" example):
```
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../../.conda/envs/xxx/lib/python3.10/site-packages/cloudpickle/cloudpickle_fast.py:73: in dumps
    cp.dump(obj)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <cloudpickle.cloudpickle_fast.CloudPickler object at 0x7f1466cad180>
obj = <class 'test_pickling.<locals>.SimpleModel'>

    def dump(self, obj):
        try:
>           return Pickler.dump(self, obj)
E           TypeError: cannot pickle '_PydanticWeakRef' object

../../../.conda/envs/xxx/lib/python3.10/site-packages/cloudpickle/cloudpickle_fast.py:632: TypeError
```
This is with:
- cloudpickle 2.2.1
- pydantic 2.3.0

I am also interested in any way that could make this work ;)

**Comment by jrapin** [comment] 2023-10-03 11:36
A bit more on my use case:
I am sending pickled model instances defining computation to a cluster where this computation will run. The issue is that the model is possibly created in a notebook/script, not in a loaded module, and using `pickle` [as in the documentation](https://docs.pydantic.dev/latest/concepts/serialization/#pickledumpsmodel) won't work because we reload it in a context where the class is not defined. This is a use case where `cloudpickle` is supposed to work well on the other hand.

 To remove the offending (class) fields I can surround the (cloud)pickling with this context manager which works fine:
```python
@contextlib.contextmanager
def picklable_pydantic_model(cls: tp.Type[pydantic.BaseModel]) -> tp.Iterator[None]:
    content: tp.Dict[str, tp.Any] = {
        "__pydantic_parent_namespace__": None,
        "__pydantic_serializer__": None,
    }
    for name in content:
        content[name] = cls.__dict__[name]
        type.__setattr__(cls, name, None)
    try:
        yield
    finally:
        for name, data in content.items():
            type.__setattr__(cls, name, data)
```
It's applied on the class, and allows both class and instances to be pickled.
But that's only useful because I am not using many pydantic features on the cluster, I'm losing features such as `model_dump` in the process, and probably others that I don't notice (yet?)
Are there easy ways to recreate them easily?

**Comment by edoakes** [comment] 2023-10-05 16:37
I also ran into the above issues:

- `SchemaSerializer` not being `cloudpickle`able due to being a native type (written in Rust).
- `_PydanticWeakref` not being `cloudpickle`able due to inheriting from `weakref.ref`, which has known issues with serialization.

I was able to enable `cloudpickle`ing a wide variety of Pydantic model definitions with the following two patches:

1) Wrap `SchemaSerializer` to save the Python arguments necessary to reconstruct it:
```python
# Define a wrapper that saves the `schema` and `core_config` to reconstruct the native `SchemaSerializer`.
class CloudpickleableSchemaSerializer:
    def __init__(self, schema, core_config):
        self._schema = schema
        self._core_config = core_config
        self._schema_serializer = SchemaSerializer(*args)

    def __reduce__(self):
        return CloudpickleableSchemaSerializer, (self._schema, self._core_config)

    def __getattr__(self, attr: str):
        return getattr(self._schema_serializer, attr)

# Override all usages of `SchemaSerializer` (obviously not needed if we upstream the above wrapper):
pydantic._internal._model_construction.SchemaSerializer = CloudpickleableSchemaSerializer
pydantic._internal._dataclasses.SchemaSerializer = CloudpickleableSchemaSerializer
pydantic.type_adapter.SchemaSerializer = CloudpickleableSchemaSerializer
```

The `__getattr__` bit is somewhat hacky. This is required because `SchemaSerializer` does not allow Python classes to subclass it. This can be cleaned up by adding the `subclass` parameter to the [PyO3 #[pyclass] macro](https://pyo3.rs/v0.3.2/class#customizing-the-class) in `pydantic_core`.

2) Wrap `weakref.ref` instead of inheriting from it:
```python
class WeakRefWrapper:
    def __init__(self, obj: Any):
        self._wr = weakref.ref(obj)

    def __reduce__(self):
        return WeakRefWrapper, (self._wr(),)

    def __call__(self) -> Any:
        return self._wr()

# Override all usages of `_PydanticWeakRef` (obviously not needed if we upstream the above wrapper):
pydantic._internal._model_construction._PydanticWeakRef = WeakRefWrapper
```

AFAICT there's no downside to this but it gets around the strange ABC-related pickling error.

@davidhewitt @dmontagu I'm happy to contribute a patch if you think this is a reasonable direction. Let me know what you think.

**Comment by davidhewitt** [comment] 2023-10-06 09:09
Thanks @edoakes for investigating. My question would be whether you plan to merge the `CloudpickleableSchemaSerializer` into `pydantic` or you just want to make the adjustments so that projects which need this functionality can patch themselves.

If your goal is to merge this fix into pydantic then it's probably better to just make `SchemaSerializer` always store these members so there's no need for wrapping.

**Comment by edoakes** [comment] 2023-10-06 13:52
@davidhewitt I'd prefer to merge the functionality into `pydantic` so that `cloudpickle` "just works" out of the box and folks don't have to worry about patching things.

Storing the members and defining `__reduce__` on `SchemaSerializer` itself would indeed be preferable, I'm just not sure how to accomplish that using PyO3 (not familiar with the framework). I can try to get it working.

So then the plan of action would be:

- PR 1 (against `pydantic_core`): Make `SchemaSerializer` directly cloudpickleable in `pydantic_core` by storing references to the constructor arguments.
- PR 2 (against `pydantic`): Use a `WeakrefWrapper` similar to the above rather than the weakref directly.

With these two, we should be good to go. Given that these changes would be split across the repos, is there any special versioning story between them? Or does `pydantic` treat `pydantic_core` like any other Python package dependency? In PR 2 I'll add a regression test but that will depend on using a version of `pydantic_core` that includes PR 1.

**Comment by edoakes** [comment] 2023-10-06 13:57
Ah, I see it looks like the `pydantic_core` version is pinned: https://github.com/pydantic/pydantic/blob/main/pyproject.toml#L64

So I assume then that this will require first patching `pydantic_core`, waiting for a release, then updating the pinned version in `pydantic`?

**Comment by davidhewitt** [comment] 2023-10-06 21:41
Yes exactly, we can release `pydantic_core` shortly after your PR is merged so there's not a long delay in getting this working on `pydantic` main.

**Comment by edoakes** [comment] 2023-10-09 16:16
I have opened PRs for each of the above issues:

- https://github.com/pydantic/pydantic-core/pull/1006
- https://github.com/pydantic/pydantic/pull/7780

I will begin testing that these fixes are comprehensive using locally installed copies. Once these PRs have been merged and a new version of `pydantic_core` has been released, I will add integration/regression tests to the `pydantic` repo.

**Comment by jrapin** [comment] 2023-10-13 13:40
@edoakes sorry for the delay
I was just able to test the updated packages, and I can confirm it worked perfectly for my use case :)
Thanks a lot!

**Closed** 2023-10-24 16:17 UTC
Labels: help wanted, unconfirmed, bug V2

**Comment by edoakes** [comment] 2023-10-24 17:33
Thanks for the help @davidhewitt 🚀 do you know when the next release is scheduled and what its version tag will be?

**Comment by davidhewitt** [comment] 2023-10-24 17:39
No specific ETA, I would assume 2.5.

**Comment by edoakes** [comment] 2023-11-07 17:29
@davidhewitt any update on when the next `pydantic` release is going to come out? This is a pretty big pain point for our users and I want to make sure we can unpin the dependency soon.

**Comment by fkaleo** [comment] 2023-11-07 22:06
> @davidhewitt any update on when the next `pydantic` release is going to come out? This is a pretty big pain point for our users and I want to make sure we can unpin the dependency soon.

Reading from https://github.com/pydantic/pydantic/issues/8028 there seems to be a couple of items still pending before 2.5 comes out

**Comment by davidhewitt** [comment] 2023-11-09 09:30
I believe we are going to release 2.5 beta today, with a view to a final 2.5 production release next week.

**Comment by jrapin** [comment] 2023-11-27 13:52
@edoakes unfortunately I have been fooled by my unit tests running better thanks to your fix ("local" classes defined within the scope of a unittest can be pickled while they could not before the fix), but I still have issues with Ipython console and Jupyter notebooks :( (see #8232). Did everything work fine on your end? Do you have any idea what can be causing this?
