### ISSUE TITLE
Pydantic2 fails to parse timedelta strings with days separated by spaces

### ISSUE THREAD

**Issue by maafy6** [pydantic/pydantic#8924] opened 2024-02-29 20:31 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Per the datetimes docs page https://docs.pydantic.dev/2.0/usage/types/datetime/, pydantic will accept a string with the following format as a time:

`[-][DD ][HH:MM]SS[.ffffff]`

When using the string `7 00:00:00` which parsed properly as `timedelta(days=7)` in pydantic v1, the field fails to validate:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pydantic/type_adapter.py", line 256, in validate_python
    return self.validator.validate_python(__object, strict=strict, from_attributes=from_attributes, context=context)
pydantic_core._pydantic_core.ValidationError: 1 validation error for timedelta
  Input should be a valid timedelta, "day" identifier in duration not correctly formatted [type=time_delta_parsing, input_value='7 00:00:00', input_type=str]
    For further information visit https://errors.pydantic.dev/2.6/v/time_delta_parsing
```

It works when appending literal `D` to the day value, and including (or not) a space between the day and the HH:MM:SS string, but it is not evident from the docs that this would be required (I discovered it just by chance).

### Example Code

```Python
from datetime import timedelta
from pydantic import TypeAdapter

# Raises ValidationError
TypeAdapter(timedelta).validate_python("7 00:00:00")

# Returns timedelta(days=7)
TypeAdapter(timedelta).validate_python("7D00:00:00")
TypeAdapter(timedelta).validate_python("7D 00:00:00")
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.3
        pydantic-core version: 2.16.3
          pydantic-core build: profile=release pgo=true
                 install path: /home/ubuntu/.local/lib/python3.8/site-packages/pydantic
               python version: 3.8.10 (default, Nov 22 2023, 10:22:35)  [GCC 9.4.0]
                     platform: Linux-5.15.0-97-generic-x86_64-with-glibc2.29
             related packages: fastapi-0.110.0 typing_extensions-4.10.0
                       commit: unknown
```

**Comment by sydney-runkle** [comment] 2024-02-29 23:39
Hi @maafy6,

Thanks for your inquiry. I believe this is a duplicate of https://github.com/pydantic/pydantic/issues/7650. We have recently updated the documentation to reflect the allowed formats for `timedelta` types, which you can see here: https://docs.pydantic.dev/latest/api/standard_library_types/#datetimetimedelta.

Let me know if you have any follow up questions!

**Closed by sydney-runkle** 2024-02-29 23:39 UTC
Labels: duplicate, documentation
