### ISSUE TITLE
`from __future__ import annotations` prevents ABC from instantiation

### ISSUE THREAD

**Issue by aiotter** [pydantic/pydantic#8102] opened 2023-11-14 08:47 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

`from __future__ import annotations` breaks the instantiation of the model with a abstract field (property) whose type is `ClassVar`.

### Example Code

```Python
from __future__ import annotations  # <- removing this line solves the problem
from abc import ABC, abstractmethod
from typing import ClassVar
from pydantic import BaseModel

class Base(ABC):
    @property
    @abstractmethod
    def _test():
        pass

class Test(BaseModel, Base):
    _test: ClassVar[str] = "test"

print(Test()._test)
# TypeError: Can't instantiate abstract class Test with abstract method _test
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.0
        pydantic-core version: 2.14.1
          pydantic-core build: profile=release pgo=true
                 install path: /private/tmp/test/.direnv/python-3.10/lib/python3.10/site-packages/pydantic
               python version: 3.10.12 (main, Jul 25 2023, 12:11:09) [Clang 14.0.0 (clang-1400.0.29.202)]
                     platform: macOS-14.0-arm64-arm-64bit
             related packages: typing_extensions-4.8.0
```

**Comment by sydney-runkle** [comment] 2023-11-17 14:33
Hi @aiotter,

Thanks for reporting this. This does look like a bug 🐛. Any interest in opening a PR with a fix?

**Comment by Viicos** [comment] 2024-11-14 17:02
Can't reproduce on latest. However, I would recommend against this pattern. If a property/method is marked as abstract, subclasses should implement it the intended way: as a property, not a (classvar) attribute.

**Closed by Viicos** 2024-11-14 17:02 UTC
Labels: bug V2
