### ISSUE TITLE
Dataclass with generic discriminator field raises error

### ISSUE THREAD

**Issue by sisp** [pydantic/pydantic#4566] opened 2022-09-26 14:16 UTC
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

I've stumbled over a divergence between the standard and `@dataclass`-based Pydantic model when creating a discriminated union where the discriminator field is generic in the base class. It works fine when inheriting from `GenericModel`, but an exception is raised when using the `@dataclass` decorator.

Please find a reproducible example below.

Any idea what is causing this issue and how to make this work? :thinking:

### Example Code

```Python
from typing import Generic, TypeVar, Union

from pydantic import Field, parse_obj_as
from pydantic.dataclasses import dataclass
from pydantic.generics import GenericModel
from typing_extensions import Annotated, Literal


# This test FAILS
def test_dataclass():
    T = TypeVar('T', bound=str)

    @dataclass
    class Pet(Generic[T]):
        pet_type: T
        name: str

    @dataclass
    class Cat(Pet[Literal['cat']]):
        pass

    @dataclass
    class Dog(Pet[Literal['dog']]):
        pass

    CommonPet = Annotated[Union[Cat, Dog], Field(discriminator='pet_type')]

    parse_obj_as(CommonPet, {'pet_type': 'dog', 'name': 'Milou'})


# This test PASSES
def test_genericmodel():
    T = TypeVar('T', bound=str)

    class Pet(GenericModel, Generic[T]):
        pet_type: T
        name: str

    class Cat(Pet[Literal['cat']]):
        pass

    class Dog(Pet[Literal['dog']]):
        pass

    CommonPet = Annotated[Union[Cat, Dog], Field(discriminator='pet_type')]

    parse_obj_as(CommonPet, {'pet_type': 'dog', 'name': 'Milou'})
```

The error for the `@dataclass`-based model is this:

```
Traceback (most recent call last):
  File "$HOME/dev/pydantic/test_issue_4546.py", line 48, in <module>
    test_dataclass()
  File "$HOME/dev/pydantic/test_issue_4546.py", line 28, in test_dataclass
    parse_obj_as(CommonPet, {'pet_type': 'dog', 'name': 'Milou'})
  File "$HOME/dev/pydantic/pydantic/tools.py", line 37, in parse_obj_as
    model_type = _get_parsing_type(type_, type_name=type_name)  # type: ignore[arg-type]
  File "$HOME/dev/pydantic/pydantic/tools.py", line 30, in _get_parsing_type
    return create_model(type_name, __root__=(type_, ...))
  File "$HOME/dev/pydantic/pydantic/main.py", line 1026, in create_model
    return meta(__model_name, resolved_bases, namespace, **kwds)
  File "$HOME/dev/pydantic/pydantic/main.py", line 198, in __new__
    fields[ann_name] = ModelField.infer(
  File "$HOME/dev/pydantic/pydantic/fields.py", line 506, in infer
    return cls(
  File "$HOME/dev/pydantic/pydantic/fields.py", line 436, in __init__
    self.prepare()
  File "$HOME/dev/pydantic/pydantic/fields.py", line 552, in prepare
    self._type_analysis()
  File "$HOME/dev/pydantic/pydantic/fields.py", line 629, in _type_analysis
    self._type_analysis()
  File "$HOME/dev/pydantic/pydantic/fields.py", line 666, in _type_analysis
    self.prepare_discriminated_union_sub_fields()
  File "$HOME/dev/pydantic/pydantic/fields.py", line 780, in prepare_discriminated_union_sub_fields
    alias, discriminator_values = get_discriminator_alias_and_values(t, self.discriminator_key)
  File "$HOME/dev/pydantic/pydantic/utils.py", line 794, in get_discriminator_alias_and_values
    raise ConfigError(f'Field {discriminator_key!r} of model {tp.__name__!r} needs to be a `Literal`')
pydantic.errors.ConfigError: Field 'pet_type' of model 'Cat' needs to be a `Literal`
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.2
       pydantic compiled: False
            install path: $HOME/dev/pydantic/pydantic
          python version: 3.9.13 (main, Sep  2 2022, 22:36:50)  [GCC 9.4.0]
                platform: Linux-5.13.0-48-generic-x86_64-with-glibc2.31
optional deps. installed: ['devtools', 'dotenv', 'email-validator', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [X] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [X] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment] 2022-10-05 09:02
Ye, we don't yet support generic dataclasses. It might be possible in V2, but I won't guarantee it.

Closing as duplicate of #1256.

**Closed by samuelcolvin** 2022-10-05 09:02 UTC
Labels: bug, unconfirmed
