### ISSUE TITLE
Mypy plugin fails with custom model config

### ISSUE THREAD

**Issue by themattmorris** [pydantic/pydantic#5547] opened 2023-04-21 14:15 UTC
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Thanks for all the great work!  Really like the `pydantic.mypy` plugin, but I did experience an issue with it today in something that is admittedly likely more of an edge case.  I want to override the config defaults in `BaseModel`, but then in a child model I update the configuration more and the mypy plugin runs into unexpected behavior:

```
example.py:14: error: The pydantic mypy plugin ran into unexpected behavior: sym_node.node: TypeInfo(
  Name(example.MyModel.Config)
  Bases(builtins.object)
  Mro(example.MyModel.Config, builtins.object)
  Names(
    allow_mutation (builtins.bool))) (of type <class 'mypy.nodes.TypeInfo'>)
Please consider reporting this bug at https://github.com/pydantic/pydantic/issues/new/choose so we can try to fix it!  [pydantic-unexpected]
```

### Example Code

```Python
from pydantic import BaseModel as PydanticBaseModel
from pydantic.config import BaseConfig as PydanticBaseConfig


class BaseConfig(PydanticBaseConfig):
    """Extend `pydantic.config.BaseConfig` to override Config defaults."""
    use_enum_values = True


class BaseModel(PydanticBaseModel):
     Config = BaseConfig  # type: ignore[pydantic-field]


class MyModel(BaseModel):
    foo: str

    class Config:
        allow_mutation = False
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.7
pydantic compiled: True
python version: 3.11.3 | packaged by conda-forge | (main, Apr  6 2023, 08:57:19) [GCC 11.3.0]
platform: Linux-4.18.0-425.19.2.el8_7.x86_64-x86_64-with-glibc2.28
optional deps. installed: ['typing-extensions']


mypy version: `v1.2.0`
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [X] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [X] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by dmontagu** [comment] 2023-07-13 22:43
Considering that we have reworked the mypy plugin a good bit in v2, and I can't reproduce this problem in v2, I'm going to close this as a won't-fix. I would suggest just using a `# type: ignore` for this line if you are still using pydantic v1.

If you run into the same issue with pydantic v2, please let us know and we will try to fix it.

**Closed by dmontagu** 2023-07-13 22:43 UTC
Labels: bug V1, unconfirmed

**Comment by themattmorris** [comment] 2023-07-28 01:39
Makes sense, thanks for the response.  I have some applications that still require v1 and just using `type: ignore` comments for that.
