### ISSUE TITLE
crash with recursive model, TypeAliasType, and discriminated union

### ISSUE THREAD

**Issue by codebutler** [pydantic/pydantic#8897] opened 2024-02-26 18:51 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

code below crashes:
```
Traceback (most recent call last):
  File "/Users/eric/Code/maybern/backend/example.py", line 22, in <module>
    @dataclass(frozen=True, kw_only=True)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eric/Code/maybern/backend/.venv/lib/python3.12/site-packages/pydantic/dataclasses.py", line 241, in create_dataclass
    pydantic_complete = _pydantic_dataclasses.complete_dataclass(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eric/Code/maybern/backend/.venv/lib/python3.12/site-packages/pydantic/_internal/_dataclasses.py", line 164, in complete_dataclass
    schema = gen_schema.clean_schema(schema)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eric/Code/maybern/backend/.venv/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 436, in clean_schema
    schema = _discriminated_union.apply_discriminators(schema)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eric/Code/maybern/backend/.venv/lib/python3.12/site-packages/pydantic/_internal/_discriminated_union.py", line 60, in apply_discriminators
    return simplify_schema_references(_core_utils.walk_core_schema(schema, inner))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eric/Code/maybern/backend/.venv/lib/python3.12/site-packages/pydantic/_internal/_core_utils.py", line 470, in simplify_schema_references
    schema = walk_core_schema(schema, count_refs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eric/Code/maybern/backend/.venv/lib/python3.12/site-packages/pydantic/_internal/_core_utils.py", line 421, in walk_core_schema
    return f(schema.copy(), _dispatch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eric/Code/maybern/backend/.venv/lib/python3.12/site-packages/pydantic/_internal/_core_utils.py", line 466, in count_refs
    recurse(definitions[ref], count_refs)
  File "/Users/eric/Code/maybern/backend/.venv/lib/python3.12/site-packages/pydantic/_internal/_core_utils.py", line 204, in walk
    return f(schema, self._walk)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eric/Code/maybern/backend/.venv/lib/python3.12/site-packages/pydantic/_internal/_core_utils.py", line 454, in count_refs
    return recurse(s, count_refs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eric/Code/maybern/backend/.venv/lib/python3.12/site-packages/pydantic/_internal/_core_utils.py", line 207, in _walk
    schema = self._schema_type_to_method[schema['type']](schema.copy(), f)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eric/Code/maybern/backend/.venv/lib/python3.12/site-packages/pydantic/_internal/_core_utils.py", line 216, in _handle_other_schemas
    schema['schema'] = self.walk(sub_schema, f)  # type: ignore
                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eric/Code/maybern/backend/.venv/lib/python3.12/site-packages/pydantic/_internal/_core_utils.py", line 204, in walk
    return f(schema, self._walk)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eric/Code/maybern/backend/.venv/lib/python3.12/site-packages/pydantic/_internal/_core_utils.py", line 454, in count_refs
    return recurse(s, count_refs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eric/Code/maybern/backend/.venv/lib/python3.12/site-packages/pydantic/_internal/_core_utils.py", line 207, in _walk
    schema = self._schema_type_to_method[schema['type']](schema.copy(), f)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eric/Code/maybern/backend/.venv/lib/python3.12/site-packages/pydantic/_internal/_core_utils.py", line 379, in handle_dataclass_args_schema
    replaced_field['schema'] = self.walk(field['schema'], f)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eric/Code/maybern/backend/.venv/lib/python3.12/site-packages/pydantic/_internal/_core_utils.py", line 204, in walk
    return f(schema, self._walk)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eric/Code/maybern/backend/.venv/lib/python3.12/site-packages/pydantic/_internal/_core_utils.py", line 466, in count_refs
    recurse(definitions[ref], count_refs)
            ~~~~~~~~~~~^^^^^
KeyError: '__main__.MyUnion:4385154336'
```

### Example Code

```Python
from typing import Literal, Annotated, TypeAliasType, Union

import yaml
from pydantic.dataclasses import dataclass
from pydantic.type_adapter import TypeAdapter
from pydantic.types import Discriminator


@dataclass(frozen=True, kw_only=True)
class OptionA:
    type: Literal["a"] = "a"


@dataclass(frozen=True, kw_only=True)
class OptionB:
    type: Literal["b"] = "b"


MyUnion = TypeAliasType("MyUnion", Annotated[Union[OptionA, OptionB], Discriminator("type")])


@dataclass(frozen=True, kw_only=True)
class MyModel:
    value: MyUnion
    children: list["MyModel"]  # no crash if this line is removed


ta = TypeAdapter(MyModel)  # crashes here
s = ta.json_schema()

print(yaml.dump(s))
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.2
        pydantic-core version: 2.16.3
          pydantic-core build: profile=release pgo=true
                 install path: /Users/eric/Code/maybern/backend/.venv/lib/python3.12/site-packages/pydantic
               python version: 3.12.1 (main, Feb  7 2024, 19:42:46) [Clang 16.0.6 ]
                     platform: macOS-14.3.1-arm64-arm-64bit
             related packages: typing_extensions-4.9.0 mypy-1.7.1
                       commit: unknown
```

**Comment by sydney-runkle** [comment] 2024-02-27 14:56
@codebutler,

Thanks for reporting this! Definitely a bug.

**Comment by NeevCohen** [comment] 2024-03-01 13:08
#@sydney-runkle I can pick this up if it's still available. Seems like another issue in `simplify_schema_references`

**Comment by NeevCohen** [comment] 2024-03-21 20:52
I couldn't replicate this issue on my machine on the main branch. @sydney-runkle I'm not sure if a recent commit fixed this issue, could you confirm if this is fixed?

**Comment by sydney-runkle** [comment] 2024-03-25 21:42
@NeevCohen,

Huh, you're right! Looks fixed. Not entirely sure what PR fixed it, but definitely not an issue on main any longer :). Maybe my fix for schema gen on discriminated unions 🤷‍♀️ . Closing as resolved for now :).

**Closed by sydney-runkle** 2024-03-25 21:42 UTC
Labels: bug V2

**Comment by kbaikov** [comment] 2024-04-16 05:49
I can still reproduce the bug with the latest pydantic 2.7.0.

**Comment by jherbel** [comment] 2024-04-22 10:32
@sydney-runkle @NeevCohen 

The bug is still there with pydantic 2.7.0 and pydantic_core 2.18.1:

```python
from collections.abc import Sequence
from pydantic import PlainValidator, BaseModel
from typing import Annotated


class Model1(BaseModel, frozen=True):
    ...


def parse_model1(x: object) -> Model1:
    return Model1()


class Model2(BaseModel, frozen=True):
    model1:  Annotated[Model1, PlainValidator(parse_model1)]


class Model3(BaseModel, frozen=True):
    model2: Sequence[Model2]


class Model4(BaseModel, frozen=True):
    model2: Model2
```

Saving this snippet into a file and executing results in:
```
Traceback (most recent call last):
  File "/home/joerg/tmp/pydantic_key_error.py", line 22, in <module>
    class Model4(BaseModel, frozen=True):
  File "/home/joerg/.pyenv/versions/3.12.1/lib/python3.12/site-packages/pydantic/_internal/_model_construction.py", line 202, in __new__
    complete_model_class(
  File "/home/joerg/.pyenv/versions/3.12.1/lib/python3.12/site-packages/pydantic/_internal/_model_construction.py", line 549, in complete_model_class
    schema = gen_schema.clean_schema(schema)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joerg/.pyenv/versions/3.12.1/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 435, in clean_schema
    schema = simplify_schema_references(schema)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joerg/.pyenv/versions/3.12.1/lib/python3.12/site-packages/pydantic/_internal/_core_utils.py", line 463, in simplify_schema_references
    schema = walk_core_schema(schema, count_refs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joerg/.pyenv/versions/3.12.1/lib/python3.12/site-packages/pydantic/_internal/_core_utils.py", line 414, in walk_core_schema
    return f(schema.copy(), _dispatch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joerg/.pyenv/versions/3.12.1/lib/python3.12/site-packages/pydantic/_internal/_core_utils.py", line 459, in count_refs
    recurse(definitions[ref], count_refs)
  File "/home/joerg/.pyenv/versions/3.12.1/lib/python3.12/site-packages/pydantic/_internal/_core_utils.py", line 197, in walk
    return f(schema, self._walk)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/joerg/.pyenv/versions/3.12.1/lib/python3.12/site-packages/pydantic/_internal/_core_utils.py", line 447, in count_refs
    return recurse(s, count_refs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joerg/.pyenv/versions/3.12.1/lib/python3.12/site-packages/pydantic/_internal/_core_utils.py", line 200, in _walk
    schema = self._schema_type_to_method[schema['type']](schema.copy(), f)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joerg/.pyenv/versions/3.12.1/lib/python3.12/site-packages/pydantic/_internal/_core_utils.py", line 209, in _handle_other_schemas
    schema['schema'] = self.walk(sub_schema, f)  # type: ignore
                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joerg/.pyenv/versions/3.12.1/lib/python3.12/site-packages/pydantic/_internal/_core_utils.py", line 197, in walk
    return f(schema, self._walk)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/joerg/.pyenv/versions/3.12.1/lib/python3.12/site-packages/pydantic/_internal/_core_utils.py", line 447, in count_refs
    return recurse(s, count_refs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joerg/.pyenv/versions/3.12.1/lib/python3.12/site-packages/pydantic/_internal/_core_utils.py", line 200, in _walk
    schema = self._schema_type_to_method[schema['type']](schema.copy(), f)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joerg/.pyenv/versions/3.12.1/lib/python3.12/site-packages/pydantic/_internal/_core_utils.py", line 337, in handle_model_fields_schema
    replaced_field['schema'] = self.walk(v['schema'], f)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joerg/.pyenv/versions/3.12.1/lib/python3.12/site-packages/pydantic/_internal/_core_utils.py", line 197, in walk
    return f(schema, self._walk)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/joerg/.pyenv/versions/3.12.1/lib/python3.12/site-packages/pydantic/_internal/_core_utils.py", line 459, in count_refs
    recurse(definitions[ref], count_refs)
  File "/home/joerg/.pyenv/versions/3.12.1/lib/python3.12/site-packages/pydantic/_internal/_core_utils.py", line 200, in _walk
    schema = self._schema_type_to_method[schema['type']](schema.copy(), f)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joerg/.pyenv/versions/3.12.1/lib/python3.12/site-packages/pydantic/_internal/_core_utils.py", line 209, in _handle_other_schemas
    schema['schema'] = self.walk(sub_schema, f)  # type: ignore
                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joerg/.pyenv/versions/3.12.1/lib/python3.12/site-packages/pydantic/_internal/_core_utils.py", line 197, in walk
    return f(schema, self._walk)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/joerg/.pyenv/versions/3.12.1/lib/python3.12/site-packages/pydantic/_internal/_core_utils.py", line 447, in count_refs
    return recurse(s, count_refs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joerg/.pyenv/versions/3.12.1/lib/python3.12/site-packages/pydantic/_internal/_core_utils.py", line 200, in _walk
    schema = self._schema_type_to_method[schema['type']](schema.copy(), f)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joerg/.pyenv/versions/3.12.1/lib/python3.12/site-packages/pydantic/_internal/_core_utils.py", line 337, in handle_model_fields_schema
    replaced_field['schema'] = self.walk(v['schema'], f)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joerg/.pyenv/versions/3.12.1/lib/python3.12/site-packages/pydantic/_internal/_core_utils.py", line 197, in walk
    return f(schema, self._walk)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/joerg/.pyenv/versions/3.12.1/lib/python3.12/site-packages/pydantic/_internal/_core_utils.py", line 447, in count_refs
    return recurse(s, count_refs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joerg/.pyenv/versions/3.12.1/lib/python3.12/site-packages/pydantic/_internal/_core_utils.py", line 203, in _walk
    schema['serialization'] = self._handle_ser_schemas(ser_schema, f)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joerg/.pyenv/versions/3.12.1/lib/python3.12/site-packages/pydantic/_internal/_core_utils.py", line 215, in _handle_ser_schemas
    ser_schema['schema'] = self.walk(schema, f)  # type: ignore
                           ^^^^^^^^^^^^^^^^^^^^
  File "/home/joerg/.pyenv/versions/3.12.1/lib/python3.12/site-packages/pydantic/_internal/_core_utils.py", line 197, in walk
    return f(schema, self._walk)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/joerg/.pyenv/versions/3.12.1/lib/python3.12/site-packages/pydantic/_internal/_core_utils.py", line 459, in count_refs
    recurse(definitions[ref], count_refs)
            ~~~~~~~~~~~^^^^^
KeyError: '__main__.Model1:106078019119872'
```

**Comment by sydney-runkle** [comment] 2024-04-28 21:29
@jherbel,

Hmm, I'm not able to reproduce the original issue, but I am able to reproduce the one that you just opened. Will definitely look into a fix!

**Comment by dimaqq** [comment] 2024-06-06 08:00
Should this be reopened then?
