### ISSUE TITLE
1.10.7: pytest is failing becauae it uses deprecated `pkg_resources`

### ISSUE THREAD

**Issue by kloczek** [pydantic/pydantic#5497] opened 2023-04-17 00:17 UTC
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Looks like pytest is failing because `pydantic` test suite uses deprecated `pkg_resources`
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-pydantic-1.10.7-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-pydantic-1.10.7-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra -m 'not network' --deselect tests/test_edge_cases.py::test_cython_function_untouched
============================= test session starts ==============================
platform linux -- Python 3.8.16, pytest-7.3.0, pluggy-1.0.0
rootdir: /home/tkloczko/rpmbuild/BUILD/pydantic-1.10.7
configfile: setup.cfg
testpaths: tests
plugins: mock-3.10.0
collected 2421 items / 1 error / 1 deselected / 2420 selected

==================================== ERRORS ====================================
_____________________ ERROR collecting tests/test_utils.py _____________________
tests/test_utils.py:11: in <module>
    from pkg_resources import safe_version
/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:121: in <module>
    warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)
E   DeprecationWarning: pkg_resources is deprecated as an API
=========================== short test summary info ============================
ERROR tests/test_utils.py - DeprecationWarning: pkg_resources is deprecated a...
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
======================== 1 deselected, 1 error in 3.15s ========================
```

### Example Code

```Python
N/A
```

### Python, Pydantic & OS Version

```Text
N/A
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by hramezani** [comment] 2023-04-17 10:50
Thank @kloczek for reporting.
I couldn't reproduce this on my end.
Could you please provide more information?

**Comment by samuelcolvin** [comment] 2023-04-17 11:16
ye `pkg_resources` is deprecated, happy to remove that test from 1.10 branch, it's already removed on `main`.

Weird that you get the warning and we (and CI) don't, maybe you have a newer version of `pkg_resources` with the warning somehow?

**Comment by kloczek** [comment] 2023-04-17 12:33
Cannot find exact commit to test that 🤔

**Comment by samuelcolvin** [comment] 2023-04-17 12:34
no need, I get that we should remove that test, it's that simple.

**Comment by hramezani** [comment] 2023-04-18 08:29
Fixed in https://github.com/pydantic/pydantic/commit/c1b11d1834d64a3eaa7bbe7182cc5bd0cbde55b1

**Closed by hramezani** 2023-04-18 08:29 UTC
Labels: bug V1
