### ISSUE TITLE
from_orm() should detect cycles when loading SQLAlchemy bi-directional relationships rather than blow stack

### ISSUE THREAD

**Issue by dand-oss** [pydantic/pydantic#659] opened 2019-07-14 14:49 UTC
# Bug

For bugs/questions:
* OS: Linux
* Python version `import sys; print(sys.version)`: .6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34)  [GCC 7.3.0]
* Pydantic version `import pydantic; print(pydantic.VERSION)`: 0.30

Where possible please include a self contained code snippet describing your 
bug, question, or where applicable feature request:

```
import sys
from sqlalchemy import (
    Column,
    ForeignKey,
    Integer,
    create_engine
    )
from sqlalchemy.orm import relationship, sessionmaker
from sqlalchemy.ext.declarative import declarative_base
from pydantic import BaseModel
from typing import List

Base = declarative_base()


# SQLA Model
class TableOne(Base):
    __tablename__ = 'table_one'
    # primary key
    one_id = Column(Integer, primary_key=True)
    # list of MANY
    table_many = relationship(
        'TableMany',
        back_populates='table_one')


class TableMany(Base):
    __tablename__ = 'table_many'
    # primary key
    many_id = Column(Integer, primary_key=True)
    # foriegn key
    one_id = Column(Integer, ForeignKey("table_one.one_id"))
    # reference to ONE
    table_one = relationship(
        'TableOne',
        back_populates='table_many'
    )


# pydantic schema reflecting SQLA Model
class t1(BaseModel):
    one_id: int
    # list of children
    table_many: List['tm']

    class Config:
        orm_mode = True


class tm(BaseModel):
    many_id: int
    one_id: int
    # reference to parent
    table_one: t1

    class Config:
        orm_mode = True


def main(argv=None):
    """

    from_orm() goes into infinite recursion
    loading bi-directional SQLA relationships

 File "pydantic/main.py", line 642, in pydantic.main.validate_model
 File "pydantic/fields.py", line 296, in pydantic.fields.Field.validate
 File "pydantic/fields.py", line 429, in pydantic.fields.Field._validate_singleton
 File "pydantic/fields.py", line 436, in pydantic.fields.Field._apply_validators
 File "pydantic/class_validators.py", line 202, in pydantic.class_validators._generic_validator_basic.lambda11
 File "pydantic/main.py", line 452, in pydantic.main.BaseModel.validate
 File "pydantic/main.py", line 373, in pydantic.main.BaseModel.from_orm
 File "pydantic/main.py", line 642, in pydantic.main.validate_model
 File "pydantic/fields.py", line 296, in pydantic.fields.Field.validate
 File "pydantic/fields.py", line 429, in pydantic.fields.Field._validate_singleton
 File "pydantic/fields.py", line 436, in pydantic.fields.Field._apply_validators
 File "pydantic/class_validators.py", line 202, in pydantic.class_validators._generic_validator_basic.lambda11
 RecursionError: maximum recursion depth exceeded while calling a Python object

    """
    if argv is None:
        argv = sys.argv

    db_url = 'put-a-db-here'
    engine = create_engine(db_url, echo=False)
    dbsession = sessionmaker(bind=engine)
    session = dbsession()

    t1.update_forward_refs()
    tm.update_forward_refs()

    qry = session.query(TableOne).first()
    res = None
    if qry:
        res = t1.from_orm(qry)
    print(res)


if __name__ == '__main__':
    sys.exit(main())

```

**Comment by tiangolo** [comment] 2019-07-14 16:03
This would be expected. You are declaring two SQLAlchemy models that reference each other. And then you're declaring 2 Pydantic models that reference each other.

They will just try to generate an infinite tree of models.

You would have to remove one of the circular references.

Another way to think about it is to ask yourself, what would you expect to happen? How would you expect the models to be created?

**Comment by dand-oss** [comment] 2019-07-15 09:26
Some consider **Blowing the stack** to exemplify poor library craftsmanship.

I agree using all memory does inform the library consumer to rewrite his database model limited as a Directed Acyclic Graph.

Alternatively, the **from_orm()** author **could detect cycles** when loading attributes which reference pydantic instances, and thus from_orm() could **handle ANY working db model.**

ex: Detecting cycles in graph traversals
[https://www.geeksforgeeks.org/graph-data-structure-and-algorithms/](https://www.geeksforgeeks.org/graph-data-structure-and-algorithms/)

Then **instead of exploding on take-off** the the API model would have 

1. "table one" instance with a list of "table many" rows instances
2. and each "table many"  instance would have a reference back to "table one" instance

SQLAchemy recommends bidirectional relationships, and indeed loads them into "cyclic" member references.

[https://docs.sqlalchemy.org/en/13/orm/basic_relationships.html](https://docs.sqlalchemy.org/en/13/orm/basic_relationships.html)

> To establish a bidirectional relationship in one-to-many, where the “reverse” side is a many to one, specify an additional relationship() and connect the two using the relationship.back_populates parameter:

[https://docs.sqlalchemy.org/en/13/orm/backref.html](https://docs.sqlalchemy.org/en/13/orm/backref.html)

**Comment by dand-oss** [comment] 2019-07-15 10:02
> Another way to think about it is to ask yourself, what would you expect to happen? How would you expect the models to be created?

You really don't know?

Marshmallow handles the problem correctly out of the box.

Replace the Pydantic model with "model =" then the correct result is printed.

class t1_mm_schema(ModelSchema):
    class Meta:
        model = TableOne

class tm_mm_schema(ModelSchema):
    class Meta:
        model = TableMany

1. "table one" instance with a list of "table many" rows instances
2. and each "table many" instance would have a reference back to "table one" instance

[https://marshmallow-sqlalchemy.readthedocs.io/en/latest/](https://marshmallow-sqlalchemy.readthedocs.io/en/latest/)

They already have a unit test for loading bidirectional relationships in the API

[https://github.com/marshmallow-code/marshmallow-sqlalchemy/blob/dev/tests/test_marshmallow_sqlalchemy.py](https://github.com/marshmallow-code/marshmallow-sqlalchemy/blob/dev/tests/test_marshmallow_sqlalchemy.py)

    class _models(object):
        def __init__(self):
            self.Course = Course
            self.School = School
            self.Student = Student
            self.Teacher = Teacher
            self.SubstituteTeacher = SubstituteTeacher
            self.Paper = Paper
            self.GradedPaper = GradedPaper
            self.Seminar = Seminar
            self.Lecture = Lecture
            self.Keyword = Keyword

**Comment by dmontagu** [comment] 2019-07-15 10:37
> Some consider Blowing the stack to exemplify poor library craftsmanship.

Others consider it a demonstration of a limited understanding of the proper use of a library and its capabilities.

------

> Alternatively, the from_orm() author could detect cycles when loading attributes which reference pydantic instances, and thus from_orm() could handle ANY working db model.

There are a number of problems with this:

1) I'm not aware of any standard way to serialize a cyclic object reference in the context of json objects and/or a json schema. This is a strong indication to me that what you are trying to accomplish is not a task for which pydantic is best suited.

In particular, given pydantic's emphasis on parsing, I think it is probably not a good idea to try to use pydantic to represent an object graph that is not a DAG.

2) In order to detect cyclic references, you'd need to maintain some sort of object graph.

If you look at the current `from_orm` implementation, it essentially just uses getattr to treat the object like a dict for parsing. Pydantic currently does nothing to track an object's identity while parsing.

Implementing relationship-resolution would be a substantial feature to develop, and would likely require tweaks for each additional ORM backend (note that your marshmallow example is specific to sqlalchemy). I would view this as outside the scope of pydantic, though @samuelcolvin may feel differently.

3) In addition to the maintenance burden of this relatively complex feature, it would likely have negative performance implications for the `from_orm` method due to needing to track references when parsing a deeply nested model. The capability to track cyclic references would be a much lower priority for me than performance implications.

4) In general, if you are not parsing and/or serializing data, then pydantic may be the wrong tool. If you are, then how are your cyclic references represented? It seems like you are misinterpreting the scope of pydantic -- `from_orm` is merely intended as a convenience method where appropriate.

-----

> You really don't know...? Perhaps FastAPI works only with toy applications.

What would cyclic references in pydantic help you accomplish with fastapi? It sounds like you don't really understand how pydantic is intended to be used with fastapi. In particular, how would you send an object with a cyclic reference to a fastapi endpoint, or have fastapi serialize it as a response?

If you need additional capabilities, you should probably be using another library to manage your objects away from the API interface. If you are using sqlalchemy, and want cyclic references, why not just keep the objects as sqlalchemy objects?

**Comment by dmontagu** [comment] 2019-07-15 10:45
> Can FastAPI serve their unit test db model without catching fire?

What do you mean by "served"? I don't see anywhere in the file you linked that a model with a cyclic reference is being serialized. Again, it's not even clear how such a model *should* be serialized.

**Comment by tiangolo** [comment] 2019-07-15 23:15
@dand-oss

You are probably requesting a cycle breaking feature.

I can imagine a case where the correct behavior wouldn't be obvious:

A person with a list of items, each item with a list of owners. If the model is serializing the person, and then it serializes the items, for each item, when serializing the owners, should it exclude the original owner from the list but include all the other owners? And make it look for that individual item as if the owner was not an owner? Or should it not include any owner at all, making it look as if the other owners didn't exist?

---

 Pydantic and FastAPI are open source projects, most of us give lots of our free time to support these tools and ideas, for free, just to help others. And you can benefit and even get *profit* from them, for free.

And we stay around here trying to help others the same way.

You are using a very aggressive and derogatory language. It is not appreciated. And it moves your issue/request to the bottom of my priority list.

**Comment by samuelcolvin** [comment] 2019-07-19 13:51
Completely agree with @tiangolo.

I'll be ignore this until someone comes back and provides a constructive approach for solving it.

**Comment by j-walker23** [comment] 2019-11-07 01:59
I wish this guy wasn't a dick, that was very dumb. OSS people literally make my life livable.
Thank you for this library, it is very cool, and I almost can't believe it's a thing in python. You guys are some slick python devs.

Even though this guy was a dipshit, what he's asking for would be a huge help in the sqlalchemy world.

I have a shitty, shitty, shitty, old version of the `Model.dict` for serializing`sqlalchemy` models.
That code has a ton of hacks to get around cyclical issues. And it is so depressing when someone at work using my code runs into a `RecursionError: maximum recursion depth exceeded` and I have to explain i'm too dumb to figure out how to make it never happen again. Especially because on the surface to people, serialization is so simple.

I just learned about pydantic and because of how fuckin amazing it is all around, I went to look how you guys were doing this hard problem.
Sadly (for me) it looks like this isn't a problem you guys have ever needed to solve or I'm sure you would have already. Then I could once again, benefit from the OSS community.

Anyway, I only wrote this because I can add a little info on how to do it if it ever becomes a priority in pydantic.

The native python `deepcopy` can handle this by memorizing types. I haven't figured out how exactly, but that would probably help.

**Comment by dmontagu** [comment] 2019-11-07 02:59
@j-walker23 thanks for the positive feedback.

I think it should be possible to write a model for which `from_orm` won't cause recursion errors, you just have to manually override the `from_orm` method.

This may not be able to handle all cases (e.g., if you have variable length cycles), but I think the vast majority of cases where this would be helpful involve a cycle of length 2 (a basic relationship), and that *could* be handled inside `from_orm`.

(In v1.0 there is even some added functionality to make it easier to override the `from_orm` method -- namely, the ability to use a custom `GetterDict` -- but I'm not sure whether it would be useful for this.)

However, even if *loading* the model didn't cause recursion errors, you'd still run into recursion errors when you tried to convert it to a dict (or json). That could also be addressed through method overriding though, just with different methods involved (probably `.dict` would be enough).

-----

At the end of the day, the logic and apis necessary to handle cycles during loading (i.e., `from_orm`) and serialization would likely require adding substantial overhead (not to mention complexity). Given 1) how infrequent a request this is, and 2) the fact that this use case can be handled now through method overrides, I don't think this currently merits additional feature work.

That said, if anyone really cares about this and wants to push for better handling of cyclic references (*especially* if you can provide a desired implementation), I think it might be best to just create a new issue.

**Comment by j-walker23** [comment] 2019-11-07 04:16
Thanks for the response.

That totally makes sense. I haven't noticed ever needing this outside of
ORM's, and I would use pydantic for a million other things outside of the
ORM and it will work perfectly.

It's not super important, but I didn't understand the part about `cycles`.
Was that your way of saying the memorization techniques of `deepcopy`
wouldn't work, or were you just referencing what was talked about earlier
in this issue?

If I ever do figure this out for myself, I'll definitely post something
about it.

Thanks again.

**Comment by tomthorogood** [comment] 2019-12-19 13:48
Could this be solved by allowing `from_orm` to accept an `exclude` in the same format as with the `BaseModel.json()` and `BaseModel.dict()` methods?

Example, using sqlalchemy orm:

```python

class Foo(BaseModel):
    bar: 'Bar'
    id: int


class FooORM(StorageModel):
   bar_id = Column(ForeignKey('BarORM.id'))
   bar = relationship('BarORM')


class Bar(BaseModel):
  foo: Foo
  id: int

class BarORM(StorageModel):
    foo_id = Column(ForeignKey('FooORM.id'))
    foo = relationship('FooORM')

# . . .

foo = Foo.from_orm(foo_orm, exclude={'bar': {'foo'}})
```

**Comment by samuelcolvin** [comment] 2019-12-19 13:52
`exclude` on `from_orm` would be fine by me, but I think it's more of a work around than an actual fix.

**Comment by tomthorogood** [comment] 2019-12-19 16:45
The more I think about it, the less I like the proposal, and agree with @dmontagu that it really seems out of scope  for pydantic.

My intent on using something like this was to have all the  context for a particular record, including all of its relationships' context, and . . . well, at some point i'm just returning the entire database. 

That seems....unwise.

**Comment by richard-to** [comment] 2019-12-29 00:53
I just ran into this problem. Here's my current workaround:

```
from __future__ import annotations

from pydantic import BaseModel

class ModelAChild(BaseModel):
    id: int

    class Config:
        orm_mode = True

class ModelA(ModelAChild):
    id: int
    model_b: ModelBChild

class ModelBChild(BaseModel):
    id: int

    class Config:
        orm_mode = True

class ModelB(ModelBChild):
    id: int
    model_a: ModelAChild

ModelA.update_forward_refs()
```

**Comment by shizidushu** [comment] 2020-04-13 14:20
@richard-to Thanks for your demo code. And my workaround for many to many relationship based on yours:

```
from __future__ import annotations
from typing import ForwardRef, List
from pydantic import BaseModel

ListRole = ForwardRef('List[RoleAlone]')

class UserAlone(BaseModel):
    id: int = None
    name: str

    class Config:
        orm_mode = True

class User(UserAlone):
    roles: ListRole = []

class RoleAlone(BaseModel):
    id: int = None
    name: str

    class Config:
        orm_mode = True

User.update_forward_refs()

class Role(RoleAlone):
    users: List[UserAlone]
```

**Comment by gemerden** [comment] 2020-06-22 11:43
I have a (tried and tested) solution that might or might not be applicable here, but it did solve the cyclic json problem for me, but it also requires some identifier to be stored in the json. It looks (simplified) like this:
```python
import json
from datetime import datetime, date

class Jsonifiable(object):
    
    # some standard conversions
    json_encoders = {
        datetime: str,
        date: str,
        # ....
    }
    

    @classmethod
    def get_type(cls, attr_name):
        return "the type of the attr, from pydantic model, descriptor, dataclass"

    @classmethod
    def from_json_dict(cls, json_dict, _reg=None, _get_id=lambda js: js['id']):
        """ _reg keeps al the id's already seen """
        _reg = _reg or {}
        id_ = _get_id(json_dict)
        if id_ in _reg:  # already seen: stop recursion
            return _reg[id_]  # return already seen and parsed

        kwargs = {}
        for name, js_value in json_dict.items():
            attr_type = cls.get_type(name)
            try:  # could also check the type, do hasattr(...)
                kwargs[name] = attr_type.from_json(js_value, _reg, _get_id)  # pass _reg
            except AttributeError:
                try:
                    kwargs[name] = attr_type(js_value)
                except (TypeError, ValueError):
                    kwargs[name] = js_value

        # kwargs can still be validated in constructor
        obj = cls(**kwargs)
        _reg[id_] = obj
        return obj
    
    @classmethod
    def from_json(cls, js):
        return cls.from_json_dict(json.loads(js))

    def __init__(self, **kwargs):
        for name, value in kwargs.items():
            setattr(self, name, value)
            
    def to_json_dict(self, _reg=None, _get_id=id):
        _reg = _reg or set()
        id_ = _get_id(self)
        if id_ in _reg:  # already encoded
            return {'id': id_}  # return a json_dict with only id; stops recursion
        _reg.add(_get_id(self))
        
        json_dict = {'id': id_}  # make json recognizable for parsing!
        for name, value in self.__dict__.items():
            try:
                json_dict[name] = value.to_json(_reg, _get_id)
            except AttributeError:
                self.json_encoders[type(value)](value)
                
        return json_dict
    
    def to_json(self):
        return json.dumps(self.to_json_dict())
```

I think storing the identifier in the json is inevitable, if you want to be able to restore the cyclic datastructure.

**Comment by t94j0** [comment] 2020-06-22 17:43
Not to +1 this issue, but I'm running into this also. @richard-to 's workaround works fine, but it's pretty ugly. To @dand-oss 's point, this should absolutely be fixed in the ORM instead of blowing the stack when a self-reference happens.

**Comment by gulfpearl** [comment] 2020-07-28 20:03
+1 on not blowing the stack when a self-reference happens. A Marshmallow like solution would be great.

**Comment by MasterBiryer** [comment] 2020-09-04 15:01
I am late to this debate and my understanding of the internals of `from_orm` are low, so please, bare with me.

My understanding of the problem is that ORM (and data modelling in general) easily accommodate(s) bi-directionnal relationships whereas pydantic cannot cope with it.
This is unfortunate because bi-directional relationships in very convenient during development.

Mathematics tell us there is not solution to that problem as it is impossible to map a cyclic graph to a tree.
So, if we want to come up with something, we have to accept to make some trade-offs.

The current state is not very clean (as @dand-oss correctly pointed out (but, indeed, not kindly)): letting Python manage the error at low level through infinite loop detection is not very kind to developers who love the pydantic library as I do.

So the very first trade-off we could make would be to send a more civilised error message, related to the discovery of the cycle in the model.

But then, the second level trade-off would not be very far away: upon discovering the cycle, a simple behaviour would just be to silently return with no error.

I admit this is where my low understand of `from_orm` hurts as I have no idea of why pydantic requires to traverse the model, thereby blowing up the stack.

Please let me know why pydantic insists on fully traversing the model: I may contribute to a solution.

Thank you.

**Comment by maitham** [comment] 2021-02-26 14:27
> I have a (tried and tested) solution that might or might not be applicable here, but it did solve the cyclic json problem for me, but it also requires some identifier to be stored in the json. It looks (simplified) like this:

How are you using this in your schemas?

**Comment by maitham** [comment] 2021-02-26 14:44
What's the best way to avoid this currently, I have two tables with a many to many relationship and I'm struggling to get any of the workarounds to work. 


```
from typing import List, Any, Optional
from uuid import UUID

from pydantic import BaseModel
from app.utils.encoders import Jsonifiable

class TeamBase(BaseModel):
    name: str
    description: Optional[str]



# Properties to receive on item creation
class TeamCreate(TeamBase):
    name: str


# Properties to receive on item update
class TeamUpdate(TeamBase):
    pass


# Properties shared by models stored in DB
class TeamInDBBase(TeamBase):
    id: UUID
    name: str
    members: List[Any] = []
    users: List[Any] = []
    
    class Config:
        orm_mode = True

TeamInDBBase.update_forward_refs()

# Properties to return to client
class Team(TeamInDBBase):
    pass


# Properties properties stored in DB
class TeamInDB(TeamInDBBase):
    pass


```

```
from typing import List, Any
from uuid import UUID

from pydantic import BaseModel

class MemberBase(BaseModel): 
    name: str
    email: str
    auth0_id: str
    avatar: str


# Properties to receive on item creation
class MemberCreate(MemberBase):
    pass


# Properties to receive on item update
class MemberUpdate(MemberBase):
    pass


# Properties shared by models stored in DB
class MemberInDBBase(MemberBase):
    id: UUID
    class Config:
        orm_mode = True



# Properties to return to client
class Member(MemberInDBBase):
    pass


# Properties properties stored in DB
class MemberInDB(MemberInDBBase):
    pass


```

**Comment by sbadisa** [comment] 2021-03-13 07:35
> What's the best way to avoid this currently, I have two tables with a many to many relationship and I'm struggling to get any of the workarounds to work. 
> 
> 
> 
> 
> 
> ```
> 
> from typing import List, Any, Optional
> 
> from uuid import UUID
> 
> 
> 
> from pydantic import BaseModel
> 
> from app.utils.encoders import Jsonifiable
> 
> 
> 
> class TeamBase(BaseModel):
> 
>     name: str
> 
>     description: Optional[str]
> 
> 
> 
> 
> 
> 
> 
> # Properties to receive on item creation
> 
> class TeamCreate(TeamBase):
> 
>     name: str
> 
> 
> 
> 
> 
> # Properties to receive on item update
> 
> class TeamUpdate(TeamBase):
> 
>     pass
> 
> 
> 
> 
> 
> # Properties shared by models stored in DB
> 
> class TeamInDBBase(TeamBase):
> 
>     id: UUID
> 
>     name: str
> 
>     members: List[Any] = []
> 
>     users: List[Any] = []
> 
>     
> 
>     class Config:
> 
>         orm_mode = True
> 
> 
> 
> TeamInDBBase.update_forward_refs()
> 
> 
> 
> # Properties to return to client
> 
> class Team(TeamInDBBase):
> 
>     pass
> 
> 
> 
> 
> 
> # Properties properties stored in DB
> 
> class TeamInDB(TeamInDBBase):
> 
>     pass
> 
> 
> 
> 
> 
> ```
> 
> 
> 
> ```
> 
> from typing import List, Any
> 
> from uuid import UUID
> 
> 
> 
> from pydantic import BaseModel
> 
> 
> 
> class MemberBase(BaseModel): 
> 
>     name: str
> 
>     email: str
> 
>     auth0_id: str
> 
>     avatar: str
> 
> 
> 
> 
> 
> # Properties to receive on item creation
> 
> class MemberCreate(MemberBase):
> 
>     pass
> 
> 
> 
> 
> 
> # Properties to receive on item update
> 
> class MemberUpdate(MemberBase):
> 
>     pass
> 
> 
> 
> 
> 
> # Properties shared by models stored in DB
> 
> class MemberInDBBase(MemberBase):
> 
>     id: UUID
> 
>     class Config:
> 
>         orm_mode = True
> 
> 
> 
> 
> 
> 
> 
> # Properties to return to client
> 
> class Member(MemberInDBBase):
> 
>     pass
> 
> 
> 
> 
> 
> # Properties properties stored in DB
> 
> class MemberInDB(MemberInDBBase):
> 
>     pass
> 
> 
> 
> 
> 
> ```
> 
> 
> 
> I still get the recursion error with the above code. 
> 
> 

Hi, how did you find a solution to this?

**Comment by gemerden** [comment] 2021-03-14 10:44
@maitham Sorry about getting back this late, i did test the above code and then changed it for this discussion (and introduced bugs). Sorry about that. Fixed what i saw, but no guarantees, the method is valid though.

**Comment by x0y-gt** [comment] 2021-12-06 13:37
I have the same issue here 0/

Maybe it can help if we can limit how depth to go in the model?, something like: from_orm(max_levels=2)

**Comment by SmokinCaterpillar** [comment] 2022-01-11 08:14
We run into a similar problem. Let's say we do not want to load any relations at all, would

`model = PydanticClass(**orm.__dict__.copy())` instead of `model = PydanticClass.from_orm(orm)` 

work, or am I missing something important here?

**Comment by lovetoburnswhen** [comment] 2022-03-02 20:52
> We run into a similar problem. Let's say we do not want to load any relations at all, would
> 
> `model = PydanticClass(**orm.__dict__.copy())` instead of `model = PydanticClass.from_orm(orm)`
> 
> work, or am I missing something important here?

I don't believe that would convert nested models

**Comment by ValentinK84** [comment] 2022-04-14 18:35
Isn't this the answer you are looking for?

https://stackoverflow.com/questions/63420889/fastapi-pydantic-circular-references-in-separate-files

**Comment by samuelcolvin** [comment] 2022-06-29 15:39
This is fixed in pydantic-core, recursion cycles will be safely caught and raised in pydantic v2.

See https://github.com/samuelcolvin/pydantic-core/pull/134.

**Comment by dmontagu** [comment] 2023-05-17 20:58
Closing given this is resolved in v2. If anyone runs into new issues with this in v2 please request this issue get reopened, or better yet, open a new issue for it.

**Closed by dmontagu** 2023-05-17 20:58 UTC
Labels: feature request, help wanted
