### ISSUE TITLE
inability to create complex models dynamically

### ISSUE THREAD

**Issue by xlotlu** [pydantic/pydantic#1493] opened 2020-05-08 18:16 UTC
# Feature Request

```
             pydantic version: 1.5.1
```

This is somewhere between a feature request and a bug report.

A result of pydantic's embrace of annotations is that (unlike others that came before it) the field data-type is separated from the field "metadata". In practice `FieldInfo` is data-type agnostic, and it needs to jump through a few hoops until it turns into a proper `ModelField`.

A side-effect is that currently, dynamic model creation is a second-class citizen, simply because one cannot provide both the type and the extra-info. What works is what I've documented in #1492, where, in fact I have cheated -- for using `Field()` as an argument works only when providing a default value (which allows the type to be inferred).

The straightforward way would be to allow calling `create_model(name, field_name=(type, Field())` -- this would add no cognitive overhead to the API user, and would be totally compatible with what already happens in the background. It's an easy fix, and I'd like to volunteer to make this my first contribution to the project.

However, I stepped into the code intent on asking to allow `FieldInfo` to take a type argument. Which is probably a bad idea as things stand now (more on that immediately), but I think it makes sense for `create_model()` to receive `ModelField`s as arguments. This would also provide an easy solution to #830.

Related to `FieldInfo` supporting type, at first contact I was somewhat fazed by the differentiation between "types" "and fields". The thing is, the current architecture shows it to be rather cumbersome as well. Take for example `schema._field_constraints` which ended up as possible `FieldInfo` kwargs, although they only make sense in the context of very specific types.

Take this with a grain of salt, as I am new to the code and haven't considered all implications, but I think it would make sense to somehow converge types and fields. "Passing arguments" to types has a precedent already in the `Constrained*` types and their factory functions.

In the older tools, the solution was obvious as there was only one way to go about it:

```python
class MyModel:
    my_field = TypeXField(default=value, type_specific_constraint=..., validators=[...])
```
Now with the advent of types moved away from the field declaration, there's this undecidedness about what belongs where. I for one would consider the default as belonging with the type definition, but pydantic's beauty consists precisely in keeping it on the other side of the equal sign. I find type constraints and validators definitely belonging with the "type", while "metadata" such as alias and title belonging elsewhere.

So, I don't have a solution, but I hope an account of my first impressions will prove useful.

**Comment by samuelcolvin** [comment] 2020-05-18 12:09
I get where you're coming from. I agree that putting information about fields on both sides of the equals sign complicates things.

The problem is:

you can't put everything in the type definitions since functions as type hints (e.g. `foobar: conint(gt=4)`) is [specifically advised against](https://www.python.org/dev/peps/pep-0484/#acceptable-type-hints) by PEP484:

> Annotations should be kept simple or static analysis tools may not be able to interpret the values. For example, dynamically computed types are unlikely to be understood. (This is an intentionally somewhat vague requirement, specific inclusions and exclusions may be added to future versions of this PEP as warranted by the discussion.)

As a result pyflakes thinks it's an error and mypy will have a fit.

You also can't put all information about a type in the initial value as that just gets you back to every other validation library and ignores type hints.

---

At a high level, I don't see a better approach than what we're doing now until python's syntax is changed to allow more information in a type hint. (this might be never)

---

If there are specific fixes you suggest on `create_model` in pydantics internals, please be specific with examples and I'll judge whether I think they're a good idea.

**Comment by samuelcolvin** [comment] 2023-04-25 18:18
This is fixed by pydantic-core and pydantic core schema.

**Closed by samuelcolvin** 2023-04-25 18:18 UTC
Labels: feature request
