### ISSUE TITLE
Unexpected behaviour for a model initialization

### ISSUE THREAD

**Issue by more-suo** [pydantic/pydantic#9230] opened 2024-04-12 17:10 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

We are having a strange behaviour while passing a class instance for `Portfolio`, which is inherited from a `BaseModel` class called `Node`. We pass an instance of this class in a list (the list has one element -- only the instance itself) to a `RootModel` class `Portfolios` like that: `Portfolios(root=[portfolio])`, where `portfolio` is an instance of the `Portfolio` class.  We receive the following exception:

```
pydantic_core._pydantic_core.ValidationError: 1 validation error for Portfolios
0
  Input should be a valid dictionary or instance of Portfolio [type=model_type, input_value=Portfolio(id=1, parent_id...rent_description='root'), input_type=Portfolio]
    For further information visit https://errors.pydantic.dev/2.6/v/model_type
```

The "fun" thing about it is, that there're some very similiar (syntactically and structurally) classes, which look almost the same like the `Portfolio` and `Portfolios` classes. E.g., `Counterparty`, which is also inherited from `Node` and `Counterparties`, which is also a `RootModel`, but only with differently called fields. There, the initialization of the `RootModel` class works perfectly fine. 

Also if you run the example code in a separate file and put everything together it seems to work. So what is the reason, why we cannot run as it's been used in the project? 

### Example Code

```Python
# projectname/foldername/nodemodel/node.py
class Node(BaseModel):
    id: int


# projectname/foldername/portfoliomodel/portfolio.py
class Portfolio(Node):
    parent_id: int = 0
    parent_description: str = "root"


class Portfolios(RootModel):
    root: List[Portfolio]
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.3
        pydantic-core version: 2.16.3
          pydantic-core build: profile=release pgo=true
                 install path: /home/more_suo/.cache/pypoetry/virtualenvs/yarimato2-roniKljy-py3.11/lib/python3.11/site-packages/pydantic
               python version: 3.11.8 (main, Feb 25 2024, 16:41:26) [GCC 9.4.0]
                     platform: Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
             related packages: typing_extensions-4.10.0 mypy-1.9.0 fastapi-0.110.0 pydantic-settings-2.2.1
                       commit: unknown
```

**Comment by Viicos** [comment] 2024-04-15 20:25
I'm not able to reproduce, could you please provide a MRE, with each model defined in some separate files?

**Comment by sydney-runkle** [comment] 2024-06-13 02:42
Closing for now. Happy to reopen if we get an MRE!

**Closed by sydney-runkle** 2024-06-13 02:42 UTC
Labels: bug V2, pending
