### ISSUE TITLE
BaseModel subclasses silently ignore properties named `model_config`

### ISSUE THREAD

**Issue by melembroucarlitos** [pydantic/pydantic#8840] opened 2024-02-16 22:23 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

It seems that pydantic uses the `model_config` property to keep track of some internal states. However, when one tries to set a property called `model_config` instead of throwing up an error or warning, it silently skips it. Ideally, it should output a warning of some kind seeing how the name `model_config` is a natural variable name in domains such as machine learning.

### Example Code

```Python
from pydantic import BaseModel

class Foo(BaseModel):
    foo: int

class Bar(BaseModel):
    model_config: Foo
    foo: Foo
    bar: int

foo = Foo(foo=12)
bar = Bar(model_config=foo, foo=foo, bar=13)

assert bar.foo == foo
assert bar.model_config == foo
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.1
        pydantic-core version: 2.16.2
          pydantic-core build: profile=release pgo=true
                 install path: /home/lucas/.local/lib/python3.10/site-packages/pydantic
               python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
                     platform: Linux-6.5.0-17-generic-x86_64-with-glibc2.35
             related packages: typing_extensions-4.9.0 mypy-1.8.0
                       commit: unknown
```

**Comment by sydney-runkle** [comment] 2024-02-18 15:23
@melembroucarlitos,

Thanks for reporting this.

Closing this as a duplicate of https://github.com/pydantic/pydantic/issues/8469, but I've added that issue to the 2.7.0 milestone, as this should be relatively easy to come up with a fix for, and it's certainly a request that many people have!

**Closed by sydney-runkle** 2024-02-18 15:23 UTC
Labels: duplicate, Change
