### ISSUE TITLE
Pydantic: Validation error when having a dataclass inside another dataclass

### ISSUE THREAD

**Issue by PepeLoperenaaa** [pydantic/pydantic#8058] opened 2023-11-08 14:43 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I am trying to solve an issue which is the following: 

I have a dataclass within another dataclass: 

```python
@dataclass(frozen=True)
class Location:
    longitude: float  
    latitude: float 
```
Location is also added into the following dataclass:
```python
@dataclass(frozen=True)
class Address:
    original_address: str
    accuracy: Accuracy
    **location: Location**
```
When creating an instance of the object address on another class (in this case I am doing it on a test case file) a warning appears: `Unexpected Argument`

This is how the setup looks: 

```python
 address = Address(
            original_address="text", 
            accuracy=Accuracy.ROOFTOP, 
            location=Location(latitude=90.0, longitude=180.0)
 )
```

When running the following test: 

```python
    def test_when_location_is_not_in_range_then_print_exception(self):
        invalid_location = Location(latitude=200.0, longitude=300.0)

        with self.assertRaises(ValueError) as context:
            address = Address(
                original_address="test",
                accuracy=Accuracy.ROOFTOP,
                location=invalid_location,
            )

        self.assertEqual(
            str(context.exception), "Location is out of range", "Expected exception message: 'Location is out of range'"
        )
```
I encounter the following error: 

```python
Input should be a dictionary or an instance of Location [type=dataclass_type, input_value=Location(longitude=180.0, latitude=90.0), input_type=Location]
```
I have done several tests around this and I still do not know how to solve it. One of the tests was done by doing the instance of the object in the same file and if it was done there everything seems to work. It is only when I do the instance on a different file that the error stated on top appears. 

If by  any chance you want to see the investigation done before, please follow this [link](https://stackoverflow.com/questions/77438553/pydantic-validation-error-input-should-be-a-valid-dictionary-or-instance)

### Python, Pydantic & OS Version

```Text
Python 3.11.5 Pydantic v2.4
```

**Comment by dmontagu** [comment] 2023-11-08 20:18
Could you provide a self-contained example script we can run that produces your problem? I am not able to reproduce the issue you are describing.

I noticed in your stackoverflow link near the bottom of your issue it had:
```python
from pydantic import BaseModel, Field
from pydantic.dataclasses import dataclass

@dataclass(frozen=True)
class Location(BaseModel):
    longitude: float = Field(None, ge=-180, le=180)
    latitude: float = Field(None, ge=-90, le=90)


Location(longitude=1.0, latitude=1.0)
```

You should not decorate a pydantic `BaseModel` subclass as a `dataclass` (pydantic or otherwise), this will almost certainly lead to other misbehavior that we probably can't easily produce a good warning for, at least for the non-pydantic `dataclass` decorator.

(Combining the dataclass and BaseModel decorators was the only way I was able to reproduce the misbehavior you described.)

**Comment by sydney-runkle** [comment] 2023-11-10 14:02
Closing this for now until we get a MRE. I'm more than happy to help once we do 👍!

**Closed by sydney-runkle** 2023-11-10 14:02 UTC
Labels: bug V2, pending, awaiting author response
