### ISSUE TITLE
Package description exceeds maximum length in Azure DevOps

### ISSUE THREAD

**Issue by thasler** [pydantic/pydantic#8103] opened 2023-11-14 09:04 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

We have a custom PyPI feed on Azure DevOps and have issues with downloading pydantic from it.

As the description contains the ever growing changelog, its size reaches a limit in Azure DevOps:
`HTTP error 400 Client Error: Bad Request - The package description exceeds the maximum length of 324608 bytes.`

**To Reproduce**
Create an Azure DevOps feed and try to download pydantic>=2.5 package from it.

I suggest to only include the changes of the corresponding version of the package, and linking to the homepage for the rest.

### Python, Pydantic & OS Version

```Text
pydantic 2.5.0
```

**Comment by hramezani** [comment] 2023-11-14 09:19
Thanks @thasler for reporting this.

Duplicate of https://github.com/pydantic/pydantic/issues/8096

Fixed in https://github.com/pydantic/pydantic/pull/8097

It will be included in the next patch release

**Closed by hramezani** 2023-11-14 09:19 UTC
Labels: bug V2, pending
