### ISSUE TITLE
Problem inheriting from frozen native dataclass in some cases

### ISSUE THREAD

**Issue by andriusbalcikonis** [pydantic/pydantic#4511] opened 2022-09-12 06:57 UTC
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Getting `TypeError: cannot inherit non-frozen dataclass from a frozen one` when trying to dynamically create pydantic dataclass from native dataclass, which is marked as frozen.

Note: Issue does not happen in any situation - for example, if class B did not have method `abc`, problem does not happen.

Related to: https://github.com/pydantic/pydantic/pull/2557

### Example Code

```Python
from dataclasses import dataclass

from pydantic.dataclasses import dataclass as pydantic_dataclass


@dataclass(frozen=True)
class A:
    field: int

@dataclass(frozen=True)
class B(A):
    field2: int

    def abc(self) -> None:
        pass

item = B(field=1, field2=2)

pydantic_dataclass(type(item))
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.2
pydantic compiled: True
install path: /Users/(...)/.env/lib/python3.10/site-packages/pydantic
python version: 3.10.5 (v3.10.5:f377153967, Jun  6 2022, 12:36:10) [Clang 13.0.0 (clang-1300.0.29.30)]
platform: macOS-12.5-arm64-arm-64bit
optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [X] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by hramezani** [comment] 2022-09-12 08:48
I think this is a duplicate of https://github.com/pydantic/pydantic/issues/4498

**Closed** 2022-09-12 08:57 UTC
Labels: bug, duplicate, unconfirmed
