### ISSUE TITLE
Partial validation for models

### ISSUE THREAD

**Issue by wsdev-co** [pydantic/pydantic#5031] opened 2023-02-09 12:06 UTC
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this feature is missing

### Description

Extremely important (classmethod) feature for pydantic model is `partial validation`. It's required by a lot of database operations. Currently I'm using a function which validates the data partially, but it's not optimized & professionally developed, because, I'm a ecosystem dev and I don't have a time to develop it as pro as you. Hence I would request this professionally developed feature by owners.

By the way, I found some 3rd part lib which written in documentation it does partial validation, but in reality it does not work `complex` models. https://pypi.org/project/pydantic-partial/

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [X] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by l-rossetti** [comment] 2023-02-09 15:24
We are interested in the same feature. We ended up with the following custom implementation:

```python
from pydantic import BaseModel, validator

# Returns a new model class which is a copy of the input one
# having all inner fields and subfields as Optional
def make_optional(cls):
    for field in cls.__fields__.values():
        field.required = False
        if hasattr(field.type_, '__base__') and issubclass(field.type_.__base__, BaseModel):
            field.type_ = make_optional(field.type_)

    return cls


class Fuel(BaseModel):
    name: str

class Engine(BaseModel):
    type: str
    fuel: Fuel

class Wheel(BaseModel):
    id: int
    @validator('id')
    def check_id(cls, v):
        if v <= 0:
            raise ValueError('ID must be greater than 0')
        return v

class Car(BaseModel):
    name: str
    wheels: list[Wheel]
    engine: Engine

# 1. Create a standard Car
car1 = Car(name="Ferrari", engine=Engine(type="V12", fuel=Fuel(name="Petrol")), wheels=[{"id": 1}, {"id": 2}, {"id": 3}, {"id": 4}])
print(car1)
# name='Ferrari' wheels=[Wheel(id=1), Wheel(id=2), Wheel(id=3), Wheel(id=4)] engine=Engine(type='V12', fuel=Fuel(name='Petrol'))

# 2. Create a CarOptional model having Optional fields also in nested objects (e.g. Fuel.name becomes Optional as well)
CarOptional = make_optional(Car)
car_opt = CarOptional(engine=Engine(type="V12", fuel=Fuel()), wheels=[{"id": 1}, {"id": 2}, {"id": 3}, {"id": 4}])
print(car_opt)
# name=None wheels=[Wheel(id=1), Wheel(id=2), Wheel(id=3), Wheel(id=4)] engine=Engine(type='V12', fuel=Fuel(name=None))

# 3. Validators are still executed for fields with a value (e.g. Wheel.id = 0)
# car_not_valid = CarOptional(engine=Engine(type="V12", fuel=Fuel()), wheels=[{"id": 0}, {"id": 2}, {"id": 3}, {"id": 4}])
# pydantic.error_wrappers.ValidationError: 1 validation error for Car
# wheels -> 0 -> id
#  ID must be greater than 0 (type=value_error)

# 4. Should raise a validation error but it seems that Car model was modified following CarOptional
car2 = Car(engine=Engine(type="V12", fuel=Fuel(name="Petrol")))
print(car2)
# name: None=None wheels=None engine=Engine(type='V12', fuel=Fuel(name='Petrol'))
```

We tried also using the `pydantic_partial` library but the recursive method for complex objects (e.g. our example code) doesn't work.

We feel like we have to create a new model (e.,g. via `create_model`) instead of modifying the original `cls` in `make_optional() `function, but every attempt we make doesn't work (e.g. we get `RuntimeError: no validator found for <class 'pydantic.fields.ModelField'>, see 'arbitrary_types_allowed' in Config`)

How can I make it work?
**Requirements**:
- make_optional must transform also nested objects as in the example code
- validators must be executed when a value is provided for that validator
- the original model (Car in the example) must not be modified

We tried with the above implementation of make_optional but if you have any other more elegant solution, feel free to suggest it, please.

**Comment by wsdev-co** [comment] 2023-02-11 19:46
You can use this static function as temporarily solution:

def as_optional(cls: Type[BaseModel]) -> Type[BaseModel]:
	"""
	@param cls: Subclass of BaseModel
	@attention: Nested sub-models are not supported, means,
	they will be inspected as is.

	@return: Model which all fields are made optional
	"""

	# create empty pydantic class which
	# does not belong to any model
	class __EmptyModel(BaseModel):
		...

	# make deep-copy of input class and assign them into "__EmptyModel" class
	__EmptyModel.__fields__ = copy.deepcopy(cls.__fields__)

	# now make all field optional of new empty class
	for field in __EmptyModel.__fields__.values():
		field.required = False

	# copy all configuration from input class.
	# note: cls.__config__ supports both inner class config ("class Config: ...") and
	# subclass initialization || class kwarg (class Model(BaseModel, ...=...)).
	__EmptyModel.__config__ = copy.deepcopy(cls.__config__)

	# return newly configured model class
	return __EmptyModel

**Comment by wsdev-co** [comment] 2023-02-11 19:48
You can use this static function as temporary solution:

import copy
from typing import Type

from pydantic import BaseModel


def as_optional(cls: Type[BaseModel]) -> Type[BaseModel]:
	"""
	@param cls: Subclass of BaseModel
	@attention: Nested sub-models are not supported, means,
	they will be inspected as is.

	@return: Model which all fields are made optional
	"""

	# create empty pydantic class which
	# does not belong to any model
	class __EmptyModel(BaseModel):
		...

	# make deep-copy of input class and assign them into "__EmptyModel" class
	__EmptyModel.__fields__ = copy.deepcopy(cls.__fields__)

	# now make all field optional of new empty class
	for field in __EmptyModel.__fields__.values():
		field.required = False

	# copy all configuration from input class.
	# note: cls.__config__ supports both inner class config ("class Config: ...") and
	# subclass initialization || class kwarg (class Model(BaseModel, ...=...)).
	__EmptyModel.__config__ = copy.deepcopy(cls.__config__)

	# return newly configured model class
	return __EmptyModel

**Comment by dmontagu** [comment] 2023-02-11 20:26
I could see an argument for adding something analogous to typescript's `Partial` class, so `Partial[MyModel]` would be treated by pydantic in the same way as `MyModel` except all fields would be made optional with default `None`. I think that would have to be a feature request for after the v2 release though.

I think making it work in a recursive way would likely require defining a new version of the model that applies the "Partial" operator everywhere appropriate, then validating against that.

My suggestion for working with this until we _can_ get to it would be to define a parallel version of the type with everything optional as desired.

**Comment by samuelcolvin** [comment] 2023-02-12 10:21
There are other issues requesting this, I'm not sure which is most complete, but we should try to stick to one issue.

I'll look for the best one when I'm at my laptop.

The short answer is I'd like the solution to be type safe which has precluded most proposed solutions.

Can we achieve this with `TypedDict`?

**Comment by samuelcolvin** [comment] 2023-02-12 10:23
Otherwise, should we propose something to the typing community?

**Comment by samuelcolvin** [comment] 2023-02-13 16:23
Closing this as a duplicate of #1673. I'll reply there with my proposal.

**Closed by samuelcolvin** 2023-02-13 16:23 UTC
Labels: feature request
