### ISSUE TITLE
Sets are not sequence_like

### ISSUE THREAD

**Issue by gsakkis** [pydantic/pydantic#1251] opened 2020-02-23 20:35 UTC
# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.4
            pydantic compiled: True
               python version: 3.7.1 (default, Dec 14 2018, 19:46:24)  [GCC 7.3.0]
                     platform: Linux-4.4.0-173-generic-i686-with-debian-stretch-sid
     optional deps. installed: ['typing-extensions']
```

```py
# model.py
from pydantic.dataclasses import dataclass
from typing import Sequence

@dataclass
class Model:
    list_of_ints: Sequence[int]

print(Model({1, 2}))
print(Model(frozenset({1, 2})))
```
Running mypy on `model.py` correctly reports 2 errors:
```
model.py:8: error: Argument 1 to "Model" has incompatible type "Set[int]"; expected "Sequence[int]"  [arg-type]
model.py:9: error: Argument 1 to "Model" has incompatible type "FrozenSet[int]"; expected "Sequence[int]"  [arg-type]
Found 2 errors in 1 file (checked 1 source file)
```
Pydantic however doesn't; additionally it converts the frozenset to list while it preserves the set:
```
Model(list_of_ints={1, 2})
Model(list_of_ints=[1, 2])
```

**Comment by MrMrRobat** [comment] 2020-02-23 22:03
Not a bug.

> A set is an unordered collection

https://docs.python.org/3/tutorial/datastructures.html#sets

**Comment by samuelcolvin** [comment] 2020-02-23 22:07
But since we allow a set as input to a list, we should allow sets here.

Or at least be clear and explicit about how all this works.

**Comment by MrMrRobat** [comment] 2020-02-23 22:12
I guess, such type should be called `SequenceLike` then, and `typing.Sequence` should expect only real sequences

**Comment by samuelcolvin** [comment] 2020-02-23 22:20
Well, pydantic (rightly or wrongly) defaults mostly to coercion, e.g. if you pass a set to a list it gets converted to a list.

You might expect the same here.

I'm not clear on the semantic differences between list, set, dict, sequence, collection and what should count as what.

**Comment by gsakkis** [comment] 2020-02-23 22:54
There's already a check that (correctly) disallows dicts although you can pass a dict to a list; I believe sets should be disallowed as well.

Interestingly, iterators are also disallowed:
```
print(Model(iter([1, 2])))

  File "pydantic/dataclasses.py", line 83, in pydantic.dataclasses._process_class._pydantic_post_init
    # Raise because not adding these methods would break the "frozen-ness"
pydantic.error_wrappers.ValidationError: 1 validation error for Model
list_of_ints
  value is not a valid sequence (type=type_error.sequence)
```

**Comment by adriangb** [comment] 2023-04-25 19:58
This is resolved in V2:

```
from typing import Sequence

from pydantic.dataclasses import dataclass


@dataclass
class Model:
    list_of_ints: Sequence[int]

print(Model({1, 2}))  # Input should be an instance of Sequence
print(Model(frozenset({1, 2})))  # Input should be an instance of Sequence
```

They'll be a conversion table for V2 that details this.

**Closed by adriangb** 2023-04-25 19:58 UTC
Labels: bug V1
