### ISSUE TITLE
Serialisation / deserialisation issues when using BaseModel as key for a dictionary

### ISSUE THREAD

**Issue by kkalinowski-reef** [pydantic/pydantic#7292] opened 2023-08-30 11:44 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

The problem is rather simple – we all know that the JSON key can only be a string. But I'd love to have something slightly more complicated, as it makes sense in my case.

So, what I've learned:
- Whenever model is used as a dict key, `__str__` method is used to create the key.
- Since the default `__str__` has nothing to do with any known representation, deserialisation fails.
- I tried to come up with a generic way of solving this issue, but I only got that far.
- I've tried quite a few different ways (including `model_construct` from manually deserialised json dictionary), but they all fail.

Am I missing something silly?

### Example Code

```Python
import datetime
from typing import Any

from pydantic import BaseModel, model_validator


class Key(BaseModel, frozen=True):
    timestamp: datetime.datetime

    @model_validator(mode='before')
    @classmethod
    def validator(cls, value: Any) -> Any:
        if isinstance(value, str):
            return cls.model_validate_json(value)
        return value

    def __str__(self) -> str:
        return self.model_dump_json()


class Container(BaseModel):
    field: dict[Key, int]


def main():
    container = Container(field={Key(timestamp=datetime.datetime.now()): 1})
    serialized = container.model_dump_json()
    print(serialized)
    deserialized = Container.model_validate_json(serialized)  # <– fails here.
    assert deserialized == container


if __name__ == '__main__':
    main()
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.3.0
        pydantic-core version: 2.6.3
          pydantic-core build: profile=release pgo=false
                 install path: <venv-path>/lib/python3.11/site-packages/pydantic
               python version: 3.11.4 (main, Jul 19 2023, 08:06:20) [Clang 14.0.3 (clang-1403.0.22.14.1)]
                     platform: macOS-13.4.1-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @lig

**Comment by kkalinowski-reef** [comment] 2023-08-30 12:11
So far, I've only came up with an idea of implementing `field_serializer` and `model_validator(mode="before")` on the object containing the `dict`, so that the `dict` is saved as "something" else, and loaded from that "something" before even Pydantic can work with it. But it surely isn't the best way to solve this issue.

**Comment by dmontagu** [comment] 2023-08-31 05:27
Okay, I feel like this is a bug, but the following tweak made it work for me:
```python
    @model_validator(mode='before')
    @classmethod
    def validator(cls, value: Any) -> Any:
        if isinstance(value, str):
            return cls.model_validate_json(value).model_dump()
        return value
```

I think what is happening here is that, in pydantic-core, it's not expecting to get an instance of basemodel while loading from JSON. Weirdly, with your code, if I try to do `deserialized = Container.model_validate(json.loads(serialized))  # <– fails here.`, I get
```
  Input should be a valid dictionary or instance of Key [type=model_type, input_value=Key(timestamp=datetime.da...30, 23, 25, 49, 877162)), input_type=Key]
```
which _definitely_ seems like a bug given the error makes no sense (it's saying it should be a `Key`, _and_ that the input _is_ a `Key`).

@davidhewitt if you have a chance to look into this I feel you might stand a good chance of resolving it quickly.

**Comment by kkalinowski-reef** [comment] 2023-08-31 06:09
Thank you! Your solution is SO much better than a custom serialiser in the `Container`! (and it does actually work and solve my issue in my "not so simple" case as well)

**Comment by davidhewitt** [comment] 2024-04-29 10:53
Looking at the "bug" here, the problem is that the "before" validator is running as a wrapper around the `model-fields` schema, not around the outer `model` schema. So the "before" validator is required to return a set of fields (i.e. a dictionary), not a complete model.

Potentially the schema needs to be changed so that the before validator runs before the whole "model" schema. I'm not sure what other stuff breaks if we do that. Needs further investigation.

**Comment by davidhewitt** [comment] 2024-04-29 10:55
Will close in favour of #9336 which reports the same "bug".

**Closed by davidhewitt** 2024-04-29 10:55 UTC
Labels: bug V2
