### ISSUE TITLE
Unable to use Literal in BaseModels with python 3.9

### ISSUE THREAD

**Issue by RothNRK** [pydantic/pydantic#5831] opened 2023-05-23 15:09 UTC
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

My code which uses `Literal` recently stopped working with a `TypeError: issubclass() arg 1 must be a class` error. While debugging it I found that I couldn't get your example to work with python 3.9, while it works with python 3.10 and 3.11.

I would expect that the code labelled as _This script is complete, it should run "as is"_ would run. 

I ran the code in a clean docker image.

`docker run -it -v $(pwd):/src python:3.8-bullseye bash` <--- Does not work
`docker run -it -v $(pwd):/src python:3.9-bullseye bash` <--- Does not work
`docker run -it -v $(pwd):/src python:3.10-bullseye bash` <--- Works
`docker run -it -v $(pwd):/src python:3.11-bullseye bash` <--- Works

Once in the container:
```
cd src
pip install pydantic  # installs 1.10.7
python foo.py # Runs the example code from [Literal Type](https://docs.pydantic.dev/latest/usage/types/#literal-type)
```
Result:
```
Traceback (most recent call last):
  File "/src/foo.py", line 6, in <module>
    class Pie(BaseModel):
  File "pydantic/main.py", line 197, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 668, in pydantic.fields.ModelField._type_analysis
  File "/usr/local/lib/python3.9/typing.py", line 852, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class
```

Any help would be appreciated.

### Example Code

```Python
from typing import Literal

from pydantic import BaseModel, ValidationError


class Pie(BaseModel):
    flavor: Literal["apple", "pumpkin"]


Pie(flavor="apple")
Pie(flavor="pumpkin")
try:
    Pie(flavor="cherry")
except ValidationError as e:
    print(str(e))
    """
    1 validation error for Pie
    flavor
      unexpected value; permitted: 'apple', 'pumpkin'
    (type=value_error.const; given=cherry; permitted=('apple', 'pumpkin'))
    """
```

### Python, Pydantic & OS Version

```Text
python -c "import pydantic.utils; print(pydantic.utils.version_info())"
             pydantic version: 1.10.7
            pydantic compiled: True
                 install path: /usr/local/lib/python3.9/site-packages/pydantic
               python version: 3.9.16 (main, May  4 2023, 06:16:43)  [GCC 10.2.1 20210110]
                     platform: Linux-5.10.104-linuxkit-x86_64-with-glibc2.31
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [X] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by hramezani** [comment] 2023-05-23 15:10
Duplicate of https://github.com/pydantic/pydantic/issues/5821

**Closed by hramezani** 2023-05-23 15:10 UTC
Labels: bug V1, unconfirmed
