### ISSUE TITLE
2.10: question about needing model rebuild with circular types

### ISSUE THREAD

**Issue by lijok** [pydantic/pydantic#10925] opened 2024-11-21 13:50 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

We're seeing two regressions with pydantic v3.10 on code that's been untouched for a while;

1. Mypy taking issue with model_fields:
```shell
src/events/event_loader/_main.py:72: error: Value of type "Callable[[BaseModel], dict[str, FieldInfo]]" is not indexable  [index]
```

Being raised by this code;

```py
...
        for implementation in JSONCloudEvent.__subclasses__():
            if implementation.model_fields["type"].default == event_type:
...
```

2. Model no longer fully defined
```shell
pydantic.errors.PydanticUserError: `RootConfig` is not fully defined; you should define `EventBusConfig`, then call `RootConfig.model_rebuild()`.
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.10.0
        pydantic-core version: 2.27.0
          pydantic-core build: profile=release pgo=false
               python version: 3.12.7 (main, Oct  1 2024, 02:05:46) [Clang 16.0.0 (clang-1600.0.26.3)]
                     platform: macOS-15.0-arm64-arm-64bit
             related packages: pydantic-settings-2.6.1 mypy-1.13.0 typing_extensions-4.12.2
                       commit: unknown
```

**Comment by Viicos** [comment] 2024-11-21 14:17
1st issue: https://github.com/pydantic/pydantic/issues/10907

2nd issue: Could you please provide more info? Is it open source? Can you provide a MRE?

**Comment by sydney-runkle** [comment] 2024-11-21 14:29
1st issue should be fixed by https://github.com/pydantic/pydantic/pull/10911 shortly :)

**Comment by sydney-runkle** [comment] 2024-11-21 17:23
@lijok,

If you're able to provide a reproducible example for the 2nd thing, we might be able to fix in our upcoming patch

**Comment by sydney-runkle** [comment] 2024-11-22 00:38
Going to close for now. Happy to reopen with a minimal repro!

**Comment by sydney-runkle** [comment] 2024-11-22 15:48
We've improved our namespace management behavior, which is probably the source of this change.

Sorry, it's hard for us to help without a reproducible example 😔

**Comment by Viicos** [comment] 2024-11-22 15:52
It could also be because of https://github.com/pydantic/pydantic/issues/10919. Could you please check on 2.10.1?

**Comment by sydney-runkle** [comment] 2024-11-25 15:26
> LMK if it's intended that this should require a model_rebuild.

Indeed, I think this should require a model rebuild.

In `multi_destination_event_bus_config.py`, we're unable to build the schema for `MultiDestinationEventBusConfig` because `EventBusConfig` is imported in an `if TYPE_CHECKING` block.

If you're looking for a more in depth explanation [this comment](https://github.com/langchain-ai/langchain/issues/28284#issuecomment-2495954444) should help!

**Comment by Viicos** [comment] 2024-11-25 15:54
Indeed, your setup is pretty unusual. The reason this was working before is pretty complex, but could lead to invalid use cases. You can try removing the `if TYPE_CHECKING:` block (which is what actually happens at runtime) in `multi_destination_event_bus_config.py` on 2.9, and it would still work (although not valid for static type checkers).

In general, you should avoid circular imports at all costs, especially when dealing with Pydantic models. In your case, you can probably simplify your code, as `MultiDestinationEventBusConfig.event_buses` is annotated as `EventBusConfig`, but `EventBusConfig` is equal to `MultiDestinationEventBusConfig`. So in the end, something like:

```python

class MultiDestinationEventBusConfig(BaseModel):
    event_buses: 'MultiDestinationEventBusConfig'
```

Should be better.

**Closed by Viicos** 2024-11-25 15:54 UTC
Labels: bug V2, pending

**Comment by sushart** [comment] 2024-11-26 12:36
Same here just used 2.10 instead of 2.9.2 and  
pydantic.errors.PydanticUserError: `SomeClass` is not fully defined; you should define `OtherClass`, then call `SomeClass.model_rebuild()`. 

suddenly all over the place. Would be nice to know why and what changed in Pydantic 2.10. that caused this.

**Comment by Viicos** [comment] 2024-11-26 14:46
@sushart, the available namespaces logic to evaluate forward annotations changed in 2.10. Issues (which in 90% of cases are actually invalid use cases that were working until now) can manifest in a number of ways. Is your project open source? If not, are you:
- making use of aliases (like `Alias = list['SomeForwardRef']`) defined in one module, and reused later in different modules?
- making use of types imported in a `if TYPE_CHECKING:` block and used as Pydantic models annotations?

**Comment by Viicos** [comment] 2024-11-26 15:19
If you remove the `if TYPE_CHECKING:` block, you will probably notice that Pydantic is still able to build the schema for your models. This is unexpected and shouldn't happen (static type checkers/your IDE will also error on annotations referencing unknown types), and this can lead to the wrong types being used by Pydantic.

Fixing the circular import is the best way forward. I know this can be challenging, but a necessary step to avoid issues in the future.
