### ISSUE TITLE
Error applying StringConstraint: StringConstraint() takes no argument 

### ISSUE THREAD

**Issue by gVallverdu** [pydantic/pydantic#7747] opened 2023-10-05 15:11 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hi
Following the example here https://docs.pydantic.dev/latest/api/types/#pydantic.types.constr

I try to apply a constraint to a string by:

```python
from typing_extensions import Annotated
from pydantic import StringConstraints, BaseModel

class Toto:
    a: Annotated[str, StringConstraints(strip_whitespace=True, pattern=r"^[A-Z][a-z]?$")]
```

But the above code leads to this error:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[4], line 1
----> 1 class Toto:
      2     a: Annotated[str, StringConstraints(strip_whitespace=True, pattern=r"^[A-Z][a-z]?$")]

Cell In[4], line 2, in Toto()
      1 class Toto:
----> 2     a: Annotated[str, StringConstraints(strip_whitespace=True, pattern=r"^[A-Z][a-z]?$")]

TypeError: StringConstraints() takes no arguments
```

### Example Code

```Python
from typing_extensions import Annotated
from pydantic import StringConstraints, BaseModel

class Toto:
    a: Annotated[str, StringConstraints(strip_whitespace=True, pattern=r"^[A-Z][a-z]?$")]


But the above code leads to this error:
```
```


### Python, Pydantic & OS Version

```Text
pydantic version: 2.4.2
        pydantic-core version: 2.10.1
          pydantic-core build: profile=release pgo=false
                 install path: /Users/gvallver/opt/miniconda3/envs/c2mc/lib/python3.9/site-packages/pydantic
               python version: 3.9.7 (default, Sep 16 2021, 08:50:36)  [Clang 10.0.0 ]
                     platform: macOS-10.16-x86_64-i386-64bit
             related packages: typing_extensions-4.7.1
```
```

**Comment by sydney-runkle** [comment] 2023-10-05 15:18
Hi,

This is a duplicate of #7745. Please see that issue for the solution. You'll need to upgrade your python version.

**Comment by sydney-runkle** [comment] 2023-10-05 15:19
This isn't a bug with pydantic. You can see more details [here](https://github.com/pydantic/pydantic/issues/7544#issuecomment-1733738457)

**Closed by sydney-runkle** 2023-10-05 15:18 UTC
Labels: duplicate, question

**Comment by gVallverdu** [comment] 2023-10-06 08:31
Ok, thank you and sorry for the duplicate.

I know that it is always difficult to empty the stack of todo task but if I can make two suggestions:

* in the [doc](https://docs.pydantic.dev/latest/api/types/#pydantic.types.constr), it is unclear if Annotated has to be imported from typing or pydantic. The link on the page leads to a page of the documentation of the typing module.
* in the [installation page](https://docs.pydantic.dev/latest/install/), you said 

> If you've got Python 3.7+ and pip installed, you're good to go.

Maybe you could stress here that for V2, 3.9.18 is the minimum requirement? Or maybe it is difficult because the min python version depends on the functionality of pydantic ones want to use.

Thank you anyway for your job and the package!!

**Comment by sydney-runkle** [comment] 2023-10-06 16:05
Hi @gVallverdu,

Thanks for following up! Yep - that's an error in the docs. I'll open a PR to fix that example today 😄 - thanks for catching that.

Yeah, I think the difficulty is that it's ok to have 3.7 if you're not using constraints that raise the CPython bug that you experienced. Hopefully that bug re the constraints can be fixed soon, then the variations between Python 3.7 versions shouldn't be a problem.

Thanks for your feedback + support 👍
