### ISSUE TITLE
allow_population_by_field_name does not work with dataclasses

### ISSUE THREAD

**Issue by sstanovnik** [pydantic/pydantic#4581] opened 2022-10-03 10:36 UTC
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

The Model Config documentation implies that `allow_population_by_field_name` works for both dataclasses and `BaseModel`, but that does not seem to be the case. I have tried the following cases

* `BaseModel` + `Field(alias=...)` (works)
* `BaseModel` + `Config.fields = {...}` (works)
* `@pydantic.dataclasses.dataclass` + `Field(alias=...)` (does not work)
* `@pydantic.dataclasses.dataclass` + `Config.fields = {...}` (does not work)

[This comment](https://github.com/pydantic/pydantic/issues/986#issuecomment-552093837) is the only place I found a mention that this would not work. 

[This second comment](https://github.com/pydantic/pydantic/issues/153#issuecomment-633708838) points out this same problem, but after the unrelated issue was already closed.

[This issue](https://github.com/pydantic/pydantic/issues/1433) also has some related discussion.

This may just be a case of amending the documentation. I'm opening a separate issue from the above because I had a hard time finding definitive information on how `allow_population_by_field_name` is used. The only place I have found this tested [tests](https://github.com/pydantic/pydantic/blob/e34ff9255f281eaccac10d0436c082626d9146c3/tests/test_decorator.py#L429) a function decorator.

_As a side note, thank you very much for implementing `Extra` in dataclasses for 1.10!_

### Example Code

```Python
import pydantic


class PocWorkingCase1(pydantic.BaseModel):
    class Config:
        allow_population_by_field_name = True

    internal: str = pydantic.Field(alias="public")


class PocWorkingCase2(pydantic.BaseModel):
    class Config:
        fields = {
            "internal": "public"
        }
        allow_population_by_field_name = True

    internal: str


@pydantic.dataclasses.dataclass
class PocNotWorkingCase1:
    class Config:
        allow_population_by_field_name = True

    internal: str = pydantic.Field(alias="public")


@pydantic.dataclasses.dataclass
class PocNotWorkingCase2:
    class Config:
        fields = {
            "internal": "public"
        }
        allow_population_by_field_name = True

    internal: str


print(PocWorkingCase1(public="hello"))     # internal='hello'
print(PocWorkingCase2(public="hello"))     # internal='hello'
print(PocNotWorkingCase1(public="hello"))  # pydantic.error_wrappers.ValidationError: 1 validation error for PocNotWorkingCase1
                                           # public
                                           #   field required (type=value_error.missing)
print(PocNotWorkingCase2(public="hello"))  # TypeError: PocNotWorkingCase2.__init__() missing 1 required positional argument: 'internal'
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.2
            pydantic compiled: True
                 install path: /redacted/.venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.6 (main, Aug 10 2022, 11:40:04) [GCC 11.3.0]
                     platform: Linux-5.15.0-46-generic-x86_64-with-glibc2.35
     optional deps. installed: ['dotenv', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [X] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [X] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment] 2022-10-03 18:34
I agree it's not that clear, but it will work properly in V2.

I don't think it's worth working on the docs for v1 now as v2 is in development.

**Comment by samuelcolvin** [comment] 2022-10-05 09:10
duplicate of #986 and other issues, will be fixed in v2.

**Closed by samuelcolvin** 2022-10-05 09:10 UTC
Labels: bug, unconfirmed
