### ISSUE TITLE
Unexpected behavior using `alias`

### ISSUE THREAD

**Issue by maringuu** [pydantic/pydantic#10649] opened 2024-10-17 15:18 UTC
### Description

From the [documentation](https://docs.pydantic.dev/latest/concepts/alias/)

 > An alias is an alternative name for a field, used when serializing and deserializing data.

So I would expect to be able to use both the non-aliased name and the aliased one.
Running the example code the last assertion fails.

I'm not quite sure if this is a bug or just me not understanding the documentation correctly.

### Example Code

```Python
from pydantic import BaseModel, Field, AliasChoices


class Model(BaseModel):
    boolean: bool = Field(
        default=False,
        # Using this line, it works as expected
        # validation_alias=AliasChoices("boolean", "my-alias"),
        # Even this non-documented code does work (Bug?)
        # alias=AliasChoices("boolean", "my-alias"),
        alias="my-alias",
    )

model=Model(**{"my-alias": True})
serialized = model.model_dump(mode="json")
deserialized = Model.model_validate(serialized, strict=False)

assert model.boolean == True
assert model.boolean == True
assert deserialized.boolean == True, "Why does this fail?!"
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.9.2
        pydantic-core version: 2.23.4
          pydantic-core build: profile=release pgo=false
                 install path: /home/maringuu/.cache/pypoetry/virtualenvs/celery-bug-TF7v5PjU-py3.12/lib/python3.12/site-packages/pydantic
               python version: 3.12.6 (main, Sep  8 2024, 13:18:56) [GCC 14.2.1 20240805]
                     platform: Linux-6.10.10-arch1-1-x86_64-with-glibc2.40
             related packages: typing_extensions-4.12.2
                       commit: unknown
```

**Comment by Viicos** [comment] 2024-10-17 15:44
Marking as a duplicate of https://github.com/pydantic/pydantic/issues/8379.

**Closed by Viicos** 2024-10-17 15:44 UTC
Labels: bug V2, pending
