### ISSUE TITLE
Cannot access member "model_dump" for type...  Member "model_dump" is unknownPylancereportGeneralTypeIssues

### ISSUE THREAD

**Issue by jiaulislam** [pydantic/pydantic#6832] opened 2023-07-24 19:01 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I have one common Base model named `CommonAttribute`. The Ledger & Policy class are inheriting the `CommonAttributes`. After instantiating the Policy or Ledger Class trying to use the `model_dump()` method from the class but i'm getting `VSCode` pylance error saying

`Cannot access member "model_dump" for type "Policy"
  Member "model_dump" is unknown`

### Example Code
```python
class CommonAttributes(BaseModel):
    policy_number: str
    insurer_name: str
    plan_code: str
    paymode: str
    premium_no: int

class Ledger(CommonAttributes):
    order_id: str
    receipt_id: str | None = None
    user_id: str | None = None
    bank_code: str | None = None
    project_code: str | None = None

class Policy(CommonAttributes):
    birthday: date
    maturity_date: date
    project_code: str
    lapse_month: float = 0.0

def ledger(order_id: str) -> Ledger:
    return Ledger(
        **self.policy.model_dump(), order_id=order_id # here pylance is giving error in strict mode
    )
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.3
        pydantic-core version: 2.3.0 release build profile
                 install path: C:\Users\jiaul\AppData\Local\pypoetry\Cache\virtualenvs\dsa-algo-python-z05dy7Ns-py3.11\Lib\site-packages\pydantic
               python version: 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)]
                     platform: Windows-10-10.0.19044-SP0
     optional deps. installed: ['devtools', 'typing-extensions']
```

Selected Assignee: @samuelcolvin

**Comment by Viicos** [comment] 2023-07-25 06:02
Could you please provide a working [MRE](https://en.wikipedia.org/wiki/Minimal_reproducible_example)? I'm not able to reproduce the issue, even by tweaking your example to make it work

![image](https://github.com/pydantic/pydantic/assets/65306057/e397ac87-a00c-45d9-8f09-136c90f984b1)

**Comment by sydney-runkle** [comment] 2024-03-27 04:51
Closing as n/a. Thanks @Viicos.

**Closed** 2024-03-27 04:52 UTC
Labels: unconfirmed, bug V2
