### ISSUE TITLE
dump_obj or equivilant

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic#1008] opened 2019-11-18 14:14 UTC
As suggested by @dmontagu at https://github.com/samuelcolvin/pydantic/pull/958#issuecomment-554670739 we should have a way to get a model's data which accounts for custom root types (e.g. like `.json()` without the JSON encoding).

This would probably rely on #1001, and might have to wait for v2 anyway.

Options:
1. `dump_obj` as suggested by @dmontagu, maybe just `dump()` would be preferable.
2. `unpack_custom_roots` argument to `.dict()` as suggested by @dmontagu, problem is that in this case `dict()` wouldn't necessarily return a `dict` which seems confusing to me, could be overcome with `@overload` i think.
3. `.dict()` respect custom root types same as `.json()`, same problem as 2 but can `@overload` work based on a class attribute?

Overall I think I prefer 2.

**Comment by theFong** [comment] 2019-12-16 18:58
Is there any existing solution that allows me to convert a Pydantic object to a json serializable python dict? Currently I'm serializing the pydantic object to a json string and deserializing it back into a python dict.

**Comment by dmontagu** [comment] 2019-12-16 19:58
@theFong Does `.dict()` not work for you?

@samuelcolvin I'm not sure how a standalone `dump_obj` function in `pydantic.tools` would factor into these options. (I'm planning to work on that now for the sake of improving FastAPI performance.)

**Comment by theFong** [comment] 2019-12-16 20:59
My model has datetime and Enum attributes. Discovered `use_enum_values = True` which solved some of my use cases but it appears that .dict() does not serialize datetime into strings (probably by design).

**Comment by dmontagu** [comment] 2019-12-16 22:27
@theFong I see. If you are using `fastapi` you can use `fastapi.encoders.jsonable_encoder(model)` -- that will create an object that is json encodable. I think you can also use `encoder=pydantic.json.pydantic_encoder` as a keyword argument to `json.dumps`.

**Comment by dmontagu** [comment] 2023-05-19 14:01
I believe this will be closed by https://github.com/pydantic/pydantic/pull/5765

**Closed** 2023-05-22 13:58 UTC
Labels: Change, v2-reviewed
