### ISSUE TITLE
`model.dict()` does not convert UUID to str, so its result is not json serializable

### ISSUE THREAD

**Issue by mmohaveri** [pydantic/pydantic#5155] opened 2023-03-08 12:06 UTC
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Pydantic automatically converts UUID to str whenever it serializes an object to json:

```python
class MyModel(BaseModel):
    id: UUID

m = MyModel(id=uuid4())
m.json()
```

This will result in:
```python
'{"id":"0a67f51a-01d9-4203-a894-c9afbd18d860"}'
```

I'm expecting it to do the same when I use the `dict` function on the model. But currently pydantic does not convert the UUID to str in this case:

```python
class MyModel(BaseModel):
    id: UUID

m = MyModel(id=uuid4())
m.dict()
```

```python
{"id": UUID("0a67f51a-01d9-4203-a894-c9afbd18d860")}
```

The problem is UUID is not json serializable, so this result is not json serializable, which contradicts with the documentation's defenition of `json` funcion: 

> json(): returns a JSON string representation dict()

It causes an issue when you what to pass the resulting dict to an other function, which expects a python dictionary and after some manipulation tries to serialize the dictionary into json.

In my case I'm using pydantic to define my JWT's structure. The JWT library I'm using expects a dictionary, so I'm using the `dict()` function to get a dictionary from the model, but the resulting dictionary is not serializable and the JWT library throws an error.

### Example Code

```Python
import json
from uuid import UUID, uuid4

import pydantic

class MyModel(pydantic.BaseModel):
    id: UUID

m = MyModel(id=uuid4())

# This will work fine, as pydantic converts UUID to str automatically.
m.json()

# This will raise an error "TypeError: Object of type UUID is not JSON serializable"
json.dumps(m.dict())
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.4
pydantic compiled: True
    install path: /home/user/.virtualenvs/pydantic-test-11/lib/python3.11/site-packages/pydantic
python version: 3.11.2 (main, Mar  5 2023, 08:28:49) [GCC 12.2.0]
platform: Linux-6.1.0-5-amd64-x86_64-with-glibc2.36
optional deps. installed: ['email-validator', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [X] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by dmontagu** [comment] 2023-03-08 14:04
This is by design — the `dict` method is just meant to convert the object to a dict, not to convert it to something directly-JSON-serializable. There are many use cases where you want to convert the object to a dict but not change the type of the items in that dict, e.g., passing the contents of the model as `**kwargs` into another function.

If you specifically want to get the model as a dict of JSON-serializable primitives, I _believe_ the best way to achieve this is honestly `json.loads(model.json())`.

**Comment by mmohaveri** [comment] 2023-03-09 14:15
I understand the need for a `dict` method that does not convert the data types. But I think the dict method should allow users to convert to something JSON serializable as well, maybe by receiving an extra argument like `json_serializable=True`.

Also if this behavior of `dict` is by design, then the documentation is misleading. As I mentioned earlier, the documentation defines `json()` function as "JSON string representation of `dict()`". But in my case `dict()` is not JSON serializable.

At the moment I'm using `json.loads(model.json())`, but it comes with an unnecessary performance cost. I believe adding an extra argument to the `dict` prevents this performance hit and does not interfere with existing usage of `dict`.

**Comment by johanvanderkuijl** [comment] 2023-08-23 08:10
Seems that they fixed this in pydantic v2.

The old .dict() is replaced with .model_dump(), in which you can pass argument 'mode' = 'json' , to create json compatible output.

link: https://docs.pydantic.dev/latest/api/base_model/#pydantic.main.BaseModel.model_dump

**Comment by sydney-runkle** [comment] 2023-12-14 20:53
Closing as completed based on the new V2 logic :)

**Closed by sydney-runkle** 2023-12-14 20:53 UTC

**Comment by custom-directive-hurt** [comment] 2025-10-07 20:31
> Seems that they fixed this in pydantic v2.
> 
> The old .dict() is replaced with .model_dump(), in which you can pass argument 'mode' = 'json' , to create json compatible output.
> 
> link: https://docs.pydantic.dev/latest/api/base_model/#pydantic.main.BaseModel.model_dump





https://lestertraumatic.github.io/kai6/
