### ISSUE TITLE
pydantic 2.5.0 not installable through Azure DevOps artifact feed, too long description

### ISSUE THREAD

**Issue by fraghag** [pydantic/pydantic#8136] opened 2023-11-15 14:11 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

We use an internal python package feed in Azure DevOps for all our work with pypi as an upstream feed.

As of pydantic 2.5.0 we cannot install pydantic and get the following error:
`ERROR: Could not install requirement pydantic<3,>=1.8 from https://pkgs.dev.azure.com/raysearch/_packaging/9c695c7d-adf5-4647-a8d4-6f094f7d25f5/pypi/download/pydantic/2.5/pydantic-2.5.0-py3-none-any.whl#sha256=7ce6e766c456ad026fe5712f7bcf036efc34bd5d107b3e669ef7ea01b3a9050c (from aws-sam-translator->-r /tmp/pipenv-qcg_0521-requirements/pipenv-t350iuwj-constraints.txt (line 15)) because of HTTP error 400 Client Error: Bad Request - The package description exceeds the maximum length of 324608 bytes. (DevOps Activity ID: B93B62E1-E724-4530-8BA4-71B2BB7C070B) for url: https://pkgs.dev.azure.com/raysearch/_packaging/9c695c7d-adf5-4647-a8d4-6f094f7d25f5/pypi/download/pydantic/2.5/pydantic-2.5.0-py3-none-any.whl for URL https://pkgs.dev.azure.com/raysearch/_packaging/9c695c7d-adf5-4647-a8d4-6f094f7d25f5/pypi/download/pydantic/2.5/pydantic-2.5.0-py3-none-any.whl#sha256=7ce6e766c456ad026fe5712f7bcf036efc34bd5d107b3e669ef7ea01b3a9050c (from https://pkgs.dev.azure.com/raysearch/_packaging/raysearch-ml-pypi/pypi/simple/pydantic/) (requires-python:>=3.7)`

Azure DevOps has a limit on the size of the package description (324608 bytes) which seems fairly resonable. It looks like the pydantic package description includes the changelog that goes back more than 5 years. At the end there is already a link to earlier changes, so maybe more of the changelog in the description could be cut of.
Another alternative is to not have links to PRs and authors in the description changelog and just keep that in the more extensive changelog on the docs page (https://docs.pydantic.dev/latest/changelog/).

Seems a bit weird to me to have such an extensive changelog in a package description instead of describing the current state of the package. Maybe a link to the changelog page is enought?

Anyway, we (and I guess quite a few other users of Azure DevOps) have to lock pydantic dependencies to <=2.4.2 for now.

### Python, Pydantic & OS Version

```Text
pydantic version: 2.4.2
        pydantic-core version: 2.10.1
          pydantic-core build: profile=release pgo=false
                 install path: C:\Users\raghag\.virtualenvs\test-lG5Cm2Di\Lib\site-packages\pydantic
               python version: 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:59:51) [MSC v.1928 64 bit (AMD64)]
                     platform: Windows-10-10.0.19041-SP0
             related packages: typing_extensions-4.8.0
```

**Comment by sydney-runkle** [comment] 2023-11-15 14:16
Hi @fraghag,

This is a duplicate of https://github.com/pydantic/pydantic/issues/8105.

This has been fixed in `2.5.1`.

**Closed by sydney-runkle** 2023-11-15 14:16 UTC
Labels: bug V2, pending
