### ISSUE TITLE
Incorrect parsing as `dict` for a `list` of `dict` with two items

### ISSUE THREAD

**Issue by sisp** [pydantic/pydantic#5523] opened 2023-04-19 07:07 UTC
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Pydantic parses a `list` of `dict`s with two items as a `dict` although it should raise an error. This may lead to unexpected behavior as I'll show in the example below.

### Example Code

```Python
from pydantic import parse_obj_as

# BUG
parse_obj_as(dict, [{"one": 1, "two": 2}])
# --> {'one': 'two'}

parse_obj_as(dict, [{"one": 1, "two": 2}, {"three": 3, "four": 4}])
# --> {'one': 'two', 'three': 'four'}

# OK
parse_obj_as(dict, [{"one": 1}])
# --> value is not a valid dict (type=type_error.dict)

parse_obj_as(dict, [{"one": 1, "two": 2, "three": 3}])
# --> value is not a valid dict (type=type_error.dict)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.7
            pydantic compiled: True
                 install path: .../.venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.8 (main, Jan 12 2023, 15:25:32) [GCC 9.4.0]
                     platform: Linux-5.13.0-48-generic-x86_64-with-glibc2.31
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment] 2023-04-19 07:14
I agree it's wrong, it's fixed in V2.

Duplicate of duplicate of #1268.

**Closed by samuelcolvin** 2023-04-19 07:14 UTC
Labels: bug V1, unconfirmed
