### ISSUE TITLE
BaseSettings with aliased fields conflicts at instantiation with field argument if an environment variable with alias name exists 

### ISSUE THREAD

**Issue by Galileo-Galilei** [pydantic/pydantic#3468] opened 2021-12-01 09:34 UTC
Hello, 

first of all, thanks for the awesome work you make with pydantic, this is fantastic library. If needed, I could contribute to push a fix for this bug, but I'll need some hints to find out what to modify since I am not familiar with the codebase.

### Checks

* [X] I added a descriptive title to this issue
* [X] I have searched (google, github) for similar issues and couldn't find anything
* [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

### Environment
Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```bash
pydantic version: 1.8.2
pydantic compiled: True
   install path: C:\ProgramData\anaconda3\envs\kedro_sas\Lib\site-packages\pydantic
 python version: 3.7.10 (default, Feb 26 2021, 13:06:18) [MSC v.1916 64 bit (AMD64)]
       platform: Windows-10-10.0.18362-SP0
optional deps. installed: ['typing-extensions']
```

### Description and setup

I have created a class which from ``BaseSettings`` with some aliased fields which refers to environment variables the settigns can be taken from. A minimal reproducible example is: 

```python
from pydantic import BaseSettings, Field
import os

class User(BaseSettings):
    username: str = Field(..., env="OS_USERNAME", alias="OS_USERNAME")
    password: str = Field(..., env="OS_PASSWORD", alias="OS_PASSWORD")

    class Config:
        extra = "forbid"  # extra keys are forbidden in the constructor
        allow_population_by_field_name = True  # you can use both "username" and "OS_USERNAME" (the alias) to populate the model

```

### Bug example

With previous setup and as far as I understand pydantic, I should be able to create a ``User`` instance with all of the following ways:

- CASE 1 (OK): no variable in env, populate with field
```python
User(username="John", password="secret_password") 
# works and returns: User(username="John", password="secret_password")
``` 

- CASE 2 (OK) : password in env, populate with field
```python
os.environ["OS_PASSWORD"]="secret_password_from_env"
User(username="John") 
# works and returns: User(username='John', password='secret_password_from_env')
```

- CASE 3 (OK) : password in env, populate with alias
```python
os.environ["OS_PASSWORD"]="secret_password_from_env"
User(username="John", OS_PASSWORD="secret_password") 
# works, provided argument has precedence over environment: User(username='John', password='secret_password')
```

- CASE 4 (KO) : password in env, populate with field
```python
os.environ["OS_PASSWORD"]="secret_password_from_env"
User(username="John", password="secret_password") # we use password (field) instead of OS_PASSWORD (alias) like in environment variable
# FAILS with: 
# ValidationError: 1 validation error for User
# password
#   extra fields not permitted (type=value_error.extra)

# EXPECTED result identical to CASE 3:
# User(username='John', password='secret_password')
```
This looks like a **bug, intutively it should behave like CASE 3**, e.g. override the environment variable with the provided field. Even worse, this is the exact same code like CASE 1: CASE 1 works if no environment variable is provided, and failed if an environment variable exists which leads to very confusing and _hard to debug_ behaviour.

**Comment by Nicholas-Schaub** [comment] 2022-02-25 17:04
I think there might be the same issue in `BaseModel`.

```python
from pydantic import BaseModel
from typing import Optional


def to_camel(string: str) -> str:
    return "".join(part.capitalize() for part in string.split("_"))


class Strict(BaseModel):
    """Don't permit extra attributes in any object."""

    index: int
    col_type: Optional[str]

    class Config:  # NOQA: D106

        extra = "forbid"
        allow_population_by_field_name = True
        alias_generator = to_camel


if __name__ == "__main__":

    # This works okay
    print(Strict(index=1, col_type="float"))
    # index=1 col_type='float'

    print(Strict(index=1, colType="float"))
    # pydantic.error_wrappers.ValidationError: 1 validation error for Strict
    # colType
    #   extra fields not permitted (type=value_error.extra)
```

**Comment by JosephMarinier** [comment] 2023-05-04 03:18
@Nicholas-Schaub Sorry if it's too late to be useful, but I think your issue is that your `alias_generator = to_camel` also capitalizes the first letter, so your code seems to run fine with
```diff
-    print(Strict(index=1, colType="float"))
+    print(Strict(index=1, ColType="float"))
```

**Comment by JosephMarinier** [comment] 2023-05-04 03:23
The issue is still there for `BaseSettings` with an env var in `1.10.7`. Here is how I reproduced:
```py
import os

from pydantic import BaseSettings, Field


class Settings(BaseSettings):
    my_field = Field("default", env="MY_FIELD", alias="my_alias")
    class Config:
        allow_population_by_field_name = True


Settings(my_alias="custom")  # OK
Settings(my_field="custom")  # OK

os.environ["MY_FIELD"] = "potato"

Settings(my_alias="custom")  # OK
Settings(my_field="custom")
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
#   File "pydantic/env_settings.py", line 39, in pydantic.env_settings.BaseSettings.__init__
#   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
# pydantic.error_wrappers.ValidationError: 1 validation error for Settings
# my_field
#   extra fields not permitted (type=value_error.extra)

del os.environ["MY_FIELD"]
```

**Comment by Nicholas-Schaub** [comment] 2023-05-04 03:24
@JosephMarinier I appreciate the feedback, but the alias generator is not the issue here.

I may have written the typo in the above example, but I have used this snake to camel converter in a variety of applications and it has always worked flawlessly.

**Comment by Nicholas-Schaub** [comment] 2023-05-04 03:31
I looked back at my code, and I definitely had a typo in the example I provided. This was what is should be:

```python
def to_camel(string: str) -> str:
    """Convert snake_case to camelCase."""
    return "".join(
        part.capitalize() if i > 0 else part for i, part in enumerate(string.split("_"))
    )
```

I have not tried it out recently, so maybe this problem has been fixed. I have not tested it recently.

**Comment by hramezani** [comment] 2023-05-04 13:12
@Galileo-Galilei I think it's the correct behavior of pydantic.
In `Case 4`, `User` model will be initialized by
```
{'OS_PASSWORD': 'secret_password_from_env', 'username': 'John', 'password': 'secret_password'}
```

Also, you need to know that `pydantic-settings` now is a separate package and is in alpha state. you can install it by `pip install pydantic-settings --pre` and test it.

Here is your provided example in the issue in new `pydantic-settings`:
```pre
from pydantic import ConfigDict, Field
from pydantic_settings import BaseSettings


class User(BaseSettings):
    username: str = Field(validation_alias="OS_USERNAME")
    password: str = Field(validation_alias="OS_PASSWORD")

    model_config = ConfigDict(
        extra="forbid",  # extra keys are forbidden in the constructor
        populate_by_name=True,  # you can use both "username" and "OS_USERNAME" (the alias) to populate the model
    )

```

**Closed by hramezani** 2023-05-04 13:12 UTC
Labels: bug V1

**Comment by pp-eyushin** [comment] 2025-01-15 14:55
> In Case 4, User model will be initialized by
{'OS_PASSWORD': 'secret_password_from_env', 'username': 'John', 'password': 'secret_password'}

@hramezani I'm not quite sure this behavior is expected. When I set an alias to the field, I expect it to represent the same abstraction/field but with different name. Otherwise, any default resolution flow with `env_prefix` should also create another field instead of setting the one that env var relates to (which doesn't make any sense in turn).

**Comment by EugeneYushin** [comment] 2025-01-16 10:02
For strangers in the night who hit the same issue, `AliasChoice` comes to rescue.
```python
password: str = Field(validation_alias=AliasChoices("password", "OS_PASSWORD"))
```
