### ISSUE TITLE
Using TypeAdapter with PyRight has typing issues

### ISSUE THREAD

**Issue by skewty** [pydantic/pydantic#9147] opened 2024-04-02 04:32 UTC
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

Hoping something can be done with typing to make it get along better with PyRight.  See below:

```python
from pydantic import AnyHttpUrl, TypeAdapter

def ensure_url(url: AnyHttpUrl | str) -> AnyHttpUrl:
    if isinstance(url, str):
        return TypeAdapter(AnyHttpUrl).validate_python(url)  # pyright: ignore [reportCallIssue, reportReturnType]
    return url
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by Viicos** [comment] 2024-04-02 09:29
Duplicate of https://github.com/pydantic/pydantic/discussions/7094

**Comment by sydney-runkle** [comment] 2024-04-02 19:40
@Viicos,

Any suggestions for how we might fix this?

**Comment by skewty** [comment] 2024-04-02 22:02
Additionally `AnyHttpUrl` (and I am expecting the other variants too) cannot be used with `isinstance()` which is counter intuitive.
Perhaps proper classes should be created and used?  `class Url(str)` and all the various subclasses with different validation requirements.

**Comment by Viicos** [comment] 2024-04-03 07:59
> Any suggestions for how we might fix this?

https://github.com/pydantic/pydantic/pull/8923 will suppress the error, however the type variable of `TypeAdapter` will be inferred as `TypeAdapter[Any]`.

To properly support this I'm afraid the only solution is to have type forms to land, but this is an active subject: https://github.com/python/mypy/issues/9773.

> Additionally AnyHttpUrl (and I am expecting the other variants too) cannot be used with isinstance() which is counter intuitive.

I agree this can be counter intuitive. Switching from `Annotated` constraints to proper subclasses probably requires a lot of work as well :/

**Comment by sydney-runkle** [comment] 2024-04-03 13:12
Yeah, I think we do actually want to switch to proper subclasses: https://github.com/pydantic/pydantic/issues/7353. So I think that's probably the way forward here.

**Comment by sydney-runkle** [comment] 2024-04-03 13:14
For now, let's have the subclasses replace the exiting types in `pydantic`, then we can move them to `pydantic-extra-types` when we do a V3 release.

**Comment by skewty** [comment] 2024-04-03 14:32
> For now, let's have the subclasses replace the exiting types in `pydantic`, then we can move them to `pydantic-extra-types` when we do a V3 release.

This should likely go into a new issue but perhaps we can sneak the fix into this re-work. URLs get "quoted" (using the `urllib.parse` function names) automatically.  The quoting additionally applies to the `username` and `password` fields. But whey are not unquoted when accessed via their property as expected.    

Example:
```python
from urllib.parse import unquote  # or unquote_plus?
from pydantic import TypeAdapter, AnyHttpUrl

url = TypeAdapter(AnyHttpUrl).validate_python("https://jsmith@abc.com:crazyp@ssw0rd@somewhere.com")
print(url.username) # 'jsmith%40abc.com'
print(url.password) # 'crazyp%40ssw0rd'
print(url.host) # 'somewhere.com'

# the unquoted version should be returned
print(unquote(url.username)) # 'jsmith@abc.com'
# it is safe to unquote twice so fixing this bug should not cause issues to existing code
print(unquote(unquote(url.username))) # 'jsmith@abc.com'
```

Perhaps I am pushing things at this point but should username and password fields remain `typing.Optional`? Isn't empty string better?  (perhaps for V3 release)

**Comment by sydney-runkle** [comment] 2024-11-06 19:17
This should be fixed on `main` because of our recent work. See https://github.com/pydantic/pydantic/issues/10783 for more details :)

**Closed by sydney-runkle** 2024-11-06 19:17 UTC
Labels: feature request, urls, pep747

**Comment by Viicos** [comment] 2026-07-17 16:09
https://github.com/pydantic/pydantic/pull/13459 adds support for [`TypeForm`](https://docs.python.org/3.15/library/typing.html#typing.TypeForm) introduced by [PEP 747](https://peps.python.org/pep-0747/), which fixes the encountered type checking issue.

This will be available in the next release.
