### ISSUE TITLE
Usage of uuid.UUID as input for BaseModel raises TypeError instead of ValidationError

### ISSUE THREAD

**Issue by tribunsky-kir** [pydantic/pydantic#7537] opened 2023-09-21 06:14 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hello,

I've faced problem with using standard python `uuid.UUID` as input for BaseModel.

Not sure if it is related to https://github.com/pydantic/pydantic/issues/7355

This problem is also reproducible in amd64 linux containers (e.g. `python:3.10-slim`)

### Example Code

```Python
import uuid

from pydantic import UUID4, BaseModel, ValidationError


class Event(BaseModel):
    id: UUID4


# 1. Regular uuid generated by uuid.uuid4()
uid = '32b2ff42-6c22-42a3-944e-b5c2fbaa1932'
# OK: Passed to pydantic as string
print(Event(id=uid))
# OK: Passed to pydantic as uuid.UUID
uid = uuid.UUID(uid)
print(uid.version)
print(Event(id=uid))

# 2. Crafted string which is recognized as uuid, but not uuid4
bad_uid = 'b34b6755-f49c-3bd2-6f06-131a708c2bf3'
# OK: Passed to pydantic as string
try:
    print(Event(id=bad_uid))
except ValidationError as e:
    print(e)
    """
    1 validation error for Event
    id
      UUID version 4 expected [type=uuid_version, input_value='b34b6755-f49c-3bd2-6f06-131a708c2bf3', input_type=str]
        For further information visit https://errors.pydantic.dev/2.3/v/uuid_version
    """

# BUG: Passed to pydantic as uuid.UUID
bad_uid = uuid.UUID(bad_uid)
# not a UUID4
print(bad_uid.version)
try:
    print(Event(id=bad_uid))
except ValidationError as e:
    print(e)
"""
Traceback (most recent call last):
  File "/Users/user/pydantic-uuid/main.py", line 38, in <module>
    print(Event(id=bad_uid))
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/pydantic-uuid-aFerQWJ7-py3.10/lib/python3.10/site-packages/pydantic/main.py", line 165, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
TypeError: 'NoneType' object cannot be interpreted as an integer
"""
```

### Python, Pydantic & OS Version

```Text
             pydantic version: 2.3.0
        pydantic-core version: 2.6.3
          pydantic-core build: profile=release pgo=false
                 install path: /Users/user/Library/Caches/pypoetry/virtualenvs/pydantic-uuid-aFerQWJ7-py3.10/lib/python3.10/site-packages/pydantic
               python version: 3.10.12 (main, Jul 28 2023, 18:34:01) [Clang 14.0.3 (clang-1403.0.22.14.1)]
                     platform: macOS-13.5.2-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
```

**Comment by hramezani** [comment] 2023-09-21 07:38
Thanks @tribunsky-kir for reporting this 🙏 

Yes, this is a duplicate of https://github.com/pydantic/pydantic/issues/7355

**Closed** 2023-09-21 14:16 UTC
Labels: bug V2
