### ISSUE TITLE
Pydantic Helper Functions Raise json.JSONDecodeError

### ISSUE THREAD

**Issue by dhruvrajan** [pydantic/pydantic#4985] opened 2023-01-25 18:28 UTC
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

The [error handling docs](https://docs.pydantic.dev/usage/models/#error-handling) provide that when an issue is encountered when validating data, a `pydantic.ValidationError` will be thrown. 

However there are cases when a json.JSONDecodeError is thrown. I'm including an example below, (`'True'` is an invalid boolean in JSON; `'true'` is valid).

Raising this issue to suggest that either the error be wrapped by a `ValidationError` or the docs be updated.

Thanks for the hard work!

### Example Code

```Python
In [1]: import pydantic

In [2]: pydantic.parse_raw_as(bool, "true")
Out[2]: True

In [3]: pydantic.parse_raw_as(bool, "True")
---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
Cell In [3], line 1
----> 1 pydantic.parse_raw_as(bool, "True")

File ~/.pyenv/versions/3.8.12/lib/python3.8/site-packages/pydantic/tools.py:74, in pydantic.tools.parse_raw_as()

File ~/.pyenv/versions/3.8.12/lib/python3.8/site-packages/pydantic/parse.py:37, in pydantic.parse.load_str_bytes()

File ~/.pyenv/versions/3.8.12/lib/python3.8/json/__init__.py:357, in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    352     del kw['encoding']
    354 if (cls is None and object_hook is None and
    355         parse_int is None and parse_float is None and
    356         parse_constant is None and object_pairs_hook is None and not kw):
--> 357     return _default_decoder.decode(s)
    358 if cls is None:
    359     cls = JSONDecoder

File ~/.pyenv/versions/3.8.12/lib/python3.8/json/decoder.py:337, in JSONDecoder.decode(self, s, _w)
    332 def decode(self, s, _w=WHITESPACE.match):
    333     """Return the Python representation of ``s`` (a ``str`` instance
    334     containing a JSON document).
    335 
    336     """
--> 337     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    338     end = _w(s, end).end()
    339     if end != len(s):

File ~/.pyenv/versions/3.8.12/lib/python3.8/json/decoder.py:355, in JSONDecoder.raw_decode(self, s, idx)
    353     obj, end = self.scan_once(s, idx)
    354 except StopIteration as err:
--> 355     raise JSONDecodeError("Expecting value", s, err.value) from None
    356 return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.9.0
            pydantic compiled: True
                 install path: /Users/{username}/.pyenv/versions/3.8.12/lib/python3.8/site-packages/pydantic
               python version: 3.8.12 (default, Oct 17 2022, 16:48:14)  [Clang 13.1.6 (clang-1316.0.21.2.5)]
                     platform: macOS-12.6.2-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [X] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by dhruvrajan** [comment] 2023-01-25 18:38
Digging into the implementation, it seems that `parse_raw_as` can return any of `pydantic.ValidationError, json.JSONDecodeError, TypeError, RuntimeError`

**Comment by hramezani** [comment] 2023-01-26 13:45
It's returning `json.JSONDecodeError` because it can't parse the value `"True"` to json. so the error happens in converting string to json not in validation or parsing.

You will get a `pydantic.ValidationError` if you parse a valid json like:

```shell
>>> pydantic.parse_raw_as(int, "{}")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hasan/work/pydantic/pydantic/tools.py", line 82, in parse_raw_as
    return parse_obj_as(type_, obj, type_name=type_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hasan/work/pydantic/pydantic/tools.py", line 38, in parse_obj_as
    return model_type(__root__=obj).__root__
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hasan/work/pydantic/pydantic/main.py", line 342, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for ParsingModel[int]
__root__
  value is not a valid integer (type=type_error.integer)
```

I think we can close this issue because or wrap string conversion error with `pydantic.ValidationError` which is not good IMHO.

What do you think @samuelcolvin

**Comment by dhruvrajan** [comment] 2023-01-26 15:09
This behavior though, is different than the behaviour with normal model fields. If you pass`True`into a bool or strictbool field within a model, the jsondecodeerror gets wrapped by ValidationError.

Would be good to keep the behaviour consistent.
For my usecase it's important to know which errors might be thrown so that they can be caught explicitly, ideally without simply catching Base exception.

**Comment by hramezani** [comment] 2023-01-26 15:23
> This behavior though, is different than the behaviour with normal model fields. If you passTrueinto a bool or strictbool field within a model, the jsondecodeerror gets wrapped by ValidationError.

Are you sure that you get `json.JSONDecodeError` wrapped by `pydantic.ValidationError`? Could you provide an example?

**Comment by samuelcolvin** [comment] 2023-01-26 18:56
Confirmed, thanks for reporting.

Question is whether fixing this in V1.10 would qualify as a breaking change? I think it might.

it'll definitely be fixed in V2 as all JSON parsing happens in pydantic-core, and `parse_raw_as` will be replaced by `validate`, see #4669.

**Comment by dhruvrajan** [comment] 2023-01-26 19:17
Thanks @samuelcolvin — that's cool to hear about V2!

I think it would be good to update this in V1.10—anyone explicitly catching `json.JSONDecodeError` must also be catching `ValidationError`, so I wouldn't consider it a breaking change. It's significantly better to know which exceptions might be thrown—otherwise, you have to catch `Exception` everywhere, which isn't great practice.

Happy to provide the PR if you agree.

**Comment by hramezani** [comment] 2023-01-26 21:25
Thanks @dhruvrajan for clearing this up.
Agree with @samuelcolvin, it will be a breaking change in `1.10.x`. Will be fixed in V2

**Comment by dhruvrajan** [comment] 2023-01-26 23:22
All makes sense!—That's a good tip, I'll use `ValueError` then. Thanks for the help.

Looking forward to the V2 release! Feel free to close the issue.

**Comment by dmontagu** [comment] 2023-05-18 00:09
It seems to me this issue has been resolved in v2 so I'm going to close this now. If you notice related issues in v2 we'd appreciate the reports!

**Closed by dmontagu** 2023-05-18 00:09 UTC
Labels: bug V1
