### ISSUE TITLE
2.10 Running airflow db init fails

### ISSUE THREAD

**Issue by kiranvasudev** [pydantic/pydantic#10924] opened 2024-11-21 12:45 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

After the latest release of Pydantic(2.10.0), when running `airflow db init`, i get the following error
![image](https://github.com/user-attachments/assets/2253f168-a8ac-4eef-8511-1de9636d0c65)

This happens when i reinstalled airflow using `apache-airflow[amazon,slack,postgres,s3]==2.9.0`

Currently quick fixed by downgrading pydantic to version 2.9.2.

### Python, Pydantic & OS Version

```Text
Python version: 3.9.17
Pydantic version: 2.10.0
OS version: MacOs 14.1.2
```

**Comment by sydney-runkle** [comment] 2024-11-21 17:03
@kiranvasudev,

Any update here? We're going to do a patch soon, and would be happy to look into this further if you're able to provide an MRE...

**Comment by kiranvasudev** [comment] 2024-11-21 17:09
Apologies @sydney-runkle and @Viicos !

the source of pydantic installation was from the dbt-databricks package.

`pip install dbt-databricks==1.7.0`

**Comment by sydney-runkle** [comment] 2024-11-21 17:11
@kiranvasudev,

Are you able to provide a minimal repro? Thanks!

**Comment by sydney-runkle** [comment] 2024-11-21 17:12
Or, is there any more traceback info that you have?

**Comment by potiuk** [comment] 2024-11-22 09:29
Actually the issue is that there is a lot of code there - like ours that suddently Pydantic 2.10 started to fail with. @sydney-runkle -> I think, to be honest, you will not avoid workarounding this because it will break a lot of the existing installations out there and you should seriously consider tackling the problem differently. Your fix will cause ripple effects in a number of places.

Maybe even you should consider looking closely at other issues. When looking at the issue here I found out that the new version of `dbt-databrick` (which is mentioned here as incompatible) implemented this "fix"

https://github.com/databricks/dbt-databricks/pull/843

> Dbt asked me to not require pydantic > 2 (as it was causing issues). So I wrote all of my pydantic in v1; however, if pydantic v2 got installed, a bunch of warnings would be emitted. So now restricting to < 2.

If I were you, then for me that is a red flag that you are doing something wrong with Pydantic, if they are asking 3rd-party package developers to restrict pydantic to `<2` . This would scare the hell out of me if I were you.

@kiranvasudev -> Both airlfow 2.9 and `dbt-databricks` are pretty fine with Pydantic 1, so If I were to advise you have to fix this problem, I'd strongly recommend to add (at least until this issue is solved ) to add `pydantic <2` - following what the `dbt-databricks` maintainer is doing

**Comment by potiuk** [comment] 2024-11-22 09:30
@sydney-runkle -> my advise would be to talk to `dbt` people and look at making sure they stop recommending others to limit pydantic to `<2`.

**Comment by Viicos** [comment] 2024-11-22 09:50
> I think, to be honest, you will not avoid workarounding this because it will break a lot of the existing installations out there and you should seriously consider tackling the problem differently.

Could you explain better: what is _this_, what is _the problem_?

> Maybe even you should consider looking closely at other issues.

Which other issues?

> If I were you, then for me that is a red flag that you are doing something wrong with Pydantic, if they are asking 3rd-party package developers to restrict pydantic to `<2` . This would scare the hell out of me if I were you.

There have been significant breaking changes in V2 [^1]. As a library, it is challenging to support both V1 and V2 at the same time. FastAPI had to implement a full compatibility layer, there's also [`pydantic-compat`](https://pypi.org/project/pydantic-compat/) that can be used.

So no, seeing library maintainers pinning Pydantic to <2 isn't unusual. Yes we know V2 is hard to transition to.
However, we're happy to help such libraries to transition to V2/support both. It is mentioned in https://github.com/databricks/dbt-databricks/pull/843 that they were asked to not require V2 as _it was causing issues_, would be great knowing which ones. We can certainly get in touch with them.

> Both airlfow 2.9 and `dbt-databricks` are pretty fine with Pydantic 1, so If I were to advise you have to fix this problem, I'd strongly recommend to add (at least until this issue is solved ) to add `pydantic <2` - following what the `dbt-databricks` maintainer is doing

Regarding the issue the author of this post, I responded [here](https://github.com/apache/airflow/pull/44249#issuecomment-2491919741).

[^1]: It has been (and still is) difficult for people to migrate. We even got [reports](https://github.com/pydantic/pydantic/issues/6523) from people asking to publish V2 under a different library name.

**Comment by potiuk** [comment] 2024-11-22 11:54
> Could you explain better: what is this, what is the problem?

I am not sure honestly. I just saw this:

https://github.com/databricks/dbt-databricks/pull/843

> Dbt asked me to not require pydantic > 2 (as it was causing issues). So I wrote all of my pydantic in v1; however, if pydantic > v2 got installed, a bunch of warnings would be emitted. So now restricting to < 2.

And this PR is effectively limiting Pydantic for dbt-databricks to <2. So probably you should reach out to @benc-db and check with them what kinf of issues caused the `dbt` team to ask 3rd-party to limit Pydantic to <2. 

I am merely quoting what I saw from one of the dependencies (`dbt-databricks`) that many of our users use - and seeing that in the RC version of theirs, they limit  Pydantic to < 2 is a bit concerning, taking into accoun that the (upcoming in 3 months) Airflow 3 is `>2.10.1` now (after I just merged https://github.com/apache/airflow/pull/44284 ). This will mean that in the current state of `dbt-databricks` - it will be incompatible with Airflow 3. Which is concerning - but really something that Pydantic , dbt and dbt-databricks maintainers should solve between themselves - while it impacts Airflow in the future, there is absolutely nothing we can do about it, unfortunately.

For you @Viicos, it's just friendly information that there are some problems that impact wider ecosystem, and possibly you should pay attention.

**Closed** 2024-11-22 14:54 UTC
Labels: bug V2, pending, awaiting author response

**Comment by potiuk** [comment] 2024-11-23 22:44
> @kiranvasudev, upgrading to the latest version of apache-airflow should fix your issue. Since 2.9.0, a new dependency was added to support the new union type syntax.

Just to clarify - not really @kiranvasudev, The `eval-type-backport` has been added as depedency in the latest Airflow 3 - it is not present as a dependency in 2.9.0 nor in 2.10.0 it has only been added in the main verison of Airflow - which in few months is goign to be released as Airflow 3. But for now, you have to install `eval-type-backport` yourself.
