### ISSUE TITLE
default_factory passed in annotation Field silently ignored

### ISSUE THREAD

**Issue by charles-dyfis-net** [pydantic/pydantic#9947] opened 2024-07-23 17:25 UTC
```
from typing import Annotated
from pydantic import Field
import pydantic.dataclasses

@pydantic.dataclasses.dataclass()
class ExampleReproducer:
    val2: Annotated[int, Field(default_factory=lambda: 3)]

value = ExampleReproducer()
```

...fails:

```none
Traceback (most recent call last):
  File "test_pydantic.py", line 11, in <module>
    value = ExampleReproducer()
            ^^^^^^^^^^^^^^^^^^^
  File "/nix/store/fcjbczh74z9hx7ingvb5ydsa9fv5y81q-python3-3.12.4-env/lib/python3.12/site-packages/pydantic/_internal/_dataclasses.py", line 140, in __init__
    s.__pydantic_validator__.validate_python(ArgsKwargs(args, kwargs), self_instance=s)
pydantic_core._pydantic_core.ValidationError: 1 validation error for ExampleReproducer
val2
  Field required [type=missing, input_value=ArgsKwargs(()), input_type=ArgsKwargs]
    For further information visit https://errors.pydantic.dev/2.7/v/missing
```

If these values can't be honored in this context, perhaps we should throw a warning or error?

**Comment by sydney-runkle** [comment] 2024-07-24 15:23
Interesting, looks like this works for `BaseModel`s but not dataclasses.

**Comment by sydney-runkle** [comment] 2024-07-24 15:27
PRs welcome. I can try to address in v2.9 if this hasn't been picked up by then. I'm guessing a fix would be in `make_pydantic_fields_compatible` in `dataclasses.py`

**Comment by AlessandroMiola** [comment] 2024-07-24 21:28
Hi @sydney-runkle, I'd be interested in investigating it further. If you could assign it to me, I would try and get back to you in case I am not able to find a solution.
From a rapid analysis, the issue seems to be due to `Annotated` as the following examples do work

    from dataclasses import field
    from typing import Annotated
    
    import pydantic.dataclasses
    from pydantic import BaseModel, Field
    
    
    @pydantic.dataclasses.dataclass()
    class ExampleReproducer:
        val2: int = field(default_factory=lambda: 3)
    
    value = ExampleReproducer()

and 

    from dataclasses import field
    from typing import Annotated
    
    import pydantic.dataclasses
    from pydantic import BaseModel, Field
    
    
    @pydantic.dataclasses.dataclass()
    class ExampleReproducer:
        val2: int = Field(default_factory=lambda: 3)
    
    value = ExampleReproducer()

**Comment by Viicos** [comment] 2024-07-25 12:31
Just out of curiosity: wasn't this on purpose? The [docs](https://docs.pydantic.dev/latest/concepts/dataclasses/) mentions:

> Keep in mind that `pydantic.dataclasses.dataclass` is not a replacement for `pydantic.BaseModel`. `pydantic.dataclasses.dataclass` provides a similar functionality to `dataclasses.dataclass` with the addition of Pydantic validation. There are cases where subclassing `pydantic.BaseModel` is the better choice.

It is also mentioned in the [linked thread](https://github.com/pydantic/pydantic/issues/710#issuecomment-530751709) that Pydantic dataclasses act as a drop in replacement for stdlib dataclasses, only with validation added.

**Closed** 2024-07-25 15:04 UTC
Labels: help wanted, bug V2, good first issue
