### ISSUE TITLE
Inconsistent behavior of pydantic.dataclasses cython version

### ISSUE THREAD

**Issue by emontnemery** [pydantic/pydantic#10387] opened 2024-09-11 11:47 UTC
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

The behavior of `pydantic.dataclasses` is inconsistent when the cython wheel is installed, and seems to somehow be affected by the global state.

In the examples below, the behaviour of the `Test` class is different depending on if the statement `x = Optional[Union[int, float]]` is executed before the `Test` class is declared.

### Example Code

```Python
# test1.py
from typing import Optional, Union
from pydantic.v1.dataclasses import dataclass

x = Optional[Union[int, float]]

@dataclass
class Test:
    attribute: Optional[Union[float, int]] = None

test = Test(attribute=1)
print(f"type(test.attribute): {type(test.attribute)}")
# outputs type(test.attribute): <class 'int'>

# test2.py
from typing import Optional, Union
from pydantic.v1.dataclasses import dataclass

@dataclass
class Test:
    attribute: Optional[Union[float, int]] = None

test = Test(attribute=1)
print(f"type(test.attribute): {type(test.attribute)}")
# outputs type(test.attribute): <class 'float'>
```

### Python, Pydantic & OS Version

```Text
python -c "import pydantic.utils; print(pydantic.utils.version_info())"
             pydantic version: 1.10.18
            pydantic compiled: True
                 install path: /home/erik/pydantic_test/.venv/lib/python3.12/site-packages/pydantic
               python version: 3.12.2 (main, Mar 25 2024, 20:29:48) [GCC 9.4.0]
                     platform: Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [X] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by Viicos** [comment] 2024-09-11 13:31
This is a known issue related to how Python deals with caching of unions. You can find more info about it here:
- https://discuss.python.org/t/changing-runtime-behavior-of-types-uniontype-to-respect-order-in-equality-and-hashing/26071
- https://github.com/python/cpython/issues/101859#issuecomment-1627713664

Going to close as a duplicate of https://github.com/pydantic/pydantic/issues/4519.

**Closed by Viicos** 2024-09-11 13:31 UTC
Labels: bug V1, pending
