### ISSUE TITLE
`TypeAdapter` with Union has `Any` type hint argument starting with Pydantic 2.7.0+

### ISSUE THREAD

**Issue by mark-henry01** [pydantic/pydantic#9532] opened 2024-05-31 09:28 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hi, with Pydantic versions 2.7.0+, I cannot have proper type hints for `TypeAdapter` in combination with `Union` / `|`. Versions 2.6.x work properly (see example below). Note this is about type hints for the IDE and not about runtime validation. Most recent Pyright/Basedpyright `v1.12.4 (pyright 1.1.365)` is used as Language server, but issue is independent of its used version.

### Pydantic v2.6.4
(Comments show static type hints by IDE)
```python
from pydantic import TypeAdapter

ad1 = TypeAdapter(str | int) # ad1: TypeAdapter[UnionType]
ad2 = TypeAdapter[str | int](str | int) # ad1: TypeAdapter[str | int]

result1 = ad1.validate_python("foo") # result1: UnionType
result2 = ad2.validate_python(42) # result2: str | int
```

It would be best, if `TypeAdapter` for `ad1` could infer `str | int` directly. At least I can annotate types manually.
If no manual type is given, type argument is `UnionType`.

### Pydantic v2.7.0+
(Comments show static type hints by IDE)
```python
from pydantic import TypeAdapter

ad1 = TypeAdapter(str | int) # ad1:TypeAdapter[Any]
ad2 = TypeAdapter[str | int](str | int) # ad2:TypeAdapter[Any]

result1 = ad1.validate_python("foo") # result1: Any
result2 = ad2.validate_python(42) # result2: Any
```

This is kind of downgrade, as `UnionType` is more specific than `Any`. `Any` also leads to IDE errors, if forbidden by linting rules, like configurable with [basedpyright](https://github.com/DetachHead/basedpyright#user-content-reportany---fully-ban-the-any-type). Last I'd like to still annotate an explicit type argument `[str | int]`, if type could not be inferred, which still results in `Any` with 2.7.0+.

### Reproduction

For most simple error reproduction on command-line and to prove occurence of `Any` type, copy above snippet in `main.py` and invoke `basedpyright` on it (or use IDE of choice with `pyright` and hover over types):

```sh
(venv) $ basedpyright main.py
/path/to/proj/main.py
  /path/to/proj/main.py:8:1 - error: Type of "result1" is Any (reportAny)
  /path/to/proj/main.py:9:1 - error: Type of "result2" is Any (reportAny)
2 errors, 0 warnings, 0 notes
```

Same happens with older `Basedpyright` versions. Hence I assume, this must be some kind of issue with Pydantic. Thanks for any help.

### Example Code

See above.

### Python, Pydantic & OS Version

```Text
pydantic version: 2.7.2
        pydantic-core version: 2.18.3
          pydantic-core build: profile=release pgo=true
               python version: 3.12.3 (main, Apr 17 2024, 00:00:00)
                     platform: Fedora 39
             related packages: typing_extensions-4.12.0 typing_extensions-4.12.0
                       commit: unknown
```

**Comment by Viicos** [comment] 2024-05-31 15:55
Duplicate of https://github.com/pydantic/pydantic/issues/9147, https://github.com/pydantic/pydantic/discussions/7094

https://discuss.python.org/t/typeform-spelling-for-a-type-annotation-object-at-runtime/51435 is what's needed for `TypeAdapter` to work with special forms

**Comment by mark-henry01** [comment] 2024-06-01 06:43
Hi @Viicos, thanks for mentioning those issues. 

Was a breaking change needed for Pydantic `2.7.x`? What I tried to express is that current behavior is a *regression* to earlier Pydantic versions `2.6.x` from start of this year.
It already was possible to narrow types by manually specifying the generic type argument for `TypeAdapter`, e.g. `TypeAdapter[str | int](str | int)`. This is not possible with `2.7.x`, given same development environment. Also  `UnionType` from `2.6.x` would be a better choice than `Any` due to reasons mentioned above.

**Comment by sydney-runkle** [comment] 2024-06-03 15:58
Closing as a duplicate!

**Closed by sydney-runkle** 2024-06-03 15:58 UTC
Labels: bug V2, pending

**Comment by Viicos** [comment] 2024-06-03 17:39
> Hi @Viicos, thanks for mentioning those issues. Has there been a breaking change for Pydantic `2.7.x`? What I tried to express is that current behavior is a _regression_ to earlier Pydantic versions `2.6.x` from start of this year.
> 
> It already was possible to narrow types by manually specifying the generic type argument for `TypeAdapter`, e.g. `TypeAdapter[str | int](str | int)`. This is not possible with `2.7.x`, given same development environment. Alos `UnionType` from `2.6.x` would be a better choice than `Any` without manual annotation due to above reasons.

This due to this change: https://github.com/pydantic/pydantic/pull/8923

I'm not sure why this was changed, but it is definitely a regression since 2.6. As a side note, the typing spec was recently updated (see https://github.com/python/typing/pull/1667) and the current `TypeAdapter.__init__` overloads are now invalid wrt to the specification (mixing class based and function based type variables).

I'll come with a PR to update `pyright` -- which will catch this issue -- and update the overloads accordingly.

**Comment by Viicos** [comment] 2026-07-17 16:10
https://github.com/pydantic/pydantic/pull/13459 adds support for [`TypeForm`](https://docs.python.org/3.15/library/typing.html#typing.TypeForm) introduced by [PEP 747](https://peps.python.org/pep-0747/), which fixes the encountered type checking issue.

This will be available in the next release.
