### ISSUE TITLE
Pydantic generates an extra allOf when providing default value of enum type

### ISSUE THREAD

**Issue by charlax** [pydantic/pydantic#2592] opened 2021-03-29 10:38 UTC
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.1
            pydantic compiled: True
                 install path: /Users/ca/Library/Caches/pypoetry/virtualenvs/pydantic-all-of-M52nj_Ql-py3.9/lib/python3.9/site-packages/pydantic
               python version: 3.9.2 (default, Mar 26 2021, 23:22:38)  [Clang 12.0.0 (clang-1200.0.32.29)]
                     platform: macOS-11.2.2-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

```py
import enum
from typing import Optional

from pydantic import Field, BaseModel


class Color(enum.Enum):
    red = "red"
    blue = "blue"


class Toaster(BaseModel):
    color: Color
    optional_color: Optional[Color]
    optional_color_2: Optional[Color] = Field(None)
    optional_color_3: Optional[Color] = Field(Color.blue)


print(Toaster.schema_json(indent=2))
```

generates the following json schema:

```json
{
  "title": "Toaster",
  "type": "object",
  "properties": {
    "color": {
      "$ref": "#/definitions/Color"
    },
    "optional_color": {
      "$ref": "#/definitions/Color"
    },
    "optional_color_2": {
      "$ref": "#/definitions/Color"
    },
    "optional_color_3": {
      "default": "blue",
      "allOf": [
        {
          "$ref": "#/definitions/Color"
        }
      ]
    }
  },
  "required": [
    "color"
  ],
  "definitions": {
    "Color": {
      "title": "Color",
      "description": "An enumeration.",
      "enum": [
        "red",
        "blue"
      ]
    }
  }
}
```

Everything seems right, except the superfluous `allOf` for `optional_color_3`. It seems related to #1209.

**Comment by charlax** [comment] 2021-03-29 13:53
Actually, now that I'm reading this carefully it makes sense, the `allOf` allows specifying the default value.

**Comment by m10d** [comment] 2022-04-17 02:24
@charlax - would you mind elaborating on your conclusion this is expected?  

`optional_color_2` and `optional_color_3` have *identical* annotations, it would seem they should have an identical `schema` definition?

We're seeing the same result in a different use case, it seems the author sees it as a bug, wondering if these are only superficially related or not.

**Comment by dmontagu** [comment] 2023-04-27 21:10
@m10d the JSON schema _also_ reflects the default value for the field. Therefore, it requires modifying the field that would otherwise just have a `$ref`. However, JSON schema does not support putting sibling fields on any (sub)schema which has a `$ref` key. The way you get around this is by putting the `$ref` schema in an `allOf` key with a single item list, and add any other desired modifications to the ref'ed schema as sibling keys next to the `allOf`. (I have seen the clearest documentation of this in the OpenAPI/swagger docs, but it does also apply to JSON schema.)

Closing this issue since as @charlax noted, I think the behavior is indeed correct.

**Closed by dmontagu** 2023-04-27 21:10 UTC
Labels: bug V1

**Comment by donkersgoed-postnl** [comment] 2023-09-16 07:55
@dmontagu I've got a case where the extra allOf is a problem. We use Pydantic to generate JSON Schema for AWS API Gateway. We use the CDK like this:
```python
ResourceProperties(
    construct_id="UpdateSubscription",
    lambda_src_path="/update",
    rest_api_resource=self._resource_with_id,
    http_method="PUT",
    request_schema=UpdateSubscriptionRequest.as_json_schema_draft_4(),
    response_schema=UpdateSubscriptionResponse.as_json_schema_draft_4()
)
```

This worked well with Pydantic 1.10, but after upgrading to 2.3 some request / response models were no longer generated by API Gateway. We traced the "root cause" to Pydantic 2 adding an additional `allOf`. Pydantic 1 rendered our models like this:
```json
      "action_log": {
         "$ref": "#/definitions/SubscriptionActionLog"
      },
```

But Pydantic 2 does it like this:
```json
      "action_log": {
       "allOf": [
        {
         "$ref": "#/definitions/SubscriptionActionLog"
        }
       ]
      },
```

I understand that this is semantically the same, and both are correct. However, AWS API Gateway - which is a system outside of my control - accepts the former but not the latter.

Having the ability to control this behavior would be very valuable to me.

**Comment by orange-pig** [comment] 2023-12-22 02:41
this is a problem for me, what time to supported that configurable the behavior prefrence with allof and anyof.

**Comment by codebutler** [comment] 2024-02-22 20:14
> If this is a problem for you, please comment and we can potentially re-open the issue to make this behavior more configurable.

@dmontagu hi, can you please reconsider this behavior now that 3.1 has been around for quite a while?

**Comment by nicksellen** [comment] 2024-06-26 13:18
I'd appreciate an option to enable or disable the behaviour (whether to allow siblings when there is a `$ref`).
