### ISSUE TITLE
`Invalid Schema` in decimal type

### ISSUE THREAD

**Issue by mo1ein** [pydantic/pydantic#7259] opened 2023-08-26 07:20 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When I'm using `None` as a default value in `Field` for decimal type, I got error.
```
pydantic_core._pydantic_core.SchemaError: Invalid Schema:
model.schema.model-fields.fields.amount.schema.default.schema.nullable.schema.function-after.max_digits
  Extra inputs are not permitted [type=extra_forbidden, input_value=32, input_type=int]
    For further information visit https://errors.pydantic.dev/2.1.2/v/extra_forbidden
model.schema.model-fields.fields.amount.schema.default.schema.nullable.schema.function-after.decimal_places
  Extra inputs are not permitted [type=extra_forbidden, input_value=16, input_type=int]
    For further information visit https://errors.pydantic.dev/2.1.2/v/extra_forbidden
```

### Example Code

```Python
from decimal import Decimal

from pydantic import BaseModel, Field


class Wallet(BaseModel):
    name: str
    amount: Decimal | None = Field(default=None, max_digits=32, decimal_places=16)


my_wallet = Wallet(name='moein', amount=Decimal('0.005'))
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.2
        pydantic-core version: 2.1.2 release build profile
                 install path: /home/moein/n/invex-services-serve/venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.4 (main, Jun  7 2023, 12:45:48) [GCC 11.3.0]
                     platform: Linux-5.19.0-50-generic-x86_64-with-glibc2.35
     optional deps. installed: ['email-validator', 'typing-extensions']
```

Selected Assignee: @adriangb

**Comment by Firescar96** [comment] 2023-08-27 15:38
Is your issue a duplicate of this issue: https://github.com/pydantic/pydantic/issues/6955
I was also confused by this error after migrating to pydantic v2.

**Comment by adriangb** [comment] 2023-08-27 15:42
Indeed it does seem like it’s a duplicate of that issue. You’ll have to do `Annotated[Decimal, Field(…)] | None`.

**Closed by adriangb** 2023-08-27 15:42 UTC
Labels: unconfirmed, bug V2

**Comment by mo1ein** [comment] 2023-08-28 05:34
OK but I can't use `default` in `Field`. Where can I use `default`? (I know the problem solved with `=None`)

```python
from typing import Annotated

from pydantic import BaseModel, Field
from decimal import Decimal

class Wallet(BaseModel):
    name: str
    amount: Annotated[Decimal, Field(default=None, decimal_places=16, max_digits=32)] | None

my_wallet = Wallet(name='moein')
```

**Comment by adriangb** [comment] 2023-08-28 12:14
`default` applies to the field itself (a type can't really have a default in the abstract) so it needs to be at the outer level (either in `Annotated` or as part of a `Field` or plain default value):

```python
from typing import Annotated

from pydantic import BaseModel, Field
from decimal import Decimal

class Wallet(BaseModel):
    name: str
    amount: Annotated[Decimal, Field(decimal_places=16, max_digits=32)] | None = None
    # or
    # amount: Annotated[Decimal, Field(decimal_places=16, max_digits=32)] | None = Field(None)
    # or, but type checkers won't like it as much
    # amount: Annotated[Annotated[Decimal, Field(decimal_places=16, max_digits=32)] | None, Field(None)]

my_wallet = Wallet(name='moein')
```
