### ISSUE TITLE
(2.4.0) After upgrading from v2.3 the old worked code starts raising SchemaError

### ISSUE THREAD

**Issue by MarshalX** [pydantic/pydantic#7638] opened 2023-09-26 13:00 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hi! After upgrading from pydantic v2.3 to v2.4 the worked codebase started raising `pydantic_core._pydantic_core.SchemaError`

Maybe rebuilding all project models on import is a tricky solution in `atproto` package but I didn't expect breaking changes from v2.3 to v2.4. I hope that's new pydantic bug. Thank you!

```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/ilyasiamionau/anaconda3/lib/python3.11/site-packages/atproto/__init__.py", line 3, in <module>
    from .firehose import models as firehose_models
  File "/Users/ilyasiamionau/anaconda3/lib/python3.11/site-packages/atproto/firehose/__init__.py", line 3, in <module>
    from atproto.firehose.client import AsyncFirehoseClient, FirehoseClient
  File "/Users/ilyasiamionau/anaconda3/lib/python3.11/site-packages/atproto/firehose/client.py", line 22, in <module>
    from atproto.firehose.models import ErrorFrame, Frame, MessageFrame
  File "/Users/ilyasiamionau/anaconda3/lib/python3.11/site-packages/atproto/firehose/models.py", line 7, in <module>
    from atproto.xrpc_client.models.utils import get_or_create
  File "/Users/ilyasiamionau/anaconda3/lib/python3.11/site-packages/atproto/xrpc_client/models/__init__.py", line 275, in <module>
    load_models()
  File "/Users/ilyasiamionau/anaconda3/lib/python3.11/site-packages/atproto/xrpc_client/models/models_loader.py", line 58, in load_models
    __on_load()
  File "/Users/ilyasiamionau/anaconda3/lib/python3.11/site-packages/atproto/xrpc_client/models/models_loader.py", line 54, in __on_load
    __rebuild_all_models()
  File "/Users/ilyasiamionau/anaconda3/lib/python3.11/site-packages/atproto/xrpc_client/models/models_loader.py", line 50, in __rebuild_all_models
    __model.model_rebuild()
  File "/Users/ilyasiamionau/anaconda3/lib/python3.11/site-packages/pydantic/main.py", line 470, in model_rebuild
    return _model_construction.complete_model_class(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ilyasiamionau/anaconda3/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 498, in complete_model_class
    cls.__pydantic_core_schema__ = schema = validate_core_schema(schema)
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ilyasiamionau/anaconda3/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 631, in validate_core_schema
    return _validate_core_schema(schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.SchemaError: Invalid Schema:
definitions.definitions.55.model.schema.model-fields.fields.parent.schema.default.schema.nullable.schema.default.schema.tagged-union.choices.`app.bsky.feed.defs#threadViewPost`
  Recursion error - cyclic reference detected [type=recursion_loop, input_value={'type': 'model', 'cls': ...eadViewPost:4873274336'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.4/v/recursion_loop
definitions.definitions.55.model.schema.model-fields.fields.replies.schema.default.schema.nullable.schema.list.items_schema.tagged-union.choices.`app.bsky.feed.defs#threadViewPost`
  Recursion error - cyclic reference detected [type=recursion_loop, input_value={'type': 'model', 'cls': ...eadViewPost:4873274336'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.4/v/recursion_loop
```

### Example Code

```Python
pip install atproto
pip install pydantic==2.3
python -c "import atproto; print(atproto.__version__)"
pip install pydantic==2.4
python -c "import atproto; print(atproto.__version__)"
```

### Python, Pydantic & OS Version

```Text
             pydantic version: 2.4.0
        pydantic-core version: 2.10.0
          pydantic-core build: profile=release pgo=false
                 install path: /Users/ilyasiamionau/anaconda3/lib/python3.11/site-packages/pydantic
               python version: 3.11.4 (main, Jul  5 2023, 08:54:11) [Clang 14.0.6 ]
                     platform: macOS-13.6-arm64-arm-64bit
             related packages: typing_extensions-4.7.1
```

**Comment by hramezani** [comment] 2023-09-26 13:05
Thanks @MarshalX for reporting this 🙏 

I think this is a duplicate of #7611 and fixed on `main`.

LMK if it's not fixed on `main` for you.

**Comment by MarshalX** [comment] 2023-09-26 13:10
> Thanks @MarshalX for reporting this 🙏
> 
> I think this is a duplicate of #7611 and fixed on `main`.
> 
> LMK if it's not fixed on `main` for you.

Thank you for your quick response! I installed pydantic from the main branch using these commands: 
```shell
pip uninstall pydantic
pip install -U git+https://github.com/pydantic/pydantic.git@main
```

Now It raises `KeyError: 'atproto.xrpc_client.models.app.bsky.feed.defs.ThreadgateView:4814129888'`

```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/ilyasiamionau/anaconda3/lib/python3.11/site-packages/atproto/__init__.py", line 3, in <module>
    from .firehose import models as firehose_models
  File "/Users/ilyasiamionau/anaconda3/lib/python3.11/site-packages/atproto/firehose/__init__.py", line 3, in <module>
    from atproto.firehose.client import AsyncFirehoseClient, FirehoseClient
  File "/Users/ilyasiamionau/anaconda3/lib/python3.11/site-packages/atproto/firehose/client.py", line 22, in <module>
    from atproto.firehose.models import ErrorFrame, Frame, MessageFrame
  File "/Users/ilyasiamionau/anaconda3/lib/python3.11/site-packages/atproto/firehose/models.py", line 7, in <module>
    from atproto.xrpc_client.models.utils import get_or_create
  File "/Users/ilyasiamionau/anaconda3/lib/python3.11/site-packages/atproto/xrpc_client/models/__init__.py", line 275, in <module>
    load_models()
  File "/Users/ilyasiamionau/anaconda3/lib/python3.11/site-packages/atproto/xrpc_client/models/models_loader.py", line 58, in load_models
    __on_load()
  File "/Users/ilyasiamionau/anaconda3/lib/python3.11/site-packages/atproto/xrpc_client/models/models_loader.py", line 54, in __on_load
    __rebuild_all_models()
  File "/Users/ilyasiamionau/anaconda3/lib/python3.11/site-packages/atproto/xrpc_client/models/models_loader.py", line 50, in __rebuild_all_models
    __model.model_rebuild()
  File "/Users/ilyasiamionau/anaconda3/lib/python3.11/site-packages/pydantic/main.py", line 470, in model_rebuild
    return _model_construction.complete_model_class(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ilyasiamionau/anaconda3/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 495, in complete_model_class
    schema = apply_discriminators(simplify_schema_references(schema))
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ilyasiamionau/anaconda3/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 519, in simplify_schema_references
    schema = walk_core_schema(schema, count_refs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ilyasiamionau/anaconda3/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 439, in walk_core_schema
    return f(schema, _dispatch)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/ilyasiamionau/anaconda3/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 515, in count_refs
    recurse(state['definitions'][ref], count_refs)
  File "/Users/ilyasiamionau/anaconda3/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 215, in walk
    return f(schema, self._walk)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ilyasiamionau/anaconda3/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 503, in count_refs
    return recurse(s, count_refs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ilyasiamionau/anaconda3/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 218, in _walk
    schema = self._schema_type_to_method[schema['type']](schema, f)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ilyasiamionau/anaconda3/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 227, in _handle_other_schemas
    schema['schema'] = self.walk(sub_schema, f)  # type: ignore
                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ilyasiamionau/anaconda3/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 215, in walk
    return f(schema, self._walk)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ilyasiamionau/anaconda3/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 503, in count_refs
    return recurse(s, count_refs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ilyasiamionau/anaconda3/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 218, in _walk
    schema = self._schema_type_to_method[schema['type']](schema, f)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ilyasiamionau/anaconda3/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 362, in handle_model_fields_schema
    replaced_field['schema'] = self.walk(v['schema'], f)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ilyasiamionau/anaconda3/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 215, in walk
    return f(schema, self._walk)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ilyasiamionau/anaconda3/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 503, in count_refs
    return recurse(s, count_refs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ilyasiamionau/anaconda3/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 218, in _walk
    schema = self._schema_type_to_method[schema['type']](schema, f)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ilyasiamionau/anaconda3/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 323, in handle_union_schema
    new_choices.append(self.walk(v, f))
                       ^^^^^^^^^^^^^^^
  File "/Users/ilyasiamionau/anaconda3/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 215, in walk
    return f(schema, self._walk)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ilyasiamionau/anaconda3/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 515, in count_refs
    recurse(state['definitions'][ref], count_refs)
  File "/Users/ilyasiamionau/anaconda3/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 218, in _walk
    schema = self._schema_type_to_method[schema['type']](schema, f)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ilyasiamionau/anaconda3/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 227, in _handle_other_schemas
    schema['schema'] = self.walk(sub_schema, f)  # type: ignore
                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ilyasiamionau/anaconda3/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 215, in walk
    return f(schema, self._walk)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ilyasiamionau/anaconda3/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 503, in count_refs
    return recurse(s, count_refs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ilyasiamionau/anaconda3/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 218, in _walk
    schema = self._schema_type_to_method[schema['type']](schema, f)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ilyasiamionau/anaconda3/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 362, in handle_model_fields_schema
    replaced_field['schema'] = self.walk(v['schema'], f)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ilyasiamionau/anaconda3/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 215, in walk
    return f(schema, self._walk)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ilyasiamionau/anaconda3/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 503, in count_refs
    return recurse(s, count_refs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ilyasiamionau/anaconda3/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 218, in _walk
    schema = self._schema_type_to_method[schema['type']](schema, f)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ilyasiamionau/anaconda3/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 227, in _handle_other_schemas
    schema['schema'] = self.walk(sub_schema, f)  # type: ignore
                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ilyasiamionau/anaconda3/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 215, in walk
    return f(schema, self._walk)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ilyasiamionau/anaconda3/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 503, in count_refs
    return recurse(s, count_refs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ilyasiamionau/anaconda3/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 218, in _walk
    schema = self._schema_type_to_method[schema['type']](schema, f)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ilyasiamionau/anaconda3/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 227, in _handle_other_schemas
    schema['schema'] = self.walk(sub_schema, f)  # type: ignore
                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ilyasiamionau/anaconda3/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 215, in walk
    return f(schema, self._walk)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ilyasiamionau/anaconda3/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 515, in count_refs
    recurse(state['definitions'][ref], count_refs)
            ~~~~~~~~~~~~~~~~~~~~^^^^^
KeyError: 'atproto.xrpc_client.models.app.bsky.feed.defs.ThreadgateView:4814129888'
```

p.s. each run the key is different

**Comment by hramezani** [comment] 2023-09-26 13:11
Could you please share an example code that help us to reproduce the problem?

**Comment by MarshalX** [comment] 2023-09-26 13:16
> Could you please share an example code that help us to reproduce the problem?

sorry, i rly don't understand this traceback from pydantic _internal module and i don't think that i can separate a small piece of the `atproto` project to small reproducible example. the model's codebase of `atproto` package is huge 

the reproduce it pretty easily with importing as i described in the issue:
```shell
pip install atproto
python -c "import atproto; print(atproto.__version__)"
```

**Comment by hramezani** [comment] 2023-09-26 18:18
It got fixed in `main`.

@MarshalX Could you please test it again?

**Comment by MarshalX** [comment] 2023-09-26 19:37
> It got fixed in `main`.
> 
> @MarshalX Could you please test it again?

You are awesome! It works! Also, I ran `atproto`'s unit tests of models. No issues! Sorry again for not providing a good code snippet to reproduce

**Comment by hramezani** [comment] 2023-09-26 20:21
Thanks for letting us know. The fix will be available in the next release soon.

**Closed by hramezani** 2023-09-26 20:21 UTC
Labels: bug V2
