### ISSUE TITLE
`anyOf` causing problems with Swagger/ReDoc on primitive types

### ISSUE THREAD

**Issue by Kludex** [pydantic/pydantic#6647] opened 2023-07-13 11:58 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

If we have an object, and a primite type, we are still creating an `anyOf`. That unfortunately doesn't work well with neither ReDoc nor Swagger.

From the code below, the following OpenAPI spec is generated:

<details><summary>Details</summary>
<p>

```json
{
    "components": {
        "schemas": {
            "HTTPValidationError": {
                "properties": {
                    "detail": {
                        "items": {
                            "$ref": "#/components/schemas/ValidationError"
                        },
                        "title": "Detail",
                        "type": "array"
                    }
                },
                "title": "HTTPValidationError",
                "type": "object"
            },
            "ValidationError": {
                "properties": {
                    "loc": {
                        "items": {
                            "type": ["string", "integer"]
                        },
                        "title": "Location",
                        "type": "array"
                    },
                    "msg": {
                        "title": "Message",
                        "type": "string"
                    },
                    "type": {
                        "title": "Error Type",
                        "type": "string"
                    }
                },
                "required": [
                    "loc",
                    "msg",
                    "type"
                ],
                "title": "ValidationError",
                "type": "object"
            }
        }
    },
    "info": {
        "title": "FastAPI",
        "version": "0.1.0"
    },
    "openapi": "3.1.0",
    "paths": {
        "/": {
            "get": {
                "operationId": "root__get",
                "parameters": [
                    {
                        "description": "Date to query",
                        "in": "query",
                        "name": "at",
                        "required": false,
                        "schema": {
                            "anyOf": [
                                {
                                    "enum": [
                                        "today",
                                        "tomorrow",
                                        "yesterday"
                                    ],
                                    "type": "string"
                                },
                                {
                                    "type": "null"
                                }
                            ],
                            "description": "Date to query",
                            "title": "At"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        },
                        "description": "Successful Response"
                    },
                    "422": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/HTTPValidationError"
                                }
                            }
                        },
                        "description": "Validation Error"
                    }
                },
                "summary": "Root"
            }
        }
    }
}
```

</p>
</details> 

Ideally, we'd have the following schema:

<details><summary>Details</summary>
<p>

```json
{
    "components": {
        "schemas": {
            "HTTPValidationError": {
                "properties": {
                    "detail": {
                        "items": {
                            "$ref": "#/components/schemas/ValidationError"
                        },
                        "title": "Detail",
                        "type": "array"
                    }
                },
                "title": "HTTPValidationError",
                "type": "object"
            },
            "ValidationError": {
                "properties": {
                    "loc": {
                        "items": {
                            "anyOf": [
                                {
                                    "type": "string"
                                },
                                {
                                    "type": "integer"
                                }
                            ]
                        },
                        "title": "Location",
                        "type": "array"
                    },
                    "msg": {
                        "title": "Message",
                        "type": "string"
                    },
                    "type": {
                        "title": "Error Type",
                        "type": "string"
                    }
                },
                "required": [
                    "loc",
                    "msg",
                    "type"
                ],
                "title": "ValidationError",
                "type": "object"
            }
        }
    },
    "info": {
        "title": "FastAPI",
        "version": "0.1.0"
    },
    "openapi": "3.1.0",
    "paths": {
        "/": {
            "get": {
                "operationId": "root__get",
                "parameters": [
                    {
                        "description": "Date to query",
                        "in": "query",
                        "name": "at",
                        "required": false,
                        "schema": {
                            "enum": [
                                 "today",
                                 "tomorrow",
                                 "yesterday"
                            ],
                            "type": ["string", "null"]
                            "description": "Date to query",
                            "title": "At"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        },
                        "description": "Successful Response"
                    },
                    "422": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/HTTPValidationError"
                                }
                            }
                        },
                        "description": "Validation Error"
                    }
                },
                "summary": "Root"
            }
        }
    }
}
```

</p>
</details> 

As you can see above, the `type` becomes an array of primitive types. This is mentioned in the [Assertions and Instance Primitive Types](https://json-schema.org/draft/2020-12/json-schema-core.html#name-assertions-and-instance-pri) on the JSON Schema Draft 2020-12.

### Example Code

```Python
from typing import Literal, Annotated

from fastapi import Query, FastAPI

app = FastAPI()


@app.get("/")
def root(
    at: Annotated[
        Literal["today", "tomorrow", "yesterday"] | None,
        Query(
            description="Date to query",
        ),
    ] = None
):
    return at
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.2
        pydantic-core version: 2.2.0 release build profile
                 install path: /Users/marcelotryle/dev/pydantic/pydantic/pydantic
               python version: 3.11.1 (main, Apr 20 2023, 11:08:52) [Clang 14.0.3 (clang-1403.0.22.14.1)]
                     platform: macOS-13.4-arm64-arm-64bit
     optional deps. installed: ['devtools', 'email-validator', 'typing-extensions']
```

Ref.:
- https://github.com/tiangolo/fastapi/discussions/9709#discussioncomment-6415698
- https://github.com/tiangolo/fastapi/discussions/9709#discussioncomment-6437341

Selected Assignee: @dmontagu

**Comment by Kludex** [comment] 2023-07-13 12:24
> You missed the anyOf in ValidationError.

I've fixed it. Thanks 🙏 

> And I'd expect null to be part of the enum due to [json-schema.org/draft/2020-12/json-schema-validation.html#name-enum](https://json-schema.org/draft/2020-12/json-schema-validation.html#name-enum)

Ah, ok. Then 2 issues here. 😅

**Comment by commonism** [comment] 2023-07-13 12:47
Currently `Literal[x]|None` is evaluated via anyOf as well, via const instead of enum

```python
data:Literal["dog"] | None
```

```yaml
        schema:
          anyOf:
          - const: dog
          - type: 'null'
```

Due to the known problems I'd unfold to enum instead of const 

```yaml
schema:
  type: [string, null]
  enum: ["dog", null]
```

The type can be skipped.

```yaml
schema:
  enum: ["dog", null]
```

Skipping the type would even work for mixed enums

```python
data: Literal["a",1,True]|None
```

```yaml
        schema:
          - enum:
            - a
            - 1
            - true
            - null
```

**Comment by rossmacarthur** [comment] 2023-07-18 07:09
Similar issue where previously `null` was shown by removing from the `required` list. Instead there is now an `anyOf` with `null` as one of the fields.

```python
from typing import Optional
from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI()


class RequestModel(BaseModel):
    name: str
    age: Optional[int]


@app.get("/")
def index(req: RequestModel):
    return {"message": "Hello World"}
```

When using **pydantic v1** it returns this OpenAPI schema for RequestModel
```json
"RequestModel": {
    "properties": {
        "name": {
            "type": "string",
            "title": "Name"
        },
        "age": {
            "type": "integer",
            "title": "Age"
        }
    },
    "type": "object",
    "required": [
        "name"
    ],
    "title": "RequestModel"
},
```
When using **pydantic v2** it returns this OpenAPI schema for RequestModel

```json
"RequestModel": {
    "properties": {
        "name": {
            "type": "string",
            "title": "Name"
        },
        "age": {
            "anyOf": [
                {
                    "type": "integer"
                },
                {
                    "type": "null"
                }
            ],
            "title": "Age"
        }
    },
    "type": "object",
    "required": [
        "name",
        "age"
    ],
    "title": "RequestModel"
},
```
I understand that both are basically the same meaing for my purposes however I have code generation that runs off the OpenAPI schema and the former generates better TypeScript code. Is there a way to generate the former?

**Comment by commonism** [comment] 2023-07-18 08:56
Refer to https://docs.pydantic.dev/latest/migration/#required-optional-and-nullable-fields to adjust your model according to your expectation. If you avoid nullable, you won't get the anyOf.

**Comment by rossmacarthur** [comment] 2023-07-18 09:19
@commonism are you suggesting the way to do it would be `age: int = None`?

**Comment by commonism** [comment] 2023-07-18 09:37
v2: `age: int = None` equals v1:`age: Optional[int]` - so I expect it'll behave all the same.

**Comment by dmontagu** [comment] 2023-07-21 20:53
I think the solution of modifying FastAPI to use a custom `GenerateJsonSchema` (the PR that @Kludex opened) is going to be preferable for fixing swagger, as it won't require anything special in user code, and I think it's not reasonable to change what we are currently generating as the JSON schema for `Optional[int]` since it's technically more correct for the type annotation, is definitely what you want for Body parameters, and FastAPI currently generates the openapi spec using functions from pydantic that couldn't be aware of this distinction.

However, once #6798 is merged, it will be possible to do:
```python
import json
from typing import TYPE_CHECKING, Annotated

from pydantic import BaseModel, Field
from pydantic.json_schema import SkipJsonSchema

if TYPE_CHECKING:
    from typing import Optional as OptionalParam
else:
    class OptionalParam:
        def __class_getitem__(cls, item):
            return Annotated[item | SkipJsonSchema[None], Field(json_schema_extra=lambda x: x.pop('default', None))]
```

which will then let you do:
```python
class MyModel(BaseModel):
    x: OptionalParam[int] = None
    y: OptionalParam[int]


print(json.dumps(MyModel.model_json_schema(), indent=2))
"""
{
  "properties": {
    "x": {
      "title": "X",
      "type": "integer"
    },
    "y": {
      "title": "Y",
      "type": "integer"
    }
  },
  "required": [
    "y"
  ],
  "title": "MyModel",
  "type": "object"
}
"""

reveal_type(MyModel.x)
# note: Revealed type is "Union[builtins.int, None]"
reveal_type(MyModel.y)
# note: Revealed type is "Union[builtins.int, None]"
```
which will get you a JSON schema that looks the way it did with Pydantic V1.

Given this, I think after merging that PR it will make sense to close this issue in Pydantic, and instead open a FastAPI issue for the bug (and/or just wait/hope for https://github.com/tiangolo/fastapi/pull/9873 to be merged).

**Comment by commonism** [comment] 2023-07-23 12:14
I consider the quality of the description document the key selling point of pydantic, and as I said - this breaks it.
A description documents consumers model for MyModel behavior is different to the original model, changing the semantics of the model.
Have the library create low quality description documents will decrease developers trust in the library itself and all software using the library.

So let's call it CompatibleOptional, document the shortcomings, and emit "x-nullable: True" as Schema Extension in the dd to document the skipped constraints.
It'll allow updating the CompatibleOptional to be a regular Optional once Swagger/* can do better wrt. to anyOf or maybe pydantic switch to `type: […, "null"]`.

**Comment by Kludex** [comment] 2023-07-24 06:31
> type: […, "null"]

Did you try to generate a Swagger with a schema that contains array as `type`? Can you show me a schema that have a Swagger UI working as you'd expect?

**Comment by commonism** [comment] 2023-07-24 07:01
Use https://editor-next.swagger.io/ 
Import https://raw.githubusercontent.com/commonism/aiopenapi3/pydanticv2/tests/fixtures/schema-discriminated-union-deep.yaml

![image](https://github.com/pydantic/pydantic/assets/164513/c3f13018-f807-479e-87dc-9538d7e811e6)

For `type: […, none]`, I'm with the reproduce ability of the description document, which I consider a strong quality aspect.

`description document -> model -> description document`

Splitting 
```
a: str|None
```

into 
```
Astr:
  type: string
Anull:
  type: "null"
a: Astr|Anull
```
requires some kind of folding for the models to get back to the original form of `a: str|None`.

Having the description document compiler emit structural … difficult to deal with … model definitions does not make it a good choice due to the complexity in the models on the consumers side.
It is valid, it validates properly, but it's horrible to work with due to the nesting of models instead of using the intended v3.1 features.

**Comment by Kludex** [comment] 2023-07-24 15:29
Can you add some endpoints that use those? I've asked because there were UI issues with it. Your example only has the components.

**Comment by commonism** [comment] 2023-07-24 15:55
Rendering is borked for `type:[…,"null"]` in path/query … most likely everything else as well.
I'll create a demo and report.

**Closed** 2023-07-24 20:59 UTC
Labels: Schema, bug V2

**Comment by dmontagu** [comment] 2023-08-08 20:02
I'll just note that if we merge #6951, it will require a subtle change to the suggested code for this.

```python
from pydantic import BaseModel, Field
from pydantic.json_schema import SkipJsonSchema


class Model(BaseModel):
    x: int | SkipJsonSchema[None] = Field(default=None, json_schema_extra=lambda x: x.pop('default'))

print(Model.model_json_schema())
#> {'properties': {'x': {'title': 'X', 'type': 'integer'}}, 'title': 'Model', 'type': 'object'}
```

In particular, what used to be:
```python
x: Annotated[int | SkipJsonSchema[None], Field(json_schema_extra=lambda x: x.pop('default'))] = None
```
should now be
```python
x: int | SkipJsonSchema[None] = Field(default=None, json_schema_extra=lambda x: x.pop('default'))
```
I think this is actually more sensible anyway since `= None` is like `= Field(default=None)`, and `Annotated[<type>, <Field(...1)>] = Field(<...2>)` is like `Annotated[<type>, <Field(...1)>, Field(<...2>)]`, and `Annotated[int | SkipJsonSchema[None], Field(json_schema_extra=lambda x: x.pop('default'))]` on its own doesn't make sense, since there won't be a default to pop.
