### ISSUE TITLE
More extensive docs on what pydantic-core schema is, and how __get_pydantic_core_schema__ should be used

### ISSUE THREAD

**Issue by lijok** [pydantic/pydantic#10745] opened 2024-10-31 10:37 UTC
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

As it stands, __get_pydantic_core_schema__ looks like a magic incantation. [The docs for customizing validation with __get_pydantic_core_schema__](https://docs.pydantic.dev/latest/concepts/types/#customizing-validation-with-__get_pydantic_core_schema__) tell us it's used to tell pydantic how to generate the pydantic-core schema, but the docs for what exactly it is, and how it factors into custom class creation, are missing.

It would be good to have documentation explaining exactly what `pydantic-core schema` is, what pydantic does with it, and how it can be manipulated to construct custom types.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by Viicos** [comment] 2024-10-31 14:10
Does [this section](https://docs.pydantic.dev/dev/internals/architecture/) answers your questions?

**Comment by sydney-runkle** [comment] 2024-10-31 14:13
I think we can probably ark this as a dupe of https://github.com/pydantic/pydantic/issues/7534, which covers this request. As @Viicos mentioned above, the architecture docs should be pretty helpful here.

If you feel like the above linked issue / architecture docs together don't address your requests / questions, let us know and we'd be happy to reopen! 🚀

**Closed by sydney-runkle** 2024-10-31 14:13 UTC
Labels: documentation
