### ISSUE TITLE
2.5 not longer installable from Azure artifacts because of the package description being too long

### ISSUE THREAD

**Issue by roman-kouzmenko** [pydantic/pydantic#8125] opened 2023-11-15 07:52 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Trying to install version 2.5.0 from azure artifacts results in this error

```HTTP error 400 Client Error: Bad Request - The package description exceeds the maximum length of 324608 bytes```

"pydantic<2.5" installs just fine.

I suspect it might be due to the "long description" of the package that includes the full change log.

### Python, Pydantic & OS Version

```Text
N/A
```

**Comment by hramezani** [comment] 2023-11-15 07:58
Duplicate of #8105.

Please check for duplicates before creating issues.

The new release will be out as soon as GitHub actions behave.

**Closed by hramezani** 2023-11-15 07:58 UTC
Labels: bug V2, pending
