### ISSUE TITLE
Incorrect model_serializer run when using Unions

### ISSUE THREAD

**Issue by illeatmyhat** [pydantic/pydantic#8648] opened 2024-01-26 21:27 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When using `@model_serializer` with Unions, the wrong @model_serializer is used. This leads to an exception if using any of the attributes.

### Example Code

```Python
from typing import Union
from pydantic import BaseModel, model_serializer


class Foo(BaseModel):
    a: str = "a"

    @model_serializer
    def serialize(self):
        return {'a': 'Foo'}


class Bar(BaseModel):
    b: str = "a"

    @model_serializer
    def serialize(self):
        return {'b': 'Bar'}


class Baz(BaseModel):
    c: Union[Foo, Bar] = Foo()

print(Baz(c=Bar()).model_dump())
# Expected `{'c': {'b': 'Bar'}}`
# Actual `{'c': {'a': 'Foo'}}`
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.3
        pydantic-core version: 2.14.6
          pydantic-core build: profile=release pgo=false
                 install path: .../miniconda3/envs/.../lib/python3.9/site-packages/pydantic
               python version: 3.9.16 (main, Mar  8 2023, 04:29:24)  [Clang 14.0.6 ]
                     platform: macOS-14.2.1-arm64-arm-64bit
             related packages: typing_extensions-4.9.0 fastapi-0.109.0 typing_extensions-4.6.2
```

**Comment by sydney-runkle** [comment] 2024-01-28 16:17
@illeatmyhat,

Thanks for reporting this. Indeed, this seems like effectively a duplicate of https://github.com/pydantic/pydantic/issues/6830. I've added that task to our `Union Issues` milestone.

Going to close this as a duplicate for now. Your example would serve as a great test down the line to confirm that we've fixed this issue, so we'll be sure to keep that in mind when we implement a fix.

@davidhewitt, let's chat this week about how we might go about implementing a fix for this type of bug 🐛.

**Closed** 2024-01-28 16:17 UTC
Labels: duplicate, bug V2
