### ISSUE TITLE
model_validator() with model_copy() bug

### ISSUE THREAD

**Issue by qhelix7** [pydantic/pydantic#9145] opened 2024-04-01 19:25 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I want to automatically modify a value after validation. Because I am using frozen models and relying on multiple fields, I am using `model_validator(mode='after')`. This works as expected if the class is nested, but not if the class is standalone, which feels like a bug.

### Example Code

```Python
import pydantic

class Child(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(frozen=True)

    name: str

    @pydantic.model_validator(mode="after")
    def decorate_name(self):
        return self.model_copy(update={"name": f"--{self.name}->"})

class Parent(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(frozen=True)

    name: str
    child: Child


# validator works for nested model:
#
# > parent = Parent(name="Freddy", child=Child(name="Teddy"))
# > print(repr(parent))
# Parent(name='Freddy', child=Child(name='--Teddy->'))
#
# > print(repr(parent.child))
# Child(name='--Teddy->')

# but not for stand-alone model
# > child = Child(name="Eddy")
# > print(repr(child))
# Child(name='Eddy')
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.4
        pydantic-core version: 2.16.3
          pydantic-core build: profile=release pgo=false
               python version: 3.9.18 (main, Feb  1 2024, 15:55:13)  [Clang 15.0.0 (clang-1500.1.0.2.5)]
                     platform: macOS-14.2.1-arm64-arm-64bit
             related packages: mypy-1.9.0 typing_extensions-4.10.0
                       commit: unknown
```

**Comment by sydney-runkle** [comment] 2024-04-02 19:49
@qhelix7,

Thanks for the report. This looks like a duplicate of https://github.com/pydantic/pydantic/issues/7252. Closing this as such, and I've added the original issue to our current milestone to make sure that we address this bug!

**Closed** 2024-04-02 19:50 UTC
Labels: duplicate, bug V2
