### ISSUE TITLE
1.9.1 breaks backward compatibility

### ISSUE THREAD

**Issue by pvicente** [pydantic/pydantic#4106] opened 2022-05-23 08:32 UTC
### Checks

* [X] I added a descriptive title to this issue
* [X] I have searched (google, github) for similar issues and couldn't find anything
* [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.9.1
            pydantic compiled: True
                 install path: /Users/pedrovicente/cytora/risk-stream-service/.venv/lib/python3.9/site-packages/pydantic
               python version: 3.9.11 (main, May  4 2022, 15:54:04)  [Clang 13.1.6 (clang-1316.0.21.2.3)]
                     platform: macOS-12.3.1-arm64-arm-64bit
     optional deps. installed: ['email-validator', 'typing-extensions']
...
```

 #3713 [PR](https://github.com/samuelcolvin/pydantic/pull/3713/files#r878228704) breaks backward compatibility.

I think it should have been released as 2.0 and not as 1.9.1.

 No matter it has a default value because there are **field_definitions** kwargs after it. Mypy was complaining and I had to add cls_kwargs={}, when calling it after updating from 1.9.0 to 1.9.1, so the change is not backward compatible and shouldn't have been a semver patch version release.

```py
   model = pydantic.create_model(
        model_name,
        __config__=None,
        __base__=None,
        __module__=__name__,
        __validators__={},
        **{k: (v, ...) for k, v in attributes.items()},
...
```
After upgrade from 1.9.0 to 1.9.1 mypy is complaining with:
```
error: No overload variant of "create_model" matches argument types "str", "None", "None", "str", "Dict[<nothing>, <nothing>]", "Dict[str, Tuple[type, ellipsis]]"
```

**Comment by hramezani** [comment] 2022-08-14 22:02
@pvicente you are right and we are sorry about this. 

@samuelcolvin shall we add `**Breaking Change` in the change of https://github.com/pydantic/pydantic/commit/42acd8f8d2bd22f114e589672a054fe07a769e45 as well?

**Comment by PrettyWood** [comment] 2022-08-14 22:08
This was a patch for v1.9 because v1.9.0 actually introduced a regression compared to v1.8.2

**Comment by samuelcolvin** [comment] 2022-08-14 22:17
Closing this but happy to add more details to the change log.

**Closed by samuelcolvin** 2022-08-14 22:18 UTC
Labels: bug
