### ISSUE TITLE
Maximum Recursion Depth when field name matches type name

### ISSUE THREAD

**Issue by jasongilman** [pydantic/pydantic#8009] opened 2023-11-04 00:18 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When defining an optional field with the name that matches the type name it returns an infinite recursion error.

`RecursionError: maximum recursion depth exceeded in __instancecheck__`

It doesn't seem to happen if the field isn't optional or the field name doesn't match the type name.

### Example Code

```Python
from pydantic import BaseModel, Field

class FruitEnum(str, Enum):
    pear = 'pear'
    banana = 'banana'

class CookingModel(BaseModel):
    FruitEnum: Optional[FruitEnum] = Field(default=None)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.4.2
        pydantic-core version: 2.10.1
          pydantic-core build: profile=release pgo=false
                 install path: ./.venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.2 (main, Mar  7 2023, 15:58:38) [Clang 14.0.0 (clang-1400.0.29.202)]
                     platform: macOS-12.7-arm64-arm-64bit
             related packages: typing_extensions-4.8.0 email-validator-2.1.0.post1
```

**Comment by sydney-runkle** [comment] 2023-11-04 02:19
@jasongilman,

Thanks for reporting. This is a duplicate of this issue: https://github.com/pydantic/pydantic/issues/7327.

I'm going to close for tracking purposes, but feel free to continue discussion on that other issue 👍

**Closed by sydney-runkle** 2023-11-04 02:19 UTC
Labels: duplicate, bug V2
