### ISSUE TITLE
Pydantic 2.5.0 description exceeds the maximum length of Azure Devops Artifacts

### ISSUE THREAD

**Issue by Pluttodk** [pydantic/pydantic#8108] opened 2023-11-14 12:23 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

The new version of Pydantic description exceeds the maximum length allowed to host in Azure Artifacts.

This result in the following error occuring once trying to store it in Azure Artifacts:

```
ERROR: HTTP error 400 while getting AZURE_URL (from AZURE_URL) (requires-python:>=3.7)
ERROR: Could not install requirement pydantic==2.5.0 from AZURE_URL because of HTTP error 400 Client Error: Bad Request - The package description exceeds the maximum length of 324608 bytes. (DevOps Activity ID: 1D60714E-B954-4423-8246-E1F6C92F4932) for url: AZURE_URL for URL AZURE_URL (from AZURE_URL) (requires-python:>=3.7)
```

### Python, Pydantic & OS Version

```Text
Python: 3.10.6
Pydantic: 2.5.0
```

**Comment by hramezani** [comment] 2023-11-14 12:30
Duplicate of https://github.com/pydantic/pydantic/issues/8096

Fixed in https://github.com/pydantic/pydantic/commit/9a9ad407a239c30e7decfde809bc8a2c7303f856

Will be available in next patch release

**Closed by hramezani** 2023-11-14 12:30 UTC
Labels: bug V2, pending
