### ISSUE TITLE
Unexpected Config Error with discriminator

### ISSUE THREAD

**Issue by gluhar2006** [pydantic/pydantic#4773] opened 2022-11-22 07:31 UTC
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Discriminator validation.

Expected: ValidationError when passing list or dict as discriminator.

Received: ConfigError.

### Example Code

```Python
from typing import Literal

import pydantic


class Model1(pydantic.BaseModel):
    target: Literal["t1"]
    a: int


class Model2(pydantic.BaseModel):
    target: Literal["t2"]
    b: int


class Foo(pydantic.BaseModel):
    foo: Model1 | Model2 = pydantic.Field(discriminator="target")


# Foo(**{"foo": {"target": []}})
Foo(**{"foo": {"target": {}}})
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.2
            pydantic compiled: True
                 install path: /home/.../lib/python3.10/site-packages/pydantic
               python version: 3.10.8 (main, Oct 19 2022, 10:31:59) [GCC 9.4.0]
                     platform: Linux-5.15.0-53-generic-x86_64-with-glibc2.31
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [X] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by gluhar2006** [comment] 2022-11-22 08:55
I wrote about error, which received by user.
I just didn't understand https://github.com/pydantic/pydantic/blob/v1.10.2/pydantic/fields.py#L1124 otherwise I would have created PR, not issue

**Comment by fatelei** [comment] 2023-01-17 09:15
> I wrote about error, which received by user. I just didn't understand https://github.com/pydantic/pydantic/blob/v1.10.2/pydantic/fields.py#L1124 otherwise I would have created PR, not issue

`discriminator` decide `target` can be `Model1` or `Model2`

example

```python
Foo(foo={'target': 't1', 'a': 1})  # this is Model1
```

```python
Foo(foo={'target': 't2', 'b': 1})  # this is Model2
```

Usage below is not right

```python
Foo(**{"foo": {"target": {}}})
```

**Comment by fatelei** [comment] 2023-01-17 09:15
this is not a bug

**Comment by gluhar2006** [comment] 2023-01-17 09:26
> this is not a bug

You mean that I need to validate `target` field separately or something else? 

> Usage below is not right

Why do you think so?

**Comment by fatelei** [comment] 2023-01-17 12:12
> ```python
> Foo(foo={'target': 't2', 'b': 1})
> ```

target should not be {}, target should be one of t1 / t2

**Comment by gluhar2006** [comment] 2023-01-17 14:03
> target should not be {}, target should be one of t1 / t2
sounds weird

In this case how to explain that all works correctly with 

`Foo(**{"foo": {"target": 123}})`?

**Comment by derek-globus** [comment] 2023-01-29 20:47
The bug report seems to be about the error handling itself.

```
Foo(**{"foo": {"target": 123}})
```
raises a `ValidationError` indicating the document failed validation

```
Foo(**{"foo": {"target": []}})
```
raises a `ConfigError` indicating the Model is incorrect

---

Both documents should be invalid and thus should both raise `ValidationError`s

**Comment by adriangb** [comment] 2023-04-28 21:05
This will be fixed when we release v2:

```python
from typing import Literal

import pydantic


class Model1(pydantic.BaseModel):
    target: Literal['t1']
    a: int


class Model2(pydantic.BaseModel):
    target: Literal['t2']
    b: int


class Foo(pydantic.BaseModel):
    foo: Model1 | Model2 = pydantic.Field(discriminator='target')


print(Foo(**{"foo": {"target": 't2', 'b': 123}}))
#> foo=Model2(target='t2', b=123)

Foo(**{"foo": {"target": []}})
"""
pydantic_core._pydantic_core.ValidationError: 1 validation error for Foo
foo
  Input should be a valid string [type=string_type, input_value=[], input_type=list]
"""
Foo(**{'foo': {'target': {}}})
"""
pydantic_core._pydantic_core.ValidationError: 1 validation error for Foo
foo
  Input should be a valid string [type=string_type, input_value={}, input_type=dict]
"""
Foo(**{"foo": {"target": 123}})
"""
pydantic_core._pydantic_core.ValidationError: 1 validation error for Foo
foo
    Input tag '123' found using 'target' does not match any of the expected tags: 't1', 't2' [type=union_tag_invalid, input_value={'target': 123}, input_type=dict]
"""
```

**Closed by adriangb** 2023-04-28 21:05 UTC
Labels: bug V1, unconfirmed
