### ISSUE TITLE
validate_assignment works on BaseModel objects but not in dataclasses objects.

### ISSUE THREAD

**Issue by gnu-fox** [pydantic/pydantic#9154] opened 2024-04-02 20:15 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I'm trying to create a dataclass with field validation on assigment, it works when I inherit from BaseModel but doesn't when I use a pydantic dataclass instead.

### Example Code

```Python
class Account(BaseModel):
    id: UUID = Field(default_factory=uuid4)
    username: str = Field(..., min_length=3, max_length=50)
    password: SecretStr = Field(...)

    @field_validator('password', mode='before')
    @classmethod
    def hash_password(cls, value: SecretStr) -> SecretStr:
        if Security.is_hashed(value):
            return value
        return Security.hash(value)
    
    model_config = ConfigDict(validate_assignment=True) # This Works!

#But when changing to a dataclass: 

@dataclass
class Account:
    id: UUID = Field(default_factory=uuid4)
    username: str = Field(..., min_length=3, max_length=50)
    password: SecretStr = Field(...)

    @field_validator('password', mode='before')
    @classmethod
    def hash_password(cls, value: SecretStr) -> SecretStr:
        if Security.is_hashed(value):
            return value
        return Security.hash(value)
    
    model_config = ConfigDict(validate_assignment=True) #This does not!

#It should work the same but doesn't.
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.4
        pydantic-core version: 2.16.3
          pydantic-core build: profile=release pgo=true
                 install path: /home/eric/.cache/pypoetry/virtualenvs/fastapi-chat-d7Hq3Bd_-py3.10/lib/python3.10/site-packages/pydantic
               python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
                     platform: Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
             related packages: pydantic-settings-2.2.1 typing_extensions-4.10.0 fastapi-0.110.0
                       commit: unknown
```

**Comment by sydney-runkle** [comment] 2024-04-04 14:02
I can confirm that this reproduces on main - looks like a bug. This is a great first issue - marking as such!

**Comment by gnu-fox** [comment] 2024-04-04 16:34
I've been reading the documentation, and it seems that mode_config is used in a different way in dataclasses and BaseModel, 

```
@dataclass(config=ConfigDict(validate_assignment=True))
class SomeClass:
    a: int

    @field_validator('a', mode='before')
    @classmethod
    def validate_a(cls, value):
        return value + 1
    

some = SomeClass(a=1)
some.a = 4
print(some.a) #gives 5 as expected
```

So it seems that dataclasses works well, is just the config dict has to be passed as the decorator argument as stated in [documentation](https://docs.pydantic.dev/latest/concepts/dataclasses/) Sorry. My bad!

**Comment by sydney-runkle** [comment] 2024-04-04 16:38
Ah yep, good catch :).

**Closed by sydney-runkle** 2024-04-04 16:38 UTC
Labels: help wanted, bug V2, good first issue
