### ISSUE TITLE
Flaky comparison for models with cached properties in version < 2.6

### ISSUE THREAD

**Issue by marcus-idealworks** [pydantic/pydantic#8274] opened 2023-12-01 09:43 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

The comparison of two objects of a pydantic model with a cached property shows unexpected behavior. The `__eq__` operator does not explicitly evaluate cached properties. Therefore, the objects are compared based on previous evaluations. If a cached property was previously evaluated for exactly one of the compared objects, `__eq__` results in `False`.

Expected behavior: If the cached properties have not been evaluated before a call to `__eq__`, they are evaluated during the comparison.

The issue is already resolved on main due to the changes of `BaseModel.__eq__` (https://github.com/pydantic/pydantic/blob/420d8c213be9983b252b769af56d072ac8fd1ade/pydantic/main.py#L863). 

### Example Code

```Python
from pydantic import BaseModel
from functools import cached_property


class M(BaseModel):
    a: int
    b: int

    @cached_property
    def c(self) -> int:
        return self.a + self.b


m0 = M(a=1, b=2)
m1 = M(a=1, b=2)
m0.c
assert m0 == m1 # failing
```

### Python, Pydantic & OS Version

```Text
             pydantic version: 2.5.0
        pydantic-core version: 2.14.1
          pydantic-core build: profile=release pgo=true
                 install path: /home/**/.venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.6 (main, Nov 14 2023, 09:36:21) [GCC 13.2.1 20230801]
                     platform: Linux-6.5.12-1-MANJARO-x86_64-with-glibc2.38
             related packages: typing_extensions-4.8.0 mypy-0.991
```

**Comment by sydney-runkle** [comment] 2023-12-01 15:45
Hi @marcus-idealworks,

Thanks for reporting this. @alexmojaki and @QuentinSoubeyranAqemia worked hard to fix this in https://github.com/pydantic/pydantic/pull/7825. This fix will be released with `2.6.0`. If you need the fix now, you can pull from main :)

Closing as a dupe of https://github.com/pydantic/pydantic/issues/7444

**Closed by sydney-runkle** 2023-12-01 15:45 UTC
Labels: duplicate, bug V2
