### ISSUE TITLE
UrlContraints’ host_required is not applied when using a custom scheme

### ISSUE THREAD

**Issue by k4nar** [pydantic/pydantic#10590] opened 2024-10-10 10:26 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When validating a `AnyUrl`, if the URL provided includes a scheme unknown by pydantic-core and no host, the URL is considered as valid.

Using `Annotated[AnyUrl, UrlConstraints(host_required=True)]` results in the same behavior.

Note: this is very similar to https://github.com/pydantic/pydantic/issues/9898, but I’m not sure this is exactly the same issue.

### Example Code

```Python
from pydantic import AnyUrl, BaseModel, ValidationError


class Dummy(BaseModel):
    url: AnyUrl


# ok
try:
    Dummy(url="http://")
except ValidationError as e:
    print(e)


# should raise the same error
dummy = Dummy(url="sftp://")
print(dummy)
# the host is empty
assert dummy.url.host is None
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.9.2
        pydantic-core version: 2.23.4
          pydantic-core build: profile=release pgo=false
                 install path: /home/yannick/Alma/main/.direnv/python-3.12/lib/python3.12/site-packages/pydantic
               python version: 3.12.6 (main, Sep  8 2024, 13:18:56) [GCC 14.2.1 20240805]
                     platform: Linux-6.11.2-arch1-1-x86_64-with-glibc2.40
             related packages: typing_extensions-4.12.2 pydantic-settings-2.5.2 mypy-1.11.2 fastapi-0.115.0
                       commit: unknown
```

**Comment by sydney-runkle** [comment] 2024-10-10 17:49
Hi!

Marking this as a duplicate of https://github.com/pydantic/pydantic/issues/7353 and https://github.com/pydantic/pydantic/issues/9898, which I'll be attempting to address next week.

**Closed by sydney-runkle** 2024-10-10 17:49 UTC
Labels: bug V2, pending
