### ISSUE TITLE
v1.9 `dataclass`es fail as `typing.Type`

### ISSUE THREAD

**Issue by dan-fritchman** [pydantic/pydantic#6245] opened 2023-06-25 18:16 UTC
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Love the library, great work! 

The issue: using a `pydantic.dataclasses.dataclass` as a value for a `typing.Type` field fails.  
The example code below generates this error: 

```
  File "<string>", line 4, in __init__
  File "/...site-packages/pydantic/dataclasses.py", line 100, in _pydantic_post_init
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for P
t
  subclass of Any expected (type=type_error.subclass; expected_class=Any)
```

A few workarounds: 
* v1.10 works
* Changing to `Type[object]` works

Perhaps known and fixed for v1.10/ v2, in which case it's just a heads-up/ note for v1.9 users.

### Example Code

```Python
from typing import Type
from pydantic.dataclasses import dataclass

@dataclass
class D:
    ...

@dataclass
class P:
    t: Type

P(t=D)
```

### Python, Pydantic & OS Version

```Text
$ python -c "import pydantic.utils; print(pydantic.utils.version_info())"

             pydantic version: 1.9.0
            pydantic compiled: False
                 install path: /Users/dan/miniconda3/envs/py311/lib/python3.11/site-packages/pydantic
               python version: 3.11.3 (main, May 15 2023, 10:43:03) [Clang 14.0.6 ]
                     platform: macOS-10.16-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [X] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [X] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [X] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by Kludex** [comment] 2023-06-25 18:33
Since the issue is not reproducible on 1.10, is there something you'd expect us to do here?

**Comment by samuelcolvin** [comment] 2023-06-25 18:53
I suspect this was fixed by all the changes @PrettyWood made to dataclasses in v1.10.

**Closed by samuelcolvin** 2023-06-25 18:53 UTC
Labels: bug V1, unconfirmed
