### ISSUE TITLE
Object has no attribute __pydantic_private__

### ISSUE THREAD

**Issue by gp1105739** [pydantic/pydantic#8809] opened 2024-02-14 01:20 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

We use sqlmodel and SQLAlchemy to define and save data models. When SQLAlchemy try to create an instance based on the query result, it calls `__new__` of ModelMetaclass. However, the `__new__` does not create `__pydantic_private__` when there is no private_attributes. It errors out when we try to compare objects by calling `__eq__` due to `self.__pydantic_private__ == other.__pydantic_private__ `. We get `AttributeError object has no attribute '__pydantic_private__' `

### Python, Pydantic & OS Version

```Text
pydantic 2.6.1
python: 3.11.5
```

**Comment by sydney-runkle** [comment] 2024-02-14 14:25
@gp1105739,

I think this is an issue with how SQLModel is initializing BaseModels, not with the logic of the Pydantic `__new__` method. When __new__ is called, __pydantic_model_post_init__ is assigned to a method that handles all private attribute logic. Perhaps the issue is that a call to `model_post_init` is missing somewhere?

You might want to check Pydantic's `model_construct` method of an example of how to properly initialize an instance using `__new__` and `model_post_init`.

Marking as resolved for now, as I don't think the onus of a fix lies on Pydantic here. Thanks for reporting the bug, though - hopefully this can help others with the same issue!

**Closed by sydney-runkle** 2024-02-14 14:25 UTC
Labels: bug V2, pending
