### ISSUE TITLE
Pylance reports problem in match-case statement (PEP 634) with dataclasses

### ISSUE THREAD

**Issue by lorenzo-w** [pydantic/pydantic#3716] opened 2022-01-21 13:56 UTC
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

The code sample shown below will run just fine and produce the expected output, but Pylance's static type checker (v2022.1.1) will report the problem `"Type[Dataclass]" is not a class`, as can also be seen in attached screenshot.

![grafik](https://user-images.githubusercontent.com/22264281/150538311-e7cb8dc9-6950-40cf-9f42-dbbca49ce1f8.png)

This might also be a bug with Pylance or you might consider lacking support for such a new language feature not a bug at all, however structural pattern matching works already quite smoothly with `BaseModel` and vanilla dataclasses, so there might be a really easy fix for this. 

See also the official specification for structural pattern matching: [PEP 634](https://www.python.org/dev/peps/pep-0634/)

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.9.0
            pydantic compiled: True
                 install path: /home/enzo/.cache/pypoetry/virtualenvs/isi-lib-fLzemPF9-py3.10/lib/python3.10/site-packages/pydantic
               python version: 3.10.2 (main, Jan 20 2022, 15:19:55) [GCC 9.3.0]
                     platform: Linux-5.10.60.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
     optional deps. installed: ['dotenv', 'typing-extensions']
```

```py
from pydantic.dataclasses import dataclass
from typing import Any

@dataclass
class Person:
  name: str

def greet(person: Any) -> None:
  match person:
    case Person(name="Max"):
      print(f"Hey, wazzup dude?")
    case Person(name=x):
      print(f"Hello {x}!")
    case _:
      print("Wud?!")

greet(Person("Eve")) # Hello Eve!
greet(Person(name="Max")) # Hey, wazzup dude?
greet(2 + 3j) # Wud?!
```

**Comment by lorenzo-w** [comment] 2022-01-22 12:49
It seems that this is a more general problem with Pylance (or rather Pyright) not recognizing Pydantic dataclasses. I still think something must be wrong with my setup, yet I can't figure out what it is.

**Comment by Kludex** [comment] 2023-08-25 14:25
Since the issue is related to your setup, and it's been quite awhile, I'll close the issue.

Please let me know if it's still happening, so we can investigate together. 🙏

**Closed by Kludex** 2023-08-25 14:25 UTC
Labels: bug V1
